### PR TITLE
Make UnpooledUnsafeHeapByteBuf class public

### PR DESCRIPTION
**Pull request by idelpivnitskiy**
Motivation:

1. Users will be able to use an optimized version of `UnpooledHeapByteBuf` and
override behavior of methods if required.
2. Consistency with `UnpooledDirectByteBuf`, `UnpooledHeapByteBuf`, and
`UnpooledUnsafeDirectByteBuf`.

Modifications:

- Add `public` access modifier to `UnpooledUnsafeHeapByteBuf` class and ctor;

Result:

Public access for an optimized version of `UnpooledHeapByteBuf`.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by idelpivnitskiy** [comment]
One test failed on JDK12:

io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendCompositeDirectByteBuf

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSend0(DatagramUnicastTest.java:189)
	at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSend(DatagramUnicastTest.java:130)
	at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendCompositeDirectByteBuf(DatagramUnicastTest.java:80)
...
```
Doesn't look related to this change.

**Comment by ejona86** [comment]
It seems weird to me to expose this, since it only works if unsafe is available and such. @idelpivnitskiy, could you explain more what methods you need to override and why you need to extend instead of compose?

**Comment by idelpivnitskiy** [comment]
I'm designing my own version of `UnpooledByteBufAllocator` with some additional features, like logging, more enhanced metrics, and configuration. Unsafe is available for my use case and I would like to utilize the performance advantages it gives. In addition, I have some configuration around to enable/disable `unsafe`.

With these requirements, it's challenging to wrap existing `UnpooledByteBufAllocator` and make sure that you are using the right implementation of `ByteBuf`. I can check `instanceof` for `UnpooledDirectByteBuf`, `UnpooledHeapByteBuf`, and `UnpooledUnsafeDirectByteBuf` because they are `public` classes, but I don't have access to `UnpooledUnsafeHeapByteBuf`. (Also, having this checks at runtime isn't great). And the implementation of `UnpooledUnsafeHeapByteBuf` isn't trivial to replicate it.

Ideally, I would like to avoid the allocation of an additional wrapping layer and runtime checks, therefore composition is not preferred.

I understand that it's not ideal to extend public API. However, in this case, consistency with other classes (like `UnpooledDirectByteBuf`, `UnpooledHeapByteBuf`, and `UnpooledUnsafeDirectByteBuf`) gives more benefits.

**Comment by ejona86** [comment]
I see, `UnpooledUnsafeDirectByteBuf` is already public due to 0ac31ae846. Then, yeah, I guess this would be fine. Github won't show me the diff at the moment because of heavy load, but I can circle back later and try again.

**Comment by idelpivnitskiy** [comment]
@ejona86 sorry, forgot to make ctor public, force pushed to update. Thanks for review!

**Comment by normanmaurer** [comment]
@idelpivnitskiy thanks a lot.

**Pull request merged**
