### PR TITLE
Introduce a native transport for linux using epoll ET

### PR DESCRIPTION
**Pull request by normanmaurer**
This transport use JNI (C) to directly make use of epoll in Edge-Triggered mode for maximal performance on Linux. Beside this it also support using TCP_CORK and produce less GC then the NIO transport using JDK NIO.
It only builds on linux and skip the build if linux is not used. The transport produce a jar which contains all needed .so files for 32bit and 64 bit. The user only need to include the jar as dependency as usually
to make use of it and use the correct classes.

### CODE REVIEW

**Comment by dawud-tan** [comment]
@normanmaurer, Mr. @bnoordhuis said in [libuv#485#issuecomment-9198365](https://github.com/joyent/libuv/issues/485#issuecomment-9198365) that he was reconsidering edge-triggered mode in libuv. It reduces the number of system calls substantially but it slows down some benchmarks because a lot more time is spent inside kernel-side spinlocks. Had you been aware of this issue?

**Comment by normanmaurer** [comment]
@dawud-tan we not saw any of his observations. That said you can use LT and ET in Netty. You can configure it via a `ChannelOption`

**Comment by bnoordhuis** [comment]
The scalability issues have, by and large, been addressed in newer kernels.  I profiled on (IIRC) a stock 2.6.32 kernel.

**Comment by normanmaurer** [comment]
@bnoordhuis thanks! This explains why I not saw these yet I guess :)

**Pull request closed without merging**
