### PR TITLE
Fix possible ByteBuf leak when CompositeByteBuf is resized

### PR DESCRIPTION
**Pull request by njhill**
Motivation:

The special case fixed in #8497 also requires that we keep a derived slice when trimming components in place, as done by the `capacity(int)` and `discardReadBytes()` methods.

Modifications:

Ensure that we keep a ref to trimmed components' original retained slice in `capacity(int)` and `discardReadBytes()` methods, so that it is released properly when the they are later freed. Add unit test which fails prior to the fix.

Result:

Edge case leak is eliminated.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by njhill** [comment]
FYI I just updated the commit message to fix a typo `discardReadComponents` -> `discardReadBytes`.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@njhill thanks!

**Pull request merged**
