### PR TITLE
Reduce use of deprecated classes in javax.security.cert

### PR DESCRIPTION
**Pull request by eirbjo**
Motivation:

Efforts are underway in the OpenJDK project to remove the long deprecated-for-removal classes in the package `javax.security.cert`. These classes were introduced for backwards compatibility concerns with the unbundled JSSE release for JDK 1.2/1.3, but their use have been discouraged since they were introduced.  

It would be good to update Netty to not depend on / use these archaic APIs.

See https://bugs.openjdk.org/browse/JDK-8227024 and the corresponding CSR https://bugs.openjdk.org/browse/JDK-8227395

Modification:

- Remove the `EMPTY_JAVAX_X509_CERTIFICATES` field from `EmptyArrays`
- Update `OcspClientExample` to use `getPeerCertificates` instead of `getPeerCertificateChain`
- Delete the `LazyJavaxX509Certificate` class which wraps the deprecated class `javax.security.cert.X509Certificate`
- Update the class `ReferenceCountedOpenSslEngine.DefaultOpenSslSession` to remove the field `X509Certificate[] x509PeerCerts` and its uses, and also to throw `UnsupportedOperationException` in the override of `SSLSession.getPeerCertificateChain`
- Update `SSLEngineTest` to not call the deprecated method `SSLSession.getPeerCertificateChain`
- Update `SocketSslGreetingTest` to not call the deprecated method `SSLSession.getPeerCertificateChain`

Result:

Netty's use of the `javax.security.cert` package is now limited to the `SSLSession.getPeerCertificateChain` implementations, which all throw `UnsupportedOperationException`. These should be easy to remove once OpenJDK removes the package. The OpenJDK ecosystem risk of removing the APIs is reduced.

### CODE REVIEW

**Comment by eirbjo** [comment]
Ok, I now realize this PR only compiled because I did so with Java >= 15, where the default `SSLSession.getPeerCertificateChain()` method was introduced.

**Comment by chrisvest** [comment]
These classes have not been removed yet from the JDK, as far as I can tell. We can't change the public API we have in 4.1, so this will have to be a Netty 5 change.

**Comment by eirbjo** [comment]
> These classes have not been removed yet from the JDK, as far as I can tell. 

Yes, that's correct. They have been deprecated since Java 9, for removal since 15 but essentially discouraged since their introduction.

I'll admit this is a bit of a knotted problem, and my effort here is to slowly try to help untangle the knot in the broader Java ecosystem to pave the way for the removal. There is always a compatibility concern, and Netty came up in the discussion in the CSR JDK-8227395.

> We can't change the public API we have in 4.1, so this will have to be a Netty 5 change.

Thanks, I'll retarget to 5, that would be the `main` branch I guess (I didn't see it when first making this PR).

**Comment by chrisvest** [comment]
Yes, Netty 5 is in the `main` branch.

**Comment by eirbjo** [comment]
> Yes, Netty 5 is in the `main` branch.

I have re-targeted this PR to the `main` branch.

**Comment by chrisvest** [comment]
@eirbjo Have you signed the CLA? https://netty.io/wiki/developer-guide.html#before-getting-started

**Comment by eirbjo** [comment]
> @eirbjo Have you signed the CLA? https://netty.io/wiki/developer-guide.html#before-getting-started

I have now 👍

**Comment by eirbjo** [comment]
The GHA build failure on windows seems to be a transient network issue with Maven Central:

```
[ERROR] Failed to execute goal on project netty5-codec-http: Could not resolve dependencies for project io.netty:netty5-codec-http:jar:5.0.0.Alpha6-SNAPSHOT: Failed to collect dependencies at com.jcraft:jzlib:jar:1.1.3: Failed to read artifact descriptor for com.jcraft:jzlib:jar:1.1.3: The following artifacts could not be resolved: com.jcraft:jzlib:pom:1.1.3 (absent): Could not transfer artifact com.jcraft:jzlib:pom:1.1.3 from/to central (https://repo.maven.apache.org/maven2): Connection reset
```

**Review by chrisvest — APPROVED** [review]

**Comment by chrisvest** [comment]
Thanks!

**Pull request merged**
