### PR TITLE
Use simple volatile read for SingleThreadEventExecutor#state instead of UNSAFE

### PR DESCRIPTION
**Pull request by fengjiachun**
Use simple volatile read for SingleThreadEventExecutor#state instead of UNSAFE(AtomicIntegerFieldUpdater#get), CAS operation still to use AtomicIntegerFieldUpdater
 
Motivation:

AtomicIntegerFieldUpdater#get is unnecessary, I think use simple volatile read is cleaner
 
Modifications:

Replace code `STATE_UPDATER.get(this)` to `state` in SingleThreadEventExecutor
 
Result:

Cleaner code

### CODE REVIEW

**Comment by ninja-** [comment]
looks good to me  :+1:

**Comment by normanmaurer** [comment]
@fengjiachun LGTM...

**Comment by normanmaurer** [comment]
@fengjiachun can you please adjust the commit message to match our template:

http://netty.io/wiki/writing-a-commit-message.html

After this is done I will merge it

**Comment by fengjiachun** [comment]
Is the commit message ok now? @normanmaurer

**Comment by normanmaurer** [comment]
@fengjiachun also please use `git commit --amend` and do the changes there. Then force push ;)

**Comment by fengjiachun** [comment]
@normanmaurer done, is ok now?

**Comment by normanmaurer** [comment]
@fengjiachun yes... let me cherry-pick

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (cd80b6c2d8677ccee372fe43deaf8509da6eb45f) and 4.0 (867fb70994)

**Comment by fengjiachun** [comment]
thanks a lot @normanmaurer

**Pull request closed without merging**
