### PR TITLE
Remove ByteBuf and friends and rely on temporary 4.1 dependency

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
We have `ByteBufConvertible` in the 4.1 branch, and we are replacing `ByteBuf` with `Buffer` in the main branch.
As an intermediate stepping stone, we can remove the `ByteBuf` code from the main branch, and rely on 4.1 for its `ByteBuf` implementation.

Modification:
- Remove all of the `ByteBuf` related code from the code base.
- Add dependencies on 4.1 versions of `netty-buffer` and `netty-common` modules.
- Adjust tons of imports to refer back to the 4.1 versions of these classes and interfaces.
- Make `ByteProcessor` extend its 4.1 version for temporary compatibility.
- Make `ReferenceCounted` extend its 4.1 version for temporary compatibility.
- Make `ReferenceCountUtil` support both versions of the `ReferenceCounted` interface.
- Retain a slimmed down version of `ByteBufUtil` for its ability to work with the Netty 5 copy of `AsciiString`.
- Fix up places around ByteBufHolder and ReferenceCounted that now need to bridge a version gap.

Result:
We temporarily rely on 4.1 for the `ByteBuf` implementation.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@chrisvest like discussed before this sounds like a good idea! Let me know once it is not a draft anymore :)

**Comment by chrisvest** [comment]
@normanmaurer Will do. Just need to iron out the kinks caused by small differences in implementation and API. The duplication of interfaces like `ReferenceCounted` caused some trouble, but the build seems to be past that at least.

**Comment by chrisvest** [comment]
@normanmaurer Looks like Graal is satisfied now.

**Comment by normanmaurer** [comment]
@chrisvest if the CI is happy I am as well... ship it!

**Comment by chrisvest** [comment]
@normanmaurer Sounds like you clicked on "Close and comment" by mistake 😅

**Comment by normanmaurer** [comment]
@chrisvest yep... Time for the weekend 🍺

**Pull request merged**
