### PR TITLE
Update twitter hpack version

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
https://github.com/twitter/hpack released version v1.0.1.

Modifications:
- Update pom files to pull in new version

Results:
Depend on the most recent hpack library.

### CODE REVIEW

**Comment by Scottmitch** [comment]
@normanmaurer @nmittler - FYI

**Comment by normanmaurer** [comment]
@Scottmitch looks good

**Comment by Scottmitch** [comment]
Cherry-picked 4.1 (b66b38d ) master (45acf6d)

**Comment by nmittler** [comment]
LGTM

**Pull request closed without merging**
