### PR TITLE
CookieDecoder.decode(value) is static

### PR DESCRIPTION
**Pull request by ddossot**

### CODE REVIEW

**Comment by trustin** [comment]
It's actually a known issue. We introduced `ClientCookieDecoder` and `ServerCookieDecoder` that fixes the problem in 4.1.

**Comment by ddossot** [comment]
In any case, the JavaDoc in 4.0 is wrong and needs to be fixed. Hence my pull request, which fixes the JavaDoc.

**Comment by ddossot** [comment]
I mean, as a user of the 4.0 branch, I want to see classes annotated with JavaDocs for 4.0, not for 4.1, don't you agree @trustin ?

**Comment by trustin** [comment]
Ugh, I thought it was a pull request about changing the method signature.  Let me cherry-pick this asap.

**Comment by trustin** [comment]
Cherry-picked: 18abc6d8937773895ee38a3cfb1fd9003f5e3f36 (4.1) and cb8a607ba5b592752bb3712511cb03c83a82f9c9 (4.0) Thanks!

**Comment by ddossot** [comment]
Oh I understand the misunderstanding now! Thanks for pulling this in :dancers:

**Pull request closed without merging**
