### PR TITLE
AsciiString contains utility methods

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
When dealing with case insensitive headers it can be useful to have a case insensitive contains method for CharSequence.

Modifications:
- Add containsCaseInsensative to AsciiString

Result:
More expressive utility method for case insensitive CharSequence.

### CODE REVIEW

**Comment by Scottmitch** [comment]
@nmittler @normanmaurer - FYI

**Comment by normanmaurer** [comment]
@Scottmitch looks good

**Comment by nmittler** [comment]
@Scottmitch Just be careful that this doesn't impact performance ... have you run any benchmarks?

**Comment by Scottmitch** [comment]
@nmittler - The focus of this PR is adding 2 new utility methods. I also consolidated some duplicate code but I can run benchmarks if you want.

**Comment by Scottmitch** [comment]
@nmittler - Ran the HeadersBenchmark. See results below. It looks like the difference reported from this benchmark in the noise (as expected).

```
Benchmark                      (exampleHeader)  Mode  Cnt     Score    Error  Units
HeadersBenchmark.http2Get                THREE  avgt   10    78.093 ±  0.878  ns/op
HeadersBenchmark.http2Get                 FIVE  avgt   10   129.421 ±  0.929  ns/op
HeadersBenchmark.http2Get                  SIX  avgt   10   160.862 ±  0.461  ns/op
HeadersBenchmark.http2Get                EIGHT  avgt   10   261.968 ±  3.053  ns/op
HeadersBenchmark.http2Get               ELEVEN  avgt   10   308.749 ±  9.947  ns/op
HeadersBenchmark.http2Get            TWENTYTWO  avgt   10   626.224 ±  5.199  ns/op
HeadersBenchmark.http2Get               THIRTY  avgt   10   900.241 ±  2.994  ns/op
HeadersBenchmark.http2Iterate            THREE  avgt   10    24.602 ±  2.053  ns/op
HeadersBenchmark.http2Iterate             FIVE  avgt   10    38.115 ±  0.859  ns/op
HeadersBenchmark.http2Iterate              SIX  avgt   10    44.636 ±  0.061  ns/op
HeadersBenchmark.http2Iterate            EIGHT  avgt   10    58.824 ±  0.086  ns/op
HeadersBenchmark.http2Iterate           ELEVEN  avgt   10    80.863 ±  1.221  ns/op
HeadersBenchmark.http2Iterate        TWENTYTWO  avgt   10   159.767 ±  0.875  ns/op
HeadersBenchmark.http2Iterate           THIRTY  avgt   10   216.707 ±  1.941  ns/op
HeadersBenchmark.http2Put                THREE  avgt   10   123.986 ±  1.483  ns/op
HeadersBenchmark.http2Put                 FIVE  avgt   10   176.997 ±  2.480  ns/op
HeadersBenchmark.http2Put                  SIX  avgt   10   207.397 ±  3.251  ns/op
HeadersBenchmark.http2Put                EIGHT  avgt   10   265.884 ±  1.990  ns/op
HeadersBenchmark.http2Put               ELEVEN  avgt   10   367.540 ±  4.628  ns/op
HeadersBenchmark.http2Put            TWENTYTWO  avgt   10   661.853 ±  7.729  ns/op
HeadersBenchmark.http2Put               THIRTY  avgt   10   876.899 ±  4.244  ns/op
HeadersBenchmark.http2Remove             THREE  avgt   10    28.571 ±  0.054  ns/op
HeadersBenchmark.http2Remove              FIVE  avgt   10    46.153 ±  0.091  ns/op
HeadersBenchmark.http2Remove               SIX  avgt   10    54.932 ±  0.208  ns/op
HeadersBenchmark.http2Remove             EIGHT  avgt   10    72.663 ±  0.722  ns/op
HeadersBenchmark.http2Remove            ELEVEN  avgt   10    99.147 ±  0.567  ns/op
HeadersBenchmark.http2Remove         TWENTYTWO  avgt   10   196.410 ±  0.472  ns/op
HeadersBenchmark.http2Remove            THIRTY  avgt   10   265.916 ±  1.000  ns/op
HeadersBenchmark.httpGet                 THREE  avgt   10    87.168 ±  0.271  ns/op
HeadersBenchmark.httpGet                  FIVE  avgt   10   145.200 ±  1.574  ns/op
HeadersBenchmark.httpGet                   SIX  avgt   10   185.909 ±  1.567  ns/op
HeadersBenchmark.httpGet                 EIGHT  avgt   10   260.444 ±  3.430  ns/op
HeadersBenchmark.httpGet                ELEVEN  avgt   10   363.772 ±  1.770  ns/op
HeadersBenchmark.httpGet             TWENTYTWO  avgt   10   819.491 ±  3.709  ns/op
HeadersBenchmark.httpGet                THIRTY  avgt   10  1263.971 ± 65.619  ns/op
HeadersBenchmark.httpIterate             THREE  avgt   10    24.656 ±  1.099  ns/op
HeadersBenchmark.httpIterate              FIVE  avgt   10    37.148 ±  0.198  ns/op
HeadersBenchmark.httpIterate               SIX  avgt   10    44.375 ±  0.539  ns/op
HeadersBenchmark.httpIterate             EIGHT  avgt   10    58.061 ±  0.505  ns/op
HeadersBenchmark.httpIterate            ELEVEN  avgt   10    78.268 ±  0.212  ns/op
HeadersBenchmark.httpIterate         TWENTYTWO  avgt   10   153.890 ±  0.233  ns/op
HeadersBenchmark.httpIterate            THIRTY  avgt   10   208.547 ±  0.415  ns/op
HeadersBenchmark.httpPut                 THREE  avgt   10   118.724 ±  3.550  ns/op
HeadersBenchmark.httpPut                  FIVE  avgt   10   186.559 ±  1.311  ns/op
HeadersBenchmark.httpPut                   SIX  avgt   10   219.485 ±  3.412  ns/op
HeadersBenchmark.httpPut                 EIGHT  avgt   10   274.133 ±  3.884  ns/op
HeadersBenchmark.httpPut                ELEVEN  avgt   10   364.993 ±  5.619  ns/op
HeadersBenchmark.httpPut             TWENTYTWO  avgt   10   665.240 ±  3.430  ns/op
HeadersBenchmark.httpPut                THIRTY  avgt   10   913.636 ± 11.250  ns/op
HeadersBenchmark.httpRemove              THREE  avgt   10    30.767 ±  0.313  ns/op
HeadersBenchmark.httpRemove               FIVE  avgt   10    50.819 ±  1.448  ns/op
HeadersBenchmark.httpRemove                SIX  avgt   10    59.720 ±  0.242  ns/op
HeadersBenchmark.httpRemove              EIGHT  avgt   10    79.857 ±  0.871  ns/op
HeadersBenchmark.httpRemove             ELEVEN  avgt   10   110.117 ±  0.184  ns/op
HeadersBenchmark.httpRemove          TWENTYTWO  avgt   10   213.864 ±  1.272  ns/op
HeadersBenchmark.httpRemove             THIRTY  avgt   10   295.773 ±  7.178  ns/op
```

Without this PR:
```
Benchmark                      (exampleHeader)  Mode  Cnt     Score    Error  Units
HeadersBenchmark.http2Get                THREE  avgt   10    81.879 ± 17.040  ns/op
HeadersBenchmark.http2Get                 FIVE  avgt   10   129.083 ±  0.257  ns/op
HeadersBenchmark.http2Get                  SIX  avgt   10   161.252 ±  0.714  ns/op
HeadersBenchmark.http2Get                EIGHT  avgt   10   258.496 ±  2.388  ns/op
HeadersBenchmark.http2Get               ELEVEN  avgt   10   305.628 ±  5.158  ns/op
HeadersBenchmark.http2Get            TWENTYTWO  avgt   10   631.508 ±  6.588  ns/op
HeadersBenchmark.http2Get               THIRTY  avgt   10   902.661 ± 15.552  ns/op
HeadersBenchmark.http2Iterate            THREE  avgt   10    24.245 ±  0.340  ns/op
HeadersBenchmark.http2Iterate             FIVE  avgt   10    37.509 ±  0.055  ns/op
HeadersBenchmark.http2Iterate              SIX  avgt   10    46.198 ±  1.021  ns/op
HeadersBenchmark.http2Iterate            EIGHT  avgt   10    58.806 ±  0.081  ns/op
HeadersBenchmark.http2Iterate           ELEVEN  avgt   10    80.842 ±  1.065  ns/op
HeadersBenchmark.http2Iterate        TWENTYTWO  avgt   10   169.357 ± 18.034  ns/op
HeadersBenchmark.http2Iterate           THIRTY  avgt   10   215.045 ±  0.717  ns/op
HeadersBenchmark.http2Put                THREE  avgt   10   124.332 ±  1.098  ns/op
HeadersBenchmark.http2Put                 FIVE  avgt   10   177.811 ±  1.244  ns/op
HeadersBenchmark.http2Put                  SIX  avgt   10   207.705 ±  2.924  ns/op
HeadersBenchmark.http2Put                EIGHT  avgt   10   268.028 ±  2.468  ns/op
HeadersBenchmark.http2Put               ELEVEN  avgt   10   366.731 ±  5.222  ns/op
HeadersBenchmark.http2Put            TWENTYTWO  avgt   10   655.920 ±  4.499  ns/op
HeadersBenchmark.http2Put               THIRTY  avgt   10   879.248 ±  5.774  ns/op
HeadersBenchmark.http2Remove             THREE  avgt   10    29.777 ±  1.865  ns/op
HeadersBenchmark.http2Remove              FIVE  avgt   10    46.415 ±  0.511  ns/op
HeadersBenchmark.http2Remove               SIX  avgt   10    55.097 ±  0.443  ns/op
HeadersBenchmark.http2Remove             EIGHT  avgt   10    79.987 ±  0.210  ns/op
HeadersBenchmark.http2Remove            ELEVEN  avgt   10    99.177 ±  0.681  ns/op
HeadersBenchmark.http2Remove         TWENTYTWO  avgt   10   197.264 ±  1.783  ns/op
HeadersBenchmark.http2Remove            THIRTY  avgt   10   266.147 ±  0.269  ns/op
HeadersBenchmark.httpGet                 THREE  avgt   10    86.885 ±  0.120  ns/op
HeadersBenchmark.httpGet                  FIVE  avgt   10   144.499 ±  0.437  ns/op
HeadersBenchmark.httpGet                   SIX  avgt   10   185.302 ±  0.579  ns/op
HeadersBenchmark.httpGet                 EIGHT  avgt   10   263.102 ±  1.353  ns/op
HeadersBenchmark.httpGet                ELEVEN  avgt   10   367.308 ±  0.315  ns/op
HeadersBenchmark.httpGet             TWENTYTWO  avgt   10   819.520 ±  2.349  ns/op
HeadersBenchmark.httpGet                THIRTY  avgt   10  1223.912 ± 16.855  ns/op
HeadersBenchmark.httpIterate             THREE  avgt   10    23.515 ±  0.034  ns/op
HeadersBenchmark.httpIterate              FIVE  avgt   10    37.144 ±  0.115  ns/op
HeadersBenchmark.httpIterate               SIX  avgt   10    43.967 ±  0.085  ns/op
HeadersBenchmark.httpIterate             EIGHT  avgt   10    57.739 ±  0.164  ns/op
HeadersBenchmark.httpIterate            ELEVEN  avgt   10    79.488 ±  0.679  ns/op
HeadersBenchmark.httpIterate         TWENTYTWO  avgt   10   153.617 ±  0.132  ns/op
HeadersBenchmark.httpIterate            THIRTY  avgt   10   210.096 ±  1.490  ns/op
HeadersBenchmark.httpPut                 THREE  avgt   10   118.119 ±  1.650  ns/op
HeadersBenchmark.httpPut                  FIVE  avgt   10   188.040 ±  1.206  ns/op
HeadersBenchmark.httpPut                   SIX  avgt   10   220.320 ±  0.977  ns/op
HeadersBenchmark.httpPut                 EIGHT  avgt   10   272.793 ±  1.430  ns/op
HeadersBenchmark.httpPut                ELEVEN  avgt   10   365.171 ±  2.395  ns/op
HeadersBenchmark.httpPut             TWENTYTWO  avgt   10   672.329 ±  4.885  ns/op
HeadersBenchmark.httpPut                THIRTY  avgt   10   905.258 ±  5.693  ns/op
HeadersBenchmark.httpRemove              THREE  avgt   10    31.489 ±  0.220  ns/op
HeadersBenchmark.httpRemove               FIVE  avgt   10    50.686 ±  0.448  ns/op
HeadersBenchmark.httpRemove                SIX  avgt   10    60.417 ±  0.730  ns/op
HeadersBenchmark.httpRemove              EIGHT  avgt   10    80.154 ±  1.140  ns/op
HeadersBenchmark.httpRemove             ELEVEN  avgt   10   108.796 ±  0.977  ns/op
HeadersBenchmark.httpRemove          TWENTYTWO  avgt   10   213.697 ±  0.980  ns/op
HeadersBenchmark.httpRemove             THIRTY  avgt   10   290.507 ±  1.911  ns/op
```

**Comment by nmittler** [comment]
@Scottmitch SGTM ... and LGTM :)

**Comment by Scottmitch** [comment]
Cherry-picked 4.1 (d4680c5) master (6d9aff2)

**Pull request closed without merging**
