### PR TITLE
IoUring: Correctly handle cancelletion of close and connect

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

When a close op is cancelled we need to not handle it the same as when it failed / worked. Also when a connect is cancelled we need to ensure we not cancel the connect timeout ans also not null out the connect promise.

Modification:

Correct handle cancellation.

Result:

Handle cancellation of ops correctly

### CODE REVIEW

**Comment by chrisvest** [comment]
Can you explain more about the changes to connect cancelling?

**Comment by normanmaurer** [comment]
@chrisvest basically I only wanted to ensure if we ever cancel a connect op we ensure we not cancel the timeout and also not null out the `connectPromise`

**Comment by chrisvest** [comment]
But if we cancel the connect operation what's the point of keeping the timeout and not completing the promise?

**Comment by chrisvest** [comment]
> @chrisvest maybe we should just fail it with a `CancellationException` directly ?

That sounds reasonable. I haven't dived deep into this, though, so don't take my questions as criticism of any particular approach.

**Review by chrisvest — APPROVED** [review]

**Pull request merged**
