### PR TITLE
Allow writing with void promise if IdleStateHandler is configured in …

### PR DESCRIPTION
**Pull request by johnou**
…pipeline.

Motivation:

Allow writing with void promise if IdleStateHandler is configured in the pipeline for read timeout events.

Modifications:

Better performance.

Result:

No more ChannelFutureListeners are created if IdleStateHandler is only configured for read timeouts allowing for writing to the channel with void promise.

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by normanmaurer** [comment]
@johnou please sign the ICLA: http://tinyurl.com/netty-icla

Let me know once done

**Comment by normanmaurer** [comment]
@netkins accept

**Comment by johnou** [comment]
@normanmaurer signed.

**Comment by normanmaurer** [comment]
@johnou Thanks a ton!

Cherry-picked into 4.0 (0decf2f64794481aa4382e18e726649294bbaf82), 4.1 (ad7f033c061e6d8fbabec6171e52a658310e21df) and master (eee7b3c07d9792ac463c2124009fd0ee34774ede)

**Pull request closed without merging**
