### PR TITLE
SSL: Execute SSL_do_handshake(...) after task is run to ensure SSLEng…

### PR DESCRIPTION
**Pull request by normanmaurer**
…ine.getHandshakeStatus() returns the correct value all the time

Motivation:

We should call SSL_do_handshake(...) after we did run the delegating task so SSLEngine.getHandshakeStatus() will be able to see data that we produce as part of finish the handshake and return NEEDS_WRAP.

Modifications:

- Add SSL_do_handshake(...) call

Result:

Correctly reflect HandshakeStatus after running delegating tasks

### CODE REVIEW

**Comment by normanmaurer** [comment]
Don't merge this yet...

**Comment by normanmaurer** [comment]
@chrisvest @bryce-anderson before this change we did return `NEED_UNWRAP` sometimes while there was nothing input src buffer again and needed to so needed to call `unwrap(...)` with an empty src buffer to actually make progress during handshake. This makes no sense, so I changed also the unit test to only call `unwrap` if there is anything left in the buffer.

**Review by bryce-anderson — APPROVED** [review]
This seems like a plausible fix to the problem of needing to pass in an empty buffer. However, I'll admit I don't know enough about boringssl to be a great reviewer, so take my approval with a grain of salt.

**Review by chrisvest — APPROVED** [review]
Same. Going by the changes to the tests, this looks fine.

**Pull request merged**
