### PR TITLE
Add an json codec using Gson

### PR DESCRIPTION
**Pull request by windie**
Motivation:

See #1129

Modifications:

Add `GsonEncoder` and `GsonDecoder`.

Result:

Add an json codec using Google Gson.

### CODE REVIEW

**Comment by slandelle** [comment]
Just sharing my opinion here (no offense meant):
* Is there really a lot of value in this that would justify promoting it as a new module? This is pretty straightforward, and yet limited (delimiter based, not HTTP). IMHO, it's more fitted to be an example.
* Why Gson? From [my experience](https://github.com/gatling/lib-benchmarks/tree/master/jsonpath-benchmark-master), it's way behind both Jackson and Boon in terms of performance.

**Comment by buchgr** [comment]
I kind of agree with @slandelle, that this should better be an example as it's so straightforward.  Also, it seems to me that this would work really well with the `JsonObjectDecoder`. It looks like the `GsonDecoder` always needs a full and valid json string. This is exactly what the `JsonObjectDecoder` provides. It buffers the json until its completely received. So probably adding an example using `JsonObjectDecoder` + gson might be a good idea.

**Comment by windie** [comment]
Agreed that this is better be an example. Will move it into an example.

**Comment by normanmaurer** [comment]
@windie do you want to close this PR and open a new one then ?

**Comment by windie** [comment]
@normanmaurer Yes.

**Pull request closed without merging**
