### PR TITLE
HTTP/2 remove PriorityStreamByteDistributor

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
PriorityStreamByteDistributor is now obsolete and can be replaced by WeightedFairQueueByteDistributor.

Modifications:
- Remove PriorityStreamByteDistributor and use WeightedFairQueueByteDistributor by default.

Result:
PriorityStreamByteDistributor no longer has to be maintained and is replaced by a better algorithm.

### CODE REVIEW

**Comment by Scottmitch** [comment]
@nmittler - This depends on https://github.com/netty/netty/pull/4599

**Comment by normanmaurer** [comment]
@Scottmitch looks good.

**Comment by nmittler** [comment]
@Scottmitch LGTM ... ship it!

**Comment by Scottmitch** [comment]
Cherry-picked 4.1 (72accce)

**Pull request closed without merging**
