### PR TITLE
Added a github action to run mvn verify on each push

### PR DESCRIPTION
**Pull request by HanSolo**
Motivation:

Runs mvn verify on each push.

Modification:

Just added a github action that executes mvn verify on Ubuntu 18.04 on each push using JDK 8

Result:

Fixes #<GitHub issue number>. 

Because I've only added a yaml file there are no changes to the codebase

### CODE REVIEW

**Comment by normanmaurer** [comment]
@HanSolo yes I wonder why we need this... Can you explain ?

**Comment by hyperxpro** [comment]
@normanmaurer I gave it a thought. I think it's a good idea because sometimes @netty-bot has lots of pending jobs to run and it takes several hours to get our job done.

GitHub Actions allows us to run parallel tests so we don't have to wait. We can use this to make sure each commit is error-free. And before finally merging, we will run the test with @netty-bot. 

WDYT?

**Comment by HanSolo** [comment]
As @hyperxpro already mentioned it's faster, offers better integration to github, can handle up to 20 parallel jobs and it doesn't hurt to have the tests running on github on each push. Just my 0.02€

**Comment by normanmaurer** [comment]
Thanks @HanSolo ... I am in the process of switching the CI to GitHub Actions all together and will incorporate this idea there.

**Comment by normanmaurer** [comment]
See https://github.com/netty/netty/pull/10879

**Pull request closed without merging**
