### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by KangZhiDong**

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@KangZhiDong please fix check style

**Comment by KangZhiDong** [comment]
> @KangZhiDong please fix check style

now is ok

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by KangZhiDong** [comment]
> @netty-bot test this please

/code/codec-http2/src/main/java/io/netty/handler/codec/http2/HttpConversionUtil.java:125: trailing whitespace [RegexpSingleline] . 
 i have  modified for the second time

**Comment by KangZhiDong** [comment]
> @netty-bot test this please

This is really rigorous

**Comment by KangZhiDong** [comment]
> @netty-bot test this please

This is really rigorous

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@KangZhiDong thanks a lot!

**Pull request merged**
