### PR TITLE
Fix InternalThreadLocalMap cpu cache sharing size to 128bytes

### PR DESCRIPTION
**Pull request by arthur-zhang**
Motivation:

in 4.0.36.Final UnpaddedInternalThreadLocalMap introduced a new field 
```
    // ArrayList-related thread-locals
    ArrayList<Object> arrayList;
```
image

this field will break InternalThreadLocalMap's cache line padding from 128 bytes to 136

this is jol output with 4.0.36.Final

```
io.netty.util.internal.InternalThreadLocalMap object internals:
OFF  SZ                                       TYPE DESCRIPTION                                                    VALUE
  0   8                                            (object header: mark)                                          N/A
  8   4                                            (object header: class)                                         N/A
 12   4                                        int UnpaddedInternalThreadLocalMap.futureListenerStackDepth        N/A
 16   4                                        int UnpaddedInternalThreadLocalMap.localChannelReaderStackDepth    N/A
 20   4                         java.lang.Object[] UnpaddedInternalThreadLocalMap.indexedVariables                N/A
 24   4                              java.util.Map UnpaddedInternalThreadLocalMap.handlerSharableCache            N/A
 28   4       io.netty.util.internal.IntegerHolder UnpaddedInternalThreadLocalMap.counterHashCode                 N/A
 32   4   io.netty.util.internal.ThreadLocalRandom UnpaddedInternalThreadLocalMap.random                          N/A
 36   4                              java.util.Map UnpaddedInternalThreadLocalMap.typeParameterMatcherGetCache    N/A
 40   4                              java.util.Map UnpaddedInternalThreadLocalMap.typeParameterMatcherFindCache   N/A
 44   4                    java.lang.StringBuilder UnpaddedInternalThreadLocalMap.stringBuilder                   N/A
 48   4                              java.util.Map UnpaddedInternalThreadLocalMap.charsetEncoderCache             N/A
 52   4                              java.util.Map UnpaddedInternalThreadLocalMap.charsetDecoderCache             N/A
 56   4                        java.util.ArrayList UnpaddedInternalThreadLocalMap.arrayList                       N/A
 60   4                                            (alignment/padding gap)                                        
 64   8                                       long InternalThreadLocalMap.rp1                                     N/A
 72   8                                       long InternalThreadLocalMap.rp2                                     N/A
 80   8                                       long InternalThreadLocalMap.rp3                                     N/A
 88   8                                       long InternalThreadLocalMap.rp4                                     N/A
 96   8                                       long InternalThreadLocalMap.rp5                                     N/A
104   8                                       long InternalThreadLocalMap.rp6                                     N/A
112   8                                       long InternalThreadLocalMap.rp7                                     N/A
120   8                                       long InternalThreadLocalMap.rp8                                     N/A
128   8                                       long InternalThreadLocalMap.rp9                                     N/A
Instance size: 136 bytes
Space losses: 4 bytes internal + 0 bytes external = 4 bytes total
```

before 4.0.36.Final eg 4.0.35.Final, InternalThreadLocalMap output is :

```
io.netty.util.internal.InternalThreadLocalMap object internals:
OFF  SZ                                       TYPE DESCRIPTION                                                    VALUE
  0   8                                            (object header: mark)                                          N/A
  8   4                                            (object header: class)                                         N/A
 12   4                                        int UnpaddedInternalThreadLocalMap.futureListenerStackDepth        N/A
 16   4                                        int UnpaddedInternalThreadLocalMap.localChannelReaderStackDepth    N/A
 20   4                         java.lang.Object[] UnpaddedInternalThreadLocalMap.indexedVariables                N/A
 24   4                              java.util.Map UnpaddedInternalThreadLocalMap.handlerSharableCache            N/A
 28   4       io.netty.util.internal.IntegerHolder UnpaddedInternalThreadLocalMap.counterHashCode                 N/A
 32   4   io.netty.util.internal.ThreadLocalRandom UnpaddedInternalThreadLocalMap.random                          N/A
 36   4                              java.util.Map UnpaddedInternalThreadLocalMap.typeParameterMatcherGetCache    N/A
 40   4                              java.util.Map UnpaddedInternalThreadLocalMap.typeParameterMatcherFindCache   N/A
 44   4                    java.lang.StringBuilder UnpaddedInternalThreadLocalMap.stringBuilder                   N/A
 48   4                              java.util.Map UnpaddedInternalThreadLocalMap.charsetEncoderCache             N/A
 52   4                              java.util.Map UnpaddedInternalThreadLocalMap.charsetDecoderCache             N/A
 56   8                                       long InternalThreadLocalMap.rp1                                     N/A
 64   8                                       long InternalThreadLocalMap.rp2                                     N/A
 72   8                                       long InternalThreadLocalMap.rp3                                     N/A
 80   8                                       long InternalThreadLocalMap.rp4                                     N/A
 88   8                                       long InternalThreadLocalMap.rp5                                     N/A
 96   8                                       long InternalThreadLocalMap.rp6                                     N/A
104   8                                       long InternalThreadLocalMap.rp7                                     N/A
112   8                                       long InternalThreadLocalMap.rp8                                     N/A
120   8                                       long InternalThreadLocalMap.rp9                                     N/A
Instance size: 128 bytes
Space losses: 0 bytes internal + 0 bytes external = 0 bytes total
```

in the latest version, InternalThreadLocalMap occupy 136bytes, break the purpose of 128 bytes align.

so i think it's better use 8 long to do the padding job, or remove all the paddings.

### CODE REVIEW

**Comment by chrisvest** [comment]
@arthur-zhang japicmp also needs to be told about this change:

```
Error:  Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.15.4:cmp (default) on project netty-common: There is at least one incompatibility: io.netty.util.internal.InternalThreadLocalMap.rp9:FIELD_REMOVED -> [Help 1]
```

**Comment by normanmaurer** [comment]
@arthur-zhang can you please sign our ICLA: https://netty.io/s/icla ?

**Comment by franz1981** [comment]
> in the latest version, InternalThreadLocalMap occupy 136bytes, break the purpose of 128 bytes align.

I don't understand this: if the padding is too generous it shouldn't be a problem...the real problem is when it's below 2 cache lines

**Comment by arthur-zhang** [comment]
> @arthur-zhang
> 
> > in the latest version, InternalThreadLocalMap occupy 136bytes, break the purpose of 128 bytes align.
> 
> I don't understand this: if the padding is too generous it shouldn't be a problem...the real problem is when it's below 2 cache lines

yes, bigger than 128 is not problem, but waste more space

**Comment by arthur-zhang** [comment]
> @arthur-zhang can you please sign our ICLA: https://netty.io/s/icla ?

done

**Comment by franz1981** [comment]
thanks @arthur-zhang 

> break the purpose of 128 bytes align.

this has led me to believe it could have caused any perf issue (while it's not)

**Comment by arthur-zhang** [comment]
> thanks @arthur-zhang
> 
> > break the purpose of 128 bytes align.
> 
> this has led me to believe it could have caused any perf issue (while it's not)

In this scenario，i think it's better remove all the rp* padding value to keep the class simple

**Comment by arthur-zhang** [comment]
why the [Build PR / linux-aarch64-verify-native (pull_request) Cancelled ] check fail

**Review by chrisvest — APPROVED** [review]

**Pull request merged**
