### PR TITLE
Add version check for JDK9 and beyond.

### PR DESCRIPTION
**Pull request by varming**

### CODE REVIEW

**Comment by normanmaurer** [comment]
@varming LGTM...

Can you please update the commit message to match our template:

http://netty.io/wiki/writing-a-commit-message.html

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (9d933091bfc82cbf5d65c2b27a1ff9dc10577d6a) and 4.0 (b336450)

**Comment by normanmaurer** [comment]
@varming thanks!

**Comment by johnou** [comment]
Any reasons for not using the "java.specification.version" system property?

**Comment by varming** [comment]
@johnou,

The code looks funky enough that I expect some interesting history. I don't know any of the history, so I chose to not do a clean-up.

**Comment by johnou** [comment]
Good enough for me 👍

**Pull request closed without merging**
