### PR TITLE
Future methods getNow() and cause() now throw on incomplete futures

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
Since most futures in Netty are of the `Void` type, methods like `getNow()` and `cause()` cannot distinguish if the future has finished or not.
This can cause data race bugs which, in the case of `Void` futures, can be silent.

Modification:
The methods `getNow()` and `cause()` now throw an `IllegalStateException` if the future has not yet completed.
Most use of these methods are inside listeners, and so are not impacted.
One place in `AbstractBootstrap` was doing a racy read and has been adjusted.

Result:
Data race bugs around `getNow()` and `cause()` are no longer silent.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@chrisvest I only reviewed the last commit... This makes a lot of sense to me as discussed offline!

**Comment by NiteshKant** [comment]
This makes sense to me.

**Comment by normanmaurer** [comment]
huge +1 as discussed offline!

**Comment by chrisvest** [comment]
Converted to draft until #11575 is merged.

**Comment by chrisvest** [comment]
Rebased

**Review by normanmaurer — APPROVED** [review]

**Review by NiteshKant — APPROVED** [review]

**Comment by chrisvest** [comment]
Hopefully the build goes green now.

**Comment by trustin** [comment]
Makes sense. The old API was easier to make a mistake for sure. :+1:

**Pull request merged**
