### PR TITLE
Remove unused parameter from method declaration.

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We had an unused paramter on a method, we should just remove it to keep code clean.

Modifications:

- Remove parameter
- Fix typo in javadoc

Result:

Cleanup done.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@nmittler @Scottmitch PTAL

**Comment by nmittler** [comment]
LGTM

**Comment by Scottmitch** [comment]
thanks @normanmaurer. lgtm!

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (e4195334988236e7e30a4a802630b14956ce5b4b) and master (1f0154e61461db02d362c3e8bc0ff26d81285da9)

**Pull request closed without merging**
