### PR TITLE
Allow to customize how SslMasterKeyHandler is enabled

### PR DESCRIPTION
**Pull request by daschl**
Motivation:

Right now after a SslMasterKeyHandler is added to the pipeline,
it also needs to be enabled via a system property explicitly. In
some environments where the handler is conditionally added to
the pipeline this is redundant and a bit confusing.

Modifications:

This changeset keeps the default behavior, but allows child
implementations to tweak the way on how it detects that it
should actually handle the event when it is being raised.

Also, removed a private static that is not used in the wireshark
handler.

Result:

Child implementations can be more flexible in deciding when
and how the handler should perform its work (without changing
any of the defaults).

### CODE REVIEW

**Comment by chrisvest** [comment]
@netty-bot test this please

**Comment by daschl** [comment]
Also pinging @fzakaria who wrote it originally.

**Comment by daschl** [comment]
@fzakaria sure - so the situation I have is that I'm working on the couchbase java SDK. We have a `SecurityConfig` and in it I allow the user to configure the export of the tls master keys, using the same configuration mechanisms as for all the other properties in the SDK. Which means that if I add the handler (which in my case is not using the wireshark handler, but a custom one) I know it should be used.

So right now I just also set the property somewhere else in the code, but usually in netty if a handler is part of the pipeline it does some work - and if you don't need it you dynamically remove and/or readd it. I think the defaults are fine for most use cases where you control the env, but in our case I want more control because we are deploying this into arbitrary user environments and I want to "tighten" it up when something gets added and how it gets used.

In the end it's a small thing, but it better reflects the potential usage pattern if you need more direct control. If you are curious, you can look at my stashed change up here: http://review.couchbase.org/c/couchbase-jvm-clients/+/135178

**Comment by normanmaurer** [comment]
This looks alright to me...

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
Thanks @daschl

**Pull request merged**
