### PR TITLE
ByteBufUtil.writeUtf8 not consistent with String.getBytes(Charset)

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
f750d6e36c80e88fb302c99b5b7413e5649e6738 added support for surrogates in the writeUtf8 conversion. However exceptions are thrown if invalid input is detected, but the JDK (and slow path of writeUtf8) uses a replacement character and does not throw. We should behave the same way.

Modificiations:
- Don't throw in ByteBufUtil.writeUtf8, and instead use a replacement character consistent with the JDK

Result:
ByteBufUtil.writeUtf8 behavior is consistent with the JDK UTF_8 conversion.

### CODE REVIEW

**Comment by Scottmitch** [comment]
@nmittler @normanmaurer - FYI

**Comment by trustin** [comment]
LGTM

**Comment by netkins** [comment]
SonarQube analysis reported 3 issues:
* MAJOR 2 major
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Add a private constructor to hide the implicit public one.](https://github.com/netty/netty/blob/96b0274a996fe9ce747d4e1d76f311c80225ad26/buffer/src/main/java/io/netty/buffer/ByteBufUtil.java#L702) [rule](https://garage.netty.io/sonarqube/coding_rules#rule_key=squid%3AS1118)
* MINOR [Define a constant instead of duplicating this literal "expected: " 4 times.](https://github.com/netty/netty/blob/96b0274a996fe9ce747d4e1d76f311c80225ad26/buffer/src/main/java/io/netty/buffer/ByteBufUtil.java#L618) [rule](https://garage.netty.io/sonarqube/coding_rules#rule_key=squid%3AS1192)
* MAJOR [StringBuffer (or StringBuilder).append is called consecutively without reusing the target variable.](https://github.com/netty/netty/blob/96b0274a996fe9ce747d4e1d76f311c80225ad26/buffer/src/main/java/io/netty/buffer/ByteBufUtil.java#L733) [rule](https://garage.netty.io/sonarqube/coding_rules#rule_key=pmd%3AConsecutiveAppendsShouldReuse)

**Comment by normanmaurer** [comment]
@Scottmitch ship it.

**Comment by Scottmitch** [comment]
Cherry-picked 4.1 (691bc16) 4.0 (8ddba82)

**Pull request closed without merging**
