### PR TITLE
Correct respect auto read configuration when using HTTP/2

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We did not correctly respect auto read when HTTP/2 is used. This was due the fact that we extended ByteToMessageDecoder but not use the out List to put decoded messages in. This lead to the situation that we will trigger a ctx.read() in channelReadComplete() as we assume we was not able to decode any data.

Modifications:

- Correctly keep track of if we were able to decode a frame and only if not trigger a read if auto read is off.
- Fix handling in Http2FrameCodec as well
- Add unit test.

Result:

Correctly respect auto read also when using HTTP2

### CODE REVIEW

**Comment by normanmaurer** [comment]
This was reported by @rschmitt here https://github.com/netty/netty/pull/8617#discussion_r238801970.

This is the first part of the fix to correctly handles it for `Http2ConnectHandler` and `Http2FrameCodec`. Once this is merged I will look into `Http2MultiplexCodec`

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
Actually @Scottmitch pointed out that it may be the correct to just keep on reading:

https://tools.ietf.org/html/rfc7540#section-5.2.2
> Even with full awareness of the current bandwidth-delay product,
implementation of flow control can be difficult.  When using flow
control, the receiver MUST read from the TCP receive buffer in a
timely fashion. Failure to do so could lead to a deadlock when
critical frames, such as WINDOW_UPDATE, are not read and acted upon.

**Comment by normanmaurer** [comment]
Also related to https://github.com/netty/netty/issues/3998

**Comment by normanmaurer** [comment]
That said I think we may still want to correctly support AUTO_READ to give the user the most flexibility. There is nothing wrong per se supporting it and give the user the flexibility. Its up to the user of-course to ensure reads are done.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@carl-mastrangelo  PTAL again.. I also fixed auto read for the multiplex codec. 

@rschmitt this should fix your problem completely. 

I am now working on some more unit tests.

**Comment by rschmitt** [comment]
@bryce-anderson @normanmaurer Is the idea to shut off auto-read for child streams only? That's what would make the most sense to me, given HTTP/2's design.

**Comment by bryce-anderson** [comment]
@rschmitt, my understanding of this commit was that it was for the socket pipeline. I completely get the need for supporting `autoRead(false)` in the stream channels (it's a beautiful way to manage flow control) but don't know of a reason that would motivate the added complexity necessary to support manually driving the HTTP/2 session itself.

**Comment by rschmitt** [comment]
Neither do I; I just want to make sure my understanding is correct.

**Comment by normanmaurer** [comment]
@rschmitt @bryce-anderson so you are saying its fine to NOT support `AUTO_READ` false for the "parent channel (socket)" in this case ? I am not strong on this PR, just noticed it while looking at some  PR. 

If we do not want to support AUTO_READ on the parent we should at least make it explicit. At the moment it just works like this by chance (a side product of implementation details in ByteToMessageDecoder and Http2ConnectionHandler). 

WDYT ?

**Comment by normanmaurer** [comment]
Also /cc @trustin @carl-mastrangelo @ejona86

**Comment by bryce-anderson** [comment]
@normanmaurer, explicitly not supporting `AUTO_READ=false` would be my preference, but I'm open to being educated about a legitimate reason to stall the socket of an HTTP/2 session.

**Comment by normanmaurer** [comment]
this would work for me... @rschmitt WDYT ?

**Comment by rschmitt** [comment]
@normanmaurer It works for me too, I also can't think of a reason to stall the parent channel (as long as it will behave correctly when the stream channels are not auto-reading).

**Comment by normanmaurer** [comment]
@rschmitt if the child channels will not read we will not "give back" to the flow-controller and so the HTTP2 flow-controlling should do the right thing here.

**Comment by normanmaurer** [comment]
Closing this in favour of https://github.com/netty/netty/pull/8647

**Pull request closed without merging**
