### PR TITLE
Java 8 migration. Auto close try catch blocks

### PR DESCRIPTION
**Pull request by doom369**
Motivation:

Since Java 7 we can automatically close resources in `try ()` construction.

Modification:

Changed all try catches in the code with autoclose `try (resource)`

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by doom369** [comment]
Fixed checkstyle error.
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@doom369 thanks

**Pull request merged**
