### PR TITLE
delete Other "Content-" MIME Header Fields exception

### PR DESCRIPTION
**Pull request by yipulash**
delete Other "Content-" MIME   Header Fields exception

Motivation:

RFC7578 4.8. Other "Content-" Header Fields

The multipart/form-data media type does not support any MIME header
fields in parts other than Content-Type, Content-Disposition, and (in
limited circumstances) Content-Transfer-Encoding. Other header
fields MUST NOT be included and MUST be ignored.

Other "Content-" Header Fields should be ignored no ecxeption

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@yipulash please fix check style and let me know one done:

```
14:33:02 [ERROR] /code/codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:767: trailing whitespace [RegexpSingleline]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:415: trailing whitespace [RegexpSingleline]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:422: Line is longer than 120 characters (found 123). [LineLength]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:422:94: '+' is not followed by whitespace. [WhitespaceAround]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:422:94: '+' is not preceded with whitespace. [WhitespaceAround]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:422:109: '+' is not followed by whitespace. [WhitespaceAround]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:422:109: '+' is not preceded with whitespace. [WhitespaceAround]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:422:123: '+' is not preceded with whitespace. [WhitespaceAround]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:423:69: '+' is not followed by whitespace. [WhitespaceAround]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:423:69: '+' is not preceded with whitespace. [WhitespaceAround]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:423:76: '+' is not preceded with whitespace. [WhitespaceAround]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:424:53: '+' is not followed by whitespace. [WhitespaceAround]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:424:53: '+' is not preceded with whitespace. [WhitespaceAround]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:424:60: '+' is not preceded with whitespace. [WhitespaceAround]
14:33:02 [ERROR] /code/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:448: trailing whitespace [RegexpSingleline]
```

**Comment by yipulash** [comment]
@normanmaurer done

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@slandelle can you have a look as well ?

**Comment by normanmaurer** [comment]
@vietj any concerns ?

**Comment by normanmaurer** [comment]
@vietj @slandelle ping

**Comment by slandelle** [comment]
LGTM

**Comment by slandelle** [comment]
Then, please note that the list of valid headers depend on the multipart type.

If looks like `HttpPostMultipartRequestDecoder` actually only currently support `multipart/form-data` spec.
Other multipart types support additional part headers, eg `multipart/related` supports `Content-ID` and `Content-Description`.

So maybe `HttpPostMultipartRequestDecoder` should be documented as only supporting `multipart/form-data` atm.

**Comment by normanmaurer** [comment]
@slandelle so you suggest this PR to be adjusted before pull it in ?

**Comment by slandelle** [comment]
@normanmaurer Yes, it would be great to make javadoc more informative (current is `This decoder will decode Body and can handle POST BODY.`). It should state that it supports RFC7578 and/or RFC2388.

**Comment by normanmaurer** [comment]
@slandelle but isn't this un-related to this PR and can just be done separately ?

**Comment by slandelle** [comment]
Maybe, as you wish.

**Comment by normanmaurer** [comment]
@fredericBregier any concerns ?

**Comment by fredericBregier** [comment]
@normanmaurer No concern at all.

**Pull request merged**
