### PR TITLE
Fix leaks in test introduced by db6d94f82a0f860131392aa483f4d1e21dc74…

### PR DESCRIPTION
**Pull request by normanmaurer**
…249.

Motivation:

db6d94f82a0f860131392aa483f4d1e21dc74249 added some testcase which did have a buffer leak and so failed the CI.

Modifications:

Fix leak by proper testing of encoder and decoder using EmbeddedChannel.

Result:

CI is happy again.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@slandelle FYI... this fixes the leaks introduced by your changes.

**Comment by slandelle** [comment]
Thanks!

**Comment by slandelle** [comment]
@normanmaurer It looks like autobahn follows RFC6455 strictly and wasn't updated to latest IANA code. Do you want me to reach out to them?

**Comment by slandelle** [comment]
Can be closed (in favor of #8664)

**Pull request closed without merging**
