### PR TITLE
Fix typo in FingerprintTrustManagerFactory docs

### PR DESCRIPTION
**Pull request by robinst**

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by normanmaurer** [comment]
@netkins build

**Comment by normanmaurer** [comment]
@robinst lol thanks! This quite changes the meaning to the correct one :D

**Comment by trustin** [comment]
:facepalm:

**Comment by normanmaurer** [comment]
@trustin lol

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (214e889937ac6c7699190d3aef106747a81ccdbb) , 4.1 (9bf636076a57aa3c58e6ca7a4a465bb0268d944a) and master (70a4ad0c25158929012ab43462e6228021637897)

@robinst thanks!

**Comment by robinst** [comment]
No worries :). Could also have added "if this sentence confused you, then don't use this in production" ;).

**Pull request closed without merging**
