### PR TITLE
Minor changes to improve PendingWriteQueue.

### PR DESCRIPTION
**Pull request by andreipet**
@normanmaurer maybe can you review it please.
Please see #3367

I also replaced Assert.* calls to simple static calls like in the other test files (IDEA with netty codestyle was complaining about them)

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by normanmaurer** [comment]
@andreipet I'm afraid this is not a complete fix for all re-entrance bugs. I will commit a proper fix soon.

**Comment by andreipet** [comment]
OK. Ty.

**Comment by normanmaurer** [comment]
@andreipet let me close this... Will submit a pr today to fix it.

**Pull request closed without merging**
