### PR TITLE
Require Java8 as minimum

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

While we are not yet quite sure if we want to require Java11 as minimum we are at least sure we want to use java8 as minimum.

Modifications:

Change minimum version to java8 and update some tests which failed compilation after this change.

Result:

Use Java8 as minimum and be able to use Java8 features.

### CODE REVIEW

**Comment by normanmaurer** [comment]
I did not replace anything with java8 APIs here yet as I think we want to do this step by step.

**Comment by normanmaurer** [comment]
Related to https://github.com/netty/netty/issues/8540

**Comment by doom369** [comment]
Omg! This is so cool. Thanks! So many code could be just removed now :).

**Comment by kezhenxu94** [comment]
> I did not replace anything with java8 APIs here yet as I think we want to do this step by step.

I'm glad to help if needed

**Comment by normanmaurer** [comment]
@kezhenxu94 please.... This is for the master branch only :)

**Comment by kezhenxu94** [comment]
> @kezhenxu94 please.... This is for the master branch only :)

@normanmaurer Now I begin wondering when should I open a PR based on branch master and when on branch 4.1?

**Comment by normanmaurer** [comment]
@kezhenxu94 master is usually the way to go

**Pull request merged**
