### PR TITLE
Make NioEventLoop group not final

### PR DESCRIPTION
**Pull request by rockwotj**
Motivation: I want to be able to subclass `NioEventLoop` so I can slightly tweak behavior or add functionality such as timing how long each event in the EventLoop takes.

Modification: Remove the `final` modifier from `NioEventLoop`

### CODE REVIEW

**Comment by normanmaurer** [comment]
@rockwotj I would love to not make it non final honestly but better understand what exactly want to do and come up with a solution which will work for other eventloops as well. Could you show me how you planed to extend it ?

**Comment by rockwotj** [comment]
@normanmaurer totally. The whole idea is I really want to know if there are tasks that are slow and locking up the event loop, since the netty version we have pins a channel to a particular `EventLoop`. I don't know if that's changed in a newer version, as I've seen plans to do so.

This is what I'd like to do (in scala):

```scala
class MyEventLoop(parent: NioEventLoopGroup, factory: ThreadFactory, selector: SelectorProvider)
  extends NioEventLoop(parent, factory, selector) {
  override protected def newTaskQueue(): util.Queue[Runnable] = new TaskTimingQueue
}

private class TaskTimingQueue extends ConcurrentLinkedQueue[Runnable] {
  override def add(task: Runnable): Boolean = {
    super.add(new WrappedTimedTask(task))
  }
}

private class WrappedTimedTask(underlying: Runnable) extends Runnable {
  override def run(): Unit = NettyTimingInfo.timeTask(underlying.run())
}

// Use this as my childGroup
class MyEventLoopGroup(nThreads: Int, threadFactory: ThreadFactory)
  extends NioEventLoopGroup(nThreads, threadFactory) {
  override def newChild(threadFactory: ThreadFactory, args: AnyRef*): EventExecutor = {
    new FbEventLoop(this, threadFactory, args(0).asInstanceOf[SelectorProvider])
  }
}
```

Currently I can't do this at all and classes such as `AbstractNioChannel` check to see if the [event loop is an instance](https://github.com/netty/netty/blob/HEAD/transport/src/main/java/io/netty/channel/nio/AbstractNioChannel.java#L379) of `NioEventLoop`, so I can't provide an wrapped implementation if I wanted to try and do this either.

Do you have better ideas for something like this? I feel very restricted by netty to add anything such as this.

**Comment by johnou** [comment]
@rockwotj how about at the event loop group thread factory level? I implemented something similar which essentially marks Netty threads as non blocking IO threads and if a DAO call tries to use one it blocks the invocation..

```java
bossGroup = new EpollEventLoopGroup(1, new NonBlockingIOThreadFactory("Epoll"));
workerGroup = new EpollEventLoopGroup(0, new NonBlockingIOThreadFactory("Epoll"));
bootstrap.group(bossGroup, workerGroup).channel(EpollServerSocketChannel.class);
```

```java
public class NonBlockingIOThreadFactory extends DefaultThreadFactory {
    
    public NonBlockingIOThreadFactory(String poolName) {
        super(poolName);
    }
    
    @Override
    public Thread newThread(Runnable r) {
        return super.newThread(() -> {
            BlockingIODetector.preventBlockingIOinThisThread();
            r.run();
        });
    }
    
    @Override
    protected Thread newThread(Runnable r, String name) {
        return super.newThread(() -> {
            BlockingIODetector.preventBlockingIOinThisThread();
            r.run();
        }, name);
    }
}
```

**Comment by rockwotj** [comment]
I can't do that for the `NioEventLoopGroup` because there is only a single thread that is executed, I want to know how long each task takes on the EventLoop, that solution doesn't quite work for me.

**Comment by Scottmitch** [comment]
This has come up a few times [1][2] and we have found more preferred alternatives in both situations. Will the wrapping approach described in https://github.com/netty/netty/pull/6441#issuecomment-281994334 work for you?

[1] https://github.com/netty/netty/pull/6441
[2] https://github.com/netty/netty/pull/4819#issuecomment-179826173

**Comment by rockwotj** [comment]
@Scottmitch like I said before, I cannot do that, because there are places that expect the concrete implementation of `NioEventLoop` ie [here](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/AbstractNioChannel.java#L119) and [here](https://github.com/netty/netty/blob/795f318c3c11ec0520e7acd963ad4b310c287c20/transport/src/main/java/io/netty/channel/nio/AbstractNioChannel.java#L379)

**Comment by Scottmitch** [comment]
Agreed there are limitations with the current APIs and assumptions made in the implementations (as discussed in the referenced issues). However as long as the Netty code sees the unwrapped objects you can work around these limitations. As you can see these classes / interfaces were not designed with wrapping / extension in mind and making these classes non-final will likely expose other extensibility issues. I put a note in https://github.com/netty/netty/issues/5430#issuecomment-284551318 to improve this scenario in the next API breaking release but until then lets be sure we exhaust other options first.

**Comment by rockwotj** [comment]
For this specific use case, I can use a dirty reflection hack. But it makes me very sad.

```scala
package io.netty.channels.nio

class FbEventLoopGroup(nThreads: Int, threadFactory: ThreadFactory)
  extends NioEventLoopGroup(nThreads, threadFactory) {

  override def newChild(threadFactory: ThreadFactory, args: AnyRef*): EventExecutor = {
    val eventLoop = new NioEventLoop(this, threadFactory, args(0).asInstanceOf[SelectorProvider])
    // Dirty, dirty hack
    val eventLoopQueue = classOf[SingleThreadEventExecutor].getDeclaredField("taskQueue")
    eventLoopQueue.setAccessible(true)
    val currentQueue = eventLoopQueue.get(eventLoop).asInstanceOf[JQueue[Runnable]]
    eventLoopQueue.set(eventLoop, new TaskTimingQueue(currentQueue))
    eventLoop
  }
}

// Guava ForwardingQueue
private class TaskTimingQueue(override val delegate: JQueue[Runnable]) extends ForwardingQueue[Runnable] {
  override def add(task: Runnable): Boolean = {
    super.add(new WrappedTimedTask(task))
  }

  override def offer(task: Runnable): Boolean = {
    super.offer(new WrappedTimedTask(task))
  }
}

private class WrappedTimedTask(underlying: Runnable) extends Runnable {
  override def run(): Unit = NettyTimingInfo.timeTask { underlying.run() }
}
```

**Comment by Scottmitch** [comment]
> I can use a dirty reflection hack. But it makes me very sad.

Me too 😢 

To clarify you want to collect metrics on everything submitted to `EventLoop` queue, not just your application stuff?  Instrumenting `Runnable`s in combination with monitoring the queue lengths over queue drain operations (been meaning to add this) may generally useful for visibility. Not the best extensibility story, but would adding support for these use cases be "good enough" for now?

**Comment by rockwotj** [comment]
So I basically want percentiles of how long tasks take in the `EventLoop` queue. We sometimes have tasks that take a long time (and block other channel's traffic) and we want visibility into when this happens.

That would seem "good enough" for my specific use case.

**Comment by Scottmitch** [comment]
ok sounds good @rockwotj ... I may not have cycles to get to this for a few weeks so maybe use the reflection hack for now if you need something urgent.

**Comment by Scottmitch** [comment]
see https://github.com/netty/netty/issues/6524

**Comment by rockwotj** [comment]
Thanks @Scottmitch!

**Pull request closed without merging**
