### PR TITLE
Consistent naming style for enum

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We should use camel-case for Enums.

Modifications:

Rename enums to use camel-case.

Result:

Consistent naming

### CODE REVIEW

**Comment by normanmaurer** [comment]
@trustin please check

**Comment by trustin** [comment]
Oh, you found this problem as well. Thanks! Please cherry-pick this into all branches.

**Comment by trustin** [comment]
LGTM

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (4feafc4a5226c6307f5a9b36665d8fe8d8a05072) and master (01ac21c63d67337f20f8a42283b117f8f12a0acb)

**Comment by trustin** [comment]
I think I misread this PR. Enum values should be uppercased.

**Comment by normanmaurer** [comment]
I fixed this already

**Comment by trustin** [comment]
@normanmaurer Thank you! :-)

**Pull request closed without merging**
