### PR TITLE
Fix the case where bitmap.lenght and bitmapLength are not equal.

### PR DESCRIPTION
**Pull request by giiiiiithub**
Motivation:

Fix the case where PoolSubpage's bitmap.lenght and bitmapLength are not equal.

e.g. runSize=8192, elemSize=8192, we got bitmap.length=8, but bitmapLength=1

Modification:

Length of bitmap initialization

Result:

PoolSubpage's bitmap.lenght always correct

### CODE REVIEW

**Comment by normanmaurer** [comment]
@giiiiiithub please add a unit test which would fail without this change

**Comment by normanmaurer** [comment]
@giiiiiithub but shouldn't this be "caught" by an assert ?

**Comment by giiiiiithub** [comment]
> @giiiiiithub but shouldn't this be "caught" by an assert ?

bitmapLength and bitmap are  PoolSubpage's internal state, I can't capture them through assert. I can only observe it through debug.

**Comment by normanmaurer** [comment]
I mean an `assert` in the code itself. This would then be triggered when try to allocate the buffer as you stated

**Comment by normanmaurer** [comment]
@chrisvest @franz1981 PTAL

**Comment by normanmaurer** [comment]
@chrisvest @franz1981 ping

**Comment by normanmaurer** [comment]
Let me close this for nw

**Pull request closed without merging**
