### PR TITLE
java.security.AccessControlException: access denied ("java.io.FilePer…

### PR DESCRIPTION
**Pull request by normanmaurer**
…mission" "/etc/os-release" "read")

Motivation:

Modifications:

- Wrap the code and execute with an AccessController
- Ignore SecurityException (by just logging it)
- Add some more debug logging

Result:

Fixes https://github.com/netty/netty/issues/10017

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by trustin** [comment]
Seems OK, but I guess a user might have configured the security manager to allow access for some of the files you're trying to read, i.e. `AccessController.doPrivileged()` could be done for each file.

**Comment by normanmaurer** [comment]
@trustin got it... so one call per file. Makes sense. Let me change it :)

**Comment by normanmaurer** [comment]
@trustin done

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Pull request merged**
