### PR TITLE
Move the PoolThreadCache finalizer to a separate object

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
PoolThreadCache objects are created even when they are not meant to pool anything.
In such a case, there is no point in giving them a finalizer() method.

Modification:
The finalizer method is moved to a separate object, which is conditionally referenced from the PoolThreadCache.
Non-pooling PoolThreadCache objects will not create their FreeOnFinalize objects.

This is an alternative implementation to #13408, which is also reverted by this PR.

Additionally, #13408 added a condition to create non-caching PoolThreadCache when the size of the small and normal caches were zero.
However, it turned out that even when these were requested to be zero, a single-element cache would be created for them.
This PR also reverts the logic to the old behaviour with the single-element cache for small and normal sizes.

Result:
We avoid creating finalizable objects when we don't pool.

### CODE REVIEW

**Comment by chrisvest** [comment]
@franz1981 @ejona86 I think this should give us the new behavior with the old performance.

**Review by franz1981 — APPROVED** [review]
LGTM! Thanks Chris 🙏

**Comment by franz1981** [comment]
FYI @ejona86

**Review by normanmaurer — APPROVED** [review]
LGTM... @ejona86 would it be possible for you to verify ?

**Comment by ejona86** [comment]
Oh, you noticed and moved fast. Excellent! I was going to dig a bit more to figure out _how_ it caused the regression before I filed an issue, because it looked pretty 1:1 with the old behavior to me.

I'll re-run the benchmarks with this and see how things fair.

**Comment by ejona86** [comment]
I've confirmed this fixes the performance regression. From grpc's local benchmark (see also https://github.com/grpc/grpc-java/issues/10401):

```
Benchmark                                           (direct)  (transport)   Mode  Cnt       Score      Error  Units
4.1.94+425aa8a+23da118:
TransportBenchmark.streamingCallsMessageThroughput     false        NETTY  thrpt   10  589712.277 ± 27543.170  ops/s
4.1.94+425aa8a+23da118+dc16c581:
TransportBenchmark.streamingCallsMessageThroughput     false        NETTY  thrpt   10  655486.821 ± 6173.681  ops/s
```

**Pull request merged**
