### PR TITLE
[#3218] Add ChannelPool abstraction and implementations

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

Many projects need some kind a Channel/Connection pool implementation. While the protocols are different many things can be shared, so we should provide a generic API and implementation.

Modifications:

Add ChannelPool API and implementations.

Result:

Reusable / Generic pool implementation that users can use.

### CODE REVIEW

**Comment by normanmaurer** [comment]
This is an alternative implementation to https://github.com/netty/netty/pull/3607. @trustin @Scottmitch please check. I kind of like it more in terms of API. WDYT ?

**Comment by daschl** [comment]
I like the implementation, but if possible I'd like to see it more flexible. Basically a dynamic pool (not just a fixed size) so you can use it easily for on-demand scaling of incoming requests..

Something where you can say pool between N and M channels and clean up after condition x (like channel idle for 1 minute or so). 

@normanmaurer do you think that's possible?

**Comment by normanmaurer** [comment]
@daschl maybe... but I think this is just another implementation, no? This API will work for this. I think we can add more implementations later.

**Comment by daschl** [comment]
@normanmaurer yeah looks like it.. Just wanted to throw it in for consideration to validate :)

**Comment by trustin** [comment]
Could you elaborate with me on the advantage of this API over the old one? What benefit does a user get?

**Comment by normanmaurer** [comment]
@trustin I think it is "cleaner" as it the user not need to hold a reference to the ChannelPool to return the Channel at some point. So it is a bit more inline with what we do with our buffers. Once a user not need the Channel anymore the user just calls PooledChannel.release() and that's it. Also we can store all needed stuff without using Attributes.

You see ?

**Comment by trustin** [comment]
@normanmaurer Then perhaps we don't need `PooledChannel` but just a simple wrapper that does not implement `Channel`? such as:

```java
public Handle<ChannelPool, Channel> {
    Channel channel();
    ChannelPool pool();
    void release();
}
```

I'm not sure if it's a good idea to add a `Channel` implementation with pool-related operations because it makes downcasting to a transport-specific type.

**Comment by normanmaurer** [comment]
@trustin Well the whole Idea was that the user not need to have any extra reference to hold to be able to release the Channel to the pool again. 

But I agree It really sucks that we need to wrap all things :/ so maybe the Handle is the best we can do. WDYT?

**Comment by Scottmitch** [comment]
@normanmaurer - I would like to explore the first option more.  Keeping the core simple and not requiring an interface that extends `Channel`.  Seems like this introduces more complexity and opportunities for things to go wrong, and also may be limiting from a practical usage standpoint as @trustin pointed out.  I think it would be good to explore keeping the core "simple", and providing reasonable extension points (factories, abstract methods, etc...) to let data external to the core which may be useful for users of the pool (i.e. the pool the channel was leased from, etc...).  I think you have identified a good practical use case (getting the pool which the channel was leased from) that we are sure we can support through extensions.

**Comment by normanmaurer** [comment]
@Scottmitch yep doing this now... Let me close this for now

**Pull request closed without merging**
