### PR TITLE
Small javadoc fix

### PR DESCRIPTION
**Pull request by opinali**

### CODE REVIEW

**Comment by opinali** [comment]
Hum, sorry for the noisy pull request (just pulled latest parent after a long time...). Maybe you can just ignore this pull request and make the same changes.

**Comment by normanmaurer** [comment]
Whick commit sha is the one you would have like in?

**Comment by opinali** [comment]
Just the b31536d28440af6ce4aa51302e7f763fb55368d6

**Comment by normanmaurer** [comment]
Alright... Will cherry-pick

**Comment by normanmaurer** [comment]
@opinali Cherry-picked as ebfc38cdc5c7ea92919f42eb7f98b4d053135a24

**Pull request closed without merging**
