### PR TITLE
Updated Maven enforcer plugin version to the latest 3.3.0

### PR DESCRIPTION
**Pull request by mabrod**
Update to the latest 3.3.0 version 

To provide nice and succinct feedback from running enforcer rules plus bug fixes included in 3.3.0 version

Modified plugin version property
<enforcer.plugin.version>3.3.0</enforcer.plugin.version>

Modified plugin id executions based on example from enforcer plugin webpage to provide more descriptive name

<id>enforce-versions</id>

### CODE REVIEW

**Comment by normanmaurer** [comment]
@mabrod can you sign our icla: https://netty.io/s/icla ?

**Comment by mabrod** [comment]
I have signed icla agreement.
Thanks for you quick response
Maciej

**Comment by normanmaurer** [comment]
@mabrod thanks a lot!

**Comment by mabrod** [comment]
you are welcome :-)

**Pull request merged**
