### PR TITLE
Solve the echo example code read-write loop problem

### PR DESCRIPTION
**Pull request by ch0ice**
Motivation:

A read/write loop occurred when I ran the echo example code
For the following reasons:
``` java
//EchoClientHandler.java
@Override
public void channelRead(ChannelHandlerContext ctx, Object msg) {
    ctx.write(msg);
}
```
The client writes out the server's return message directly, resulting in a read/write loop

Modification:

The modified:
``` java
//EchoClientHandler.java
@Override
public void channelRead(ChannelHandlerContext ctx, Object msg) {
    System.err.println(msg.toString());
}
```

Result:
Solved the read-write loop problem

### CODE REVIEW

**Comment by amizurov** [comment]
Hi, according description this is expected behavior 
https://github.com/netty/netty/blob/21eb936dbe713561505ea46b325ede29cd51e49e/example/src/main/java/io/netty/example/echo/EchoClientHandler.java#L23-L27

**Comment by ch0ice** [comment]
Thank you for your reply!

I think it's meaningless to read and write circularly, and I can't see any display without turning on the log.

I resubmitted the code, increased the client log printing, and deleted the added System.out.println (). 
When the client sends a message to the server, the client should be able to see the message it sent and the reply it received in the console output.

I think this is more reasonable. If you think this modification is useless, I will turn off the request.

**Comment by amizurov** [comment]
In current approach logging is useless because client server works in ping-pong mode without any backoff. In a couple of seconds we will have a ton of identical messages. It would be better if we customize example for reading message from console and send it to echo server, IMHO. 
WDYT @normanmaurer ?

**Comment by ch0ice** [comment]
I think you are right, but I think ping-pong mode is meaningless. My modified version has removed ping-pong mode, so the log can be displayed normally.

**Pull request closed without merging**
