### PR TITLE
AggregatedFullHttpMessage .toString()

### PR DESCRIPTION
**Pull request by d-t-w**
related to #3019, #3637

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by normanmaurer** [comment]
@d-t-w nice! Could you please update the commit message to match our template:

http://netty.io/wiki/writing-a-commit-message.html

**Comment by d-t-w** [comment]
certainly, I'm not the most natural with git but I'll give it a go!

**Comment by normanmaurer** [comment]
@d-t-w :

git commit --amend
(edit the message)
git push -f origin 4.0

**Comment by d-t-w** [comment]
done, and I think it updated the commit message ok. ta.

**Comment by normanmaurer** [comment]
@d-t-w looks good :) Will cherry-pick shortly

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (b7aef7bec81018c76828d476336f922844631116) , 4.1 (854859ba69f88c115a82a1a84228e2a860a1a873) and master (2a20eb92ae9edb85319acfa615e13d812e745491)

@d-t-w thanks!

**Pull request closed without merging**
