### PR TITLE
SslHandler LocalChannel read/unwrap reentry fix

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
SslHandler invokes channel.read() during the handshake process. For some
channel implementations (e.g. LocalChannel) this may result in re-entry
conditions into unwrap. Unwrap currently defers updating the input
buffer indexes until the unwrap method returns to avoid intermediate
updates if not necessary, but this may result in unwrapping the same
contents multiple times which leads to handshake failures [1][2].

[1] ssl3_get_record:decryption failed or bad record mac
[2] ssl3_read_bytes:sslv3 alert bad record mac

Modifications:
- SslHandler#unwrap updates buffer indexes on each iteration so that if
  reentry scenario happens the correct indexes will be visible.

Result:
Fixes https://github.com/netty/netty/issues/11146

### CODE REVIEW

**Comment by rkapsi** [comment]
@Scottmitch tested and fixes #11146. All our Unit Tests pass.

**Comment by Scottmitch** [comment]
the state consolidation was moved into https://github.com/netty/netty/pull/11160, and this PR has been rebased

**Review by chrisvest — APPROVED** [review]

**Comment by Scottmitch** [comment]
@rkapsi - would you mind re-checking this PR resolves your issues. it has been rebased and there are some additional changes made since your first verified.

**Comment by rkapsi** [comment]
@Scottmitch re-tested; still works and all tests pass.

**Comment by Scottmitch** [comment]
master (59867fa0fd)

**Pull request merged**
