### PR TITLE
Java 8 migration. Replace Collection.newSetFromMap with ConcurrentHas…

### PR DESCRIPTION
**Pull request by kachayev**
…hMap.newKeySet

Motivation:

Simplify code with newer Java API. It also reduces levels of indirection, but I don't
think we can gain any visible performance improvements out of this.

Modifications:

Replace Collection.newSetFromMap(new ConcurrentHashMap()) with ConcurrentHashMap.newKeySet().

### CODE REVIEW

**Comment by normanmaurer** [comment]
@kachayev was already fixed :) Thanks a lot tho ...

**Comment by doom369** [comment]
@normanmaurer this seems a similar PR, but it is in a different place. So this is correct PR.

**Comment by normanmaurer** [comment]
@doom369 you are right...

@kachayev can you rebase ?

**Comment by kachayev** [comment]
@normanmaurer Sure. A lot of PRs today :)

**Comment by normanmaurer** [comment]
@kachayev haha yeah... Trying to process all of them

**Comment by kachayev** [comment]
@normanmaurer Done.

**Comment by normanmaurer** [comment]
@kachayev thanks!

**Pull request merged**
