### PR TITLE
fix snappy crc32c checksum

### PR DESCRIPTION
**Pull request by andyxning**
Motivation:

Explain here the context, and why you're making that change.
What is the problem you're trying to solve.

Modification: The Snappy crc32c checksum produced by `SnappyFrameEncoder` maybe failed to be validated on other languages snappy decoder, such as [golang/snappy](https://github.com/golang/snappy).

Describe the modifications you've done.

Result:

Fixes #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

This will make the 4-byte cast later after the mask operation. Because whether retaining the higher 4-7 bytes in a long java type will make difference in `(checksum >> 15 | checksum << 17) + 0xa282ead8` result.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@andyxning can you add a testcase ?

**Comment by andyxning** [comment]
@normanmaurer Will do.

**Comment by normanmaurer** [comment]
@andyxning please ping me once done.

**Comment by andyxning** [comment]
@normanmaurer Update is done. PTAL.

**Comment by andyxning** [comment]
@normanmaurer If this PR will be merged, when will the next release will be cut?

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@andyxning can you please fix the checkstyle error ?:

```
20:51:33 [INFO] Starting audit...
20:51:33 [ERROR] /code/codec/src/main/java/io/netty/handler/codec/compression/Snappy.java:659:20: 'typecast' is not followed by whitespace. [WhitespaceAfter]
20:51:33 [ERROR] /code/codec/src/test/java/io/netty/handler/codec/compression/SnappyTest.java:244: Line is longer than 120 characters (found 129). [LineLength]
20:51:33 Audit done.
```

**Comment by andyxning** [comment]
@normanmaurer Comments addressed. PTAL again.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@andyxning I just noticed you did not sign our ICLA yet... Can you do and let me know once done ?

https://netty.io/s/icla

**Comment by normanmaurer** [comment]
@andyxning there are test failures... not sure if your change is incorrect or if the tests needs to be fixed ?

**Comment by andyxning** [comment]
@normanmaurer CLA is Done. codes are updated.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@andyxning there are still failures

**Comment by johnou** [comment]
Test Result (4 failures / ±0)

io.netty.handler.codec.compression.SnappyFrameDecoderTest.testInvalidChecksumDoesNotThrowException
io.netty.handler.codec.compression.SnappyFrameEncoderTest.testStreamStartIsOnlyWrittenOnce
io.netty.handler.codec.compression.SnappyFrameEncoderTest.testSmallAmountOfDataIsUncompressed
io.netty.handler.codec.compression.SnappyTest.testCalculateChecksum

**Comment by andyxning** [comment]
@netty-bot test this please

**Comment by andyxning** [comment]
@normanmaurer Ut are resolved. PTAL. This is the last time that i will ping you for reviewing this PR, i promise. :-)

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@andyxning thanks a lot!

**Comment by andyxning** [comment]
@normanmaurer When will the next release will be cut and a new jar will be pushed to maven?

**Comment by martinfurmanski** [comment]
Is this a breaking change?

**Comment by normanmaurer** [comment]
@martinfurmanski I dont think so... Why you think it is ? To me it seems like we did not correctly calculate the checksum before.

**Comment by martinfurmanski** [comment]
@normanmaurer I didn't look at the details, but what I mean is if the prior patch version of netty is talking with this version, are they now calculating differently?

**Comment by normanmaurer** [comment]
@martinfurmanski I didn't think about this... yes I think this could happen if the crc value overflows  `Integer.MAX_VALUE`.

**Pull request merged**
