### PR TITLE
NIO channel: always fire interestChanged from IO thread

### PR DESCRIPTION
**Pull request by huguesb**
See https://github.com/netty/netty/issues/3546

### CODE REVIEW

**Comment by normanmaurer** [comment]
@huguesb looks good... Can you please adjust the commit message to match our template[1] and sign the ICLA[2].

Please let me know once you done it and I will cherry-pick.

[1] http://netty.io/wiki/writing-a-commit-message.html
[2] http://netty.io/s/icla

**Comment by huguesb** [comment]
@normanmaurer commit message amended and CLA signed.

When can we expect a release including this change?

**Comment by normanmaurer** [comment]
@huguesb sorry.. but can you do the pr against 3.10 branch ?

**Comment by huguesb** [comment]
I'm seeing test failures when I rebase on 3.10:

    testMixedWritability(org.jboss.netty.channel.socket.nio.NioChannelTest): expected:<[false ]> but was:<[]>
    testWritability(org.jboss.netty.channel.socket.nio.NioChannelTest): expected:<[false ]> but was:<[]>

I suspect these tests make assumptions that are no longer correct but it'll take me a little more time to figure out what changes are required to get them to pass.

**Comment by huguesb** [comment]
@normanmaurer github doesn't allow the destination branch of a PR to be changed. New PR: https://github.com/netty/netty/pull/3556

**Pull request closed without merging**
