### PR TITLE
Introduce ReadableObject interface and make ByteBuf and FileRegion im…

### PR DESCRIPTION
**Pull request by Apache9**
…plement it

### CODE REVIEW

**Comment by Apache9** [comment]
@nmittler A first try. I haven't modify the epoll part yet but I think `SingleReadableObjectWriter` introduced in this patch could work.

To maximize compatibility, I rename all the method in `ReadableObject` to avoid changing the original method declaration in `ByteBuf` and `FileRegion`. But the code is a bit ugly I think...

Any suggestions?
Or I could try to solve #3927 without `ReadbleObject`. Let's see which is better?
Thanks.

**Comment by Apache9** [comment]
And should I start my work based on branch `4.1` or `master_deprecated`?

**Comment by normanmaurer** [comment]
4.1

**Comment by nmittler** [comment]
@Apache9 see https://github.com/netty/netty/pull/4611#issuecomment-168743125.  I think this PR is a better approach overall, but I think we should stick with int-based indices.

**Comment by normanmaurer** [comment]
let me just close this for now

**Pull request closed without merging**
