### PR TITLE
exist and fix the issue: can't null out the latter non-null entrys in array

### PR DESCRIPTION
**Pull request by jiafu1115**
@normanmaurer   move i++ before "if";  the old fix can't null out entries in the array due to the " selectedKeys[i] = null" in the line 462  so that the "for loop" in line 477 is useless:

this will cause when we need select again due to cancel keys total number>256. we will leave some values in the keys' array with one null before them.
so if the new requests' size < the null's position, the latter values never be GCed. So in my applications' test. the memory can't down if no any requests existed.
my test is : connect->send only 3 requests> disconnect and keep one day and make sure the request handle speed< received request's speed so that the capacity is very big and the cancel keys is too much due to huge disconnect.

// See netty#2363
                for (;;) {
            
                    if (selectedKeys[i] == null) { 
                        break;  //must break due to 462 line had set the value to null. so the latter part can't be null.
                    }
                    selectedKeys[i] = null;
                }
           i++;

### CODE REVIEW

**Comment by trustin** [comment]
LGTM. Could you please update the commit message and PR description? http://netty.io/wiki/writing-a-commit-message

**Comment by trustin** [comment]
and.. please sign the ICLA if you did not yet: http://netty.io/s/icla

**Comment by jiafu1115** [comment]
@trustin  so can you confirm is it one bug? I think it is bug. so it is, i will commit it.

**Comment by jiafu1115** [comment]
@trustin hi, I had sign the ICLA and format the commit in another pull request:　https://github.com/netty/netty/pull/4672，3ks for checking it.

**Comment by jiafu1115** [comment]
@normanmaurer   @trustin hi, I had sign the ICLA and format the commit in another pull request:　https://github.com/netty/netty/pull/4672，3ks for checking it.

**Comment by normanmaurer** [comment]
Fixed by #4673

**Pull request closed without merging**
