### PR TITLE
Revert #9561 (epoll changes)

### PR DESCRIPTION
**Pull request by johnou**
Motivation:

@njhill believes he has found the regression, see https://github.com/netty/netty/pull/9561#issuecomment-532926597

### CODE REVIEW

**Comment by johnou** [comment]
@normanmaurer I had a spare five minutes between dailies :)

**Comment by normanmaurer** [comment]
@johnou sorry but this still not fix it ... Unfortunately I have no isolated reproducer yet and also have no time atm :/ 

/cc @njhill

**Comment by njhill** [comment]
Thanks @johnou @normanmaurer, disappointing that it wasn't the solution. I understand re the reproduction difficulty and time needed for that. I guess it would make sense to deal with the remaining two one by one.

**Comment by normanmaurer** [comment]
alright... let me close this one for now.

**Comment by njhill** [comment]
@normanmaurer thanks for reinstating those two changes, I will scrutinise the remaining one further.

**Pull request closed without merging**
