### PR TITLE
Ensure calling ReferenceCountedOpenSslEngine.wrap(...) after closeOut…

### PR DESCRIPTION
**Pull request by normanmaurer**
…bound() was called will not throw an SSLException

Motivation:

PR [#6238] added guards to be able to call wrap(...) / unwrap(...) after the engine was shutdown. Unfortunally one case was missed which is when closeOutbound() was called and produced some data while closeInbound() was not called yet.

Modifications:

Correctly guard against SSLException when closeOutbound() was called, produced data and someone calls wrap(...) after it.

Result:

No more SSLException. Fixes [#6260].

### CODE REVIEW

**Comment by normanmaurer** [comment]
@Scottmitch @rkapsi added an unit-test FTW 🎉

**Comment by rkapsi** [comment]
Deploying... Should get some results in a few minutes...

**Comment by normanmaurer** [comment]
@Scottmitch double is better then single approved 👍

**Comment by rkapsi** [comment]
Make it triple, exception is gone.

**Comment by normanmaurer** [comment]
@rkapsi 😍 thanks for the quick turn-around

**Comment by Scottmitch** [comment]
that was quick @rkapsi! I guess the exception reproduces quickly when the issue is present?

**Comment by rkapsi** [comment]
Yea, a couple of times per minute (before the first fix it was every other second). All I needed to do is to deploy one server with the new artifact and watch the logs. It's something we can thankfully do very quickly (and Netty is thanks to the Unit Tests quite low risk).

**Comment by Scottmitch** [comment]
sgtm @rkapsi ... ship it @normanmaurer

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (e9fa40d) and 4.0 (f1130e4)

**Pull request closed without merging**
