### PR TITLE
Add pinnedHeap/DirectMemory methods to ByteBufAllocatorMetric

### LINKED ISSUE #11637: Add support getting the pooled memory size for each PooledByteBufAllocator instance
### Motivation
Our server has its own implementation to decide whether to provide service for users according to the real-time total free memory of the heap memory and the direct memory (mainly the memory used by `io.netty.buffer.PooledByteBufAllocator` for our server). If our server detects it's running out of physical memory, it will just respond with the client requests with something like `Service Unavailable`.

But the problem is: We cannot know the free memory of PooledByteBufAllocator efficiently. For example, we have allocated and cached 8GB chunks in a `PooledByteBufAllocator`, but there is no property to know: what exactly the free memory is, 1GB or 8GB?

### Solution
The [PR](https://github.com/netty/netty/pull/5133/files) in 2016 is similar to what we want and it provides a new property `pooledBytes` to record the free memory of the arena but we want the free memory in the scope of each allocator instance.

And `io.netty.maxDirectMemory` is similar but isn't what we want because it applies the limit to all buffers while we just want to know the free memory size of a PooledByteBufAllocator instance

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
The "used memory" is the amount of memory that a pooled allocator has currently allocated and committed for itself.
Ths is useful for managing resource usage of the pool versus the available system resources.
However, it is not useful for managing resources of the currently circulating buffer instances versus the pool.
The pinned memory is the memory currently in use by buffers in circulation, plus memory held in the thread-local caches.

Modification:
Add pinned memory accounting to PoolChunk.
We cannot just use the existing freeBytes because that field is only updated when pool subpages are retired, and a chunk will never retire its last subpage instance.

Result:
It is now possible to get a fairly accurate (with slight over-counting due to the thread-local caches) picture of how much memory is held up in buffer instances at any given moment.

Fixes #11637

### CODE REVIEW

**Comment by chrisvest** [comment]
@JamesChenX could you give this branch a try and see if it works for your use case?

**Comment by chrisvest** [comment]
`japicmp` says we can't add methods to public interfaces… hmm.

**Comment by normanmaurer** [comment]
> `japicmp` says we can't add methods to public interfaces… hmm.

Yep that's correct

**Comment by JamesChenX** [comment]
@chrisvest Thanks for the PR! I have tested it, and it can also work for our use cases.

**Comment by JamesChenX** [comment]
@chrisvest Thanks for the PR! `pinnedDirectMemory()` can work and is acceptable for our cases though it's not that accurate for our use cases and I prefer the closed PR(https://github.com/netty/netty/pull/11642) honestly, which is accurate for our use cases.

`pinnedDirectMemory` isn't accurate for our use cases because when calling `io.netty.buffer.PooledByteBuf#deallocate`, the buffer may be queued if the queue isn't full in `io.netty.buffer.PoolThreadCache.MemoryRegionCache#add`, if so `pinnedDirectMemory` will not change and cannot reflect the "used memory" that we want. For example:
```java
    @Test
    void test() {
        PooledByteBufAllocator allocator = newAllocator(true);
        // Equals to the size of the queue (256) in PoolThreadCache so it won't count
        // pinnedBytes down when deallocating a buffer 
        int count = 256;
        ByteBuf[] buffers = new ByteBuf[count];
        for (int i = 0; i < count; i++) {
            buffers[i] = allocator.directBuffer(1024);
        }
        for (int i = 0; i < count; i++) {
            buffers[i].release();
            System.out.println(allocator.pinnedDirectMemory()); // It's always "262144", which isn't what we want
        }
    }
```
It will count `pinnedDirectMemory` down only if the queue in PoolThreadCache is full, which is acceptable but not accurate for our use cases.

What we want is exactly the behaviors mentioned in the asserts: https://github.com/netty/netty/pull/11642/files#diff-5356c1287108c4b93aee8b54109d5ef4d4b9cb2179af1806384e0c520aa9dfe6R694-R722.

**Review by NiteshKant — APPROVED** [review]

**Pull request merged**
