### PR TITLE
Support semicolons in query parameters (correction for #8855)

### LINKED ISSUE #8855: Support semicolon as a normal character in URI (no longer a parameter separator)
### Expected result
According to the 2014 W3C Recommendation, semicolon is now illegal as a parameter separator in a http URI.
`?foo=bar;baz` means the parameter `foo` will have the value `bar;baz`

see https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#url-encoded-form-data
(thanks to https://stackoverflow.com/questions/3481664/semicolon-as-url-query-separator)

### Current result
The URI decoder now supports the obsolete 1999 W3C recommendation
 `?foo=bar;baz` is decoded as `?foo=bar & baz=`

(see QueryStringDecoder.java, line 230 :  `case '&': case ';':` both characters are handled equally)

### Netty version
tested (through vert.x) on 1.4.19

### JVM version (e.g. `java -version`)
1.8.0_60

### OS version (e.g. `uname -a`)
Windows i686-pc Intel

_Of course this issue is linked to  #3044 and #2896, but as the norm changed, I suppose it's better to open a new issue_

### PR DESCRIPTION
**Pull request by marcban**
Motivation:

Support semicolons in query parameters

Modification:

deleted specific case for ";" in QueryStringDecoder, corrected test

Result:

Fixes #8855

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by ejona86** [comment]
Looking at the issue, this seems like a change in algorithm. I don't understand how this can be considered safe, since it could be rightly depended on if someone is using the previous encoder.

Note that #8855 only linked to the _encoding_ algorithm. That is not the same as a _decoding_ algorithm, which has to take into account previous encoding algorithms for compatibility.

**Comment by marcban** [comment]
- #8855 refers to a change in the W3C recommendation from 1999 to 2014 
- it concerns the decoding of query strings by the server, hence the change in QueryStringDecoder
- other servers (IIS, Apache, etc.) already implement this

**Comment by ejona86** [comment]
I'm sorry. I now see that there is a decoding algorithm later in the section. I skimmed and searched for "decoding" (to mirror the "encoding algorithm" used earlier), but they just said "to decode...".

For a new implementation, I do think I would follow their recommendation. It's not clear how it impacts existing implementations though. Netty will be decoding parameters generated from an assortment of sources, and it would seem that changing the behavior of `;` could break some of them. Most of the time I would be happy to change the behavior to align to the standard, but this is a case where the standard changed in an incompatible way.

I'd be fine with an option, or a new method, or changing the behavior in Netty 5. But as has been made clearly evident with things like URLs, just because the standard says something doesn't mean it is actually compatible.

**Comment by normanmaurer** [comment]
@ejona86 good point... maybe we should make it a constructor arg ?

**Comment by normanmaurer** [comment]
@marcban as mentioned can you please add a new constructor arg to the `QueryStringDecoder` which allows to change how decoding is done (using the old way as default).

**Comment by normanmaurer** [comment]
@ejona86 would this make you more comfortable ^^ ?

**Comment by ejona86** [comment]
I'd have no reservation with a way to opt-in to the new behavior.

**Comment by normanmaurer** [comment]
@marcb can you please update your PR to use the constructor flag ?

**Comment by normanmaurer** [comment]
Closing this as the author did not respond anymore and the ICLA was not signed so there is no way I can finish it

**Comment by marcban** [comment]
I'm very sorry, I realize I lack some elementary skills to work on open source projects, like if I should open another branch, how to choose parameter names, how many constructors to implement for this class, etc. I don't even know what an ICLA is and how to sign it... At the end I duplicated the modified method in my project, ignoring Vertx/Netty standard method for reading URI parameters

**Pull request closed without merging**
