### PR TITLE
Support non chunked HTTP request bodies larger than Integer.MAX_VALUE.

### PR DESCRIPTION
**Pull request by alkemist**

### CODE REVIEW

**Comment by trustin** [comment]
LGTM. Could you please update your commit message to conform to our guideline?

http://netty.io/wiki/writing-a-commit-message

**Comment by alkemist** [comment]
@trustin sure, done.

**Comment by normanmaurer** [comment]
@alkemist one last thing... Can you please sign our ICLA:

http://netty.io/s/icla

**Comment by alkemist** [comment]
@normanmaurer done.

**Comment by normanmaurer** [comment]
@alkemist thanks a lot.

Cherry-picked into 4.1 (d97f17060f56f4ca1c43ac2fe1a2dc8850cee845) . 4.0 is not affected.

**Pull request closed without merging**
