### PR TITLE
Add a few more default methods to Buffer

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

Let's make it easier to write implementations by adding more default methods

Modifications:

Add default methods

Result:

Easier to implement Buffer

### CODE REVIEW

**Review by chrisvest — APPROVED** [review]

**Review by Kvicii — APPROVED** [review]

**Comment by chrisvest** [comment]
@normanmaurer Try rebasing so you're on top of #12397 — that _should_ hopefully fix that test failure.

**Comment by normanmaurer** [comment]
@chrisvest it already is on top of this... hmm

**Comment by normanmaurer** [comment]
Also cant reproduce the failure here :(

**Comment by chrisvest** [comment]
@normanmaurer I'm also not getting failures locally. I suspect it's running out of native memory, because the unsafe buffers are relying on the GC to free their memory. I'll post a PR soon to change that, and then we'll see if it helps.

**Comment by chrisvest** [comment]
Let's see… #12413

**Comment by normanmaurer** [comment]
Rebased...

**Pull request merged**
