### PR TITLE
Add builder for `EmbeddedChannel`

### PR DESCRIPTION
**Pull request by opennikish**
Motivation:

Have slightly cleaner API when writing unit tests with `EmbeddedChannel`. For example, when we do set `register` to `false` with some handler.

Modifications:

- Extend `EmbeddedChannel` API with one more constructor. There was 2 separate constructors which are setting fields independently (e.g. doesn't call `this(...)`).
- Add `Builder` static class with fluent API.

Result:

Now I could setup `EmbeddedChannel` using fluent builder API without setting up extra fields such as `hasDisconnect`, `parent`, `channelId`, etc.

Motivation:

Explain here the context, and why you're making that change.
What is the problem you're trying to solve.

Modification:

Describe the modifications you've done.

Result:

Fixes #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by opennikish** [comment]
Also, looks like there is typo in java doc for existing constructors:
```
@param hasDisconnect {@code false} if this {@link Channel} will delegate {@link #disconnect()}
     *                      to {@link #close()}, {@link false} otherwise.
```

It should be `... {@link true} otherwise` because: https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/embedded/EmbeddedChannel.java#L762

**Comment by normanmaurer** [comment]
@opennikish I think I would prefer to not add this to 4.1. Imho it does not provide a clear win. Let me fix the javadocs tho.

**Comment by opennikish** [comment]
@normanmaurer Well, the win that I see is:
in case if we need don't register a cannel in an event loop I have to write like this:
```
var channel = new EmbeddedChannel(
        DefaultChannelId.newInstance(),
        false, // register, true by default
        false // hasDisconnect, false by default
);
// ...
channel.register();
```

With builder I could:
```
var channel = EmbeddedChannel.builder()
        .register(false)
        .build();
```

I don't force this change, if u think that it's suites not very well in Netty -- no problem, we could just decline it :)

**Comment by opennikish** [comment]
@normanmaurer BTW, don't u mind if I will make separate PR for the new constructor for `EmbeddedChannel` (the same is in the current PR)?
Because it's impossible now to instantiate embedded channel with `config` and `register` arguments.

**Pull request closed without merging**
