### PR TITLE
Add reflection metadata for buffers

### PR DESCRIPTION
**Pull request by dsyer**
Needed this when creating a gRPC server. Sample here: https://github.com/dsyer/native-grpc

### CODE REVIEW

**Comment by chrisvest** [comment]
@gradinac Please take a look

**Comment by gradinac** [comment]
It appears we may be missing some metadata - @dsyer, just to double check, the Spring application is built with the `graalvm-reachability-metadata` repository enabled? We some metadata for the `AbstractByteBufAllocator` that registers all declared methods, but it's only done if some other classes are reachable: https://github.com/oracle/graalvm-reachability-metadata/blob/master/metadata/io.netty/netty-common/4.1.80.Final/reflect-config.json#L1166

**Comment by dsyer** [comment]
Here is the stack trace:

```
Caused by: java.lang.ExceptionInInitializerError: null
        at java.base@17.0.5/java.lang.Class.ensureInitialized(DynamicHub.java:528) ~[demo:na]
        at io.grpc.netty.Utils.getByteBufAllocator(Utils.java:138) ~[na:na]
        at io.grpc.netty.NettyServer.start(NettyServer.java:205) ~[na:na]
        at io.grpc.internal.ServerImpl.start(ServerImpl.java:184) ~[na:na]
        at io.grpc.internal.ServerImpl.start(ServerImpl.java:93) ~[na:na]
        at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.createAndStartGrpcServer(GrpcServerLifecycle.java:113) ~[demo:2.14.0.RELEASE]
        at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.start(GrpcServerLifecycle.java:72) ~[demo:2.14.0.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[demo:6.0.2]
        ... 12 common frames omitted
Caused by: java.lang.IllegalArgumentException: Can't find '[toLeakAwareBuffer]' in io.netty.buffer.AbstractByteBufAllocator
        at io.netty.util.ResourceLeakDetector.addExclusions(ResourceLeakDetector.java:596) ~[na:na]
        at io.netty.buffer.AbstractByteBufAllocator.<clinit>(AbstractByteBufAllocator.java:37) ~[demo:4.1.85.Final]
        ... 20 common frames omitted
```

Does that mean we should be adding reachability metadata for grpc-netty instead?

**Comment by gradinac** [comment]
Hmm, judging from the stacktrace, at a first glance it seems to be more fitting for `io.grpc`, but I think this may be more fitting for Netty due to:
```
Caused by: java.lang.IllegalArgumentException: Can't find '[toLeakAwareBuffer]' in io.netty.buffer.AbstractByteBufAllocator
        at io.netty.util.ResourceLeakDetector.addExclusions(ResourceLeakDetector.java:596) ~[na:na]
        at io.netty.buffer.AbstractByteBufAllocator.<clinit>(AbstractByteBufAllocator.java:37) ~[demo:4.1.85.Final]
```
`AbstractByteBufAllocator.<clinit>` itself seems to require these methods, we don't seem to have hit this before as it wasn't used outside of the context covered by the metadata repository.
One note is that by default, Netty 4.1 is build-time initialized. As this metadata originates in the `<clinit>` of `AbstractByteBufAllocator`, this wouldn't be a problem for projects that do not use the reachability metadata repository (which switches Netty to runtime initialization). Because of this, I think it may be more fitting to create a PR that adds this reachability metadata to https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata/io.netty/netty-common

**Comment by dsyer** [comment]
I did it in the metadata repo, but linked to gRPC: https://github.com/oracle/graalvm-reachability-metadata/pull/148. Is that wrong?

**Comment by dsyer** [comment]
So are you suggesting we should have `"typeReachable": "io.grpc.netty.NettyServer"` etc. in the `io.netty/netty-common` or `io.netty-buffer` metadata? Or should we just make the `AbstractByteBufAllocator` entry unconditional (I thought that was not the preferred way)? I'm not sure what the best way to publish this is.

**Comment by gradinac** [comment]
Ah, my bad for not saying this, I think we should add it as it is added here:
```
[
  {
    "name": "io.netty.buffer.AbstractByteBufAllocator",
    "condition": {
      "typeReachable": "io.netty.buffer.AbstractByteBufAllocator"
    },
    "allDeclaredMethods": true
  }
]
```
but we should do that under `netty-common` in the reachability metadata repository. This way, we will register all of `AbstractByteBufAllocator` declared methods for reflection as soon as `AbstractByteBufAllocator` itself is reachable. All of Netty 4.1's metadata lives under `netty-common`, but this should (in theory) cause no overhead due to conditional metadata.

**Comment by dsyer** [comment]
I can do that I guess. What about the tests (which are gRPC specific)?

**Comment by dsyer** [comment]
Doesn't `"typeReachable": "io.netty.buffer.AbstractByteBufAllocator"` make all the other declarations for `AbstractByteBufAllocator` redundant?

**Comment by dsyer** [comment]
I think it’s better for this change to go into either the reachability metadata or grpc.

**Pull request closed without merging**
