### PR TITLE
unify nullability checking

### PR DESCRIPTION
**Pull request by kezhenxu94**
Motivation:

Unify nullability checking

Modification:

Unify nullability checking

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Yes I know, and for now I just rewrite the ObjectUtil.checkNotNull with Objects.checkNonNull(...) in case that we may need to add extra logic, and it is easy to do so if you would like me to replace it with Java 8 version(just inline ObjectUtil.checkNotNull)

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@kezhenxu94 please fix Checkstyle:

```
06:33:22 [INFO] Starting audit...
06:33:22 [ERROR] /code/common/src/main/java/io/netty/util/DomainNameMappingBuilder.java:19: Using the '.*' form of import should be avoided - java.util.*. [AvoidStarImport]
06:33:22 [ERROR] /code/common/src/main/java/io/netty/util/DomainNameMapping.java:22: Using the '.*' form of import should be avoided - java.util.*. [AvoidStarImport]
06:33:22 [ERROR] /code/common/src/main/java/io/netty/util/DomainNameMapping.java:85: Line is longer than 120 characters (found 123). [LineLength]
06:33:22 [ERROR] /code/common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java:25: Using the '.*' form of import should be avoided - java.util.*. [AvoidStarImport]
06:33:22 [ERROR] /code/common/src/main/java/io/netty/util/concurrent/NonStickyEventExecutorGroup.java:22: Using the '.*' form of import should be avoided - java.util.*. [AvoidStarImport]
06:33:22 [ERROR] /code/common/src/main/java/io/netty/util/internal/DefaultPriorityQueue.java:18: Using the '.*' form of import should be avoided - java.util.*. [AvoidStarImport]
06:33:22 Audit done.
```

**Comment by normanmaurer** [comment]
@netty-bot Test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by kezhenxu94** [comment]
Closing it for now, reopen when fixed

**Pull request closed without merging**
