### PR TITLE
Update HTTP/2 to RFCs

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
HTTP/2 RFC 7540 has been released.

Modifications:
- Make changes RFC 7540 introduced since draft 17.

Result:
HTTP/2 RFC 7540 compliant code

### CODE REVIEW

**Comment by Scottmitch** [comment]
@nmittler - FYI.  This is to address https://github.com/netty/netty/issues/3787.  You mentioned you previously reviewed the spec and also didn't see any changes that would impact us....so this PR is just updating the version strings we use.

**Comment by normanmaurer** [comment]
@Scottmitch ship it

**Comment by nmittler** [comment]
@Scottmitch Make it so! :)

**Comment by trustin** [comment]
Go!

**Comment by Scottmitch** [comment]
Cherry-picked 4.1 (0f28bdf) master (4cac795)

**Pull request closed without merging**
