### PR TITLE
    Correctly check if cipher is supported for each SslProvider before trying to run test and fix buffer leaks in test.

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

5aaa16b24cee9d7455ea1cbb4cb9f2e43eb931b7 introduced a testcase for specific ciphersuites and checked if these are supported by our native implementation before running it. Unfortunally this is not good enough as even on the JDK it may not be supported on various JDK versions (like Java7). Beside this the test leaked buffers.

Modifications:

- Correctly check if ciphersuite is supported on each SslProvider before trying to run test.
- Fix buffer leaks.

Result:

Testsuite pass again on Java7 and others when -Pleak is used.

### CODE REVIEW

**Comment by normanmaurer** [comment]
Before it failed on java7:

```

(new) io.netty.handler.ssl.CipherSuiteCanaryTest.testHandshake(0: serverSslProvider = JDK, clientSslProvider = JDK, rfcCipherName = TLS_DHE_RSA_WITH_AES_128_GCM_SHA256) |   | details »
-- | -- | --
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(...)(Unknown Source)
------- Stdout: -------
15:11:51.814 [defaultEventLoopGroup-117-12] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0xb82b23b7]
java.lang.IllegalArgumentException: Unsupported ciphersuite TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
	at sun.security.ssl.CipherSuite.valueOf(CipherSuite.java:235)
	at sun.security.ssl.CipherSuiteList.<init>(CipherSuiteList.java:82)
	at sun.security.ssl.SSLEngineImpl.setEnabledCipherSuites(SSLEngineImpl.java:2003)
	at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:231)
	at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:221)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:914)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:906)
	at io.netty.handler.ssl.CipherSuiteCanaryTest$2.initChannel(CipherSuiteCanaryTest.java:163)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:115)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:107)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1487)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1161)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:686)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rkapsi** [comment]
Sorry about that. When are we moving to Java 11?

**Comment by normanmaurer** [comment]
@rkapsi no worries... netty already works with java 11 ;) That said I think for 5 we may move to java11+

**Comment by normanmaurer** [comment]
@rkapsi also just noticed that the test leaks buffers... Fixed this as well.

**Pull request merged**
