### PR TITLE
Enable per origin Cors configuration

### PR DESCRIPTION
**Pull request by gustavonalle**
Fixes  https://github.com/netty/netty/issues/7785

### CODE REVIEW

**Comment by normanmaurer** [comment]
@danbev can you check as you added the original support ?

**Comment by normanmaurer** [comment]
@Scottmitch @trustin any concerns ?

**Comment by normanmaurer** [comment]
@gustavonalle can you please update the commit message to match our template and force push?

https://netty.io/wiki/writing-a-commit-message.html

**Comment by gustavonalle** [comment]
@normanmaurer The commit message is already in that format, am I missing something?

**Comment by normanmaurer** [comment]
@gustavonalle stupid me... Sorry I guess it was too late :(

**Comment by gustavonalle** [comment]
@normanmaurer no worries mate, thanks for pulling this in! ;)

**Pull request merged**
