### PR TITLE
Upgrade Conscrypt to 1.0.0.RC11

### PR DESCRIPTION
**Pull request by nmittler**
Motivation:

Getting the latest Conscrypt goodies.

Modifications:

A few API changes have occurred, specifically in the Conscrypt
class.

Result:

Netty now builds and tests against Conscrypt 1.0.0.RC11

### CODE REVIEW

**Comment by normanmaurer** [comment]
@nmittler can you please rebase ?

**Comment by nmittler** [comment]
@normanmaurer done

**Comment by nmittler** [comment]
@normanmaurer any other comments or shall I commit?

**Comment by normanmaurer** [comment]
@nmittler go for it

**Comment by nmittler** [comment]
@normanmaurer I'm in the process of cutting another release candidate that the Jetty guys need, which has a couple more API changes.  I'll just update this PR to use RC11 once it's available on Maven central.

**Comment by normanmaurer** [comment]
@nmittler works for me

**Comment by nmittler** [comment]
@normanmaurer PTAL

**Comment by normanmaurer** [comment]
@nmittler ship it to 4.1 and 4.0 please

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (5a6ee27cee9df99404016f124d3768f9793dff59) and 4.0 (1cac3d6cee4abdb44b3b45d81a7bee35ed589a18)

**Pull request closed without merging**
