### PR TITLE
Add script which can be used to build affected modules only

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

At the moment we always build all modules. This script can be used to only build affected modules for a given change

Modifications:

Add script that will only build modules that are affected by a change

Result:

More targeted build

### CODE REVIEW

**Comment by normanmaurer** [comment]
This would then be used like this:

```
.github/scripts/build_affected_only.sh 4.1 clean package
```

**Review by hyperxpro — APPROVED** [review]
Thanks a lot for this. It's really going to save tons of time we spend waiting for CI to finish.

**Comment by normanmaurer** [comment]
So the idea whould be to use this for all the PR build jobs except one which would still do a full-build just to ensure we not miss something

**Review by NiteshKant — APPROVED** [review]
My bash foo is non existent but I checked the `diff -> cut -> sort -> sed` shenanigans and they seem to work 😄 

The idea sounds good and the fact that we will run one full build, covers the bases I think.

**Pull request merged**
