### PR TITLE
Allow HTTP decoding post CONNECT in `HttpClientCodec`

### PR DESCRIPTION
**Pull request by NiteshKant**
__Motivation__

`HttpClientCodec` skips HTTP decoding on the connection after a successful HTTP CONNECT response is received.
 This behavior follows the spec for a client but pragmatically, if one creates a client to use a proxy transparently, the codec becomes useless after HTTP CONNECT.
 Ideally, one should be able to configure whether HTTP CONNECT should result in pass-through or not. This will enable client writers to continue using HTTP decoding even after HTTP CONNECT.

 __Modification__

 Added overloaded constructors to accept `parseHttpPostConnect`. If this parameter is `true` then the codec continues decoding even after a successful HTTP CONNECT.

 Also fixed a bug in the codec that was incrementing request count post HTTP CONNECT but not decrementing it on response. Now, the request count is only incremented if the codec is not `done`.

 __Result__

 Easier usage by HTTP client writers who wants to connect to a proxy but still decode HTTP for their users for subsequent requests.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@NiteshKant please fix check style.

**Comment by NiteshKant** [comment]
@normanmaurer done!

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (a093b89bfef7efe8a1c8ad1d3ab07a7c17ac59c4)

**Comment by normanmaurer** [comment]
@NiteshKant thanks buddy!

**Pull request closed without merging**
