### PR TITLE
fix a typo in RecyclableArrayList

### PR DESCRIPTION
**Pull request by ThomasLau**

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by normanmaurer** [comment]
Can you please sign our cla:

https://docs.google.com/spreadsheet/viewform?formkey=dHBjc1YzdWhsZERUQnhlSklsbG1KT1E6MQ

**Comment by normanmaurer** [comment]
@netkins build

**Comment by ThomasLau** [comment]
@normanmaurer  Tks. just signed the cla.

**Comment by normanmaurer** [comment]
@netkins build

**Comment by trustin** [comment]
For a simple type, we don't need to have the contributor sign the CLA.

**Comment by normanmaurer** [comment]
@trustin can't harm either ;)

Cherry-picked into 4.0 (cf8ec39d517e9c93abf312d40a95a2e03d6e42c5), 4.1 (021957becc51d15202fd9e276f065ffa11dbf963) and master (a3dba3d40a76f6b4297265da6f8398cce671a941)

**Pull request closed without merging**
