### PR TITLE
Try running tests more aggressively in parallel

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
If we can run more tests in parallel in these slowest modules, we might make the build faster.

Modification:
Make the `buffer` and `handler` modules parallelize their tests fully concurrently, instead of concurrently-per-class as perviously. Also make the `transport-epoll` module run its tests in parallel.

Result:
Faster build.

### CODE REVIEW

**Comment by chrisvest** [comment]
The next step in making our build faster would be to investigate all the `Thread.sleep` calls we have in our tests. Some of these calls are in parameterized tests, which means the sleep gets called over and over again, dragging the test execution out significantly.

**Comment by hyperxpro** [comment]
Should we use high-end self hosted runners?

**Comment by chrisvest** [comment]
I think we still have some low hanging fruit to pick before going that far. I worry self-hosting will be a headache to maintain.

**Comment by hyperxpro** [comment]
Alright, that makes sense. However, do let me know if we consider self-hosting in the future. I will handle maintenance.

**Pull request merged**
