### PR TITLE
Cleanup of codec-mqtt

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

codec-mqtt had some typos and was not restrict enough in terms of making things final and private constructors.

Modifications:

- Fix typos
- Make most pojos final
- Remove redundant else blocks.

Result:

Cleaner and more restrict code.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@trustin @Scottmitch PTAL

**Comment by Scottmitch** [comment]
@normanmaurer - LGTM

**Comment by normanmaurer** [comment]
@trustin WDYT?

**Comment by trustin** [comment]
LGTM

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 as 269677820df53b1b26cc17f772049cd6b7e88c9b

**Pull request closed without merging**
