### PR TITLE
Minor idiomatic changes to java docs

### PR DESCRIPTION
**Pull request by mcraveiro**
Whilst reading netty documentation I noticed that some of the comments were not using idiomatic English expressions. I've fixed a couple.

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by normanmaurer** [comment]
@netkins accept

**Comment by normanmaurer** [comment]
@mcraveiro tanks!  Cherry-picked into 4.0 (108a95caca14814ba5a47b7edb241d68a5a2c27e) , 4.1 (6d07264412d8524d73af2da4d5bb7d54532786c6) and master (9d4c460b4ff15e11aa8b66fbad6060f2c34b8e12)

**Comment by mcraveiro** [comment]
No problems. Thanks for merging.

**Pull request closed without merging**
