### PR TITLE
Improvement : added overloaded method in order to avoid unnecessary a…

### PR DESCRIPTION
**Pull request by doom369**
Motivation : 

Avoid unnecessary array allocation when using function with varargs in `DefaultChannelPipeline` class.

Modifications : 

Added `addLast` and `addFirst` overloaded methods with 1 handler instead of varargs.

Result : 

No array allocation when using simple construction like `pipeline.addLast(new Handler());`

### CODE REVIEW

**Comment by normanmaurer** [comment]
@doom369 we can not do this as this is an API breakage change for now.

**Comment by doom369** [comment]
@normanmaurer how do you usually solve this?

**Comment by normanmaurer** [comment]
@doom369 we will not merge this until we create 4.2 branch ;)

**Comment by normanmaurer** [comment]
@doom369 also I wonder if we really need this. I mean its only happening when you add handlers to the pipeline so this should be not happen super frequently. Or I am missing something ?

**Comment by doom369** [comment]
@normanmaurer you are right, however if allocation could be easily avoided - why not? 
Please consider 2 use cases where is could be useful : 

1) Ramp up period. When I do new deployment I start new server and get thousands of connections instantly. Every connection creates its own pipeline, handlers, allocations. I have enough allocations in my app and would be nice if netty could generate less, even in this particular case it is 0.01% of all garbage. Also I'm using very low-end VMs with 512, 1024 MB of RAM. Every allocation for me does matter :).

2) Connection is opened, 1 message is send and connection is closed. Even in this case overhead will be very small, however with such use case - less allocations - less pressure on GC, better performance.

**Comment by johnou** [comment]
@doom369 I guess in the meantime you can simply invoke pipeline.addLast(null, new Handler());?

**Comment by doom369** [comment]
@johnou this exactly what I do right now. And that's why this PR appeared.

**Comment by normanmaurer** [comment]
@doom369 maybe just only add it to `DefaultChannelPipeline` for now and we will adjust the interface once we can ? WDYT ?

**Comment by doom369** [comment]
@normanmaurer actually the idea is very good. Let me remove interface change.

**Comment by doom369** [comment]
Sorry. Messed up with rebasing. Will create separate PR.

**Pull request closed without merging**
