### PR TITLE
Updated AIO transport abandoned in 4.0.CR3 to 4.0.23

### PR DESCRIPTION
**Pull request by ajayappa**
Updated AIO transport abandoned in 4.0.CR3 to 4.0.23 to drastically reduce CPU usage.

Motivation:

We use Netty for several of our production servers and received several complaints about high CPU usage under heavy load on windows OS. So we tried to see if using AIO transport instead of NIO transport would address this. 

Modifications:

Updated the AIO transport from 4.0.CR3 to 4.0.23, Updated the read() and write() to conform to the API changes in 4.0.23

Result:

The AIO transport consumes significantly less CPU usage under heavy load. We tested against windows 2008 R3. Other parameters like throughput, latency were found to be slightly better than NIO transport.

### CODE REVIEW

**Comment by Scottmitch** [comment]
@ajayappa - Thanks a bunch for the work you have done so far!  It would be great for the community to get this in based upon the performance benefits you report.  The community may also help us understand in what use cases and environments (i.e. windows) AIO is beneficial.  Do you have any interest in finishing this PR up based upon outstanding comments (including @normanmaurer's test suggestion)?

Do you have any updated metrics or feedback since your last report?

**Comment by Scottmitch** [comment]
@ajayappa - Ping.

@trustin @normanmaurer - Perhaps we should plan on taking this over (for a future 4.1 release)?  Seems to be most of the way there....

**Comment by bwzhang2011** [comment]
@Scottmitch , could aio transport supported be merged into  master branch ?

**Comment by Scottmitch** [comment]
@bwzhang2011 - I think this still needs some more work before we merge it in.  Test suite, and resolve of open review items, etc...

@netty/contributors - Anyone interested in taking ownership of this?

**Comment by normanmaurer** [comment]
@ajayappa are you still interested in this ?

**Comment by Gambert** [comment]
Hi guys,
Just want to confirm @ajayappa 's observations on Windows. There is much less CPU usage on Windows, when using the AIO classes submitted here, e.g. when using AioServerSocketChannel, instead of NioServerSocketChannel. This is the case at least on Windows Server 2012 (on Amazon EC2).

**Comment by Scottmitch** [comment]
@Gambert - Thanks for the info. Do you have any interest in taking on the remaining issuse on this PR so we can more easily support it? I think we have all been a bit strapped for time.

**Comment by Gambert** [comment]
@Scottmitch Sorry for the delay. When I can find the time, I would be very interrested in looking further into this. I will however undoubtedly also have to spend a little time, getting familiar with working on projects with github. I will get back when I have had a little time looking into this.

**Comment by Gambert** [comment]
These AIO classes, result in a lot of failed JUnit tests, even something as simple as SocketConnectTest fails in assertLocalAddress(InetSocketAddress), and the same with a lot of the other tests.

I didn't expect this since my test server seems to work fine with it (runs on Windows), and performs significantly better than when using the equivalent NIO classes. In a typical publish-subscribe scenario where each message has to be sent to several clients, with as little latency as possible, then as mentioned when using these AIO classes on the server-side, it results in less CPU usage, which in the end means a lot more concurrent connections can be handled, before we start seeing connection-related issues like packet-losses and so on.

I hope I will have time soon to look closer at why so many seemingly basic tests fails - if nobody else will be able to do it first.

**Comment by Scottmitch** [comment]
@Gambert - Thanks for the update. As you can see I don't think anyone has the bandwidth to take this on ATM ... so It would be great if you have a vested interest in this PR to bring it up to date and increase test coverage.

**Comment by normanmaurer** [comment]
Let me close this for now as there seems to be no interested anymore

**Pull request closed without merging**
