### PR TITLE
Various performance optimizations in OpenSslEngine

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

There are various places in OpenSslEngine wher we can do performance optimizations.

Modifications:

- Reduce JNI calls when possible
- Detect finished handshake as soon as possible
- Eliminate double calculations
- wrap multiple ByteBuffer if possible in a loop

Result:

Better performance

### CODE REVIEW

**Comment by normanmaurer** [comment]
@trustin please review

**Comment by normanmaurer** [comment]
@jenkins build

**Comment by normanmaurer** [comment]
@netkins build

**Comment by trustin** [comment]
Looks good to me. However, the CI job ran on a machine without OpenSSL properly configured. Please make sure that the tests for `OpenSslEngine` pass on your machine before cherry-picking.

**Comment by normanmaurer** [comment]
cherry-picked into 4.0 (f7ccdd5d3b49a699d40e0d04831f7086f9ab2be7), 4.1(f20439b6d35d47cd13bdee0dd794560bbd7b8090) and master (c0ceef25df1e24b410714cc11b420ed210494c50)

**Pull request closed without merging**
