### PR TITLE
Optimize Case Conversion Methods

### PR DESCRIPTION
**Pull request by jchrys**
Motivation:
The initial implementation utilized ternary operator, potentially impacting performance due to branching.

Modification:
The methods have been refactored, employing bitwise operations to achieve the same functionality without relying on branching.

Result:
Improved performance of the case conversion methods.

### CODE REVIEW

**Comment by jchrys** [comment]
I am currently running a benchmark on my Apple M1 chip. I will share the results shortly.

**Comment by jchrys** [comment]
Closed this pull request. The benchmark results indicate that the new implementation is slower than the original implementation when processing random byte arrays. A brief benchmark on a byte array containing only alphabet characters has led to incorrect expectations.

**Comment by franz1981** [comment]
@jchrys share the benchmark and numbers and I can help :)

**Comment by jchrys** [comment]
@franz1981 I really appreciate for your comment! and help.

Regarding the benchmark results, I ran the tests using `41x-perf-to-x-case-bench`, which can be found at this location: (https://github.com/jchrys/netty/tree/41x-perf-to-x-case-bench). Unfortunately, I deleted the specific results, but they clearly indicated a 20%ish decrease in performance compared to the original implementation. 

I'll definitely give it another shot with SplittableRandom.

Once again, thanks you for your support and valuable insights!

**Comment by franz1981** [comment]
Yep, often branchy approaches with repeatable patterns perform much better, but is a benchmarking quirk, unless is what happen in the real world eg validations are supposed to be...valid!

**Comment by franz1981** [comment]
Mmmm I don't understand why I see twice the results for the same conversion method...
Said that, sadly M1 doesn't have reported counters hence I cannot say *why* (you should run the bench in a Linux box using -prof perfnorm), but in short; if the real inputs in the real world are vary, the branchy version relies on how good is the branch predictor (and the JIT ti arrange branches based on path taken paths) to predict the outcome of a specific condition, while the version using a lookup table is omitted by other factors (the table is in L1 memory or not?) but its performance is not limited by past decisions.

**Comment by jchrys** [comment]
> Mmmm I don't understand why I see twice the results for the same conversion method...

The results contain both `toUpperCase(old, new)` and `toLowerCase(old, new)`, and this might be the reason for seeing the same conversion method results twice. I find it a bit confusing as well.

**Comment by franz1981** [comment]
My Sunday brain makes me very unable to understand simple things sorry 😐

**Comment by jchrys** [comment]
Hello, @franz1981 !
I have some new benchmark results to share. [(source)](https://github.com/jchrys/netty/blob/41x-perf-to-x-case-bench/microbench/src/main/java/io/netty/microbenchmark/common/AsciiStringCaseConversionBenchmark.java)
I ran the benchmark on an AWS EC2 instance with the `-prof perfnorm` option. The instance used was c4.2xlarge with 8 vCPUs(Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz).

It appears that the original implementation of the method is faster when the input is predictable but slower when it becomes unpredictable. On the other hand, the new implementation shows stable performance in both situations.


```bash
Benchmark                                          (logPermutations)  (seed)  (size)   Mode  Cnt   Score   Error   Units
AsciiStringCaseConversionBenchmark.toLowerCase                     5       1       7  thrpt   10  95.316 ± 1.187  ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                     5       1      23  thrpt   10  48.943 ± 1.149  ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                     5       1      47  thrpt   10  27.827 ± 0.461  ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                     5       1      97  thrpt   10  14.449 ± 0.166  ops/us

AsciiStringCaseConversionBenchmark.toLowerCase                    11       1       7  thrpt   10  76.466 ± 0.316  ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                    11       1      23  thrpt   10  26.464 ± 0.067  ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                    11       1      47  thrpt   10  13.498 ± 0.001  ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                    11       1      97  thrpt   10   7.135 ± 0.003  ops/us

AsciiStringCaseConversionBenchmark.toLowerCase                    23       1       7  thrpt   10  60.499 ± 0.065  ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                    23       1      23  thrpt   10  23.541 ± 0.040  ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                    23       1      47  thrpt   10  13.017 ± 0.090  ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                    23       1      97  thrpt   10   6.960 ± 0.006  ops/us


AsciiStringCaseConversionBenchmark.toLowerCaseNew                  5       1       7  thrpt   10  83.944 ± 0.024  ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseNew                  5       1      23  thrpt   10  38.287 ± 0.026  ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseNew                  5       1      47  thrpt   10  21.080 ± 0.015  ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseNew                  5       1      97  thrpt   10  11.275 ± 0.004  ops/us

AsciiStringCaseConversionBenchmark.toLowerCaseNew                 11       1       7  thrpt   10  83.900 ± 0.018  ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseNew                 11       1      23  thrpt   10  38.311 ± 0.006  ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseNew                 11       1      47  thrpt   10  21.055 ± 0.019  ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseNew                 11       1      97  thrpt   10  11.262 ± 0.003  ops/us

AsciiStringCaseConversionBenchmark.toLowerCaseNew                 23       1       7  thrpt   10  81.416 ± 0.143  ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseNew                 23       1      23  thrpt   10  37.749 ± 0.055  ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseNew                 23       1      47  thrpt   10  20.704 ± 0.065  ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseNew                 23       1      97  thrpt   10  11.122 ± 0.016  ops/us

Benchmark                                          (logPermutations)  (seed)  (size)   Mode  Cnt   Score   Error   Units
AsciiStringCaseConversionBenchmark.toUpperCase                     5       1       7  thrpt   10  99.737 ± 0.128  ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                     5       1      23  thrpt   10  49.336 ± 2.918  ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                     5       1      47  thrpt   10  27.915 ± 0.194  ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                     5       1      97  thrpt   10  14.458 ± 0.088  ops/us

AsciiStringCaseConversionBenchmark.toUpperCase                    11       1       7  thrpt   10  76.169 ± 0.187  ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                    11       1      23  thrpt   10  26.173 ± 0.053  ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                    11       1      47  thrpt   10  13.187 ± 0.013  ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                    11       1      97  thrpt   10   7.102 ± 0.006  ops/us

AsciiStringCaseConversionBenchmark.toUpperCase                    23       1       7  thrpt   10  60.992 ± 0.050  ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                    23       1      23  thrpt   10  23.699 ± 0.040  ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                    23       1      47  thrpt   10  13.036 ± 0.053  ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                    23       1      97  thrpt   10   6.931 ± 0.010  ops/us


AsciiStringCaseConversionBenchmark.toUpperCaseNew                  5       1       7  thrpt   10  79.761 ± 0.042  ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseNew                  5       1      23  thrpt   10  38.260 ± 0.137  ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseNew                  5       1      47  thrpt   10  21.116 ± 0.007  ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseNew                  5       1      97  thrpt   10  11.533 ± 0.017  ops/us

AsciiStringCaseConversionBenchmark.toUpperCaseNew                 11       1       7  thrpt   10  79.636 ± 0.703  ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseNew                 11       1      23  thrpt   10  38.372 ± 0.007  ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseNew                 11       1      47  thrpt   10  21.062 ± 0.005  ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseNew                 11       1      97  thrpt   10  11.524 ± 0.006  ops/us

AsciiStringCaseConversionBenchmark.toUpperCaseNew                 23       1       7  thrpt   10  77.701 ± 0.076  ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseNew                 23       1      23  thrpt   10  37.828 ± 0.062  ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseNew                 23       1      47  thrpt   10  20.732 ± 0.072  ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseNew                 23       1      97  thrpt   10  11.365 ± 0.013  ops/us
```

**Comment by franz1981** [comment]
Thanks to have tried; so, the short answer is, depends if the real method is exposed to this level of unpredictability in real world. In which case the more stable nature of a branchless approach paid off
eg the indexOf method I have implemented was mean to find   end-of-line for HTTP 1.1 inputs, which rarely follow predictable patterns.
The next step imo is to find out how to make it fast enough even in the predictable case and I would inspect perfasm.
If you have table lookup approach in general is to try hard save bound checks to happen

**Comment by jchrys** [comment]
Thank you very much for your valuable answer & guidance.

I'm really grateful for the guidance you provided, and I will definitely make an effort to improve using perfasm and investigating `indexOf` implementation more. It seems to be a challenging journey ahead, but it's also quite intriguing.

Regarding the table lookup approach, I had excluded it previously because the local benchmark results showed it was slower than the branchless approach. However, I will also work on improving the table lookup approach.

Once again, thank you so much 👍

**Pull request closed without merging**
