### PR TITLE
Revert "Add PooledSlicedByteBuf and PooledDuplicatedByteBuf"

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
Currently the "derived" buffer will only ever be recycled if the release call is made on the "derived" object, and the "wrapped" buffer ends up being "fully released" (aka refcount goes to 0). From my experience this is not the common use case and thus the "derived" buffers will not be recycled.

Modifications:
- revert https://github.com/netty/netty/pull/3788

Result:
Less complexity, and less code to create new objects in majority of cases."

### CODE REVIEW

**Comment by normanmaurer** [comment]
+1

**Comment by Scottmitch** [comment]
I will submit a followup PR to restore changes we want (reseting the indexes, etc..)

**Comment by Scottmitch** [comment]
Cherry-picked 4.0 (33001e8) 4.1 (e280251) master (77ff24b)

Each commit was a `git revert` for the commits listed in #3788.

**Comment by ninja-** [comment]
@Scottmitch while using netty .30 I noticed that pooledslicedbytebuf isn't recycled properly _anyway_ (frame decoder = more gc pressure). now that I see it removed for future netty version, are you planning something related to this so it could be recycled or something?

**Comment by Scottmitch** [comment]
@ninja- - `.slice()` and `.duplicate()` share the same underlying data (no copy) but just maintain different indexes over the data. `copy()` not only has difference indexes, but also does not share data (makes a copy). So they are different operations.

This PR fixes the complications introduced while attempting to "pool" the "derived" (slices, duplicates) taken from pooled buffers.  However in most cases the pooling would never really happen and a new object would be allocated anyways because of the description of this PR.

Does that answer your question?

**Comment by ninja-** [comment]
@Scottmitch yes thanks for explaining. I am sticking with copy instead.

**Pull request closed without merging**
