### PR TITLE
Only suppert TLSv1.3 when JDK does support it as well

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We tightly integrate the TrustManger and KeyManager into our native SSL implementation which means that both of them need to support TLSv1.3 as protocol. This is not always the case and so can produce runtime exceptions.

As TLSv1.3 support was backported to Java8 quite some time now we should be a bit more conservative and only enable TLSv1.3 for our native implementation if the JDK implementation supports it as well. This also allows us to remove some hacks we had in place to be able to support it before in Java8.

Modifications:

- Only enable TLSv1.3 support for our native SSL implementation when the JDK supports it as well
- Remove OpenSslTlsv13X509ExtendedTrustManager as its not needed anymore

Result:

Fixes https://github.com/netty/netty/issues/11589

### CODE REVIEW

**Review by ejona86 — APPROVED** [review]
The world is a better place.

**Review by NiteshKant — APPROVED** [review]

**Review by chrisvest — APPROVED** [review]

**Comment by vkostyukov** [comment]
@normanmaurer I tried bumping our Netty version today and if I'm reading this right, this effectively disables TlSv1.3 for anyone who is on older JDKs (we're on Java 1.8.0_242 as far as I can tell). These are the failures I see:

```
java.lang.IllegalArgumentException: Protocol TLSv1.3 is not supported.
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.setEnabledProtocols0(ReferenceCountedOpenSslEngine.java:1749)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.setEnabledProtocols(ReferenceCountedOpenSslEngine.java:1739)
	at com.twitter.finagle.ssl.SslConfigurations$.configureProtocols(SslConfigurations.scala:126)
	at com.twitter.finagle.ssl.client.SslClientEngineFactory$.configureEngine(SslClientEngineFactory.scala:73)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslConfigurations$.createClientEngine(Netty4ClientSslConfigurations.scala:115)
	at com.twitter.finagle.mtls.client.ReloadingClientEngineFactory.apply(ReloadingClientEngineFactory.scala:62)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslChannelInitializer.$anonfun$initChannel$1(Netty4ClientSslChannelInitializer.scala:141)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslChannelInitializer.$anonfun$initChannel$1$adapted(Netty4ClientSslChannelInitializer.scala:138)
	at scala.Option.foreach(Option.scala:407)
```

What I'm trying to figure out is if this was intentional or not?

**Comment by normanmaurer** [comment]
@vkostyukov yes it was as we delegate to the JDK and had a hack before which we removed as it could cause issues

**Comment by vkostyukov** [comment]
> @vkostyukov yes it was as we delegate to the JDK and had a hack before which we removed as it could cause issues

I see. It certainly wasn't causing issues to us but I did read the linked issue and saw that there were some problems on other JVMs.

I think TLSv1.3 has been backported to 8u261. Sounds like we'd need to either upgrade or stick to the previous Netty version for a time being.

**Comment by normanmaurer** [comment]
Yeah … u261 is out for a long time . Can’t you just upgrade ? I mean I could also add it back with some system property if we really need too

**Pull request merged**
