### PR TITLE
KObjectHashMap probeNext improvement

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
KObjectHashMap.probeNext(..) usually involves 2 conditional statements and 2 aritmatic operations. This can be improved to have 0 conditional statements.

Modifications:
- Use bit masking to avoid conditional statements

Result:
Improved performance for KObjecthashMap.probeNext(..)

### CODE REVIEW

**Comment by Scottmitch** [comment]
@nmittler - PTAL

**Comment by normanmaurer** [comment]
@Scottmitch LGTM

**Comment by nmittler** [comment]
@Scottmitch ship it! :)

**Comment by Scottmitch** [comment]
Cherry-picked 4.1(c5faa14)

**Pull request closed without merging**
