### PR TITLE
Support for more types of DNS Records

### LINKED ISSUE #8962: netty-resolver-dns "Got bad packet: bad label type"
I have built a simple DNS proxy server using the Netty DNS resolver library. [See the code here.](https://github.com/nzhenry/dns-proxy)

It works for most queries but not all. For example, when I try to query the A records for "www.apple.com" using nslookup or dig, it fails intermittently with this error:
```;; Got bad packet: bad label type
305 bytes
ca 20 80 00 00 01 00 04 00 00 00 01 03 77 77 77          .............www
05 61 70 70 6c 65 03 63 6f 6d 00 00 01 00 01 03          .apple.com......
77 77 77 05 61 70 70 6c 65 03 63 6f 6d 00 00 05          www.apple.com...
00 01 00 00 00 37 00 1b 03 77 77 77 05 61 70 70          .....7...www.app
6c 65 03 63 6f 6d 07 65 64 67 65 6b 65 79 03 6e          le.com.edgekey.n
65 74 00 03 77 77 77 05 61 70 70 6c 65 03 63 6f          et..www.apple.co
6d 07 65 64 67 65 6b 65 79 03 6e 65 74 00 00 05          m.edgekey.net...
00 01 00 00 30 2b 00 2f 03 77 77 77 05 61 70 70          ....0+./.www.app
6c 65 03 63 6f 6d 07 65 64 67 65 6b 65 79 03 6e          le.com.edgekey.n
65 74 0b 67 6c 6f 62 61 6c 72 65 64 69 72 06 61          et.globalredir.a
6b 61 64 6e 73 c0 41 03 77 77 77 05 61 70 70 6c          kadns.A.www.appl
65 03 63 6f 6d 07 65 64 67 65 6b 65 79 03 6e 65          e.com.edgekey.ne
74 0b 67 6c 6f 62 61 6c 72 65 64 69 72 06 61 6b          t.globalredir.ak
61 64 6e 73 03 6e 65 74 00 00 05 00 01 00 00 0c          adns.net........
b7 00 19 05 65 36 38 35 38 05 64 73 63 65 39 0a          ....e6858.dsce9.
61 6b 61 6d 61 69 65 64 67 65 c0 41 05 65 36 38          akamaiedge.A.e68
35 38 05 64 73 63 65 39 0a 61 6b 61 6d 61 69 65          58.dsce9.akamaie
64 67 65 03 6e 65 74 00 00 01 00 01 00 00 00 11          dge.net.........
00 04 68 5f a0 7e 00 00 29 10 00 00 00 00 00 00          ..h_....).......
00                                                       .
```
When it fails the debug log looks like this:
```DefaultDnsQuestion(www.apple.com. IN A)
DefaultDnsRawRecord(www.apple.com. 885 IN CNAME 27B)
DefaultDnsRawRecord(www.apple.com.edgekey.net. 10239 IN CNAME 47B)
DefaultDnsRawRecord(www.apple.com.edgekey.net.globalredir.akadns.net. 441 IN CNAME 25B)
DefaultDnsRawRecord(e6858.dsce9.akamaiedge.net. 9 IN A 4B)] RECEIVED: [[[id: 0xc9dafb10], 36804, /192.168.1.1:53, DatagramDnsResponse(from: /192.168.1.1:53, to: /0:0:0:0:0:0:0:0:51678, 36804, QUERY(0), NoError(0), RD RA)
DefaultDnsQuestion(www.apple.com. IN A)
DefaultDnsRawRecord(www.apple.com. 885 IN CNAME 27B)
DefaultDnsRawRecord(www.apple.com.edgekey.net. 10239 IN CNAME 47B)
DefaultDnsRawRecord(www.apple.com.edgekey.net.globalredir.akadns.net. 441 IN CNAME 25B)
DefaultDnsRawRecord(e6858.dsce9.akamaiedge.net. 9 IN A 4B)]: {}], {}
```
When it succeeds the log looks like this:
```DefaultDnsQuestion(www.apple.com. IN A)
DefaultDnsRawRecord(www.apple.com. 881 IN CNAME 27B)
DefaultDnsRawRecord(www.apple.com.edgekey.net. 10235 IN CNAME 50B)
DefaultDnsRawRecord(www.apple.com.edgekey.net.globalredir.akadns.net. 437 IN CNAME 28B)
DefaultDnsRawRecord(e6858.dsce9.akamaiedge.net. 5 IN A 4B)
DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)] RECEIVED: [[[id: 0xc9dafb10], 37086, /192.168.1.1:53, DatagramDnsResponse(from: /192.168.1.1:53, to: /0:0:0:0:0:0:0:0:51678, 37086, QUERY(0), NoError(0), RD RA)
DefaultDnsQuestion(www.apple.com. IN A)
DefaultDnsRawRecord(www.apple.com. 881 IN CNAME 27B)
DefaultDnsRawRecord(www.apple.com.edgekey.net. 10235 IN CNAME 50B)
DefaultDnsRawRecord(www.apple.com.edgekey.net.globalredir.akadns.net. 437 IN CNAME 28B)
DefaultDnsRawRecord(e6858.dsce9.akamaiedge.net. 5 IN A 4B)
DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)]: {}], {}
```
Notice the additional OPT record when it succeeds. This appears to be the key. I just don't know how I can fix the problem when it fails.

I've discovered that if I remove the CNAME records from the response, then the query resolves with no errors. I would like to return a proper copy of the server response including the CNAME records. Any help would be greatly appreciated!

### PR DESCRIPTION
**Pull request by qeesung**
Motivation:
Current DNS encoding and decoding only supports a few record types (PTR, OPT), but DNS records have many kinds, such as type A, NS, CNAME, MX and so on.

Modification:
Add different types of DNS Records and codec.

Currently only the following types are supported:

A, NS, CNAME, SOA, PTR, MX, TXT, RP, AFSDB, SIG, AAAA, OPT(LLQ, SUBNET)

Result:
Fixes #8962

### CODE REVIEW

**Comment by qeesung** [comment]
If there is no problem with this patch, I will support more types of records in the future. 😄

**Comment by qeesung** [comment]
@normanmaurer Would you please take a moment to review this patch?

**Comment by normanmaurer** [comment]
@qeesung yes I will... but it may take a bit, sorry :/

**Comment by qeesung** [comment]
@normanmaurer thank you, I rebased the 4.1 branch to resolve the conflict.

**Comment by normanmaurer** [comment]
@qeesung do you think we can do this without breaking any API's ? If not we would need to target the master branch.

**Comment by qeesung** [comment]
@normanmaurer It's been a long time. I need to take a moment to review the code.

**Comment by normanmaurer** [comment]
@qeesung let me know once you did...

**Comment by qeesung** [comment]
@normanmaurer I'm sorry for being so late. I'm a little busy recently.

I reviewed the code again. This PR will break the existing API and have some compatibility problems:
1. Removed the existing specific DNS type classes, such as `DnsOptEcsRecord`, `DnsOptPseudoRecord`.
2. `DefaultDnsRecordDecoder` will decode more specific DNS type objects. The existing API implementation only supports PTR type and text type, and the unsupported types will return `DefaultDnsRawRecord` objects. Although they are all subclasses of `DnsRecord`, the internal implementation has changed, which may lead to incompatibility.

So for compatibility, the master branch is more suitable.

**Comment by normanmaurer** [comment]
Sorry but for now I will close this. Please re-open after rebasing if you are still interested

**Pull request closed without merging**
