### PR TITLE
[#5507] SingleThreadEventExecutor should reject call invoke*() from w…

### PR DESCRIPTION
**Pull request by normanmaurer**
…ithin the EventLoop.

Motivation:

ExecutorService.invoke*(...) methods may block by API definition. This can lead to deadlocks if called from inside the EventLoop in SingleThreadEventExecutor as it only has one Thread that does all the work.

Modifications:

Throw a RejectedExectionException if someone tries to call SingleThreadEventExecutor.invoke*(...) while in the EventLoop.

Result:

No more deadlock possible.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler @trustin PTAL

**Comment by nmittler** [comment]
LGTM

**Comment by Scottmitch** [comment]
lgtm

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (ce95c50) and 4.0 (438b29f)

**Pull request closed without merging**
