### PR TITLE
Retain AbstractBinaryMemcacheDecoder.currentMessage when sending it o…

### PR DESCRIPTION
**Pull request by windie**
…ut and release it when it's not used.

Motivation:

AbstractBinaryMemcacheDecoder.currentMessage is not retained after sending it out. Hence, if a message contains `extras`, `io.netty.util.IllegalReferenceCountException` will be thrown in `channelInactive`.

Modifications:

Retain AbstractBinaryMemcacheDecoder.currentMessage After putting it to `out` and release it when it's not used.

Result:

No IllegalReferenceCountException or leak.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@windie LGTM..

@daschl ok ?

**Comment by daschl** [comment]
@normanmaurer @windie in the catch block we are passing the invalid chunk up the pipeline with out.add, right? So if you release it here it won't be accessible up the pipeline?

**Comment by normanmaurer** [comment]
@daschl link ?

**Comment by daschl** [comment]
@normanmaurer here for example: https://github.com/windie/netty/commit/b43d57f8c76c62571f934d401e0ab44e9194c97c#diff-a5317e7fab57c10c246e483c669307ecR159 .. to me it seems it is released but next line its passed up the the chain as invalid chunks.

**Comment by normanmaurer** [comment]
@daschl I may be missing something but doesn't invalidChunk(...) return a new object and so its ok to release the currentMessage ?

**Comment by daschl** [comment]
aah right! then LGTM :)

**Comment by normanmaurer** [comment]
@windie thanks again!

Cherry-picked into 4.1 as 4606890513f72a620aa29fb7b446cd8e2d3ae5fc

**Pull request closed without merging**
