### PR TITLE
Extract the builder of CorsConfig to top level

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

Consistency in API design

Modifications:

- Deprecate CorsConfig.Builder and its factory methods
- Deprecate CorsConfig.DateValueGenerator
- Add CorsConfigBuilder and its factory methods
- Fix typo (curcuit -> circuit)

Result:

Consistency with other builder APIs such as SslContextBuilder and
Http2ConnectionHandlerBuilder

### CODE REVIEW

**Comment by trustin** [comment]
@Scottmitch @danbev PTAL

**Comment by normanmaurer** [comment]
@trustin looks good.

**Comment by danbev** [comment]
@trustin :+1:

**Comment by trustin** [comment]
Cherry-picked: 412f719 (4.1)

**Pull request closed without merging**
