### PR TITLE
Java 8 migration. Similar catch blocks joined

### PR DESCRIPTION
**Pull request by doom369**
Motivation:

Avoid IDE warnings, easier to read.

Modification:

Same catch blocks joined.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@doom369 please fix check style :)

**Comment by doom369** [comment]
Sure. Fixed.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Pull request merged**
