### PR TITLE
Small typos fixes

### PR DESCRIPTION
**Pull request by pdalpra**
This PR fixes some (very) small typos in Channel's Javadoc.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@pdalpra could you please sing our ICLA:
http://tinyurl.com/netty-icla

**Comment by CruzBishop** [comment]
♫ He is singing your ICLA ♪♩

Sorry, I couldn't resist :)

**Comment by pdalpra** [comment]
:)
@normanmaurer Just signed it !

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (2221dc6b20e38cc84e5c17ef27d35266b3def554) , 4.1 (2ebf07e62234d02804a6707957288f4292294f16) and master (d7581e57269eb291b3cec217c5beaf25e76a90af)

**Pull request closed without merging**
