### PR TITLE
clear code about Websocket drafts

### PR DESCRIPTION
**Pull request by moons7**
Motivation:

linked #8529

Modification:

clear code about Websocket drafts and only retain tests for version 13

Result:

only support the final websocket rtc

### CODE REVIEW

**Review by hyperxpro — CHANGES_REQUESTED** [review]
We cannot remove the WebSocket drafts code. Unacceptable change.

**Comment by slandelle** [comment]
@hyperxpro This PR is for master = Netty 5

**Comment by hyperxpro** [comment]
> @hyperxpro This PR is for master = Netty 5

Sorry for the wrong review. I think I need to get my eyes rechecked. :p

**Comment by normanmaurer** [comment]
There is a compile error... Let's close this and re-open once fixed

**Pull request closed without merging**
