### PR TITLE
Some small improvements

### PR DESCRIPTION
**Pull request by skyguard1**
Motivation:
Some small improvements

Modification:

1.The minimum or the maximum of two numbers can be calculated by means of `Math.max()` or `Math.min()` instead of doing it manually.
2.Simplify the judgment of size
3.When the collection is initialized, specify the initial value of the collection.

Result:
The code is more efficient than the original implementation

### CODE REVIEW

**Review by NiteshKant — APPROVED** [review]

**Comment by NiteshKant** [comment]
Thanks a lot @skyguard1

**Comment by skyguard1** [comment]
@NiteshKant It is my pleasure

**Comment by skyguard1** [comment]
@NiteshKant  Could you please re-run ci build? Thanks

**Comment by chrisvest** [comment]
@skyguard1 Try rebasing.

**Pull request merged**
