### PR TITLE
Removed redundant assignment

### PR DESCRIPTION
**Pull request by terrarier2111**
Motivation:

Found a redundant assignment.

Modification:

Removed the redundant assignment.

Result:

Minor performance improvement.

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Review by hyperxpro — CHANGES_REQUESTED** [review]
It's not a redundant assignment. It needs to be initialized with 0 so we can further increment it.

**Comment by terrarier2111** [comment]
But java itself is initializing it with its default value so where us the point in assigning a value in the constructor which is already present

**Comment by normanmaurer** [comment]
@hyperxpro this change looks correct.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by hyperxpro** [comment]
Looks like I should review codes in a better way. ;/

**Comment by hyperxpro** [comment]
You should replace this with `ObjectUtil#checkPositive`.

https://github.com/netty/netty/blob/a882a3e774a760924815cb34c6020156e168611a/handler/src/main/java/io/netty/handler/stream/ChunkedNioStream.java#L58

**Comment by normanmaurer** [comment]
@terrarier2111 thanks a lot

**Pull request merged**
