### PR TITLE
MemoryRegionCache$Entry objects are not recycled

### LINKED ISSUE #4071: MemoryRegionCache$Entry objects are not recycled
Netty Version: 4.0.30.Final

MemoryRegionCache$Entry instances are allocated from a Recycler but not recycled when done using them, leading to a lot of GCed objects.

### PR DESCRIPTION
**Pull request by merlimat**
Motivation:

Even though `MemoryRegionCache$Entry` instances are allocated through a recycler they are not properly recycled,
leaving a lot of instances to be GCed along with `Recycler$DefaultHandle` objects.
Fixes #4071

Modification:

Recycle `Entry` when done using it.

Result:

Less GCed objects.

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by normanmaurer** [comment]
@netkins accept

**Comment by normanmaurer** [comment]
@merlimat looks good! Can you please sign our ICLA so I can merge this ?
http://netty.io/s/icla

**Comment by merlimat** [comment]
@normanmaurer Thanks, I already signed that.

**Comment by normanmaurer** [comment]
@merlimat sorry for the delay..

Cherry-picked into 4.0 (53f9438aec259f267b90f45fc21e4250d74217b5), 4.1 (0be53f296f8c0342fb9f5c4dd69cd2f3f5bd6ddf) and master (de4b7145a9a7e383f133f7d6aafd5fd65df4d07f)

**Pull request closed without merging**
