### PR TITLE
Support removal using values iterator.

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Motivation:

As ActiveMQ project using netty, we want to make use of this class, unfortunately the iterator on values(), seems to not support remove method, even so the delegated iterator does. Currently we have to clone and modify this class locally albeit a one line change is needed, it would be ideal if netty could allow remove, then removing the need to maintain a clone.  

Modifications:

* remove throws UnsupportedOperationException, and instead call remove method on delegated iterator

Result

* allows users of the collection when iterating over values to call remove.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot Test this please

**Comment by normanmaurer** [comment]
@michaelandrepearce there is a `KObjectHashMapTest.template` that you can modify.

**Comment by normanmaurer** [comment]
@michaelandrepearce also can you please sign our icla: https://netty.io/s/icla

**Comment by michaelandrepearce** [comment]
@normanmaurer i signed this back in 2017.
see.
https://github.com/netty/netty/pull/7077

**Comment by normanmaurer** [comment]
@michaelandrepearce ah right... sorry did miss it. Then please just add the unit test and I will merge it :)

**Comment by normanmaurer** [comment]
@michaelandrepearce ping

**Comment by normanmaurer** [comment]
@michaelandrepearce I just merged this one and opened https://github.com/netty/netty/pull/8891 for a testcase.

**Pull request merged**
