### PR TITLE
Improve performance of StringUtil.simpleClassName()

### PR DESCRIPTION
**Pull request by jingene**
(netty 4.0)

Motivation:
static Package getPackage(Class<?> c) uses synchronized block internally.
(for get a package from "pkgs" Map)
It may be hotspot when called frequently.

(related dumps)
- java.lang.Thread.State: BLOCKED (on object monitor)
  at java.lang.ClassLoader.getPackage(ClassLoader.java:1651)
  - locked <0x00000007729bc028> (a java.util.HashMap)
  at java.lang.Package.getPackage(Package.java:332)
  at java.lang.Class.getPackage(Class.java:717)
  at io.netty.util.internal.StringUtil.simpleClassName(StringUtil.java:309)
  at io.netty.util.internal.StringUtil.simpleClassName(StringUtil.java:296)
  at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1103)

Modifications:
use "org.apache.commons.lang.ClassUtils.getShortCanonicalName()" instead of  "clazz.getPackage()"

Result:
Hotspot is disappeared.

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by normanmaurer** [comment]
@jingene thanks..  But we have a zero-dependency rule for our core (which includes the common module). Maybe we should just merge the related code of them into ours. Let me check what this would take or would you like to do this by yourself ?

**Comment by normanmaurer** [comment]
@jingene also you may want to sign the ICLA if you plan to contribute. We require to have all authors sign it:

http://tinyurl.com/netty-icla

**Comment by normanmaurer** [comment]
@jingene I just checked the source-code of this implementation and it should be very easy to just "copy it". So my suggestion is to "just" copy the code into our implementation. 

You can find the source here:
https://github.com/apache/commons-lang/blob/trunk/src/main/java/org/apache/commons/lang3/ClassUtils.java

Once this is done we need to update the LICENSE stuff as we then include something that was written not by us.

Let me know if you want to do this or if I should just do it. 

In any case good find!

**Comment by jingene** [comment]
@normanmaurer 
OK. I'll check it out. thanks :)

**Comment by normanmaurer** [comment]
@jingene thanks you! We love contributions and feedback. Let me know if you have any questions or need help. Happy to assist.

**Comment by normanmaurer** [comment]
@jingene I had some time and will submit a fix for this shortly!

**Comment by jingene** [comment]
@normanmaurer
I'm sorry I'm late.
I copied ClassUtils(commons.lang3) code into netty, but not copied all.
because ClassUtils has needless dependency(not use in netty(ArrayUtils, StringUtils, MutableObject etc..)
And I copied some commons.lang3.StringUtils methods(isEmpty, deleteWhitespace) into StringUtil
Please check this.

**Comment by normanmaurer** [comment]
@jingene I think we just need to merge parts of the `ClassUtils.getShortClassName` into StringUtils. That said I have the change for this already here, just want to write some more unit tests. So Just wait and I will commit the code. Thanks again for the report and the idea @jingene

**Comment by normanmaurer** [comment]
Super-seeded by #3652. @jingene please check

**Comment by jingene** [comment]
@normanmaurer 
I checked the committed code. Thank you for your modifications:)

**Pull request closed without merging**
