### PR TITLE
Java 8 migration: omitted explicit argument

### PR DESCRIPTION
**Pull request by thinkerou**
Motivation:

Calls to parametrized methods where explicit argument types can be omitted.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@thinkerou can you please sign our ICLA and let me know once done:

https://netty.io/s/icla

**Comment by thinkerou** [comment]
@normanmaurer done!

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@thinkerou can I ask you to also fix all the others ? I am sure there are more :)

**Comment by thinkerou** [comment]
@normanmaurer I'm glad, I will commit tonight.

**Comment by normanmaurer** [comment]
@thinkerou thanks a lot.. just make it part of this pr.

**Comment by thinkerou** [comment]
@normanmaurer done!

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@thinkerou thanks!

**Pull request merged**
