### PR TITLE
Refactoring to move ascii related methods from ByteString to AsciiString

### PR DESCRIPTION
**Pull request by Spikhalskiy**
Motivation:

ByteString contains some bugs (tests provided) + there is some mess now related to ascii-only code in general ByteString while we have AsciiString

Modifications:

1) Http2 headers have been refactored to use AsciiString instead of ByteString, because 1. they already use ascii-only methods of ByteString thru ByteStringValueConverter 2. It's valid according to spec https://http2.github.io/http2-spec/#HttpHeaders

2) Ascii-only methods moved down to AsciiString and classes using this method refactored to use AsciiString class

3) Error in constructor of ByteString fixed, incorrect method fromChar moved down to AsciiString and implemented for Ascii correctly

Result:

Mostly cleanup changes to make structure and usage of AsciiString class and methods implemented only for Ascii clear.

### CODE REVIEW

**Comment by Spikhalskiy** [comment]
Started to work on #4331 and found some mess from my point of view around ByteString and AsciiString, decided to propose this refactoring as a first step.

**Comment by Scottmitch** [comment]
@Spikhalskiy - Thanks for the PR! Can you separate the bug (and associated unit tests) referenced in your `#3` from any larger restructuring?

Also I'm not sure moving HTTP/2 from using `ByteString` to `AsciiString` makes sense. HTTP/2 headers are generally not restricted to ascii encoding and can generally carry arbitrary bytes (https://tools.ietf.org/html/rfc7541#section-1.3). However because HTTP/2 is more of a framing layer around HTTP/1.x semantics it can cross over into the HTTP/1.x domain where headers are ASCII (https://tools.ietf.org/html/rfc7230#section-3.2).  `ByteString` was introduced in part to clarify this distinction and separate concerns of ASCII only concerns with more general byte operations. That is not to say we can't restructure a bit but I think it would be worth discussing options before putting in too much effort. @nmittler - WDYT?

**Comment by Spikhalskiy** [comment]
Hi @Scottmitch, thanks for comment.

> Can you separate the bug (and associated unit tests) referenced in your #3 from any larger restructuring?

Nope, because main bug here is design bug ByteString contains code related to some specific encoding while ByteString even doesn't know encoding of underlying bytes.

Let's take a look deeply.
ByteString#parseChar(int index):
```
    public char parseChar(int start) {
        if (start + 1 >= length()) {
            throw new IndexOutOfBoundsException("2 bytes required to convert to character. index " +
                    start + " would go out of bounds.");
        }
        final int startWithOffset = start + offset;
        return (char) (((value[startWithOffset] & 0xFF) << 8) | (value[startWithOffset + 1] & 0xFF));
    }
```

1. ByteString has no information about own encoding and implements method parseChar()?
2. Even if ByteString knows it's encoding - it's impossible to implement this method effectively for UTF-8 for example. It can be implemented only by iteration because we don't know where "start" char located.
3. We use this method in ByteStringValueConverter#convertToChar for HTTP2 headers. It should parse ASCII char by spec when it actually parse... I don't know... UTF-16 and look like it's implemented incorrectly.

On the same time, this method using actually for ASCII and can be implemented for ASCII easily and effectively - so fixed by moving and reimplementing.

> Also I'm not sure moving HTTP/2 from using ByteString to AsciiString makes sense. HTTP/2 headers are generally not restricted to ascii encoding and can generally carry arbitrary bytes.

Yep, AsciiString is ByteString, so it contains arbitrary bytes and we can work with this as bytes, so it's correct. But if we works as text with it - it should be ASCII and we already consider it as ASCII  Take a look at ByteStringValueConverter#convertToShort for example.

**Comment by Scottmitch** [comment]
@Spikhalskiy - Yes `parseChar()` does not take into account any character encoding, and is just converting from byte[2] to char (independent of encoding).  Adding a `Charset` encoding parameter to this method that seems fine (and throw for charsets which are not feasible, or if the character can't fit in a char which may happen for UTF-8).

> it should be ASCII and we already consider it as ASCII

Nothing in the core makes assumptions about character encoding.  `ValueConverter` exists because we have methods on `Headers` which expose native types for getters/setters.  I'm not convinced it *should* or *has* to be ASCII. I think we should consider the alternative approaches of either 1. allow the user to plugin a `ValueConverter` if the default doesn't make sense, or 2. take character encoding into account where it makes sense to provide a more complete default.

**Comment by Scottmitch** [comment]
> Nope, because main bug here is design bug ByteString contains code related to some specific encoding while ByteString even doesn't know encoding of underlying bytes.

I was referring to https://github.com/netty/netty/pull/4391/files#diff-6aa19f105e3757b951056afc49f45962L207
```diff
-        CharBuffer cbuf = CharBuffer.wrap(value, start, start + length);
+        CharBuffer cbuf = CharBuffer.wrap(value, start, length);
```

which seems independent from all other refactoring.

**Comment by Spikhalskiy** [comment]
> Yes parseChar() does not take into account any character encoding, and is just converting from byte[2] to char (independent of encoding). Adding a Charset encoding parameter to this method that seems fine (and throw for charsets which are not feasible, or if the character can't fit in a char which may happen for UTF-8).

**Comment by Spikhalskiy** [comment]
> Yes parseChar() does not take into account any character encoding, and is just converting from byte[2] to char (independent of encoding). Adding a Charset encoding parameter to this method that seems fine (and throw for charsets which are not feasible, or if the character can't fit in a char which may happen for UTF-8).

This method moved down to AsciiString. No need to implement general version for all charsets. You want to add great-switch or strategies in ByteString for different encodings? For this purpose we have subclasses, which are strategies in fact, which can provide encode-specific and optimizing methods for each encoding. But now we need only version for Ascii strings, so this method should be just in AsciiString. If we will need this method for all encodings - we will not implement it in any case for byte representation. So, we don't need to generalize and make complicated general purpose things when we need only Ascii version and we already have separate class for it. + We already have methods implemented only for ASCII - all this parse*Ascii methods, that should be in AsciiString.

Abstract question - you just prefer to leave everything as it is? So, half of methods for ascii encoding in AsciiString and half in ByteString and without any rules and system. So, me as new contributor just think "WTF? Where I should put my new string logic and by which rules and what's going on here at all?" Or something other to formalize this mess?

> Nothing in the core makes assumptions about character encoding.
Great, we don't need to use AsciiString in core. Just continue to use ByteString in core. All fixes related to http and http2 headers support, which are bytes or ascii by spec - so it's absolutely AsciiString, which is ByteString with encoding-specific parsing methods. And they use ascii methods, which should be in AsciiString if we have this class. Or AsciiString should be deleted and all encoding & ascii-related methods should be moved to static helper methods.

**Comment by Scottmitch** [comment]
> Abstract question - you just prefer to leave everything as it is?

No but I'm not sure this PR covers what it should. Having methods specific to encoding in `ByteString` is not ideal, and it would be nice to move them to AsciiString. It may make sense to have `AsciiString` (or `CharSequence`) represent the key type (assuming we don't want to expose HPACK under pinnings), but I don't think it makes sense to have `AsciiString` as the value type . All of the methods in question (called from `ByteStringValueConverter`) operate on the the value types, and so I'm not sure using `AsciiString` will help.

On a somewhat related note...It may make sense to expand `Headers<T>` to `Headers<K, V>`.  For all inheriting types of `Headers`, `K = V`except for `Http2Headers<CharSequence, ByteString>`.  This may also simplify the relationship between `ByteString` and `AsciiString` where the `equals` and `hashCode` have to line up for case sensitive and case insensitive (and at the very least remove 1 `int` for each `AsciiString`). @nmittler @normanmaurer - WDYT? I can throw something together if this makes sense.

**Comment by nmittler** [comment]
@Scottmitch IIRC, we originally went the `ByteString` path in HTTP/2 because at one point, the HTTP/2 spec allowed raw bytes.  I don't believe this is the case any more, although I'm having trouble identifying the section in the spec. Certainly for HTTP/2 to be useful in the real world, it will have to play nice with HTTP/1.x semantics, which will require ascii: https://httpwg.github.io/specs/rfc7540.html#HttpHeaders.  I'm fine with switching over to `AsciiString` for HTTP/2 headers, so long as we don't necessarily lose any performance.

**Comment by nmittler** [comment]
@Scottmitch regarding your comment in https://github.com/netty/netty/pull/4391#issuecomment-151327298 ... agreed, I think the HTTP/2 headers should probably be `AsciiString` to `ByteString`.  I think your proposal makes sense ... ping me if you get a PR together.

**Comment by Spikhalskiy** [comment]
Ok, I will try to rework values to ByteString and leave Header's names as AsciiString when I get a chance. But more I look at this, more I think that ascii logic should be just a static helper methods. Code which works with this fields should determine the encoding and not this headers/fields itself. So, it will be much more flexible to just have ByteString everywhere and code which assumes that it should be ASCII just uses static transform methods from something like AsciiStringHelper class. Let's see what I can do with first approach and maybe take a look at static methods if it doesn't fit to current code.

**Comment by Scottmitch** [comment]
@Spikhalskiy - I have a PR in the works for this. I'll ping you for review.

**Comment by Scottmitch** [comment]
@Spikhalskiy - Thanks for pointing out the issue. I would like to close this in favor of PR https://github.com/netty/netty/pull/4413. Any objections?

**Comment by Scottmitch** [comment]
@Spikhalskiy - I will close this now. Please re-evaluate the new state and feel free to submit another PR.

**Pull request closed without merging**
