### PR TITLE
Cleanup PlatformDependent* code

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

PlatformDependent* contains some methods that are not used and some other things that can be cleaned-up.

Modifications:

- Remove unused methods
- cleanup

Result:

Code cleanup.

### CODE REVIEW

**Comment by normanmaurer** [comment]
just some cleanup

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (0c48265) and 4.0 (01d747a)

**Comment by Scottmitch** [comment]
@normanmaurer - The hyperlink for 4.1 isn't correct ... did it get merged correctly?

**Comment by normanmaurer** [comment]
@Scottmitch yep... fixed the comment.

**Pull request closed without merging**
