### PR TITLE
Update tcnative 2.0.61 -> 2.0.62

### PR DESCRIPTION
**Pull request by idelpivnitskiy**

### CODE REVIEW

**Review by chrisvest — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
This is needed to fix a crash on zipkin's alpine docker image when run on M1 macbook. Please prioritize for us, thanks!

**Comment by idelpivnitskiy** [comment]
The remaining boringssl pipelines failed 3 times in a raw, @chrisvest can you please have a look?

**Comment by codefromthecrypt** [comment]
@normanmaurer as you are no stranger to pain, wonder if you have a minute to figure this one out? It is a bit of techdebt to wrap around and override versions due to lack of merge due to failing build here 🙏

**Comment by codefromthecrypt** [comment]
this is a dupe of #13654 (which is also broke), maybe we can close one and try to get this resolved. It is pretty crufty to override this dep for all platforms downstream. It looks like this.. 

```xml
  <dependencies>
    <dependency>
      <groupId>com.linecorp.armeria</groupId>
      <artifactId>armeria</artifactId>
      <exclusions>
        <!-- temporary until netty includes https://github.com/netty/netty/pull/13724 -->
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-tcnative-boringssl-static</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <!-- temporary until netty includes https://github.com/netty/netty/pull/13724 -->
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.62.Final</version>
      <classifier>linux-x86_64</classifier>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.62.Final</version>
      <classifier>linux-aarch_64</classifier>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.62.Final</version>
      <classifier>osx-x86_64</classifier>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.62.Final</version>
      <classifier>osx-aarch_64</classifier>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.62.Final</version>
      <classifier>windows-x86_64</classifier>
      <scope>runtime</scope>
    </dependency>
```

**Comment by normanmaurer** [comment]
I will have a look... it's just that I have no time atm.

**Comment by normanmaurer** [comment]
working on this now

**Comment by normanmaurer** [comment]
The timeouts here should be fixed by https://github.com/netty/netty-tcnative/pull/846

**Comment by normanmaurer** [comment]
Let me close this as I will open a new one to upgrade to 2.0.63.Final

**Comment by codefromthecrypt** [comment]
@normanmaurer thanks a lot for focus on this. build fix looked like it required eagle eyes and glad you have them! cheers

**Comment by codefromthecrypt** [comment]
ps I opened https://github.com/netty/netty-tcnative/issues/853 for follow-up

**Pull request closed without merging**
