### PR TITLE
Fix deprecated GC logging switch

### PR DESCRIPTION
**Pull request by alexbudgh**
Motivation:

This caused test failures due to the deprecation warning and produced a
dumpstream.

Modification:

Replace deprecated flag with recommended one.

Result:
Fix deprecation and cause of test failure in codec project.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@alexbudgh on which JDK version is this ? I never saw a test-failure because of this.

**Comment by normanmaurer** [comment]
@alexbudgh also can you sign our ICLA: https://netty.io/s/icla

**Comment by alexbudgh** [comment]
This is on Apple M1 MacBook Pro.
```
% javac -version
javac 16.0.1
% java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Zulu16.30+19-CA (build 16.0.1+9)
OpenJDK 64-Bit Server VM Zulu16.30+19-CA (build 16.0.1+9, mixed mode)
```
~/src/netty/codec/target/surefire-reports/2021-06-16T19-17-33_172-jvmRun1.dumpstream:

```
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command '[0.001s][warning][gc] -XX:+PrintGCDetails is deprecated. Will use -Xlog:gc* instead.'.
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:507)
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:210)
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:177)
        at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
        at java.base/java.lang.Thread.run(Thread.java:831)

```
Will do.

**Comment by normanmaurer** [comment]
@alexbudgh I think this breaks the build on JDK8.

**Comment by chrisvest** [comment]
Yeah, it breaks the JDK8 build, so it needs to either be controlled by profiles, or only done on the `master` branch where Java 11 is the minimum supported Java version.

**Comment by normanmaurer** [comment]
@alexbudgh thanks a lot!

**Pull request merged**
