### PR TITLE
Explicit need to specify -Piouring-native to compile the native bits …

### PR DESCRIPTION
**Pull request by normanmaurer**
…of iouring transport

Motivation:

At the moment our CI can not build and run the native bits for the iouring transport so we should just not compile this at the moment. The java classes itself should still be compiled tho

Modifications:

Add explicit profile to compile native bits of iouring

Result:

CI passes with iouring transport

### CODE REVIEW

**Comment by normanmaurer** [comment]
/cc @1Jo1

Please note that you will need to specify `-Piouring-native` now when you want to compile the native bits as well.

**Comment by normanmaurer** [comment]
Also I am currently checking how we can get a build note that has the right kernel to test io_uring

**Comment by chrisvest** [comment]
Build doesn't seem to work yet. The io_uring jar is not visible to Netty/Examples?

**Comment by normanmaurer** [comment]
@chrisprobst let me move the "example code" to the io_uring transport for now.

**Comment by chrisvest** [comment]
I guess `HashedWheelTimerTest` is flaky.

**Comment by chrisvest** [comment]
Since you moved the io_uring example to the io_uring module, the example module no longer needs to depend on the io_uring module. Removing that dependency might fix the build.

**Comment by normanmaurer** [comment]
@chrisvest 🤦 ... just fixed

**Comment by normanmaurer** [comment]
Let me merge this one for now so we at least don't have the CI failing all the time

**Pull request merged**
