### PR TITLE
Replace `allLeaks` set with an AtomicBoolean variable `closed`

### LINKED ISSUE #9215: A question about allLeaks in DefaultResourceLeak
Hi community
   Recently I have gone through the code of ResourceLeakDetector and I have a question. In my opinion, the `allLeaks` set is the key to determine whether a leak exist. If the method `dispose` invoke `allLeaks.remove` before `close`, then netty will find a leak. 
  My question is, why we use a set (based on ConcurrentHashMap) to do the check, we can just use an AtomicFieldUpdate or AtomicBoolean to store the status and check leaks. The cas will have some performance advantage to `allLeaks` set.

### PR DESCRIPTION
**Pull request by ro9er**
Motivation:
Update and check the resource release status via atomic variable `closed` will have a better performance than the solution based on the `allLeaks` set, which is a ConcurrentHashMap originally.

Modification:
use an AtomicBoolean variable `closed` to mark whether the resource has been closed correctly or not (which means a leak happen). Delete the original code based on the solution of `allLeaks` set
Describe the modifications you've done.

Result:

Fixes #9215

### CODE REVIEW

**Comment by normanmaurer** [comment]
As far I know remember we need to hold a reference and thats why we used the `Set`. 

@carl-mastrangelo correct ?

**Comment by ro9er** [comment]
yeah. that's the only reason I think why use set here. But if there's no reference to the tracker object,there will always be leaks right? is there any other solution to check that?

**Comment by carl-mastrangelo** [comment]
Norman you are right.  Without holding a strong reference to the leaks, they will be GCed.

@ro9er :  if the referent is lost, we find out by noticing the reference in the queue.  If the reference is lost before the referent, we don't find out about a possibly leaked referent.

**Comment by ro9er** [comment]
Ok I got it. Thx for your help

**Pull request closed without merging**
