### PR TITLE
	DefaultPromise make listeners not volatile

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
DefaultPromise has a listeners member variable which is volatile to allow for an optimization which makes notification of listeners less expensive when there are no listeners to notify. However this change makes all other operations involving the listeners member variable more costly. This optimization which requires listeners to be volatile can be removed to avoid volatile writes/reads for every access on the listeners member variable.

Modifications:
- DefaultPromise listeners is made non-volatile and the null check optimization is removed

Result:
DefaultPromise.listeners is no longer volatile.

### CODE REVIEW

**Comment by Scottmitch** [comment]
This is the counterpart for https://github.com/netty/netty/pull/5503 for the 4.0 branch. The second commit is kept separate for now ... this commit isn't strictly related to this PR but is needed in order to backport the DefaultPromise fix.

**Comment by Scottmitch** [comment]
@normanmaurer - PTAL

**Comment by normanmaurer** [comment]
@Scottmitch LGTM

**Comment by Scottmitch** [comment]
@normanmaurer - I'll pull in after the build completes just to be double sure all is well :)

**Comment by normanmaurer** [comment]
@Scottmitch complete =P

**Comment by Scottmitch** [comment]
4.1 (4baff69)

**Pull request closed without merging**
