### PR TITLE
Migrate some tests to JUnit 5

### PR DESCRIPTION
**Pull request by kashike**
I had some free time so I thought I would start work towards completing #10757.

The following modules have been moved over, with some exceptions:

- [ ] all
- [ ] bom
- [x] buffer
  - [ ] `io.netty.buffer.ByteBufUtilTest`
  - [ ] `io.netty.buffer.search.SearchProcessorTest`
- [x] codec
  - [ ] `io.netty.handler.codec.marshalling.AbstractMarshallingTest`
- [x] codec-dns
- [x] codec-haproxy
- [ ] codec-http
- [ ] codec-http2
- [x] codec-memcache
- [ ] codec-mqtt
- [ ] codec-redis
- [x] codec-smtp
- [x] codec-socks
- [x] codec-stomp
- [x] codec-xml
- [ ] common
- [ ] dev-tools
- [ ] example
- [ ] handler
- [x] handler-proxy
- [ ] microbench
- [ ] resolver
- [ ] resolver-dns
- [ ] resolver-dns-native-macos
- [ ] tarball
- [ ] testsuite
- [ ] testsuite-autobahn
- [ ] testsuite-http2
- [ ] testsuite-native
- [ ] testsuite-native-image
- [ ] testsuite-native-image-client
- [ ] testsuite-native-image-client-runtime-init
- [ ] testsuite-osgi
- [ ] testsuite-shading
- [ ] transport
- [ ] transport-blockhound-tests
- [ ] transport-native-epoll
- [ ] transport-native-kqueue
- [ ] transport-native-unix-common
- [ ] transport-native-unix-common-tests
- [ ] transport-sctp

### CODE REVIEW

**Comment by normanmaurer** [comment]
@kashike have you signed the icla ?
https://netty.io/s/icla ?

**Comment by kashike** [comment]
I have, yes, in the past - have contributed before :smile:

**Comment by kashike** [comment]
`codec` module tests have been migrated.

**Comment by idelpivnitskiy** [comment]
@kashike we use an incremental approach in [ServiceTalk](https://github.com/apple/servicetalk/issues/1568), converting module by module. Benefits:
- PRs are small and easier to review;
- first PRs help to agree on the style of using jUnit5 (how to define parametrized tests, how to apply timeouts, etc.) without the need to redo all modules if others prefer different approach;
- faster to integrate changes, people can start using jUnit5 in some modules, while other modules still use jUnit4;

Netty is evolving quickly. If you will hold a single PR until all modules are done, you may end up in rebase hell, because too many tests will be changed while you are working on this PR. Consider opening independent PRs for each module.

**Comment by idelpivnitskiy** [comment]
@kashike and btw, thanks for the huge work!

**Comment by kashike** [comment]
@idelpivnitskiy Sure - I will split this pull request into individual pull requests.

**Comment by kashike** [comment]
I've moved the tracking list into the original issue: https://github.com/netty/netty/issues/10757#issuecomment-848445551

**Pull request closed without merging**
