### PR TITLE
Fix for https://github.com/netty/netty/issues/4296

### PR DESCRIPTION
**Pull request by jenskordowski**

### CODE REVIEW

**Comment by normanmaurer** [comment]
@jenskordowski could you please update the commit message to follow our template:

http://netty.io/wiki/writing-a-commit-message.html

And also sign the ICLA:
http://netty.io/s/icla

**Comment by normanmaurer** [comment]
@jenskordowski did you sign the icla ?

**Comment by jenskordowski** [comment]
Sorry, missed it. I just did. A LOT of overhead to fix a != to ==.

**Comment by normanmaurer** [comment]
@jenskordowski yeah sorry but we just want to ensure we not get into any legal problems later. 

Thanks again. Cherry-picked into 3.10 as de16cfe3537246d916ea966b2c9380f84d8113e8

**Comment by jenskordowski** [comment]
When is the next 3.10 release planned that will include this fix? Will this take some days, weeks or even months? A rough estimation will help.

**Comment by normanmaurer** [comment]
@jenskordowski let me cut the release this week.

**Comment by jenskordowski** [comment]
What's the status? Any new estimations?

**Comment by normanmaurer** [comment]
Sorry was very busy. Will do tomorrow latest

**Comment by jenskordowski** [comment]
thanks for the release :)

**Comment by normanmaurer** [comment]
@jenskordowski you are welcome :) Thanks for the fix !

**Pull request closed without merging**
