### PR TITLE
Faster safe pooled heap allocations

### PR DESCRIPTION
**Pull request by franz1981**
Motivation:

Heap pooled allocations are spending some time into NioBuffer::fill and to create PooledAllocatorControl instances

Modification:

Reducing AllocatorControl instances allocations to just one per allocator and adding fast path for heap buffer fill

Result:

Faster heap (not-unsafe) pooled allocations

### CODE REVIEW

**Comment by franz1981** [comment]
According to the benchmark referenced on https://twitter.com/chvest/status/1510727080354324481 ie `SslHandlerEchoBenchmark` the improvement is dramatic

`from the pr on https://github.com/netty/netty/pull/12221
```
Benchmark                                  (bufferType)                               (cipher)  (messageSize)  (numWrites)  (sslProvider)   Mode  Cnt     Score     Error  Units
SslHandlerEchoBenchmark.wrapUnwrap                 HEAP  TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256            128           10            JDK  thrpt   20  5827.444 ± 602.813  ops/s
```
from this pr:
```
Benchmark                                  (bufferType)                               (cipher)  (messageSize)  (numWrites)  (sslProvider)   Mode  Cnt      Score      Error  Units
SslHandlerEchoBenchmark.wrapUnwrap                 HEAP  TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256            128           10            JDK  thrpt   20  68140.003 ± 2022.471  ops/s
```

**Comment by franz1981** [comment]
I can improve NioBuffer::fill for the direct memory use case as well although I still think is a low handing fruit (and this PR as well) if compared to `UnsafeBuffer` that should be the most used one...said that, the improvement is free lunch

**Comment by franz1981** [comment]
Ignore https://github.com/netty/netty/pull/12275#issuecomment-1087376872: done :)

**Comment by chrisvest** [comment]
Nice finds!

I don't think `ByteBuf` had any guarantees about the unwritten contents, so I think we can drop that feature of `Buffer`. There will probably be some tests that fail when zeroing is removed, but they can most likely call `fill()` themselves. Perhaps that's a separate PR.

**Comment by franz1981** [comment]
> I don't think ByteBuf had any guarantees about the unwritten contents, so I think we can drop that feature of Buffer. There will probably be some tests that fail when zeroing is removed, but they can most likely call fill() themselves. Perhaps that's a separate PR.

Yep, a-la `calloc` I believe it would be better a separate API method
Just close this if is not needed @chrisvest : a deleted code is the fastest possible optimization :P

**Review by chrisvest — APPROVED** [review]
I've made #12277 for dropping the zeroing. I think making `fill()` faster, and removing a superfluous allocation makes sense regardless, so let's merge this as well.

**Comment by franz1981** [comment]
Tomorrow I'm going to add a fill jmh benchmark for all the different types of buffer(s)/allocator wdyt @chrisvest ?

**Comment by chrisvest** [comment]
@franz1981 Sounds good!

**Comment by chrisvest** [comment]
@franz1981 Shall we merge this and you can add your benchmark in a separate PR?

**Comment by franz1981** [comment]
yes @chrisvest I was already assuming it to be on a separate PR; sorry that I didn't mentioned it 
Sent https://github.com/netty/netty/pull/12221 that should improve further perf

**Pull request merged**
