### PR TITLE
Lazily allocate ChunkedWriteHandler#queue

### PR DESCRIPTION
**Pull request by slandelle**
Motivation:

When building an HTTP client, a `ChunkedWriteHandler` might be added to the pipeline just in case a `ChunkedInput` might be written, but that might never happen.
In this case, we don't need the extra queue allocation and ChunkedWriteHandler should just behave as a pass-through.

Modifications:

* lazily initialize the queue
* bypass work when the queue is empty

### CODE REVIEW

**Comment by slandelle** [comment]
CI 🤷‍♂️

**Comment by normanmaurer** [comment]
@slandelle there is a related test-failure:

```
2-04T15:33:11.2293946Z [INFO] 
2023-12-04T15:33:11.2294384Z [INFO] Results:
2023-12-04T15:33:11.2294790Z [INFO] 
2023-12-04T15:33:11.2295157Z [ERROR] Failures: 
2023-12-04T15:33:11.2296428Z [ERROR]   ChunkedWriteHandlerTest.testWriteFailureUnchunkedData:303->checkFirstFailed:715 expected: <true> but was: <false>
2023-12-04T15:33:11.2299160Z [INFO] 
```

**Comment by normanmaurer** [comment]
@slandelle ping

**Comment by slandelle** [comment]
Sorry for the delay. I'll have a look by tomorrow.

**Comment by slandelle** [comment]
@normanmaurer Test fixed. Happy new year, BTW.

**Comment by normanmaurer** [comment]
@slandelle thanks... happy new year :)

**Comment by slandelle** [comment]
@normanmaurer do you need me to provide a PR against the main branch too?

**Comment by normanmaurer** [comment]
@slandelle nope... already cherry-pick 756892ce1a479967b63e4b786e4279fc57746282

**Comment by slandelle** [comment]
Great, thanks!

**Pull request merged**
