### PR TITLE
Replace synchronized blocks + assert with synchronized method

### PR DESCRIPTION
**Pull request by nitsanw**
Reduce verbosity and more idiomatic use of keyword. Also rename the method to better describe what it's for.

Motivation:

Following up on discussion with @normanmaurer with suggestion to improve code clarity.

Modification:

Method is synchronized, no need for assert or verbose sync blocks around calls.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@franz1981 @nitsanw no big preference here (it is private anyway)... So whatever makes you guys happy :)

**Comment by franz1981** [comment]
@normanmaurer Go for what @nitsanw has chosen then ;) I'm happy :)

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@nitsanw thanks a lot!

**Pull request merged**
