### PR TITLE
Remove codec-stomp

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
This project now lives in the Netty Contrib organisation:
https://github.com/netty-contrib/codec-stomp

Modification:
The netty-codec-stomp maven module and code is removed.
The dependency is also removed from the BOM, and from netty-all, and the benchmarks and examples are removed as well.

Result:
The codec-stomp module now lives in contrib.

### CODE REVIEW

**Comment by chrisvest** [comment]
@amizurov please take a look as well

**Review by normanmaurer — APPROVED** [review]

**Comment by amizurov** [comment]
> 

Hmm, not found https://github.com/netty-contrib/codec-stomp repository

**Review by amizurov — APPROVED** [review]

**Comment by chrisvest** [comment]
@amizurov Oops, well spotted. I accidentally created the repo in my own account (an annoying default), instead of the org. Fixed now.

**Comment by amizurov** [comment]
> @amizurov Oops, well spotted. I accidentally created the repo in my own account (an annoying default), instead of the org. Fixed now.

Cool, thanks. Do we have any contribution guide for the new structure and release flow ?

**Review by hyperxpro — APPROVED** [review]

**Comment by chrisvest** [comment]
@amizurov I'll write something up tomorrow

**Comment by chrisvest** [comment]
@amizurov Wrote this up and sent you an invite: https://github.com/netty-contrib/.github/wiki

**Comment by amizurov** [comment]
> @amizurov Wrote this up and sent you an invite: https://github.com/netty-contrib/.github/wiki

Thanks a lot, accepted.

**Pull request merged**
