### PR TITLE
Provide an Automatic-Module-Name for the netty-all artifact

### LINKED ISSUE #7644: netty-all artifact missing automatic-module-name
The `netty-all` artifact doesn't have a `Automatic-Module-Name` defined in the manifest like the rest of the projects do, resulting in `requires netty.all`.

### PR DESCRIPTION
**Pull request by kashike**
fixes #7644

### CODE REVIEW

**Comment by normanmaurer** [comment]
@kashike can you please sign our ICLA 👍 
https://netty.io/s/icla

**Comment by kashike** [comment]
already have: https://github.com/netty/netty/pull/6988#issuecomment-316146391

**Comment by normanmaurer** [comment]
Doh! Somehow I missed it

**Comment by normanmaurer** [comment]
@doom369 FYI

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (1c7125750).

@kashike thanks

**Pull request closed without merging**
