### PR TITLE
Validate cookie name and value characters

### PR DESCRIPTION
**Pull request by slandelle**
Motivation:

RFC6265 specifies which characters are allowed in a cookie name and value.

Netty is currently too lax, which can used for HttpOnly escaping.

Modification:

In ServerCookieDecoder: discard cookie key-value pairs that contain invalid characters.
In ClientCookieEncoder: throw an exception when trying to encode cookies with invalid characters.
Drop old Cookie encoders and decoders that were deprecated in 4.1.

Result:

The problem described in the motivation section is fixed.

### CODE REVIEW

**Comment by slandelle** [comment]
@normanmaurer Ping. Note that I dropped the old encoders and decoders that were deprecated in 4.1.

**Comment by normanmaurer** [comment]
@slandelle awesome! ... Let me pull in once the CI build it :)

**Comment by normanmaurer** [comment]
@slandelle can you please fix the compile error ?

**Comment by slandelle** [comment]
Sorry, I was in a rush, so I only checked the http module, not the examples.
Should be fine, now.

**Comment by normanmaurer** [comment]
@netkins build

**Comment by slandelle** [comment]
@normanmaurer This one is fine

**Comment by slandelle** [comment]
@normanmaurer This is the last one to be cherry-picked.

**Comment by normanmaurer** [comment]
@slandelle thanks!

Cherry-picked into master as fb6eae15911790f2af89254b16765c33b05515a5

**Pull request closed without merging**
