### PR TITLE
Preserve the original filename when encoding a multipart/form in mixe…

### LINKED ISSUE #9269: HttpPostRequestEncoder will overwrite the original filename when switching to mixed mode
### Expected behavior
The `HttpPostRequestEncoder` preserves the original filename of file uploads sharing the same name encoded in mixed mode. 

### Actual behavior
The `HttpPostRequestEncoder` overwrites the original filename of file uploads sharing the same name encoded in mixed mode when it rewrites the multipart body header of the previous file.

### Steps to reproduce
Use an `HttpPostRequestEncoder` with multipart and the default mode and add several body file upload using the same name and different filenames. The test suite contains already such test but the test is wrong and will not check correctly that the original filename is preserved.

### Minimal yet complete reproducer code (or URL to code)
Update `HttpPostRequestEncoderTest#testMultiFileUploadInMixedMode` and change the first occurence of _filename=\"file-02.txt\""_ by _filename=\"file-01.txt\""_

### Netty version
All ?

### JVM version (e.g. `java -version`)
N/A

### OS version (e.g. `uname -a`)
N/A

### PR DESCRIPTION
**Pull request by vietj**
…d mode.

Motivation:

The HttpPostRequestEncoder overwrites the original filename of file uploads sharing the same name encoded in mixed mode when it rewrites the multipart body header of the previous file. The original filename should be preserved instead.

Modifications:

Change the HttpPostRequestEncoder to reuse the correct filename when the encoder switches to mixed mode. The original test is incorrect and has been modified too, in addition it tests with an extra file upload since the current test was not testing the continuation of a mixed mode.

Result:

The HttpPostRequestEncoder will preserve the original filename of the first fileupload when switching to mixed mode

Fixes #9269.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by fredericBregier** [comment]
Correct for me

**Comment by normanmaurer** [comment]
@vietj thanks a lot!

**Comment by vietj** [comment]
you are welcome, @normanmaurer happy to contribute and give back to community even if that's a small change like this :-)

**Pull request merged**
