### PR TITLE
Remove native-image.properties from netty-transport

### LINKED ISSUE #13595: Use of ReflectionConfigurationResources results in warning starting with GraalVM for JDK 21 (23.1)
### Expected behavior

Building native-images with netty should succeed without warnings.

### Actual behavior

Native builds print the following warning:

```
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.netty/netty-transport/reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
```

The options is passed in 
https://github.com/netty/netty/blob/f1fa227ddf675f055766d04900cce6804fd7f710/transport/src/main/resources/META-INF/native-image/io.netty/netty-transport/native-image.properties#L15

### Steps to reproduce

```
wget https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/23.1.0-dev-20230817_2024/graalvm-community-java21-linux-amd64-dev.tar.gz
wget https://repo1.maven.org/maven2/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
tar xf graalvm-community-java21-linux-amd64-dev.tar.gz
cat > Main.java <<EOF                                                                                                                                                                     
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
EOF
./graalvm-community-openjdk-21+34.1/bin/javac Main.java
./graalvm-community-openjdk-21+34.1/bin/native-image -cp ./netty-transport-4.1.97.Final.jar:./ Main
```

### Netty version

4.1.97.Final

### JVM version (e.g. `java -version`)

```
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment GraalVM CE 21-dev+34.1 (build 21+34-jvmci-23.1-b12)
OpenJDK 64-Bit Server VM GraalVM CE 21-dev+34.1 (build 21+34-jvmci-23.1-b12, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)

Linux 6.4.12-200.fc38.x86_64

### PR DESCRIPTION
**Pull request by zakkak**
Motivation:

See #13595

Modification:

Rename reflection-config.json to reflect-config.json and let native-image detect it automatically.

Result:

Fixes #13595

### CODE REVIEW

**Comment by zakkak** [comment]
Hello @normanmaurer, could you please have a look at this?

**Comment by violetagg** [comment]
Previously there was a decision that this is backwards incompatible (see #12601) because of that @gradinac added the metadata to https://github.com/oracle/graalvm-reachability-metadata/issues/10

**Comment by zakkak** [comment]
@violetagg the metadata will still be loaded (by any GraalVM version AFAIK). `native-image` automatically picks the file if it's called `reflect-config.json`. The only reason `native-image.properties` was needed was to point `native-image` to `reflection-config.json` since the file was not named as expected.

Furthermore, since the best practice nowadays is to use the metadata from https://github.com/oracle/graalvm-reachability-metadata instead of having them in the project itself (and I see you are a contributor there) are there any plans on completely dropping the metadata from netty?

**Comment by violetagg** [comment]
> @violetagg the metadata will still be loaded (by any GraalVM version AFAIK). `native-image` automatically picks the file if it's called `reflect-config.json`. The only reason `native-image.properties` was needed was to point `native-image` to `reflection-config.json` since the file was not named as expected.

If you take a look at the mentioned PR above, you will see that some of the `native-image.properties` files have a lot more than this.
So theoretically some people may still depend on this functionality. (I don't know)
In Spring Framework all `native-image.properties` files provided by Netty 4.1 are deleted and the metadata for Netty 4.1 from https://github.com/oracle/graalvm-reachability-metadata is used.

> 
> Furthermore, since the best practice nowadays is to use the metadata from https://github.com/oracle/graalvm-reachability-metadata instead of having them in the project itself (and I see you are a contributor there) are there any plans on completely dropping the metadata from netty?

I don't think it is a best practice. It is the opposite.
When you contribute to https://github.com/oracle/graalvm-reachability-metadata there is an explicit question:
`I have considered including reachability metadata directly in the library or the framework`.
For Netty 5 the metadata is here in Netty repository and for Netty 5 all `native-image.properties` files are deleted. (again reference to the PR discussion)
Spring Framework has an experimental support for Netty 5 and uses the metadata that Netty 5 provides (no more https://github.com/oracle/graalvm-reachability-metadata).

So I would say that if it is decided that the backwards compatibility issue is not an issue anymore, all metadata related to Netty 4.1 can be moved from 
https://github.com/oracle/graalvm-reachability-metadata here to Netty repository.

**Comment by zakkak** [comment]
> If you take a look at the mentioned PR above, you will see that some of the `native-image.properties` files have a lot more than this. So theoretically some people may still depend on this functionality. (I don't know) 

That's fine, this PR only removes a single `native-image.properties` files which only contains the following line:

```
Args = -H:ReflectionConfigurationResources=${.}/reflection-config.json
```

Which is only needed because the file doesn't have the expected name, i.e. `reflect-config.json`. As a result I don't expect this PR to break any of the other use cases you mention.

> In Spring Framework all `native-image.properties` files provided by Netty 4.1 are deleted and the metadata for Netty 4.1 from https://github.com/oracle/graalvm-reachability-metadata is used.

Nice.

> > Furthermore, since the best practice nowadays is to use the metadata from https://github.com/oracle/graalvm-reachability-metadata instead of having them in the project itself (and I see you are a contributor there) are there any plans on completely dropping the metadata from netty?
> 
> I don't think it is a best practice. It is the opposite. When you contribute to https://github.com/oracle/graalvm-reachability-metadata there is an explicit question: `I have considered including reachability metadata directly in the library or the framework`. For Netty 5 the metadata is here in Netty repository and for Netty 5 all `native-image.properties` files are deleted. (again reference to the PR discussion) Spring Framework has an experimental support for Netty 5 and uses the metadata that Netty 5 provides (no more https://github.com/oracle/graalvm-reachability-metadata).
> 

You are right, it's even in [the README file](https://github.com/oracle/graalvm-reachability-metadata#readme). Sorry for misguiding you.

> So I would say that if it is decided that the backwards compatibility issue is not an issue anymore, all metadata related to Netty 4.1 can be moved from https://github.com/oracle/graalvm-reachability-metadata here to Netty repository.

Yes, that would make sense. Note however that this would be orthogonal to this PR.

**Comment by zakkak** [comment]
Hello @violetagg, are there any updates regarding this?

**Comment by violetagg** [comment]
@zakkak I didn't state any objections for this change. I just explained a bit of the history here. I'm not stopping this change from merge.

**Comment by zakkak** [comment]
> @zakkak I didn't state any objections for this change. I just explained a bit of the history here. I'm not stopping this change from merge.

Thank you @violetagg. I misinterpreted your replies as objection.

> I think I need to defer to @gradinac or @violetagg for this... I dont have enough knowledge on this topic

@normanmaurer AFAIK @gradinac is no longer part of the GraalVM team. Are you OK with merging this after the discussion with @violetagg or are there still concerns? Thank you

**Comment by normanmaurer** [comment]
I would be fine with this... but again I dont have much knowledge when it comes to native image etc... Maybe @vietj also want to chime in ?

**Comment by vietj** [comment]
like you I'm not knowledgeable unfortunately (by design and not by will :-) ), sorry for that

**Comment by zakkak** [comment]
Hello @normanmaurer, given the lack of reviewers how do you suggest proceeding with this?

**Comment by geoand** [comment]
Not a Netty maintainer, but as someone who uses Netty in Quarkus and frequently deals with GraalVM stuff, I'm +1.

**Review by franz1981 — APPROVED** [review]
Given the previous discussion with @violetagg I am fine with it.
@yawkat do you have any concern?

LGTM

**Comment by yawkat** [comment]
LGTM

**Comment by franz1981** [comment]
thanks @normanmaurer and @yawkat

**Pull request merged**
