### PR TITLE
SockJS Support for Netty4

### PR DESCRIPTION
**Pull request by danbev**
Please see sockjs/README.md for instructions about running tests general information regarding the SockJS support.

### CODE REVIEW

**Comment by mortan** [comment]
Any update on this? Would love sock.js support in netty! :+1:

**Comment by danbev** [comment]
@mortan I'm currently working on getting https://github.com/netty/netty/pull/3271 merged and after that I'll rebase and hopefully a final round of reviews before merging. Can't give an exact date but there should be some updates to this PR shortly, hopefully later this week or next.

**Comment by tigertoes** [comment]
Hey @danbev, is there any update to this? Is there anything I can do to help?

**Comment by danbev** [comment]
This needs to be rebased against the latest 4.1 version and verify that
things are working correctly. The last rebase passed the
sockjs-protocol-0.3.3 but only after custom updates due to how header
values are compared in the test, so nothing major. I've not got much time
at the moment due to parental leave but will try to rebase and run the
sockjs-protocol tests this weekend and also update the PR against
sockjs-protocol (the header issue mentioned above)

onsdag 4 mars 2015 skrev Tiger Toes <notifications@github.com>:

**Comment by mortan** [comment]
Still sitting on the edge of my seat and waiting for it! :)

**Pull request closed without merging**
