### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by louxiu**
Motivation:

MessageReciever should be MessageReceiver

Modifications:

Refactor MessageReciever to MessageReceiver

Result:

No more typo

### CODE REVIEW

**Comment by normanmaurer** [comment]
Checking

**Comment by Scottmitch** [comment]
@normanmaurer - This fix looks fine to me. I'll look at the leak.

**Comment by normanmaurer** [comment]
@Scottmitch leak should be fixed by https://github.com/netty/netty/commit/79bc90be3215509e98a86239217226572e7887e5

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (da17b44fb22d3fd1eb652b9474e287316b95c6d5) and 4.1 (6ee5341cdfa397a7b2ca123b0f8a5f3170133429)

**Comment by normanmaurer** [comment]
@louxiu thanks!

**Pull request closed without merging**
