### PR TITLE
Fixed ServerBootstrap#group(EventLoopGroup, EventLoopGroup) javadoc

### LINKED ISSUE #3429: Netty 4.0.24 Final doc bug for ServerBootstrap.group(). [bug]
The javadoc for ServerBootstrap.group() in 4.0.24.Final is incorrect.

netty doc bug

The SocketChannel should be ServerChannel.

This bug is first reported in this stackoverflow thread:
http://stackoverflow.com/questions/28473116/netty-doc-bug-for-serverbootstrap-group

### PR DESCRIPTION
**Pull request by casidiablo**
Fixes #3429

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by normanmaurer** [comment]
@netkins accept

**Comment by normanmaurer** [comment]
@casidiablo please sign the ICLA: https://docs.google.com/forms/d/1GKuaUw10DfPzPy_XBnp3Wk_OLYnA4-Kg16wSiUkO3-A/viewform?formkey=dHBjc1YzdWhsZERUQnhlSklsbG1KT1E6MQ

**Comment by normanmaurer** [comment]
Thanks.. Cherry-picked into 4.0 (c03f57e9bde50db89859ebc91b291e188b7408b8) , 4.1 (4b83eee1338ab018b802c3e195317fa83f785154)  and master (e6bf1353d567b38754322346a2ef02701dce99ed)

**Pull request closed without merging**
