### PR TITLE
Http2ConnectionHandlerBuilder: make initialSettings() public

### PR DESCRIPTION
**Pull request by mostroverkhov**
Motivation:

Be able to modify `Http2Settings` of `Http2ConnectionHandlerBuilder`

Modification:

make `initialSettings()` of `Http2ConnectionHandlerBuilder` public

Result:

public `initialSettings()` of `Http2ConnectionHandlerBuilder`, aligned with `Http2FrameCodecBuilder`

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by hyperxpro** [comment]
```
13:13:03 [ERROR] Failed to execute goal on project netty-testsuite-osgi: Could not resolve dependencies for project io.netty:netty-testsuite-osgi:jar:4.1.52.Final-SNAPSHOT: Could not transfer artifact org.codehaus.mojo:animal-sniffer-annotations:jar:1.9 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/codehaus/mojo/animal-sniffer-annotations/1.9/animal-sniffer-annotations-1.9.jar: Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.188.215] failed: Connection timed out (Connection timed out) -> [Help 1]
```

Need to re-run tests.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@mostroverkhov thanks

**Pull request merged**
