### PR TITLE
Java 8 migration: replace anonymous class with lambda

### PR DESCRIPTION
**Pull request by kezhenxu94**
Motivation:

Using lambda instead of anonymous inner class to imporve readablity

Modification:

Replace anonymous inner class with lambda

### CODE REVIEW

**Comment by normanmaurer** [comment]
@kezhenxu94 please revert the changes where you removed `throws ...` for now.

**Comment by kezhenxu94** [comment]
@normanmaurer I've rebased the patch and revert the removed `throws...`, now it only contains changes that replace anonymous types with lambda.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@kezhenxu94 there is something wrong with the patch... please recheck

**Comment by kezhenxu94** [comment]
Checking

**Comment by kezhenxu94** [comment]
@normanmaurer It was problem about LF, should fixed now :)

**Comment by kezhenxu94** [comment]
It's problem about checkstyle,  checking

**Comment by kezhenxu94** [comment]
@normanmaurer It seems that the current version(2.12.1) of  checkstyle plugin doesn't recognize lambda expression, and upgrade to version 3.0.0 requires update the checkstyle.xml too, which resides in another project, any suggestions?

**Comment by kezhenxu94** [comment]
@normanmaurer Thanks

**Comment by kezhenxu94** [comment]
@normanmaurer I've rebase this patch after your updating checkstyle plugin to support lambdas

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@kezhenxu94 thanks a lot!

**Pull request merged**
