### PR TITLE
Deprecate ChannelInboundHandlerAdapter and ChannelOutboundHandlerAdapter

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

As we now us java8 as minimum java version we can deprecate ChannelInboundHandlerAdapter / ChannelOutboundHandlerAdapter and just move the default implementations into the interfaces. This makes things a bit more flexible for the end-user and also simplifies the class-hierarchy.

Modifications:

- Mark ChannelInboundHandlerAdapter and ChannelOutboundHandlerAdapter as deprecated
- Add default implementations to ChannelInboundHandler / ChannelOutboundHandler
- Refactor our code to not use ChannelInboundHandlerAdapter / ChannelOutboundHandlerAdapter anymore

Result:

Cleanup class-hierarchy and make things a bit more flexible.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@franz1981 @vietj @njhill PTAL as well. I am not concerned about performance for default methods as we have the `@Skip` optimisation in place anyway.

**Comment by vietj** [comment]
looks good :-)

**Comment by acdebaca** [comment]
@normanmaurer 
Shouldn't [HttpContentDecoderTest.java line 549](https://github.com/netty/netty/blob/33072228efb110e2969701048e94a6832a3a4f25/codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java#L549) be:

```java
        EmbeddedChannel channel = new EmbeddedChannel(decoder, new ChannelInboundHandler() {
            @Override
            public void channelInactive(ChannelHandlerContext ctx) throws Exception {
                assertTrue(channelInactiveCalled.compareAndSet(false, true));
                ctx.fireChannelInactive();
            }
        });
```
?

**Comment by normanmaurer** [comment]
@acdebaca good catch! Thanks

**Comment by carl-mastrangelo** [comment]
@normanmaurer did the plan to move everything to ChannelHandler ever pan out?

**Comment by normanmaurer** [comment]
@carl-mastrangelo I am still investigate... I thought it make sense to do it step by step in any case :)

**Pull request merged**
