### PR TITLE
Added VW mode to resource leak detection

### PR DESCRIPTION
**Pull request by jroper**

### CODE REVIEW

**Comment by normanmaurer** [comment]
@jroper honestly I don't see why we need this ... A user can just disable the leak detector via system property when specify stuff for the ci

**Comment by jroper** [comment]
But wouldn't that be a bit obvious to the officials if you set up your CI to disable leak detection during emissions control tests?

**Comment by normanmaurer** [comment]
@jroper maybe ;) Anyway I think I want to reject this one ;)

**Comment by jroper** [comment]
It's your loss...

**Comment by daschl** [comment]
@jroper no worries, @normanmaurer is from germany ;)

**Pull request closed without merging**
