### PR TITLE
[#4275] Discard bytes after X reads to guard against OOME.

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

If a remote peer writes fast enough it may take a long time to have fireChannelReadComplete(...) triggered. Because of this we need to take special care and ensure we try to discard some bytes if channelRead(...) is called to often in ByteToMessageDecoder.

Modifications:

- Add ByteToMessageDecoder.setDiscardAfterReads(...) which allows to set the number of reads after which we try to discard the read bytes
- Use default value of 16 for max reads.

Result:

No risk of OOME.

### CODE REVIEW

**Comment by ninja-** [comment]
interesting change but I guess if I am not a victim of out-of-memory it wouldn't affect me much. @normanmaurer could you also consider another change I discussed in #4205?

Consider a simple frame decoder right. There could be a case when there are 10000 small frames read in one batch before channelReadComplete. That would push the needed number of buffers to 10000 at the same time and also be a big overhead for small frames. So I changed it so that channelRead(msg) is called after decoding one and not in a batch after everything has been decoded.

**Comment by normanmaurer** [comment]
@Scottmitch WDYT ?

**Comment by normanmaurer** [comment]
@ninja- let me think a bit about it

**Comment by ninja-** [comment]
@normanmaurer I think this can be pulled without problems

**Comment by normanmaurer** [comment]
@ninja- let @Scottmitch or @trustin review first

**Comment by Scottmitch** [comment]
@normanmaurer - Do we need to reset `numReads` in `channelInactive`?

**Comment by normanmaurer** [comment]
@Scottmitch nope :)

**Comment by Scottmitch** [comment]
@normanmaurer - lgtm

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (f96777312d299483b2b547c489dbfcc24f7f080f) , 4.1 (c8a941d01e85148c21cc01bae80764bc134b1fdd) and master (3540ae64baed5bceb9e9e555627853f8c7d1dae8)

**Pull request closed without merging**
