### PR TITLE
add a really simple gradle build script.

### PR DESCRIPTION
**Pull request by wf2030**
add a really simple gradle build script. very glad to see netty switched to gradle one day

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by wf2030** [comment]
@netkins accept

**Comment by trustin** [comment]
And the benefit for Netty is ..?

**Comment by normanmaurer** [comment]
I think we should close as 'Won't fix'

**Comment by trustin** [comment]
Well, we should at least listen to his opinion, although my impression of Gradle wasn't great.

**Comment by normanmaurer** [comment]
Yep... I'm no fan either

**Comment by wf2030** [comment]
1. Gradle is as simple as it could be, at least much easier to understand than maven, with the build requirement so far, no plugins, no profiles, ALL IS CODE, especially it is based on jvm, so pleasure for java developers.

2. Obviously dynamic language scales better than xml configuration, easy to extend.

3. Gradle is 100% compatable with maven and ant, of cource it is glad to have one more choice.Developers could choose the build way they like.

4. Many ways to manage dependencies, 

5. More powerful on multiproject build, and easy to deploy.

6. Share build scripts with no need to write plugins, more flexiable.

There are many more reasons that i don't mentioned, and all these are the reasons for Spring, Hibernate, Android and etc to use it.

Why not provider one more way to build netty and let developers choose what they like(In fact, i wrote this due to the failure on maven).

**Comment by normanmaurer** [comment]
@wf2030 thanks for the details... However I'm not convinced as this means we will have to maintain both, while maven works very well for us. @trustin wdyt ?

**Comment by danbev** [comment]
I would prefer Gradle over Maven if given a choice. I really like that one can specify project/module dependencies between projects/modules, and not have to run everything (build, tests) if the changes made have not affected those projects/modules.

**Comment by Scottmitch** [comment]
I don't have a strong preference gradle vs maven but I do think from a maintenance/development perspective we should strive to have 1 set of build/configuration files.  I would be fine with gradle if we think it is mature enough (seems like some high profile projects are using it) and there will be enough general familiarity for developers/users.

@wf2030 - Is this PR intended to be a complete equivalent gradle build to what we have with maven today (all sub-projects, all pom.xml files functionality captured, etc...)?

**Comment by wf2030** [comment]
I'm so sorry that due to recently busy work, I have no much time on it, and i will reopen it when works finished.

**Comment by jsbd** [comment]
In my opinion Maven and Gradle are not important both.  @wf2030

**Comment by Scottmitch** [comment]
@wf2030 - Thanks for your feedback and effort.  Unless you enjoy and want to do this I don't want you to put too much time into this until everyone is on board.

@netty/contributors - Are we fine with maven...or would anyone care to make a case for gradle?

**Comment by nmittler** [comment]
Just my $0.02 ... I'm still somewhat new to gradle, but I find its configuration much more concise and easy to follow.  I also find it more flexible with complex builds, which often get rather hairy with Maven.

**Comment by spullara** [comment]
If it isn't broke, don't fix it.

**Comment by normanmaurer** [comment]
+1

**Comment by nmittler** [comment]
Sounds good to me :) +1

**Comment by trustin** [comment]
Added the `won't fix` label.

**Comment by Scottmitch** [comment]
+1. Thanks everyone for the input, and thanks @wf2030  for your hard work.

**Comment by jsbd** [comment]
+1

**Pull request closed without merging**
