### PR TITLE
Opportunity for lazy initialization in Headers interface

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
The Headers interface had two member variables (addAllVisitor, setAllVisitor) which are not necessarily always needed but are always instantiated.  This may result in excess memory being used.

Modifications:
 - addAllVisitor will be accessed via a method addAllVisitor() which will use lazy initialization.
 - setAllVisitor will be accessed via a method addAllVisitor() which will use lazy initialization.

Result:
Potential memory savings by using lazy initialization.

### CODE REVIEW

**Comment by Scottmitch** [comment]
@normanmaurer - WDYT?  Some additional rational is that the number of `Headers` objects is expected to be large and these members may not be used at all (or potentially infrequently).

**Comment by Scottmitch** [comment]
If we have consensus I will backport to 4.1 and 4.0.

**Comment by normanmaurer** [comment]
@Scottmitch looks good !

**Comment by Scottmitch** [comment]
Cherry-picked. master (3b1f15e366c36cffe5e638f60dfddd7fb7badfb9), 4.1 (27a2017f7f5db2707b21600c2d976afbc7b57cfd), 4.0 (?).

Humm it looks like the header updates are not in 4.0.  I thought I backported them a while ago...perhaps not because of backwards compatibility?

**Comment by Scottmitch** [comment]
@trustin - Do you remember what we decided to do for the header modifications on the 4.0 branch?  Looks like we decided not to backport, or was this a miss?

**Comment by normanmaurer** [comment]
@Scottmitch we can't back port because of api breakage  I think...

**Pull request closed without merging**
