### PR TITLE
Removal of split package between netty-codec and netty-codec-xml

### LINKED ISSUE #4228: Netty's Default Executor requires Unsafe, even on platforms that don't support it
The DefaultExecutorServiceFactory class creates a netty ForkJoinPool -> https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/concurrent/DefaultExecutorServiceFactory.java#L75

This ForkJoinPool requires sun.misc.Unsafe -> 
https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/internal/chmv8/ForkJoinPool.java#L1048

This breaks on systems without Unsafe, so the code in the DefaultExecutorServiceFactory should be using PlatformDependent to detect which implementation it should use.

### LINKED ISSUE #14228: Split package between io.netty.codec and io.netty.codec.xml
### Expected behavior

No split package between modules.

### Actual behavior

Split package on `io.netty.handler.codec.xml`, the `io.netty.codec` module contains the `io.netty.handler.codec.xml.XmlFrameDecoder`

This can trivially be solved by moving this class to the `io.netty.handler.codec.xml` module. That would be a breaking change since the same class would be moved to another jar, but it seems reasonable for 4.2.

I can provide a PR.

### PR DESCRIPTION
**Pull request by vietj**
Motivation:

The `netty-code`c maven module contains the `io.netty.handler.codec.xml.XmlFrameDecoder` class which shares a package with the package of the `netty-codec-xml` maven module, and therefore exhibit a split package. A split package is not allowed by the java module system.

Changes:

The class `io.netty.handler.codec.xml.XmlFrameDecoder` is moved from the `netty-codec` maven module to the `netty-codec-xml` maven module along with its tests. Since it is a breaking change the revapi difference has been added to the list of ignored breaking changes.

Results:

The split package is removed, users of the class `io.netty.handler.codec.xml.XmlFrameDecoder` will need to add the `netty-codec-xml` maven module to their dependencies in order to continue using the class.

Fixes #14228

### CODE REVIEW

**Comment by chrisvest** [comment]
The graal metadata needs to be updated as well

**Comment by vietj** [comment]
@chrisvest please have a look

**Comment by vietj** [comment]
still failing, having another look

**Comment by vietj** [comment]
ok got it, it is repeated for each jar that is a dependency

**Comment by vietj** [comment]
A few builds failed without a log

**Review by chrisvest — APPROVED** [review]
I restarted the failed builds. Never seen them fail like that before.

**Pull request merged**
