### PR TITLE
Let OpenSslContext implement the ReferenceCounted interface

### PR DESCRIPTION
**Pull request by rkapsi**
Motivation

[#4958]: OpenSslContext retains native resources that get released by the
Garbage Collector via object finalization. This works fine for traditonal SSL
deployments with static working sets of SslContext(s). We intend to load large
sets of [Open]SslContext(s) on a per connection basis.

Having OpenSslContext implement the ReferenceCounted interface would
facilitate efficient sharing and timely relase of all native resources once all
client disconnected that used the same context.

Modifications

Let OpenSslContext implement the ReferenceCounted and delegate all calls
to an inner AbstractReferenceCounted field that calls OpenSslContext's destroy()
method once the reference count reaches 0.

Result

It's possible to release OpenSslContext's native resources as soon as it's
no longer in use.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@rkapsi do you really need reference counted here or would it be enough if you would be able to "shutdown" a context ?

**Comment by rkapsi** [comment]
@normanmaurer isn't a context a shareable resource? One context can have many engines. We load a context dynamically and try to re-use the instance for as long as possible but not for longer than necessary. When the last client disconnects we want to `free()` it.

**Comment by trustin** [comment]
I'm not sure the use case mentioned here justifies backward-
compatibility breakage and inconvenience of having to reference-count
long-living shared resource.
 
Perhaps you could implement your own SslContext implementation that
implements ReferenceCounted and wraps an existing non-refCnt'd
SslContext?

**Comment by rkapsi** [comment]
Does it break backwards compatibility?

(the wrapping certainly works and is what I'm currently doing. It's just not particularity elegant and in that regard it'd be nice if OpenSslContext wouldn't hide its destroy() method)

**Comment by Scottmitch** [comment]
In terms of cleanup it seems this PR will retain the existing functionality, but also allow someone to be proactive about cleanup. IIUC the only change that may be interpreted as "backwards breaking" would be that `OpenSslContext` now implements `ReferenceCounted` and could be viewed as "leaked" if it is not released before it is GCed ... however this is just a strict interpretation of the interface and practically may be safe to ignore in this case.

While we are on this train of thought ... similar idea to https://github.com/netty/netty/pull/4661 ... the finalizers are perceived to cause pain in general in terms of reclaiming resources and creating more work for GC. I wonder if we could deprecate the openssl classes which rely on a finalizer (OpenSslContext, OpenSslEngine), move all the functionality (except the finalizer) into a base  classes which provide `ReferenceCounted` functionality, and have the existing finalizers just do some sort of "safe release" (make sure to not throw if it has already been released). This could be "opt in" (at the builder level?) so the user would acknowledge they are either inserting something into the pipeline to be released, or otherwise assume responsibility for releasing.

**Comment by rkapsi** [comment]
@Scottmitch I certainly like that idea.

I have no strong opinion regards the presence of finalizer methods. I usually have no problem with them as long as freeing the underlying resources doesn't depend on them. It's a bit like with classes such as `FileInputStream`. We all agree closing streams is a good idea and leaving it up to the finalizer is a bad one. If SslContext wasn't a shareable resource it'd be a no brainier to let it implement the Closeable interface. But because it is shareable the ReferenceCounted interface seems more appropriate (possibly in addition to Closeable). Just throwing it out there because there are maybe folks who don't want to re-use a context.

**Comment by Scottmitch** [comment]
@rkapsi - Yip ReferenceCounted fits nicely for shared objects.

@normanmaurer @trustin - WDYT about the above proposal?

**Comment by trustin** [comment]
So, the proposal is to implement reference counting and finalization, right? SGTM.

**Comment by Scottmitch** [comment]
@trustin - Yes. Finishers would be the default (to preserve existing behavior). Reference counting would be opt-in (users acknowledge change in behavior).

**Comment by Scottmitch** [comment]
maybe superseded by https://github.com/netty/netty/pull/5547

**Comment by normanmaurer** [comment]
Let us close this in favour of #5547

**Pull request closed without merging**
