### PR TITLE
Validate cookie name and value characters

### PR DESCRIPTION
**Pull request by slandelle**
Motivation:

RFC6265 specifies which characters are allowed in a cookie name and value.

Netty is currently too lax, which can used for HttpOnly escaping.

Modification:

In ServerCookieDecoder: discard cookie key-value pairs that contain invalid characters.
In ClientCookieEncoder: throw an exception when trying to encode cookies with invalid characters.

Result:

The problem described in the motivation section is fixed.

### CODE REVIEW

**Comment by slandelle** [comment]
@normanmaurer ping

**Comment by normanmaurer** [comment]
@slandelle please fix check style errors

**Comment by slandelle** [comment]
Fixed

**Comment by normanmaurer** [comment]
@slandelle thanks!

Cherry-picked into 4.0 (d98b21be045a315ced88ada84000e4757cfb9892)

**Pull request closed without merging**
