### PR TITLE
[#5882] Ensure we even process tasks if processing of ready channels …

### PR DESCRIPTION
**Pull request by normanmaurer**
…throws an Exception in event loop.

Motivation:

If an exception is thrown while processing the ready channels in the EventLoop we should still run all tasks as this may allow to recover. For example a OutOfMemoryError may be thrown and runAllTasks() will free up memory again. Beside this we should also ensure we always allow to shutdown even if an exception was thrown.

Modifications:

- Call runAllTasks() in a finally block
- Ensure shutdown is always handles.

Result:

More robust EventLoop implementations for NIO and Epoll.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler @trustin PTAL

**Comment by Scottmitch** [comment]
lgtm. Recovery from OOME may be a bit optimistic though :)

**Comment by normanmaurer** [comment]
@Scottmitch true enough... That said I think it is a good thing in general

**Comment by nmittler** [comment]
LGTM

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (a09e568) and 4.0 (c49ec72)

**Pull request closed without merging**
