### PR TITLE
Change hosts file resolver to be case-insensitive

### PR DESCRIPTION
**Pull request by alexlehm**
fix issue #5182: HostsFileParser tries to resolve hostnames as case-sensitive

### CODE REVIEW

**Comment by normanmaurer** [comment]
Just one comment. Please address and sign ICLA. Once done I will pull in

**Comment by normanmaurer** [comment]
@alexlehm any news here in terms of the ICLA:

http://netty.io/s/icla

Please squash your commits and sign the ICLA. Once done I can pull this in....

**Comment by alexlehm** [comment]
@normanmaurer I signed the ICLA now and squashed the 2nd commit into the 1st one

**Comment by normanmaurer** [comment]
Thanks will cherry-pick :)

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 as 24784bfcd17edd6109fe9ffb22fbcaa72779871e. 

@alexlehm thanks again!

**Pull request closed without merging**
