### PR TITLE
Do not call System.nanoTime() in ReadTimeoutHandler.channelRead()

### PR DESCRIPTION
**Pull request by rovarga**
Motivation:

We mitigate callouts to System.nanoTime() in SingleThreadEventExecutor
as it is 'relatively expensive'. On a modern system, tak translates to
about 20ns per call. With channelReadComplete() we can side-step this in
channelRead().

Modifications:

Introduce a boolean flag, which indicates that a read batch is currently
on-going, which acts as a flush guard for lastReadTime. Update
lastReadTime in channelReadComplete() just before setting the flag to
false. We set the flag to true in channelRead().

The periodic task examines the flag, and if it observes it to be true,
it will reschedule the task for the full duration. If it observes as
false, it will read lastReadTime and adjust the delay accordingly.

Result:

ReadTimeoutHandler calls System.nanoTime() only once per read batch.

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by normanmaurer** [comment]
@netkins accept

**Comment by normanmaurer** [comment]
@rovarga did you sign the ICLA yet ?

**Comment by trustin** [comment]
LGTM.  @normanmaurer, he signed the ICLA at 2/15/2015 3:30:51

**Comment by normanmaurer** [comment]
@rovarga thanks!

Cherry-picked into 4.0 (addc4413aa5538eca7ffb7d20684ccfe2ec21f6e) , (f3dcad32306aeb953d47f8ca02ef4ac1744d0436) and master (b87cb06b93947e4b2035e7fd393adad3edf1d82a)

**Comment by normanmaurer** [comment]
@trustin @rovarga I think the same fix should be done for `IdleStateHandler`, WDYT ?

**Pull request closed without merging**
