### PR TITLE
Explicit module support for Netty

### LINKED ISSUE #14176: Declarative JPMS support
The current version of Netty supports automatic module names.

This should bring declarative JPMS support in the new Netty 4.2 branch with a set of module-info descriptors that provides a better support for JPMS for Netty consumers.

## Motivation

Although Netty remains compatible with old version of Java, the Java runtime can often be a recent JVM. The JEP [Integrity by default](https://openjdk.org/jeps/8305968) will restrict how Netty operates in the future (JNI, Unsafe). Supporting JPMS will help to mitigate this by making Netty a clear identified consumer of these features, letting users configure Netty to use them (e.g. `--enable-native-access=io.netty.xxx`).

JPMS is a multi-year / multi-project effort, this is only a second step toward JPMS support.

## Goals

- Netty continue to operate as before when Netty jars are on the classpath
- No breaking changes with classpath, module path might have behavioural changes which should be considered as acceptable
- Give the opportunity to JPMS consumers (libraries / frameworks / applications) of Netty (e.g. Eclipse Vert.x) to use Netty on the module path instead of the classpath

## Non goals

- Encapsulation is not a goal as it requires impacting changes in Netty

## Implementation

Since Netty 4.2 aims to use Java 8, the considered approach is the generation of module descriptors in Netty jars using a tool like [moditect](https://github.com/moditect/moditect) or [module-info](https://github.com/dmlloyd/module-info).

Module descriptors is generated at `META-INF/versions/11/module-info.class` (multi release jar) which makes it invisible as a class to Java 8 class loading.

Descriptor will export all Netty packages by default, it might be restricted in later versions, e.g. having logging internal packages could be attempted.

Maven integration tests should be provided to test the behaviour, e.g. creating a jlink image (jlink does not accept automatic modules), etc...

## Contribution

I am volunteering to implement JPMS support and supporting it in the long run. I welcome any help for this effort of course.

### PR DESCRIPTION
**Pull request by vietj**
Motivation:

Although Netty remains compatible with old version of Java, the Java runtime can often be a recent JVM. The JEP [Integrity by default](https://openjdk.org/jeps/8305968) will restrict how Netty operates in the future (JNI, Unsafe). Supporting explicit modules will help to mitigate this by making Netty a clear identified consumer of these features, letting users configure Netty to use them (e.g. `--enable-native-access=io.netty.xxx`). This also allows to use tool like jlink to create runtime image with a smaller application footprint.

In addition it gives the opportunity to libraries (such as Vert.x) and framework to support explicit modules as well.

The supported dependencies of Netty (those which are not in maintenance mode) provides already explicit modules.

A lot of cleanup and decoupling as already been done in previous pull requests, this is the final step to support declarative JPMS.

Changes:

Drop the support for named automatic modules, a maven module either provides a module-info descriptor class and supports module or does not.

Most maven modules do provide this, the following maven modules `netty-transport-rxtx` `netty-transport-sctp`, `netty-transport-udt` cannot support modularity.

Other modules provides a descriptor in yml format compiled to a module-info class by the module-info maven plugin located in `META-INF/versions` turning jars into multi release jars.

A new testsuite is added (`testsuite-jpms`) that only runs for Java versions supporting Java modules (11 and forward). In addition the testsuite module builds a jlink image with an HTTP server that can be used to perform checks and/or demos. The server supports native SSL as well as native transports.

Result:

Provide a better support for the Java Platform Module System.

Fixes #14176

### CODE REVIEW

**Comment by chrisvest** [comment]
Could we make our modules first-class multi-release, so we can use that feature for more than just `module-info`? I haven't explored the tooling in this area, but it might be nice to have with all the Java versions we support.

**Comment by vietj** [comment]
@chrisvest you mean that all jar shipped by Netty are by default multi release jars ? yes that would simplify the build a bit and avoid some un-necessary repetition

**Comment by chrisvest** [comment]
@vietj exactly, make all jars multi-release (because they need module-info) and also allow us to use it for version-specific code paths so we can do less reflection in e.g. `PlatformDependent0` and other places.

**Comment by vietj** [comment]
I'll update the PR soon @chrisvest

**Comment by vietj** [comment]
@chrisvest ptal

**Comment by vietj** [comment]
@normanmaurer you can try Nicolai Parlog blog on JPMS https://nipafx.dev/j_ms/

I think I should write a document that explains how to upgrade/add a dependency and how it should be tested in the README.

**Comment by normanmaurer** [comment]
> @normanmaurer you can try Nicolai Parlog blog on JPMS https://nipafx.dev/j_ms/
> 
> I think I should write a document that explains how to upgrade/add a dependency and how it should be tested in the README.

Yes that would be good!

**Comment by vietj** [comment]
I'll do it in a follow up PR to avoid blocking this one.

**Comment by chrisvest** [comment]
I was imagining that with proper multi-release support we wouldn't need the plugin that converts the yaml files to module-info.class files. I'm otherwise happy to accept this as is if you want to look at that in a follow-up PR, or if there are other reasons why the yaml+plug-in way is best.

**Comment by vietj** [comment]
@chrisvest I haven't investigated a way to compile module-info.java to classes as most other open source projects are using a maven plugin to implement that. I believe it might bring more complexity to the build at the benefit of having a more traditional approach (trade off) but I haven't tried yet.

I am glad contributing to improve this according to the project decision, I will definitely spend time investigating a less exotic build, I can open another issue and discuss the options here with the community. As I said in my initial issue I have committed to support JPMS in Netty on the long run.

**Comment by vietj** [comment]
@chrisvest at the beginning I was a bit pessimistic because using the java compiler add more constraints, basically it is a java compilation phase where the compiler will be more stringent which could be a problem with some dependencies of the project (e.g. graal VM jars as it stands), we need to keep in mind that this JPMS support is something we add on top of Netty 4.1 compiled for JDK 8 and we are trying to find the best way toward the best JPMS support we can get (and I believe we are looking quite good as it stands).

That being said, I went with a prototype that looks reasonable to me by faking the Netty package hierarchy with `DoNotRemove` classes which are then filtered when building the jar. The main reason is that cannot compile the original sources for two reasons:

- some classes use dependencies which can be to be problematic
- it will compile the same source code again and we don't need that, we only want our module-info to be produced

Please have a look at this commit of an alternative build prototype : https://github.com/vietj/netty/pull/7/commits/64bba2f965ec23ae33d9a5e8a3f805661792eee9

That would remove the usage of module-info maven plugin for java based maven module, however I think we should keep using the module-info plugin for maven modules which do not compile java files like the native jars.

If that is fine I can try to roll it out early next week.

**Comment by vietj** [comment]
@chrisvest here are the pro/cons I found between the two approaches, let's call that `module-info.yml` vs `module-info.java`

## How it works

`module-info.yml` uses the module-info plugin to produce a `module-info.class` descriptor, some entries are computed automatically like the list of export declarations, the module name is given in the plugin configuration.

`module-info.java` uses a second compilation phase to produce a new class output in `META-INFO/versions/11`, the actual java classes have already been compiled by the `default-compile` maven compiler execution. Actually the Java 11 compilation phases uses the class output previously created as classpath, e.g. some code in the `java11` source tree can reference classes from the `java` source tree.

## Java version requirements

`module-info.java` approach requires to use Java 11 to produce module descriptors, `module-info.yml` works with plain Java 8. However testing JPMS requires to use Java 11 always.

## Maven properties handling

`module-info.yml` handles maven properties, suitable for building a module descriptor with a variable name per classifer (native jars), which is why `io.netty.transport.kqueue`/`io.netty.transport.kqueue.osx-aarch_64`/... (same for epoll/io_uring) still use the module-info plugin (without a `module-info.yml`)

## Module export declarations

`module-info.java` requires to export every java package name of the module and is hence error prone, `module-info.yml` builds the export list according to the classes output

## Multi release jar

`module-info.java` infrastructure provides code adapted to a specific Java version (but not in an IDE friendly fashion)

## Require declarations

`module-info.java` enforces to have the module dependency in the module-path (e.g. compiling with an incorrect `require` fails the compilation), `module-info.yml` will not enforce it (as it stands). However a missing require declaration does not seem enforced, e.g. commenting `requires com.google.protobuf` in `io.netty.codec.protobuf` does not fail the compilation, I believe it is due to the fact there are two compilation phases, the java11 phase produces the module descriptor, the classes have already been compiled with a classpath before.

**Comment by chrisvest** [comment]
@vietj Thank you for looking into this, and making this thorough write-up! On balance it looks like the module-info plug-in is the best approach for 4.2 where need to support Java 8. And perhaps that holds true for Netty 5 as well, if building with more than one version of Java will always be required. It's a little disappointing the tooling isn't better in this area, but we can deal with Java versions using reflect as we've always done, and then keep our build simple.

**Review by chrisvest — APPROVED** [review]

**Comment by vietj** [comment]
@chrisvest actually I was about to give my final thoughts after investigating this which are basically:

"I recommend using the module-info plugin, because it provides more value at the moment since Netty is not using strong encapsulation, the research I have done by switching to the actual Java compilation demonstrate that if we were to opt it for this solution it can be done for a very cheap cost and quite easily and I believe at any time, in addition it could be done on a per module basis."

while doing the research I found actually a small typo in the contribution, I will add a new commit to fix it, that you can squash after.

**Comment by vietj** [comment]
@chrisvest added commit/testing for commons-logging incorrect module name in the branch

**Comment by normanmaurer** [comment]
@vietj so this is ready to go now ?

**Comment by vietj** [comment]
@normanmaurer good to merge!

**Comment by normanmaurer** [comment]
@vietj amazing work! Thanks for all the efforts to make this happen. Can you please also take a stab on the main branch ?

**Comment by vietj** [comment]
thanks @normanmaurer do you mean porting it to the main branch ?

**Comment by normanmaurer** [comment]
@vietj yes

**Comment by vietj** [comment]
of course I will @normanmaurer , I'll update the README for the 4.2 branch first tho

**Pull request merged**
