### PR TITLE
Specialized writeBytes for each Buffer impl

### PR DESCRIPTION
**Pull request by franz1981**
Motivation:

Buffer::writeBytes is not optimized for each Buffer impl

Modifications:

Impl optimized and specialized version of writeBytes

Result:

Better performance on Buffer::writeBytes impls

### CODE REVIEW

**Comment by franz1981** [comment]
This is for the NIO version and byte[] but I plan to send a single PR implementing it for all the buffer types and for different arg types

**Comment by normanmaurer** [comment]
@franz1981 there are test-failures... please check

**Comment by chrisvest** [comment]
@franz1981 ping me when this is ready to be looked at.

**Comment by normanmaurer** [comment]
@franz1981 should we close this one ?

**Comment by franz1981** [comment]
Yep, let me close this! One my RH friend impl it already !

**Pull request closed without merging**
