### PR TITLE
Add methods to easily release messages from inbound / outbound buffer…

### PR DESCRIPTION
**Pull request by normanmaurer**
… of EmbeddedChannel

Motivation:

Often the user uses EmbeddedChannel within unit tests where the only "important" thing is to know if any pending messages were in the buffer and then release these.
We should provide methods for this so the user not need to manually loop through these and release.

Modifications:

Add methods to easily handle releasing of messages.

Result:

Less boiler-plate code for the user to write.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@Scottmitch @trustin PTAL

**Comment by trustin** [comment]
How about adding finishAndReleaseAll() instead of using a boolean
parameter?

**Comment by normanmaurer** [comment]
@trustin fine with me as well. Rest looks good ?

**Comment by trustin** [comment]
Yeah, rest LGTM

**Comment by Scottmitch** [comment]
lgtm

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (b6c320bd0a08b31ce4a300dec5e2c79f1fc01037) and 4.1 (9a183ec38f27ccc1dc541d9a5e6a6cc541a6b0b0)

**Pull request closed without merging**
