### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by idelpivnitskiy**
Motivation:

Update dependencies with newer versions to use more stable libraries.

Modification:

Update versions for some libs in the main pom.xml.

Result:

Updeted dependencies in pom.xml.

Each update in a separate commit for a quick revert in case that newer version of dependency will be incompatible.

### CODE REVIEW

**Comment by normanmaurer** [comment]
+1... Lets wait after the next release

**Comment by normanmaurer** [comment]
@idelpivnitskiy can you please squash these comments into one . I will merge after this.

**Comment by normanmaurer** [comment]
@idelpivnitskiy ping

**Comment by normanmaurer** [comment]
@idelpivnitskiy sorry for the long delay... can you rebase ?

**Comment by njhill** [comment]
and there are newer versions of many of these now (for example gson 2.8.5, slf4j 1.7.26, probably others), may as well bump to the latest?

**Comment by idelpivnitskiy** [comment]
@normanmaurer @njhill sure, will rebase and revisit all versions

**Comment by normanmaurer** [comment]
@idelpivnitskiy I think it would be safer to just do this for master. Can we just re-open this for master ? Sorry for all the mess :/

**Comment by normanmaurer** [comment]
@idelpivnitskiy ping

**Comment by normanmaurer** [comment]
closing this for now... @idelpivnitskiy please do against master

**Pull request closed without merging**
