### PR TITLE
HttpMethod.valueOf hot spot

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
HttpMethod.valueOf shows up on the hot path and can be optimized.

Modifications:
- Change the underlying storage mechanism backing HttpMethod.valueOf

Result:
HttpMethod.valueOf is more efficient.

### CODE REVIEW

**Comment by Scottmitch** [comment]
I will do a bit more digging to see if this is necessary and provide a summary of results.

@nmittler @normanmaurer - FYI

**Comment by nmittler** [comment]
benchmarks? :)

**Comment by Scottmitch** [comment]
@nmittler https://github.com/netty/netty/pull/4424#issuecomment-152599754 on it :)

**Comment by Scottmitch** [comment]
I think this was just an artifact of profiler sampling capturing valueOf when HashMap was used and coincidentally not catching it in the next few runs after changed to TreeMap.  Looks like HashMap is faster for these size inputs...

```
Benchmark                            Mode  Cnt          Score   Error  Units
HttpMethodBenchmark.testValueOfNew  thrpt       85501496.424          ops/s
HttpMethodBenchmark.testValueOfOld  thrpt       126710559.488          ops/s
```

**Pull request closed without merging**
