### PR TITLE
Add test cases for MathUtil.

### PR DESCRIPTION
**Pull request by seedeed**
Motivation:

MathUtil needs more test cases.

Modification:

Add several test cases for MathUtil.

Result:

Improve test coverage slightly.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by seedeed** [comment]
@normanmaurer It seems that some checks fail with building timed out. But no useful error info about this commit was found from CI's console output.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@seedeed thanks a lot!

**Pull request merged**
