### PR TITLE
[#5976] Ensure we only consume as much data on wrap(...) as we can ha…

### PR DESCRIPTION
**Pull request by normanmaurer**
…ndle.

Motiviation:

We need to ensure we only consume as much da as we can maximal put in one ssl record to not produce a BUFFER_OVERFLOW when calling wrap(...).

Modification:

- Limit the amount of data that we consume based on the maximal plain text size that can be put in one ssl record
- Add testcase to verify the fix
- Tighten up testcases to ensure the amount of produced and consumed data in SslEngineResult matches the buffers. If not the tests will fail now.

Result:

Correct and conform behavior of OpenSslEngine.wrap(...) and better test coverage during handshaking in general.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler @jrudolph PTAL

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (c8575c42d0964812c0d2617f98efa7cb64c46be8) and 4.0 (595b2676be9fae5ead92263d0a8396929b3f88b5)

**Comment by jrudolph** [comment]
:+1:

**Comment by normanmaurer** [comment]
@jrudolph thanks! Let me know if you find any other issues.

**Comment by Scottmitch** [comment]
@normanmaurer - did you run benchmarks for use cases this may impact so we can understand the impact?

**Comment by normanmaurer** [comment]
@Scottmitch yes but I did not see any impact even if I wrote 32k buffers.

**Comment by Scottmitch** [comment]
@normanmaurer - great thanks!

**Pull request closed without merging**
