### PR TITLE
Enhance `AsciiString#toLowerCase` and `AsciiString#toUpperCase`

### PR DESCRIPTION
**Pull request by jchrys**
Motivation:
Enhancing the `AsciiString#toLowerCase` and `AsciiString#toUpperCase` methods with SWAR could lead to improved performance.

Modification:
Implementing SWAR in the conversion methods.

Result:
Enhanced performance.

### CODE REVIEW

**Comment by jchrys** [comment]
Below is the benchmark result. It demonstrates that the performance can be up to 8 times faster.

1X10X2, Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz, openjdk 17.0.8 2023-07-18, Ubuntu 22.04.3 LTS, tuend network low-latency

```
----------------------------------------------------------- noUnsafe = false --------------------------------------------------------------
Benchmark                                                                (logPermutations)  (size)   Mode  Cnt    Score   Error      Units
AsciiStringCaseConversionBenchmark.toLowerCase                                           4       7  thrpt   16   45.649 ± 0.123     ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                                           4      16  thrpt   16   34.548 ± 0.103     ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                                           4      23  thrpt   16   26.716 ± 0.228     ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                                           4      32  thrpt   16   22.178 ± 0.004     ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                                          11       7  thrpt   16   35.144 ± 1.549     ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                                          11      16  thrpt   16   34.128 ± 0.078     ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                                          11      23  thrpt   16   20.010 ± 0.144     ops/us
AsciiStringCaseConversionBenchmark.toLowerCase                                          11      32  thrpt   16   21.811 ± 0.179     ops/us

AsciiStringCaseConversionBenchmark.toLowerCaseOld                                        4       7  thrpt   16   32.992 ± 0.006     ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseOld                                        4      16  thrpt   16   22.200 ± 0.063     ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseOld                                        4      23  thrpt   16   18.951 ± 0.005     ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseOld                                        4      32  thrpt   16   15.125 ± 0.009     ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseOld                                       11       7  thrpt   16   21.283 ± 0.011     ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseOld                                       11      16  thrpt   16   14.929 ± 0.321     ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseOld                                       11      23  thrpt   16   13.165 ± 0.013     ops/us
AsciiStringCaseConversionBenchmark.toLowerCaseOld                                       11      32  thrpt   16   10.820 ± 0.126     ops/us

AsciiStringCaseConversionBenchmark.toUpperCase                                           4       7  thrpt   16   51.766 ± 0.048     ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                                           4      16  thrpt   16   40.735 ± 0.154     ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                                           4      23  thrpt   16   32.441 ± 0.182     ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                                           4      32  thrpt   16   30.421 ± 1.130     ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                                          11       7  thrpt   16   45.257 ± 0.126     ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                                          11      16  thrpt   16   39.016 ± 0.120     ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                                          11      23  thrpt   16   26.893 ± 0.595     ops/us
AsciiStringCaseConversionBenchmark.toUpperCase                                          11      32  thrpt   16   32.311 ± 0.034     ops/us


AsciiStringCaseConversionBenchmark.toUpperCaseOld                                        4       7  thrpt   16   37.976 ± 0.017     ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseOld                                        4      16  thrpt   16   25.338 ± 0.061     ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseOld                                        4      23  thrpt   16   21.727 ± 0.036     ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseOld                                        4      32  thrpt   16   17.466 ± 0.013     ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseOld                                       11       7  thrpt   16   24.220 ± 0.117     ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseOld                                       11      16  thrpt   16    9.305 ± 0.051     ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseOld                                       11      23  thrpt   16    5.659 ± 0.004     ops/us
AsciiStringCaseConversionBenchmark.toUpperCaseOld                                       11      32  thrpt   16    4.145 ± 0.009     ops/us

```

**Comment by jchrys** [comment]
The previous PR(#13534) was too large for benchmarking, so I split it into more appropriate sizes.

**Comment by franz1981** [comment]
Lovely work  @jchrys !

**Review by franz1981 — APPROVED** [review]
LGTM! great job!!

Please if you can, add a String case as well in the benchmark so we can actually compare how they behave (with some recent JDK 17/21 versions)

**Comment by jchrys** [comment]
@franz1981 
Thanks for your review and the support you've provided! :D 
I'll be adding the String case shortly.

**Comment by jchrys** [comment]
Below is the `AsciiString`, `String` case conversion benchmark result([raw](https://gist.github.com/jchrys/56bcdf0c85332abfc1e45309e757d52c)).

1X10X2, Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz, openjdk 17.0.10 2024-01-16, Ubuntu 22.04.3 LTS, tuend network low-latency, no turbo boost, noUnsafe = false

```
Benchmark              (logPermutations)  (size)   Mode  Cnt    Score   Error      Units
toLowerCase                            4       7  thrpt   16   47.723 ± 0.486     ops/us
toLowerCase                            4      16  thrpt   16   33.046 ± 0.134     ops/us
toLowerCase                            4      23  thrpt   16   26.358 ± 0.014     ops/us
toLowerCase                            4      32  thrpt   16   21.325 ± 0.006     ops/us

toLowerCase                           11       7  thrpt   16   35.956 ± 0.250     ops/us
toLowerCase                           11      16  thrpt   16   31.390 ± 0.147     ops/us
toLowerCase                           11      23  thrpt   16   20.235 ± 0.174     ops/us
toLowerCase                           11      32  thrpt   16   21.992 ± 0.239     ops/us

toUpperCase                            4       7  thrpt   16   51.152 ± 0.228     ops/us
toUpperCase                            4      16  thrpt   16   40.610 ± 0.190     ops/us
toUpperCase                            4      23  thrpt   16   32.947 ± 0.018     ops/us
toUpperCase                            4      32  thrpt   16   30.446 ± 1.159     ops/us

toUpperCase                           11       7  thrpt   16   45.614 ± 0.523     ops/us
toUpperCase                           11      16  thrpt   16   38.437 ± 0.624     ops/us
toUpperCase                           11      23  thrpt   16   27.224 ± 0.075     ops/us
toUpperCase                           11      32  thrpt   16   31.880 ± 0.176     ops/us

stringToLowerCase                      4       7  thrpt   16   30.604 ± 0.520     ops/us
stringToLowerCase                      4      16  thrpt   16   24.676 ± 0.022     ops/us
stringToLowerCase                      4      23  thrpt   16   19.093 ± 0.023     ops/us
stringToLowerCase                      4      32  thrpt   16   15.968 ± 0.004     ops/us

stringToLowerCase                     11       7  thrpt   16   20.742 ± 0.347     ops/us
stringToLowerCase                     11      16  thrpt   16   16.104 ± 0.008     ops/us
stringToLowerCase                     11      23  thrpt   16   13.324 ± 0.079     ops/us
stringToLowerCase                     11      32  thrpt   16   11.389 ± 0.005     ops/us

stringtoUpperCase                      4       7  thrpt   16   32.986 ± 0.030     ops/us
stringtoUpperCase                      4      16  thrpt   16   20.096 ± 0.016     ops/us
stringtoUpperCase                      4      23  thrpt   16   15.729 ± 0.042     ops/us
stringtoUpperCase                      4      32  thrpt   16   12.480 ± 0.008     ops/us

stringtoUpperCase                     11       7  thrpt   16   18.060 ± 0.046     ops/us
stringtoUpperCase                     11      16  thrpt   16    6.683 ± 0.030     ops/us
stringtoUpperCase                     11      23  thrpt   16    4.778 ± 0.010     ops/us
stringtoUpperCase                     11      32  thrpt   16    3.460 ± 0.005     ops/us
```

**Comment by franz1981** [comment]
Numbers for OpenJDK are very low, which version is? 

Last but not least, what with noUnsafe = true?


Next time you can use some online visualiser of jmp results to help reading the data, just need to produce it via -rf json

**Comment by jchrys** [comment]
The `noUnsafe=true` comment refers to the benchmark configuration where I set the system property `io.netty.noUnsafe` to `true` . This configuration determines whether the use of unsafe operations is permitted or not.(https://github.com/netty/netty/blob/45ba439cc0584f6ed0c3a0d7cdb7f319c5618b08/common/src/main/java/io/netty/util/internal/PlatformDependent0.java#L514)

In the first benchmark, I used version 17.0.7, but I didn't pay attention to whether it was an old version or not. In the second one, I used 17.0.10 (the latest GA provided by https://wiki.openjdk.org/display/JDKUpdates/JDK+17u). Do you have any recommended versions?

Let me update it with online visualizable data.

Thanks for your tips 👍

**Comment by jchrys** [comment]
I have uploaded the JSON results of the Benchmark using openjdk 17.0.10. ([result](https://gist.github.com/jchrys/40519d59412dd5f4df0936e0986c13c2))

**Review by normanmaurer — APPROVED** [review]
Great work!

**Comment by franz1981** [comment]
Numbers for OpenJDK are very low, which version is? 

Last but not least, what with noUnsafe = true?


Next time you can use some online visualiser of jmp results to help reading the data, just need to produce it via -rf json

**Comment by franz1981** [comment]
Thanks @jchrys has been a fabulous job (useful too, if I think the Content-Type like http 2 transformations to work well with the lower case requirements

**Comment by jchrys** [comment]
@franz1981 
The `noUnsafe=true` comment refers to the benchmark configuration where I set the system property `io.netty.noUnsafe` to `true` . This configuration determines whether the use of unsafe operations is permitted or not.(https://github.com/netty/netty/blob/45ba439cc0584f6ed0c3a0d7cdb7f319c5618b08/common/src/main/java/io/netty/util/internal/PlatformDependent0.java#L514)

In the first benchmark, I used version 17.0.7, but I didn't pay attention to whether it was an old version or not. In the second one, I used 17.0.10 (the latest GA provided by https://wiki.openjdk.org/display/JDKUpdates/JDK+17u). Do you have any recommended versions?

Let me update it with online visualizable data.

Thanks for your tips 👍 

I have uploaded the JSON results of the Benchmark using openjdk 17.0.10. ([result](https://gist.github.com/jchrys/40519d59412dd5f4df0936e0986c13c2))

**Review by franz1981 — APPROVED** [review]

**Pull request merged**
