### PR TITLE
Optimize FastThreadLocal

### PR DESCRIPTION
**Pull request by laosijikaichele**
Motivation:

The object array's `index` of `FastThreadLocal` was application scope, so the increment of `index` within one thread will affect all the other threads. 

For example:

If one thread's threadLocal stores more than 32(the initial table size) elements, then the second thread will do the table expansion even it only needs store just 1 element, this will cause the object array expansion more frequently and eat more memory. 

Code example:
```
public static void main(String[] args) throws InterruptedException {
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < 31; i++) {
                    FastThreadLocal<Integer> fst = new FastThreadLocal<Integer>();
                    fst.set(i);
                }
            }
        });
        t1.start();
        t1.join();
        // After t1 thread finished, the main thread create a FastThreadLocal fst2.
        FastThreadLocal<Integer> fst2 = new FastThreadLocal();
        // The object table of 'fst2' will do expansion, even it only needs store just ONE element.
        fst2.set(2);
    }
```

Modification:

1. Change the index of threadLocal array scope from global scope to thread scope.
2. Postpone the generation of the `index` value from `FastThreadLocal`'s construction method to get()/set() method.

Result:

Save memory space and lower the table expansion overhead.

(Partly)Fixes: #11937.

### CODE REVIEW

**Comment by chrisvest** [comment]
This does not look correct. The `FastThreadLocal` instances may be shared across threads (that's the point of `ThreadLocal` objects after all), and each thread have their own `InternalThreadLocalMap`. The index in the thread-local needs to be coordinated across the maps, so they can all agree on what storage slot to use.
With your change, if two threads initialize the `FastThreadLocal` at the same time, they can produce different indexes and one will loose an update, such that the storage slot used will change. If another thread already initialized a thread-local, they could put in an index that is already used by other thread-locals in other threads.

**Comment by laosijikaichele** [comment]
@chrisvest , thanks for replying, I think `FastThreadLocal` instance may be accessed from different threads, but it finally will leads to their own thread's `InternalThreadLocalMap `, which seems to be fine.  May be I am not quite follow your thought, would you please give some example code to help me better understand it, thanks a lot.

**Comment by chrisvest** [comment]
The `FastThreadLocal.index` field is shared across threads, but the specific value now means different things to different threads because the next index counters are now thread-specific.

Like, what happens in this case, for instance?

```
a = new FastThreadLocal();
b = new FastThreadLocal();

T1:                     T2:
                        a.set(1);
b.set(2);
a.set(3);
assert b.get() == ???
```

**Comment by laosijikaichele** [comment]
@chrisvest Yes you are right, I wrongly understand the logic. Let me think whether where is an alternative way to approach. Thanks a lot for correcting me.

**Pull request closed without merging**
