### PR TITLE
Ensure we not schedule multiple timeouts for close notify

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We should only schedule one timeout to wait for the close notify to be done.

Modifications:

Keep track of if we already scheduled a timeout for close notify and if so not schedule another one.

Result:

No duplicated timeouts.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@doom369 FYI... related to https://stackoverflow.com/questions/49338730/how-to-deal-with-netty-last-write-attempt-timed-out-force-closing-the-connecti/49348029?noredirect=1#comment85739344_49348029

**Comment by doom369** [comment]
@normanmaurer thanks! I'll be able to make new deploy in few days.

**Comment by normanmaurer** [comment]
Yep on my to do list

**Comment by normanmaurer** [comment]
@carl-mastrangelo I am a bit out of ideas how to add a unit test :(

**Comment by normanmaurer** [comment]
@trustin can you check as well ?

**Comment by normanmaurer** [comment]
Let me merge this now

**Pull request merged**
