### PR TITLE
Minor simplifications/optimizations to AbstractByteBuf methods

### PR DESCRIPTION
**Pull request by njhill**
Motivation

While working on other changes I noticed some opportunities to streamline a few things in `AbstractByteBuf`.

Modifications

- Avoid duplicate `ensureAccessible()` checks in `discard`(`Some`)`ReadBytes()` and `ensureWritable0(int)` methods
- Simplify `ensureWritable0(int)` logic
- Make some conditional checks more concise

Result

Cleaner, possibly faster code

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by carryxyh** [comment]
@njhill 
hi, I have a confusion about this modification. According to the comment of `ensureAccessible`, every time we try to `access the buffers content`, we should call `ensureAccessible` to check it.

According to this statement, in the `discardReadBytes` method, the content of the current ByteBuf has been modified(call `setBytes(0, this, readerIndex, writerIndex - readerIndex)`) under the branch of` readerIndex! = WriterIndex`. Why did it not call `ensureAccessible` to detect it?

**Comment by njhill** [comment]
@carryxyh `setBytes` is a public method and so itself will check accessibility... hence the redundant check on that path

**Comment by carryxyh** [comment]
@njhill 
Solved my confusion, thank you very much...

**Pull request merged**
