### PR TITLE
Load Conscrypt method via reflection only once

### PR DESCRIPTION
**Pull request by ejona86**
Motivation:

The code did reflection every method call which made the code slower and
harder to read with additional cases to consider.

Modifications:

Instead of loading the method and then throwing it away, save the Method
reference instead of the Class reference. Then also use more precise
exception handling for the method invocation.

Result:

Simpler, speedier code.

### CODE REVIEW

**Comment by ejona86** [comment]
Unfortunately the diff is pretty ugly because I moved the code from getConscryptClass up to the top of the class so that methods called during initialization are not mixed with other static methods.

P.S... _or_ Norman can approve the PR before I write my peace.

**Comment by ejona86** [comment]
Doh. Just realized I hadn't tested this again after the more fine-grain exceptions. It doesn't compile. One moment.

**Comment by ejona86** [comment]
Okay. This time with the missing semicolon. Conscrypt test still runs all 93 tests.

**Comment by normanmaurer** [comment]
When you are already on it can you also do another or to update to 1.0.0 ?

**Comment by ejona86** [comment]
Sure. I'll send out a PR for bumping to Conscrypt 1.0.0.

**Comment by normanmaurer** [comment]
@ejona86 thanks !

Cherry-picked into 4.1 (8b273983f05b75e32353b07bad0dac2ecbbca9c7)

**Pull request closed without merging**
