### PR TITLE
Correctly handle the case when BUFFER_OVERFLOW happens during unwrap …

### PR DESCRIPTION
**Pull request by normanmaurer**
…but the readable bytes are bigger then the expected applicationBufferSize

Motivation:

We need to ensure we handle the case when BUFFER_OVERFLOW happens during unwrap but the readable bytes are bigger then the expected applicationBufferSize. Otherwise we may produce an IllegalArgumentException as we will try to allocate a buffer with capacity < 0.

Modifications:

- Guard against this case.
- Ensure we not double release buffer on exception when doing unwrap.

Result:

No more exception when running testsuite with java 9.

### CODE REVIEW

**Comment by johnou** [comment]
@normanmaurer works with JRE8 and fails with JRE9?

**Comment by normanmaurer** [comment]
Yes... that said I think it is a valid behavior of a SSLEngine implementation

**Comment by johnou** [comment]
Nice catch!

**Comment by normanmaurer** [comment]
@Scottmitch PTAL .... once this is in we will get successful builds with java9 on our CI servers 👍

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (2055f4c) and 4.0 (b1d6b30)

**Pull request closed without merging**
