### PR TITLE
Add `FUNDING.yml`

### PR DESCRIPTION
**Pull request by trustin**
We now have a registered non-profit entity in South Korea. We could start to accept donation from the community to cover the cost related with running the projects under @netty GitHub organization, such as (but not limited to):

- Build and dev infra, SaaS subscriptions and equipment
- Hosting and attending the community events
- Paying the core developers for their work; and
- Establishing a non-profit tax-deductible foundation.

We're currently a non-profit entity located in South Korea (this is where @trustin lives). Please note that the donation is not tax-deductible at the moment.

### CODE REVIEW

**Comment by trustin** [comment]
Here are the links to the donation platforms I signed up for:

- GitHub Sponsors: https://github.com/sponsors/netty/
- Ko-Fi: https://ko-fi.com/netty_project
- Liberapay: https://liberapay.com/netty/
- Open Collective: https://opencollective.com/netty_project
- Patreon: https://www.patreon.com/netty
- PayPal.me: https://paypal.me/nettyproject

**Comment by trustin** [comment]
@normanmaurer Gentle ping 😉

**Comment by normanmaurer** [comment]
@trustin LGTM

**Review by normanmaurer — APPROVED** [review]

**Comment by trustin** [comment]
Thanks, @normanmaurer!

**Pull request merged**
