### PR TITLE
Add nativeAddress() method to Buffer.

### LINKED ISSUE #12609: Hard to get direct memory address for netty5 Buffer
I want to get a direct memory address for Buffer where `writerOffset() == readerOffset()` but current design of Buffer in netty5 is hard.
If `writerOffset() == readerOffset() && writerOffset() == capacity()` then `forEachReadable` and `forEachWritable` do not `foreach`.
If there any readable or writable bytes then this _solution_ add something similar of netty4 ByteBuf memoryAddress:
```
var address = 0L
buf.forEachReadable(
  0,
  (_, component) =>
    address = component.readableNativeAddress() - buf.readerOffset()
    false
)
if address == 0 then
  buf.forEachWritable(
    0,
    (_, component) =>
      address = component.writableNativeAddress() - buf.writerOffset()
      false
  )
address match
  case 0L => throw BufferMemoryAddressIsZero
  case _ => address
```

Why this is so hard in netty5? Previous ByteBuf'er is easy to use with native code (JEP-419).

### Expected behavior

When I parsing a Buffer and get to the end I want to get raw memoryAddress of my single offheap Buffer and pass it to native code with my offset and length variables by myself, for example to check integrity in STUN protocol.

### Actual behavior

forEachReadable and forEachWritable do not foreach without changing writerOffset or readerOffset. And there no ability to get direct memory address without a proxy class like SingleComponentIterator.

### Netty version

netty-5.0.0.Alpha3

### PR DESCRIPTION
**Pull request by timothyklim**
Motiviation:

We should be able to support of getting the raw memory address of single and direct Buffer.

Modifications:

- Add hasNativeAddress() method to Buffer.
- Make nativeAddress() method public.

Result:

Be able to get memory address of a Buffer like in netty 4.

Fixes #12609.

### CODE REVIEW

**Comment by timothyklim** [comment]
I have webrtc like project on netty5 (migrated from netty4). There only UDP protocol with single direct Buffers. There is no Buffer's on the heap or any usage of CompositeBuffer.
Netty is really good fit in it. But new design of Buffer has no ability to get memory address like in netty 4. All I want is to able to get native address for native code through JEP-419 with own offset and length variables without any additional writer/reader offsets subtraction and GC non free iterators.

**Comment by chrisvest** [comment]
I want to try a different idea before deciding on this one. I'm thinking we could collapse the split between iterating readable and writable components into just iterating components, and then provide a base native address. The objective being to make all the different Buffer implementations behave as similar as possible.

**Comment by hyperxpro** [comment]
I think we should try different approach because this one is kind of unsafe and provides minimal information about type of address type. (Readable or Writable)

However, +1 for this idea.

**Comment by normanmaurer** [comment]
> I want to try a different idea before deciding on this one. I'm thinking we could collapse the split between iterating readable and writable components into just iterating components, and then provide a base native address. The objective being to make all the different Buffer implementations behave as similar as possible.

Did you have time for this yet ?

**Comment by chrisvest** [comment]
> Did you have time for this yet ?

Not yet. Wanted to do HTTP headers changes first.

**Pull request closed without merging**
