### PR TITLE
Add NetBSD support

### LINKED ISSUE #10809: NetBSD support
### Expected behavior

Build and work on NetBSD.

### Actual behavior

Not working on NetBSD.

### Steps to reproduce

Try to build in pkgsrc-wip with these build rules:

https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=commitdiff;h=216b86d9ff25fb21af74d56ca1f45afe87031aab

Package is called 'java-netty'.

The package is inspired by FreeBSD's ports package for the same software.

### Minimal yet complete reproducer code (or URL to code)

https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=blob;f=java-netty/files/patch-netty_kqueue_bsdsocket.c;h=130c5bf49a2bedf8be46ba489d1e2c7476b792f1;hb=216b86d9ff25fb21af74d56ca1f45afe87031aab

1. TCP_NOPUSH is unsupported
2. sendfile() is unsupported
3. netty_kqueue_bsdsocket_getPeerCredentials needs a custom implementation

Does this patch looks good? At minimum, the 1-3 problems have to be fixed.

### Netty version

4.1.53

### JVM version (e.g. `java -version`)

https://pkgsrc.se/lang/openjdk11

openjdk11 version 1.11.0.9.11

### OS version (e.g. `uname -a`)

NetBSD/amd64 9.99.x

### PR DESCRIPTION
**Pull request by krytarowski**
Motivation:

Add NetBSD support.

Modification:

NetBSD is a BSD target, but with:
 - lack of sendfile()
 - lack of TCP_NOPUSH
 - different semantics of netty_kqueue_bsdsocket_getPeerCredentials

Result:

Fixes #10809

### CODE REVIEW

**Comment by krytarowski** [comment]
@normanmaurer PTAL

**Comment by krytarowski** [comment]
> @krytarowski can you sign our ICLA and let me know once done ?
> 
> https://netty.io/s/icla

Done.

`Your response has been recorded.`

**Comment by normanmaurer** [comment]
@krytarowski Can you test my latest changes  ? I just pushed an update which should hopefully fix stuff on netbsd.

**Comment by krytarowski** [comment]
How to test (other than build-test)? Is there some command I can run to execute a test suite?

**Comment by normanmaurer** [comment]
```
./mvnw -pl transport-native-unix-common,transport-native-kqueue clean package
```

**Comment by krytarowski** [comment]
```
JAVA_HOME=/usr/pkg/java/openjdk11 ./mvnw -Djavax.net.ssl.trustStorePassword=changeit -pl transport-native-unix-common,transport-native-kqueue clean package
```

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: netbsd
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 9.99
[INFO] os.detected.version.major: 9
[INFO] os.detected.version.minor: 99
[INFO] os.detected.classifier: netbsd-x86_64
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Netty/Transport/Native/Unix/Common                                 [jar]
[INFO] Netty/Transport/Native/KQueue                                      [jar]
[INFO] 
[INFO] ------------< io.netty:netty-transport-native-unix-common >-------------
[INFO] Building Netty/Transport/Native/Unix/Common 4.1.55.Final-SNAPSHOT  [1/2]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ netty-transport-native-unix-common ---
[INFO] Deleting /public/netty/transport-native-unix-common/target
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-tools) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.0:check (check-style) @ netty-transport-native-unix-common ---
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] --- xml-maven-plugin:1.0.1:check-format (check-style) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:get (get-jetty-alpn-agent) @ netty-transport-native-unix-common ---
[INFO] Resolving org.mortbay.jetty.alpn:jetty-alpn-agent:jar:2.0.10 with transitive dependencies
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:parse-version (parse-version) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (write-version-properties) @ netty-transport-native-unix-common ---
[INFO] Executing tasks

main:
     [echo] Current commit: ba83a8840f on 2020-11-23 14:03:32 +0100
    [mkdir] Created dir: /public/netty/transport-native-unix-common/target/classes/META-INF
[propertyfile] Creating new property file: /public/netty/transport-native-unix-common/target/classes/META-INF/io.netty.versions.properties
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-scm-plugin:1.11.2:checkout (get-netty-jni-util) @ netty-transport-native-unix-common ---
[INFO] Removing /public/netty/transport-native-unix-common/target/netty-jni-util
[INFO] Executing: /bin/sh -c cd '/public/netty/transport-native-unix-common/target' && 'git' 'clone' '--branch' '0.0.1' 'https://github.com/netty/netty-jni-util.git' 'netty-jni-util'
[INFO] Working directory: /public/netty/transport-native-unix-common/target
[INFO] Executing: /bin/sh -c cd '/tmp/' && 'git' 'ls-remote' 'https://github.com/netty/netty-jni-util.git'
[INFO] Working directory: /tmp
[INFO] Executing: /bin/sh -c cd '/public/netty/transport-native-unix-common/target/netty-jni-util' && 'git' 'fetch' 'https://github.com/netty/netty-jni-util.git'
[INFO] Working directory: /public/netty/transport-native-unix-common/target/netty-jni-util
[INFO] Executing: /bin/sh -c cd '/public/netty/transport-native-unix-common/target/netty-jni-util' && 'git' 'checkout' '0.0.1'
[INFO] Working directory: /public/netty/transport-native-unix-common/target/netty-jni-util
[INFO] Executing: /bin/sh -c cd '/public/netty/transport-native-unix-common/target/netty-jni-util' && 'git' 'ls-files'
[INFO] Working directory: /public/netty/transport-native-unix-common/target/netty-jni-util
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-source (default) @ netty-transport-native-unix-common ---
[INFO] Source directory: /public/netty/transport-native-unix-common/src/main/c added.
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ netty-transport-native-unix-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /public/netty/transport-native-unix-common/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ netty-transport-native-unix-common ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 21 source files to /public/netty/transport-native-unix-common/target/classes
[INFO] 
[INFO] --- forbiddenapis:2.2:check (check-forbidden-apis) @ netty-transport-native-unix-common ---
[INFO] Skipping forbidden-apis checks.
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.16:check (default) @ netty-transport-native-unix-common ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO] 
[INFO] >>> maven-bundle-plugin:2.5.4:manifest (generate-manifest) > process-classes @ netty-transport-native-unix-common >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-tools) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.0:check (check-style) @ netty-transport-native-unix-common ---
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] --- xml-maven-plugin:1.0.1:check-format (check-style) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:get (get-jetty-alpn-agent) @ netty-transport-native-unix-common ---
[INFO] Resolving org.mortbay.jetty.alpn:jetty-alpn-agent:jar:2.0.10 with transitive dependencies
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:parse-version (parse-version) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (write-version-properties) @ netty-transport-native-unix-common ---
[INFO] Executing tasks

main:
     [echo] Current commit: ba83a8840f on 2020-11-23 14:03:32 +0100
   [delete] Deleting: /public/netty/transport-native-unix-common/target/classes/META-INF/io.netty.versions.properties
[propertyfile] Creating new property file: /public/netty/transport-native-unix-common/target/classes/META-INF/io.netty.versions.properties
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-scm-plugin:1.11.2:checkout (get-netty-jni-util) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-source (default) @ netty-transport-native-unix-common ---
[INFO] Source directory: /public/netty/transport-native-unix-common/src/main/c added.
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ netty-transport-native-unix-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /public/netty/transport-native-unix-common/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ netty-transport-native-unix-common ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- forbiddenapis:2.2:check (check-forbidden-apis) @ netty-transport-native-unix-common ---
[INFO] Skipping forbidden-apis checks.
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.16:check (default) @ netty-transport-native-unix-common ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO] 
[INFO] <<< maven-bundle-plugin:2.5.4:manifest (generate-manifest) < process-classes @ netty-transport-native-unix-common <<<
[INFO] 
[INFO] 
[INFO] --- maven-bundle-plugin:2.5.4:manifest (generate-manifest) @ netty-transport-native-unix-common ---
[WARNING] Manifest io.netty:netty-transport-native-unix-common:jar:4.1.55.Final-SNAPSHOT : Unused Import-Package instructions: [sun.misc.*, sun.security.*] 
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ netty-transport-native-unix-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /public/netty/transport-native-unix-common/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ netty-transport-native-unix-common ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /public/netty/transport-native-unix-common/target/test-classes
[INFO] 
[INFO] --- forbiddenapis:2.2:testCheck (check-forbidden-test-apis) @ netty-transport-native-unix-common ---
[INFO] Skipping forbidden-apis checks.
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ netty-transport-native-unix-common ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Netty/Transport/Native/Unix/Common 4.1.55.Final-SNAPSHOT:
[INFO] 
[INFO] Netty/Transport/Native/Unix/Common ................. FAILURE [ 10.483 s]
[INFO] Netty/Transport/Native/KQueue ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.154 s
[INFO] Finished at: 2020-11-23T19:38:17+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project netty-transport-native-unix-common: There are test failures.
[ERROR] 
[ERROR] Please refer to /public/netty/transport-native-unix-common/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /public/netty/transport-native-unix-common && /usr/pkg/java/openjdk11/bin/java -server -dsa -da -ea:io.netty... -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -D_ -D_ -D_ --illegal-access=deny -D_ -jar /public/netty/transport-native-unix-common/target/surefire/surefirebooter7328725072756181938.jar /public/netty/transport-native-unix-common/target/surefire 2020-11-23T19-38-17_624-jvmRun1 surefire3770798270220406988tmp surefire_05569624046007173582tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /public/netty/transport-native-unix-common && /usr/pkg/java/openjdk11/bin/java -server -dsa -da -ea:io.netty... -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -D_ -D_ -D_ --illegal-access=deny -D_ -jar /public/netty/transport-native-unix-common/target/surefire/surefirebooter7328725072756181938.jar /public/netty/transport-native-unix-common/target/surefire 2020-11-23T19-38-17_624-jvmRun1 surefire3770798270220406988tmp surefire_05569624046007173582tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
[ERROR] 	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
[ERROR] 	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:60)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by normanmaurer** [comment]
uff ... no idea. I have no netbsd box here and also not much experience with netbsd :/

**Comment by normanmaurer** [comment]
Can you see if you can run other tests ? like:

```
./mvnw -pl common,buffer clean package
```

**Comment by krytarowski** [comment]
I was told to check surefire tests and they trigger an openjdk11 error on NetBSD, related to kqueue (EINVAL). I need to dig into it.

**Comment by normanmaurer** [comment]
@krytarowski keep me posted.

**Comment by normanmaurer** [comment]
Any progress here ? If not I suspect we should close this for now.

**Comment by krytarowski** [comment]
I was moving my house over the past 1-2 months and I can have a look at openjdk bug for NetBSD. There is something wrong with kqueue.

**Comment by krytarowski** [comment]
I need to punt java for now, if you like close this PR.. or merge.

**Comment by normanmaurer** [comment]
Let me close it for now

**Pull request closed without merging**
