### PR TITLE
Moving KObjectHashMapTest to propert directory

### LINKED ISSUE #4546: Netty 4.1 generates the XxxObjectHashMapTest.java to the wrong package?
hi,when i update my branch to netty4.1,i get some compile errors:

netty-4-1-2015-12-09

(i  use maven 3.3.3, Mac OS)

i guess that is because we should move "templates/io.netty.util.collection/KObjectHashMapTest.template"
to 
"templates/io/netty/util/collection/KObjectHashMapTest.template"
,but i'm not sure about it, or did i missed something?

### PR DESCRIPTION
**Pull request by nmittler**
Motivation:

The KObjectHashMapTest is in a directory called "io.netty.util.collection" rather than "io/netty/util/collection". This causes the generated tests to be created in the wrong directory as well.

Modifications:

Moved the file.

Result:

Fixes #4546

### CODE REVIEW

**Comment by nmittler** [comment]
@Scottmitch PTAL

**Comment by normanmaurer** [comment]
@nmittler LGTM

**Comment by Scottmitch** [comment]
ship it! thanks!

**Comment by nmittler** [comment]
Cherry-picked as 27b330d

**Comment by Scottmitch** [comment]
@nmittler - does this need to go into master too?

**Comment by normanmaurer** [comment]
Done for @nmittler as b172411570cd9963b1a9e09adc5a93c0ada1c394

**Comment by nmittler** [comment]
@normanmaurer oof sorry .... I thought master was gone :/

**Comment by normanmaurer** [comment]
Not yet... Will kill it today or tomorrow

**Pull request closed without merging**
