### PR TITLE
Add test to verify that its possible to add another ChannelInitialize…

### PR DESCRIPTION
**Pull request by normanmaurer**
…r in the initChannel(...) method.

Motivation:

I received a report the its not possible to add another ChannelInitialiter in the initChannel(...) method, so we should add a test case for it.

Modifications:

Added testcase.

Result:

Validate that all works as expected.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@mosesn FYI

**Comment by mosesn** [comment]
Thanks!  Can you also check the order in which they'll be applied if I try to do this for two?  And can you also check that if you manipulate the pipeline directly after adding the ChannelInitializer that the ChannelInitializer's initchannel hasn't been applied yet?

**Comment by normanmaurer** [comment]
@mosesn sure... will adjust the pr and ping you again once done.

**Comment by normanmaurer** [comment]
@mosesn let me merge this first. Will do another PR.

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (b97a36a10f738d946cb8ff920c8e1177db40c74b) and 4.0 (2bc902e71ba40e354d1bda87cdcf40e5860041db)

**Pull request closed without merging**
