### PR TITLE
Java 9 introduced Arrays:equals intrinsics

### PR DESCRIPTION
**Pull request by franz1981**
Motivation:

AsciiStrings and others are heavy users of byte[] equality checks

Modifications:

Leverage existing Arrays::equals(byte[]) intrinsics

Result:

Faster equality matches on hit(s)

### CODE REVIEW

**Comment by franz1981** [comment]
These are the numbers on my Ryzen box: please @chrisvest if you have a  mac OS would be great to see what you got too

on 4.1:
```
Benchmark                                    (size)  Mode  Cnt     Score   Error  Units
PlatformDependentBenchmark.arraysBytesEqual      10  avgt   20     1.992 ± 0.080  ns/op
PlatformDependentBenchmark.arraysBytesEqual      50  avgt   20     1.823 ± 0.037  ns/op
PlatformDependentBenchmark.arraysBytesEqual     100  avgt   20     2.557 ± 0.052  ns/op
PlatformDependentBenchmark.arraysBytesEqual    1000  avgt   20    14.933 ± 0.018  ns/op
PlatformDependentBenchmark.arraysBytesEqual   10000  avgt   20   129.324 ± 0.033  ns/op
PlatformDependentBenchmark.arraysBytesEqual  100000  avgt   20  1405.409 ± 1.867  ns/op
PlatformDependentBenchmark.unsafeBytesEqual      10  avgt   20     3.756 ± 0.012  ns/op
PlatformDependentBenchmark.unsafeBytesEqual      50  avgt   20     5.803 ± 0.006  ns/op
PlatformDependentBenchmark.unsafeBytesEqual     100  avgt   20     7.532 ± 0.037  ns/op
PlatformDependentBenchmark.unsafeBytesEqual    1000  avgt   20    26.729 ± 0.158  ns/op
PlatformDependentBenchmark.unsafeBytesEqual   10000  avgt   20   222.200 ± 0.213  ns/op
PlatformDependentBenchmark.unsafeBytesEqual  100000  avgt   20  2772.075 ± 2.376  ns/op
```
with `# VM version: JDK 17.0.7, Java HotSpot(TM) 64-Bit Server VM, 17.0.7+8-LTS-224`

which suggest `Arrays::equals` intrinsics to be quite in place (while they weren't on java 8, for example.

I need to perform more measurements, feel free to add more if you can

**Review by normanmaurer — APPROVED** [review]
LGTM

**Comment by chrisvest** [comment]
@franz1981 This is what I get with `JDK 17.0.8, OpenJDK 64-Bit Server VM, 17.0.8+7-LTS` on MacOS 14.1.2 M1 Pro.

4.1:
```
Benchmark                                    (size)  Mode  Cnt     Score    Error  Units
PlatformDependentBenchmark.arraysBytesEqual      10  avgt   20     1.611 ±  0.001  ns/op
PlatformDependentBenchmark.arraysBytesEqual      50  avgt   20     3.162 ±  0.002  ns/op
PlatformDependentBenchmark.arraysBytesEqual     100  avgt   20     5.033 ±  0.009  ns/op
PlatformDependentBenchmark.arraysBytesEqual    1000  avgt   20    21.493 ±  0.011  ns/op
PlatformDependentBenchmark.arraysBytesEqual   10000  avgt   20   201.622 ±  0.076  ns/op
PlatformDependentBenchmark.arraysBytesEqual  100000  avgt   20  2665.022 ±  2.115  ns/op
PlatformDependentBenchmark.unsafeBytesEqual      10  avgt   20     1.992 ± 0.006  ns/op
PlatformDependentBenchmark.unsafeBytesEqual      50  avgt   20     4.364 ± 0.002  ns/op
PlatformDependentBenchmark.unsafeBytesEqual     100  avgt   20     6.009 ± 0.009  ns/op
PlatformDependentBenchmark.unsafeBytesEqual    1000  avgt   20    32.657 ± 0.046  ns/op
PlatformDependentBenchmark.unsafeBytesEqual   10000  avgt   20   273.309 ± 0.122  ns/op
PlatformDependentBenchmark.unsafeBytesEqual  100000  avgt   20  3703.141 ± 2.126  ns/op
```

This PR:
```
PlatformDependentBenchmark.unsafeBytesEqual      10  avgt   20     1.871 ±  0.001  ns/op
PlatformDependentBenchmark.unsafeBytesEqual      50  avgt   20     3.325 ±  0.001  ns/op
PlatformDependentBenchmark.unsafeBytesEqual     100  avgt   20     5.199 ±  0.015  ns/op
PlatformDependentBenchmark.unsafeBytesEqual    1000  avgt   20    21.832 ±  0.012  ns/op
PlatformDependentBenchmark.unsafeBytesEqual   10000  avgt   20   202.340 ±  0.146  ns/op
PlatformDependentBenchmark.unsafeBytesEqual  100000  avgt   20  2653.689 ± 13.924  ns/op
```

**Review by chrisvest — APPROVED** [review]

**Comment by franz1981** [comment]
thanks @chrisvest to have tried it, I've tried with another oldish laptop with `Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
` and still same JDK than the previous test with Ryzen:
```
Benchmark                                    (size)  Mode  Cnt     Score     Error  Units
PlatformDependentBenchmark.arraysBytesEqual      10  avgt   20     8.345 ±   0.247  ns/op
PlatformDependentBenchmark.arraysBytesEqual      50  avgt   20     8.244 ±   0.171  ns/op
PlatformDependentBenchmark.arraysBytesEqual     100  avgt   20    10.499 ±   0.051  ns/op
PlatformDependentBenchmark.arraysBytesEqual    1000  avgt   20    43.411 ±   0.378  ns/op
PlatformDependentBenchmark.arraysBytesEqual   10000  avgt   20   378.831 ±   1.878  ns/op
PlatformDependentBenchmark.arraysBytesEqual  100000  avgt   20  4416.417 ±  33.592  ns/op
PlatformDependentBenchmark.unsafeBytesEqual      10  avgt   20     7.397 ±   0.043  ns/op
PlatformDependentBenchmark.unsafeBytesEqual      50  avgt   20    13.516 ±   0.109  ns/op
PlatformDependentBenchmark.unsafeBytesEqual     100  avgt   20    16.964 ±   0.138  ns/op
PlatformDependentBenchmark.unsafeBytesEqual    1000  avgt   20    62.867 ±   1.300  ns/op
PlatformDependentBenchmark.unsafeBytesEqual   10000  avgt   20   536.335 ±   3.593  ns/op
PlatformDependentBenchmark.unsafeBytesEqual  100000  avgt   20  7849.485 ± 220.603  ns/op
```
And interestingly it seems that the case with very we bytes it's slightly slower, I'm retrying few times

**Comment by normanmaurer** [comment]
@franz1981 thanks a lot!

**Comment by normanmaurer** [comment]
@franz1981 can you also do a PR against main ?

**Pull request merged**
