### PR TITLE
[#4373] Fix assert error when trying to release Channel to closed Fix…

### PR DESCRIPTION
**Pull request by normanmaurer**
…edChannelPool

Motivation:

Once a FixedChannelPool was closed we must not allow to acquire or release Channels to prevent assert errors.

Modifications:

Fail release and acquire calls when FixedChannelPool is closed.

Result:

No more assert errors.1

### CODE REVIEW

**Comment by normanmaurer** [comment]
@nmittler @Scottmitch PTAL

**Comment by nmittler** [comment]
LGTM

**Comment by fratboy** [comment]
LGTM

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (082e9cc722cc77b9bbc9e020c04f29db48221dcb), 4.1 (8687475eb77e794ed56e8285aa0dc982d93a1048) and master (313c6315ef2c1c27358f9242eda2d8c51a6fb544)

**Pull request closed without merging**
