### PR TITLE
Reduce object allocation during wrap/unwrap while handshake is in progre...

### PR DESCRIPTION
**Pull request by normanmaurer**
...ss

Motivation:

Unnecessary object allocation is currently done during wrap/unwrap while a handshake is still in progress.

Modifications:

Use static instances when possible.

Result:

Less object creations.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@trustin @Scottmitch please review

**Comment by Scottmitch** [comment]
LGTM

**Comment by trustin** [comment]
LGTM

**Comment by normanmaurer** [comment]
Thanks..

Cherry-picked into 4.0 (d376bf6a58e3e4f0b6a6b5d90b5c88d16c0bf524) , 4.1 (bdfdf3094db00c7bfd610a3fb3e34ecae8e95aba) and master (b63fe25)

**Pull request closed without merging**
