### PR TITLE
HttpObjectEncoder Improvements

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
HttpObjectEncoder has a few areas which can be improved:
- HttpObjectEncoder currently inherits from MessageToMessageEncoder but an extra layer of queueing can be removed if it inherits directly from TypeSensitiveMessageEncoder
- HttpObjectEncoder has a few small (2 or 5 bytes) statically defined ByteBuf objects. To use these requires duplication which incurs upwards of 30 bytes of allocation to maintain the duplicate object. Now that we have a PooledAllocator we can just rely on it to pool these small buffers and reduce overall allocation assuming the pool is effectively configured and utilized.

Modifications:
- Make the above improvements

Result:
HttpObjectEncoder has less queuing and less overhead to allocate small ByteBufs

### CODE REVIEW

**Comment by Scottmitch** [comment]
@trustin @normanmaurer - PTAL (just the second commit ... this PR is dependent on https://github.com/netty/netty/pull/5187)

This is a slight API change ... but not changing methods that users are expected to interact with ... let me run some benchmarks are report results

**Comment by normanmaurer** [comment]
@Scottmitch any benchmark results yet ?

**Comment by Scottmitch** [comment]
microbench for this is in https://github.com/netty/netty/pull/5213 ... need to run it somewhere that isn't a VM :) I also suspect that over time this will have GC implications as we allocate less promise objects.

**Comment by normanmaurer** [comment]
Let us close this one for now and re-visit for next major version

**Pull request closed without merging**
