### PR TITLE
Updating "Branches to look" section to match the current branching structure of the project

### PR DESCRIPTION
**Pull request by mm-binary**
Updating "Branches to look" section to match the current branching structure of the project.

### CODE REVIEW

**Comment by trustin** [comment]
Thanks! Could you update the commit message so that it contains 'why' of the change? I know why, but just for record.

**Comment by mm-binary** [comment]
Done.

**Comment by normanmaurer** [comment]
@mm-binary @trustin asked to update the comment message a.k.a `git commit --amend`

**Comment by mm-binary** [comment]
A New PR is created for this: https://github.com/netty/netty/pull/4961

**Pull request closed without merging**
