### PR TITLE
Simplify SingleThreadEventExecutor.awaitTermination() implementation

### PR DESCRIPTION
**Pull request by njhill**
Motivation

A `Semaphore` is currently dedicated to this purpose but a simple wait/notify will do.

Modification

Remove private `threadLock` Semaphore from `SingleThreadEventExecutor` and instead use the existing private `shutdownHooks` Set object as a monitor.

Also eliminate use of `PlatformDependent.throwException()` in `startThread` method, and combine some nested if clauses.

Result

Cleaner `EventLoop` termination notification and slightly smaller object footprint.

### CODE REVIEW

**Comment by njhill** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by ejona86** [comment]
I'm not convinced this is cleaner. It seems a wash at best. If it's not been shown to cause trouble, I'd just assume leave it as-is.

I'm in favor of the removal of PlatformDependent.throwException, but that seems unrelated to the core of the change. (I'd honestly be happy if we removed most references to it and replaced them with something like [Throwables.throwIfUnchecked](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/Throwables.html#throwIfUnchecked-java.lang.Throwable-); there's a lot of options for bikeshedding, but not the "I'll happily throw checked exceptions")

**Comment by ejona86** [comment]
To be clear: my position is this seems like something that is personal preference. (And while I may even prefer your approach, the current approach isn't bad and has its own advantages.)

**Comment by njhill** [comment]
@ejona86 fair enough, for the reasons you stated I also don't feel too strongly about this. It was mainly that `Semaphore` seemed like the wrong fit. If not using a primitive monitor I'd suggest at least changing it to a `CountDownLatch`.

And you are right I snuck in a couple of minor unrelated simplifications, just cleanup I noticed while going along, equally happy to leave that out or put it in separate PR...

**Comment by njhill** [comment]
@normanmaurer WDYT? Options include:
- Change to `CountDownLatch`
- Keep PR as-is
- Abandon it

I'm fine with any of them...

**Comment by normanmaurer** [comment]
I am fine to keep the PR as it is or abandon it... At the end it does not matter too much IMHO.

**Comment by njhill** [comment]
@normanmaurer @ejona86 I changed it to a `CountDownLatch` which is a better fit here imho. Still includes the change to avoid use of PlatformDependent.throwException.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@njhill thanks a lot!

**Pull request merged**
