### PR TITLE
Fix buffer leaks in the transport module

### PR DESCRIPTION
**Pull request by violetagg**
Motivation:
Manually enabling leak detection for `transport` module, reveals buffer leaks in tests.

Modification:
- Fix leaks in tests

Result:
No more leaks in `transport` module.

### CODE REVIEW

**Review by chrisvest — APPROVED** [review]

**Comment by violetagg** [comment]
`WebSocketHandshakeHandOverTest.testClientHandshakerForceClose:269 expected: <false> but was: <true>` is failing on the CI, but I don't think this change can cause the failure.

**Comment by chrisvest** [comment]
@violetagg yeah, I've seen that one fail in many PRs… can't get it to fail locally, though. In theory it should be a single-threaded test, so I'm guessing it's a test isolation failure.

**Comment by chrisvest** [comment]
Thanks!

**Comment by violetagg** [comment]
@chrisvest Thanks

**Pull request merged**
