### PR TITLE
Add a test case to check sub strings' AsciiString hash code

### PR DESCRIPTION
**Pull request by luyiisme**
Motivation:

AsciiString.hashCode(o) , if "o" is a subString, the hash code is not always same, when netty’s version is 4.1.1.Final and jdk’s version is 1.6.

Modifications:

Use a test to assert hash codes are equal between a new string and any sub string (a part of  a char array),If their values are equal.

Result:

Create a test method to AsciiStringCharacterTest.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@luyiisme can you please sign our ICLA and let me know once done:

http://netty.io/s/icla

**Comment by luyiisme** [comment]
ok,@normanmaurer  I signed it.

**Comment by normanmaurer** [comment]
Cherry-picked as be3e6972a18e9a673ef54a63cd2fb16b20ee936e into 4.1

@luyiisme thanks!

**Comment by Scottmitch** [comment]
thanks @luyiisme !

**Pull request closed without merging**
