### PR TITLE
Speedup AbstractCoalescingBufferQueue::remove

### PR DESCRIPTION
**Pull request by franz1981**
Motivation:

AbstractCoalescingBufferQueue::remove is performing slow-path type check against ByteBuf's to check if it's of type ChannelFutureListener

Modifications:

Performing concrete type checks to speedup performing the right decision on which type the element belong

Result:

Fixes one of the cases at #13745

### CODE REVIEW

**Comment by franz1981** [comment]
This is fixing this case 
```
--------------------------
8:      io.netty.buffer.UnpooledSlicedByteBuf
Count:  40123310
Types:
        io.netty.channel.ChannelFutureListener
Traces:
        io.netty.channel.AbstractCoalescingBufferQueue.remove(AbstractCoalescingBufferQueue.java:157)
                class: io.netty.channel.ChannelFutureListener
                count: 40123310
--------------------------
```
but it introduces 2 changes:
- the number of casts is now increased (but `ChannelFutureListener` type check shouldn't really happen, for real, anymore)
- we don't die anymore due to `ClassCastException` if the queue's element isn't `ChannelFutureListener` or `ByteBuf`

**Comment by franz1981** [comment]
@normanmaurer this is one of the cases which should work fine with https://github.com/netty/netty/issues/13745#issuecomment-1866031400, but it requires JDK 22.
The impact now is visible in some profiling data

eg

image

the violet part is the remove, which in theory should be super cheap, but its cost is due to:
- the mentioned slow path type check
- the synchronized block at https://github.com/netty/netty/blob/ba804498ac1baf4da91275326eeba45552ab6ebf/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java#L181 (it's running against JDK 21 which doesn't have biased locking anymore...)

**Comment by franz1981** [comment]
As said earlier, this change is mostly a low hanging fruit which speedup an already cheap but visible operation, so feel free to reject if the change make the code too much complex if compared to what it is now.

**Review by chrisvest — APPROVED** [review]

**Comment by chrisvest** [comment]
I wonder if we can make the listener/wait/notify thing more efficient, with biased locking gone. I made an attempt a few years ago with #11799, but that was rather complicated and did not address the `addListener0` locking.

**Review by normanmaurer — APPROVED** [review]

**Comment by franz1981** [comment]
@normanmaurer FYI

I've run some profiling sessions to see how much this have impacted, and the saving in term of CPU cycles is interesting

before:
image

this this pr:
image

the `io/netty/channel/CoalescingBufferQueue.remove` part has moved from 191 samples to 85 samples, which is a 2X speedup, which in the global picture looks like...from this:
image

to this:
image

That's reducing the global cost of it from ~5% to ~2%; it's not a huge win, but is a free lunch, still

**Pull request merged**
