### PR TITLE
fix issue #11963.

### PR DESCRIPTION
**Pull request by wanglunhui2012**
Motivation:

I see the issue #11963 , but the solution might cause some problem, so push this pr.

Result:

the issue #11963 can use the method : `ByteBufUtil#indexOf(ByteBuf, ByteBuf, int, int, int, int)} `.

### CODE REVIEW

**Comment by chrisvest** [comment]
> I see the issue #11963 , but the solution might cause some problem

What problem is this solving?

**Comment by shichaoyuan** [comment]
this pr will create even more confusion

**Comment by wanglunhui2012** [comment]
> > I see the issue #11963 , but the solution might cause some problem
> 
> What problem is this solving?

**Comment by wanglunhui2012** [comment]
> > I see the issue #11963 , but the solution might cause some problem
> 
> What problem is this solving?

```java
ByteBuf haystack = Unpooled.copiedBuffer("abcdefgh", CharsetUtil.UTF_8);
ByteBuf needle = Unpooled.copiedBuffer("fgh", CharsetUtil.UTF_8);
/**
 *          +-------------------------------------------------+
 *          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
 * +--------+-------------------------------------------------+----------------+
 * |00000000| 61 62 63 64 65 66 67 68                         |abcdefgh        |
 * +--------+-------------------------------------------------+----------------+
 *          +-------------------------------------------------+
 *          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
 * +--------+-------------------------------------------------+----------------+
 * |00000000| 66 67 68                                        |fgh             |
 * +--------+-------------------------------------------------+----------------+
 */
System.out.println(ByteBufUtil.prettyHexDump(haystack));
System.out.println(ByteBufUtil.prettyHexDump(needle));
System.out.println(ByteBufUtil.indexOf(needle,haystack)); // 5
haystack.readByte();
/**
 *          +-------------------------------------------------+
 *          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
 * +--------+-------------------------------------------------+----------------+
 * |00000000| 62 63 64 65 66 67 68                            |bcdefgh         |
 * +--------+-------------------------------------------------+----------------+
 *          +-------------------------------------------------+
 *          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
 * +--------+-------------------------------------------------+----------------+
 * |00000000| 66 67 68                                        |fgh             |
 * +--------+-------------------------------------------------+----------------+
 */
System.out.println(ByteBufUtil.prettyHexDump(haystack));
System.out.println(ByteBufUtil.prettyHexDump(needle));
System.out.println(ByteBufUtil.indexOf(needle,haystack)); // 5
needle.readByte();
/**
 *          +-------------------------------------------------+
 *          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
 * +--------+-------------------------------------------------+----------------+
 * |00000000| 62 63 64 65 66 67 68                            |bcdefgh         |
 * +--------+-------------------------------------------------+----------------+
 *          +-------------------------------------------------+
 *          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
 * +--------+-------------------------------------------------+----------------+
 * |00000000| 67 68                                           |gh              |
 * +--------+-------------------------------------------------+----------------+
 */
System.out.println(ByteBufUtil.prettyHexDump(haystack));
System.out.println(ByteBufUtil.prettyHexDump(needle));
System.out.println(ByteBufUtil.indexOf(needle,haystack)); // 6
```
the pr #11970 should be cancel , every read method can make readerIndex increament.

**Comment by wanglunhui2012** [comment]
> this pr will create even more confusion

But the pr #11970 may not work well.

**Comment by chrisvest** [comment]
@wanglunhui2012 The `indexOf` method is matching the _readable_ regions of the buffers. When you call `needle.readByte()` in your example, the readable part of the needle changes from `fgh` to `gh`, and the absolute start index of the matching part of the haystack likewise moves forward by one byte. So it is working as intended.

**Comment by wanglunhui2012** [comment]
> @wanglunhui2012 The `indexOf` method is matching the _readable_ regions of the buffers. When you call `needle.readByte()` in your example, the readable part of the needle changes from `fgh` to `gh`, and the absolute start index of the matching part of the haystack likewise moves forward by one byte. So it is working as intended.

yes,when you call `readByte()` method,the readable regions will be changed,if call `ByteBuf#discardReadBytes()`,the result will be changed.

**Comment by chrisvest** [comment]
> yes,when you call readByte() method,the readable regions will be changed,if call ByteBuf#discardReadBytes(),the result will be changed.

Yeah, that's how it works with indexOf. An API that worked in terms of just the readable region would be called `bytesBefore`. We have one for individual byte matching, but not for string/buffer matching.

**Pull request closed without merging**
