### PR TITLE
SSL: Only try to use TLSv1.3 if a compatible ciphersuite is configured

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We should not try to use TLSv1.3 if only TLSv1.2 ciphers are configured

Modifications:

- Don't use TLSv1.3 if the ciphers that are configured are not for TLSv1.3
- Add unit tests

Result:

Fixes https://github.com/netty/netty/issues/13810

### CODE REVIEW

**Comment by normanmaurer** [comment]
@yawkat PTAL

**Review by yawkat — APPROVED** [review]
thanks!

**Comment by chrisvest** [comment]
Tests are complaining:

```
2024-02-21T15:47:02.2257456Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2259506Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2262173Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2264214Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2266159Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2270258Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2272731Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2274806Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2276699Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2278608Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2280526Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2282379Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2284788Z [ERROR]   ConscryptSslEngineTest>SSLEngineTest.testTLSv13DisabledIfNoValidCipherSuiteConfigured:4478 expected: <TLSv1.2> but was: <TLSv1.3>
2024-02-21T15:47:02.2286804Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2288671Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2290770Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2292691Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2294614Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2296556Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2298603Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2300518Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2302405Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2304337Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2306205Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2308133Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
2024-02-21T15:47:02.2310153Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2312468Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2314474Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2316606Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2318666Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2320759Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2322830Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2325056Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2327429Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2329527Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2331576Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2334028Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2335887Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2337961Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2339744Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2341432Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2343262Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2344936Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2346623Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2348325Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2350137Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2351758Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2353324Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2355052Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2357593Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2360414Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2362734Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2364612Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2366489Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2368517Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2370417Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2372287Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2374144Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2375947Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2377890Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2379659Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2382053Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2384013Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2385963Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2387930Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2389827Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2391718Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2393773Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2395777Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2397720Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2399651Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2401739Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
2024-02-21T15:47:02.2403661Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
```

**Comment by normanmaurer** [comment]
> Tests are complaining:
> 
> ```
> 2024-02-21T15:47:02.2257456Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2259506Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2262173Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2264214Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2266159Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2270258Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2272731Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2274806Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2276699Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2278608Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2280526Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2282379Z [ERROR]   ConscryptOpenSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2284788Z [ERROR]   ConscryptSslEngineTest>SSLEngineTest.testTLSv13DisabledIfNoValidCipherSuiteConfigured:4478 expected: <TLSv1.2> but was: <TLSv1.3>
> 2024-02-21T15:47:02.2286804Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2288671Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2290770Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2292691Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2294614Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2296556Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2298603Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2300518Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2302405Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2304337Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2306205Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2308133Z [ERROR]   JdkOpenSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4353 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2310153Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2312468Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2314474Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2316606Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2318666Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2320759Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2322830Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2325056Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2327429Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2329527Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2331576Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2334028Z [ERROR]   OpenSslConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2335887Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2337961Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2339744Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2341432Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2343262Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2344936Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2346623Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2348325Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2350137Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2351758Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2353324Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2355052Z [ERROR]   OpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2357593Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2360414Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2362734Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2364612Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2366489Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2368517Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2370417Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2372287Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2374144Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2375947Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2377890Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2379659Z [ERROR]   OpenSslJdkSslEngineInteroptTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2382053Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2384013Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2385963Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2387930Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2389827Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2391718Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2393773Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2395777Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2397720Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2399651Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2401739Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> 2024-02-21T15:47:02.2403661Z [ERROR]   ReferenceCountedOpenSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:4351 expected: <true> but was: <false>
> ```

doh! Will investigate

**Comment by normanmaurer** [comment]
@chrisvest PTAL ... should be fixed now

**Review by chrisvest — APPROVED** [review]

**Comment by yawkat** [comment]
Thanks!

**Pull request merged**
