### PR TITLE
[#4936] NetUtil can prevent using Netty due to SecurityManager denial

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

A custom SecurityManager may prevent calling File.exists() and so throw a SecurityException in the static init block of NetUtil.

Modifications:

Correctly catch the exception and so allow to static init NetUtil.

Result:

Allow static init method of NetUtil to work even with custom SecurityManager.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@ejona86 @trustin @nmittler PTAL

**Comment by ejona86** [comment]
LGTM

**Comment by trustin** [comment]
LGTM

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (97df3cb03939eabe30c3cc091eddbe4cb9be2fda) and 4.0 (559e77c12af64a7cce5b9e66934a889671f46746)

**Pull request closed without merging**
