### PR TITLE
[#3798] Extract dump method to ByteBufUtil

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

Dumping the content of a ByteBuf in a hex format is very useful.

Modifications:

Move code into ByteBufUtil so its easy to reuse.

Result:

Easy to reuse dumping code.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@trustin please check... Basically this is just a backport of code in 4.1 and master now with some small adjustments to keep backward compatibility in terms of api in LoggingHandler :)

**Comment by normanmaurer** [comment]
@trustin can we merge this ?

**Comment by trustin** [comment]
Sure! LTGM :-)

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 as 9a30b6860f21c9c66ba65ae7edd0635785d15242

**Pull request closed without merging**
