### PR TITLE
Change the netty.io homepage scheme(http -> https)

### PR DESCRIPTION
**Pull request by jingene**
### Motivation:
* Netty homepage(```netty.io```) serves both "http" and "https".
* It's recommended to use https than http.

### Modification:
* I changed from "http://netty.io" to "https://netty.io"

### Result:
* No effects.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@jingene please fix the check style error: 

```
15:08:32 [ERROR] /code/transport-native-epoll/src/main/java/io/netty/channel/epoll/Epoll.java:22: Line is longer than 120 characters (found 121). [LineLength]
15:08:32 Audit done.
```

**Comment by jingene** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@jingene thanks a lot!

**Pull request merged**
