### PR TITLE
remove unused shutdownLock

### PR DESCRIPTION
**Pull request by subbarao**
Motivation:

This is unused variable

Modification:

removed variable

Result:

Removes unused lock

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@subbarao can you please sign our ICLA: https://netty.io/s/icla ?

**Comment by subbarao** [comment]
@normanmaurer signed

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
Thanks a lot...

**Pull request merged**
