### PR TITLE
Make AbstractChannelPoolMap support concurrent access.

### PR DESCRIPTION
**Pull request by ZDMaxCoder**
Motivation:

When multiple threads use the same key to access the get method in AbstractChannelPoolMap at the same time, each thread calls the newPool method to create a new pool. 

Modification:

Use ReentrantLock to lock before creating a new ChannlPool. 

Result:

AbstractChannelPoolMap support multiple threads use the same key to access the get method at the same time.

### CODE REVIEW

**Comment by qeesung** [comment]
`ConcurrentMap` has been used to avoid concurrency issues. What is your consideration for locking here?

**Comment by ZDMaxCoder** [comment]
> 
> 
> `ConcurrentMap` has been used to avoid concurrency issues. What is your consideration for locking here?

**Comment by ZDMaxCoder** [comment]
> 
> 
> `ConcurrentMap` has been used to avoid concurrency issues. What is your consideration for locking here?

 ConcurrentMap's get method can be accessed concurrently. When multiple threads holding the same key get the pool empty at the same time, they call newPool concurrently.

**Comment by qeesung** [comment]
Yes, `check-then-act` does cause multiple calls to the `newPool` method, but the `putIfAbsent` method of `ConcurrentMap` is used to avoid thread-safe issues. I think locking is a heavyweight operation relative to `newPool` method calls

**Comment by ZDMaxCoder** [comment]
> 
> 
> Yes, `check-then-act` does cause multiple calls to the `newPool` method, but the `putIfAbsent` method of `ConcurrentMap` is used to avoid thread-safe issues. I think locking is a heavyweight operation relative to `newPool` method calls

Yes, you're right. I'm sorry.Thank you.

**Pull request closed without merging**
