### PR TITLE
Remove Progressive*Promise / Progressive*Future

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

This special case implementation of Promise / Future requires the implementations responsible for completing the promise to have knowledge of this class to provide value. It also requires that the implementations are able to provide intermediate status while the work is being done. Even throughout the core of Netty it is not really supported most of the times and so just brings more complexity without real gain.

Let's remove it completely which is better then only support it sometimes.

Modifications:

Remove Progressive* API

Result:

Code cleanup.... Fixes https://github.com/netty/netty/issues/8519

### CODE REVIEW

**Comment by trustin** [comment]
Thanks for cleaning this up! I'm curious how we will notify our users for a large file transfer with `FileRegion` though. Any thought? Using a separate callback?

**Comment by normanmaurer** [comment]
@trustin I am not sure yet... I am even not sure about `FileRegion` in general and if it is really as useful as we may have thought these days (as most protocols use encryption under the hood and so FileRegion doesn't work at all).

**Comment by normanmaurer** [comment]
@trustin yep I think thats possible... That said I think we should think about `FileRegion` in general as it is just another special case that usually a lot of handlers not handle correctly :/

**Comment by hyperxpro** [comment]
@normanmaurer `FileRegion` is a great instrument to serve static files. These static files can be pre-compressed and might not need encryption because we can match the fingerprint of the downloaded files.

Just my feedback. Rest up to you guys. :-)

**Review by chrisvest — APPROVED** [review]

**Comment by chrisvest** [comment]
@hyperxpro Web site assets are usually small enough that you can hold them in buffers. `FileRegion` exists to call `sendfile(2)`, which will bypass the pipeline, and kind of go against the architecture in Netty. I wonder if the use case with bigger files would be better served by file-backed (`mmap(2)`) buffers.

**Comment by hyperxpro** [comment]
I am especially talking about static downloads, like some sort of file download server or movie download server.

**Comment by normanmaurer** [comment]
I think we should continue the discussion outside of this PR @hyperxpro @trustin @chrisvest

**Review by NiteshKant — APPROVED** [review]
✔️ 

progressive promise to me felt like a poor man's streaming callback 😄. 
I am also interested in @trustin 's question about `FileRegion` but I think progressive promise is heavy handed for that.

**Review by trustin — APPROVED** [review]

**Pull request merged**
