### PR TITLE
Fix causing the connection to hang without flushing data

### PR DESCRIPTION
**Pull request by wangzihaogithub**
Motivation:

Explain here the context, and why you're making that change.
What is the problem you're trying to solve.

Modification:

channel.flush() after a few channel.write() operations may get processed by the pipeline before the writes, causing the connection to hang without flushing data.

Result:

If the write fails, I let it continue to try again.  All the way up to writeSpinCount is zero.

before

`

                    int attemptedBytes = buffer.remaining();
                    final int localWrittenBytes = ch.write(buffer);
                    if (localWrittenBytes <= 0) {
                        incompleteWrite(true);
                        return;
                    }
                    adjustMaxBytesPerGatheringWrite(attemptedBytes, localWrittenBytes, maxBytesPerGatheringWrite);
                    in.removeBytes(localWrittenBytes);
                    --writeSpinCount;
`

after

`
                    

                    int attemptedBytes = buffer.remaining();
                    final int localWrittenBytes = ch.write(buffer);
                    if (localWrittenBytes <= 0) {
                        incompleteWrite(true);
                    }else {
                        adjustMaxBytesPerGatheringWrite(attemptedBytes, localWrittenBytes, maxBytesPerGatheringWrite);
                        in.removeBytes(localWrittenBytes);
                    }
                    --writeSpinCount;

`

Fixes #<10353>. 
fix https://github.com/netty/netty/issues/10353

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by normanmaurer** [comment]
I have a hard time to see how this could fix the issue . Can you explain why you think it will ?

**Comment by wangzihaogithub** [comment]
In the case of frequent writes,  
ch.write(buffer);  It's going to return 0. and buffer is not read.

but before the logic was this, 

`

            if (localWrittenBytes <= 0) {
                    incompleteWrite(true);
                    return;
                }
`

It simply returns, causing the buffer not to be read and written at all, and then there is no room to process the buffer again.

I think if the buffer is not read, I will retry it until writeSpinCount is zero

**Comment by wangzihaogithub** [comment]
Something like this

`

      while ((length = inputStream.read(buffer)) != -1) {
                out.write(buffer, 0, length);
                out.flush();
            }
            out.flush();

`

**Comment by normanmaurer** [comment]
That's incorrect ... if we fail to write the buffer we will retry as soon as the channel becomes writable again

**Comment by wangzihaogithub** [comment]
But there is no normal retry because there is no place to set OP_WRITE again

**Comment by wangzihaogithub** [comment]
isFlushPending method  Always returns

**Comment by wangzihaogithub** [comment]
The committed code has been changed, and retry to writeSpinCount to end

**Comment by wangzihaogithub** [comment]
please... Thank you

**Comment by wangzihaogithub** [comment]
My system in Window 10, My friend's MAC OS,  there's no event here

`


           if ((readyOps & SelectionKey.OP_WRITE) != 0) {
                // Call forceFlush which will also take care of clear the OP_WRITE once there is nothing left to write
                ch.unsafe().forceFlush();
            }

`

**Comment by wangzihaogithub** [comment]
Because I'm currently inEventLoop , I haven't been able to trigger OP_WRITE, I think. 

`


          if(inEventLoop){
              trigger processSelectKeys()
         }

`

How about this idea?

**Comment by normanmaurer** [comment]
@wangzihaogithub sorry but this change is not valid... OP_WRITE should be triggered by the OS as soon as the channel becomes writable again. Spinning will not fix anything.

**Comment by wangzihaogithub** [comment]
We found the problem,

My solution now is to modify the user code and use another business thread to execute the submit writetask or flushtask. This will not block processselectedkeys() and runalltasks() of the EventLoop

Because you are currently in the processselectedkeys() of the EventLoop in unsafe.read (), at this time, the write operation is executed in the Current IO thread. If the write is busy, the read method of the current thread has not been completed, so the next selectionkey (OP_ WRITE) cannot be triggered).

Tip: even if the operating system does not actively notify the Op_ Write, spin 2 ~ 3 times, write successfully.

**Comment by wangzihaogithub** [comment]
but , I'll try and find a better way

**Comment by hyperxpro** [comment]
Sorry, I don't understand the actual issue. Can you give us code to reproduce and explain the issue in more detail?

**Comment by normanmaurer** [comment]
I agree with @hyperxpro here... its not clear to me what exactly happens and why you think your solution will fix it.

**Comment by wangzihaogithub** [comment]
@hyperxpro @sprsquish 
hi.
I created a use case that you can run directly with replay。
Just look at UseCase1, Case2 and I'm not done yet.

https://github.com/wangzihaogithub/netty-issues-10353.git

**Comment by hyperxpro** [comment]
Your code is super complicated for no reason. :-|

**Comment by wangzihaogithub** [comment]
@hyperxpro 
I've simplified the code a little bit, please take a look at it again.

place open Browser. enter http://localhost:8080  . Will not complete 6GB data write to browser.

**Comment by hyperxpro** [comment]
Improved your code.

```java
package io.netty.channel.nio;

import io.netty.bootstrap.ServerBootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.channel.*;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.codec.http.*;
import io.netty.util.concurrent.DefaultThreadFactory;
import io.netty.util.internal.OutOfDirectMemoryError;
import io.netty.util.internal.logging.InternalLogger;
import io.netty.util.internal.logging.InternalLoggerFactory;
import org.junit.Assert;

import java.nio.channels.SelectionKey;

/**
 * channel.flush() after a few channel.write() operations may get processed by the pipeline before the writes,
 * causing the connection to hang without flushing data.
 *
 * case 1 ->
 *  if run at IO, is block. never trigger processSelectedKey() method. the event #OP_WRITE.
 *  causing the connection to hang without flushing data.
 *
 * https://github.com/netty/netty/issues/10353
 */
public class UseCase1 {
    private static final InternalLogger logger = InternalLoggerFactory.getInstance(UseCase1.class);

    public static void main(String[] args) {
        ServerBootstrap bootstrap = new ServerBootstrap();

        NioEventLoopGroup parentGroup = new NioEventLoopGroup(6);
        EventLoopGroup childGroup = new NioEventLoopGroup(6);
        bootstrap.group(parentGroup, childGroup)
                .channelFactory(NioServerSocketChannel::new)
                .childHandler(new ChannelInitializer() {
                    @Override
                    protected void initChannel(Channel ch) throws Exception {
                        ch.pipeline().addLast(new HttpServerCodec());
                        ch.pipeline().addLast(new Write6GBDataChannelHandler());
                    }
                });

        bootstrap.bind(8080).addListener(new ChannelFutureListener() {
            @Override
            public void operationComplete(ChannelFuture future) throws Exception {
                logger.info("place open Browser. enter http://localhost:8080  . Will not complete 6GB data");
            }
        });
    }

    private static class Write6GBDataChannelHandler extends SimpleChannelInboundHandler<HttpObject>{

        @Override
        protected void channelRead0(ChannelHandlerContext ctx, HttpObject msg) throws Exception {
            if(msg instanceof LastHttpContent) {
                long length = 5000000000L;

                HttpResponse httpResponse = new DefaultHttpResponse(HttpVersion.HTTP_1_1,HttpResponseStatus.OK);
                httpResponse.headers().set("content-length", length);
                httpResponse.headers().set("content-disposition", "attachment;");
                httpResponse.headers().set("content-type","application/octet-stream");
                ctx.writeAndFlush(httpResponse);

                for (int i = 1; i <= 5000000; i++) {
                    byte[] bytes = new byte[1000];
                    length -= bytes.length;

                    ByteBuf buffer = ctx.alloc().buffer();
                    buffer.writeBytes(bytes);
                    ctx.writeAndFlush(new DefaultHttpContent(buffer));

                    long start = System.nanoTime();
                    while(start + 10000 >= System.nanoTime());

                    if (i == 5000000) {
                        ctx.writeAndFlush(LastHttpContent.EMPTY_LAST_CONTENT);
                    }
                }
            }
        }

        @Override
        public void channelReadComplete(ChannelHandlerContext ctx) throws Exception {
            logger.info("channelReadComplete = {}",ctx.channel());
        }

        @Override
        public void channelWritabilityChanged(ChannelHandlerContext ctx) throws Exception {
            logger.info("channelWritabilityChanged = {}",ctx.channel());
        }
    }
}
```

**Comment by hyperxpro** [comment]
This patch looks valid. 

> Without this PR, the write operation stops, and memory increases.
> With this PR, even after writability changes, we can still write data.

I'm not sure if it's a bug or `channelWritabilityChanged` needs to be handled by us. @normanmaurer Help :)

**Comment by wangzihaogithub** [comment]
Because you are currently in a worker thread after a busy write, the next OP_WRITE event can never be triggered.
My patch tried not to be notified by the operating system, because if the current thread had to be released when the operating system notified it, the recovery was quick in most cases, requiring only a few spin retries.

**Comment by wangzihaogithub** [comment]
Although after testing, waiting for the operating system notification will get better performance, but it must require the user to release the current working thread.

I think this can give the user more choice. If the user wants to get better performance, he can release the current thread. If the user does not care, it will not affect the normal execution logic of the program

**Comment by normanmaurer** [comment]
@wangxiyuan honestly what you do here is just an user error.. I mean sure we can spin a bit but at the end the will not solve the real porblem which is that you basically "block" the EventLoop.

**Comment by normanmaurer** [comment]
So I am not convinced this patch does anything useful... It may even harm as it may delay the processing of other channels.

**Pull request closed without merging**
