### PR TITLE
Fix incorrect memory allocation intervals

### PR DESCRIPTION
**Pull request by brucelwl**
bug fix https://github.com/netty/netty/issues/9549

### CODE REVIEW

**Comment by normanmaurer** [comment]
Can you please add a testcase

**Comment by brucelwl** [comment]
@normanmaurer  please see https://github.com/brucelwl/demo/tree/netty_bug_demo

**Comment by normanmaurer** [comment]
Sure but still an isolated unit test should be added

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@brucelwl csn you please sign our ICLA:

https://netty.io/s/icla

**Comment by brucelwl** [comment]
> @brucelwl csn you please sign our ICLA:
> 
> https://netty.io/s/icla

ok, All right, it's done

**Comment by normanmaurer** [comment]
@brucelwl can you please rebase so it only contains one commit (which is your change )

**Comment by brucelwl** [comment]
> @brucelwl can you please rebase so it only contains one commit (which is your change )

@normanmaurer please see https://github.com/netty/netty/pull/9555

**Pull request closed without merging**
