### PR TITLE
Reference-counted SslEngines retain a reference to their parent SslContext

### PR DESCRIPTION
**Pull request by bryce-anderson**
Motivation:
With the Netty ref-counted OpenSSL implementation the parent SslContext
maintains state necessary for the SslEngine's it produces. However, it's
possible for the parent context to be closed and release those resources
before the child engines are finished which causes problems.

Modification:
Spawned ReferenceCountedOpenSslEngine's retain a reference to their
parent ReferenceCountedOpenSslContext.

Result:
The lifetime of the shared data is extended to include the lifetime of
the dependents.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
Ping. Any more feedback on this?

**Comment by rkapsi** [comment]
LGTM as well

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@bryce-anderson good one!

**Pull request merged**
