### PR TITLE
Remove the old headers implementation and APIs

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:

The HTTP/1 and HTTP/2 headers APIs and implementations no longer derive from the old APIs and implementations.
There is no reason for us to keep the old APIs around as we don't use them.

Modification:
Change `CharSequenceMap` to use the new `MultiMap`, because that was the last usage of `DefaultHeaders`.
Then remove everything related to the old `Headers` interface and its implementations.
The `MultiMap` is not suitable to be exposed as a public API, so no replacement is offered for what `Headers` did previously.

Result:
Cleaner code, less baggage.
Downstream projects are encourage to choose header implementations more suited for their use case.

### CODE REVIEW

**Comment by chrisvest** [comment]
Notifying @amizurov @violetagg @pderop @ejona86 in case this is impacting your stuff.

**Comment by ejona86** [comment]
The new header APIs are a lot cleaner and easier to manage. Sort of like the buffer stuff. This isn't much of a worry for me.

**Review by idelpivnitskiy — APPROVED** [review]
🎉

**Comment by amizurov** [comment]
@chrisvest Thanks, looks good, I'll try to book time to migrate STOMP to the new API.

**Pull request merged**
