### PR TITLE
Workaround for regex bug in Android SDK

### LINKED ISSUE #13515: SSL certificate parsing issue when upgrading beyond 4.1.78 on Android
### Expected behavior

We're running a gRPC server on Android. We use SSL and have certificates that work until version 4.1.79, and we'd like to be able to continue to use them on more recent versions. Looking for hints to debug why this would suddenly start failing.

### Actual behavior

Certificates fail to parse with:

```
org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0c0000a2:ASN.1 encoding routines:OPENSSL_internal:NOT_ENOUGH_DATA
```

### Steps to reproduce

Upgrade Netty.

### Minimal yet complete reproducer code (or URL to code)

Unfortunately this is a complex and proprietary project so it's difficult to provide a reproduction. The relevant interactions are between Netty and gRPC version 1.47.0 and conscrypt-android version 2.5.1, and the code is running on Android API 28.

If the short diff between 4.1.78 and 4.1.79 is not enough to find a good solution I can try to build a minimum reproducer. I've also tried to use Jitpack to build intermediate commits but I'm having trouble getting those to run on Android.

### Netty version

4.1.79

### JVM version (e.g. `java -version`)

Android API 28.

### OS version (e.g. `uname -a`)

Android 9.

### LINKED ISSUE #13625: In some cases when release a pool directBuffer, it locks on a different head subpage
I accidentally found this issue when doing another PR [13626](https://github.com/netty/netty/pull/13626).
### Expected behavior
When releasing a pool directBuffer, it should lock on the head subpage as same as the one when it allocated.
### Actual behavior
In some cases, it locks on a different head subpage when releasing.
### Minimal yet complete reproducer code (or URL to code)
Run the following test code within `io.netty.buffer`'s test package, the test will fail, because when releasing the `byteBuf`, it locks on a different head subpage.
```
    @Test
    public void testDirectSubpageReleaseLock() throws Exception {

        int initialCapacity = 0;
        int directMemoryCacheAlignment = 32;

        PooledByteBufAllocator allocator = new PooledByteBufAllocator(
                true,
                0,
                1,
                PooledByteBufAllocator.defaultPageSize(),
                PooledByteBufAllocator.defaultMaxOrder(),
                0,
                0,
                false,
                directMemoryCacheAlignment);

        final PooledByteBuf byteBuf = (PooledByteBuf)allocator.directBuffer(initialCapacity, 16);

        byteBuf.chunk.arena.smallSubpages();
        Field smallSubpagesField = Class.forName("io.netty.buffer.PoolArena").getDeclaredField("smallSubpagePools");
        smallSubpagesField.setAccessible(true);
        // get the smallSubpagePools[] array in arena.
        PoolSubpage<byte[]>[] smallSubpagePools = (PoolSubpage<byte[]>[])smallSubpagesField.get(byteBuf.chunk.arena);
        PoolSubpage head = null;
        for (PoolSubpage subpage : smallSubpagePools) {
            if (subpage.next != subpage) {
                // Find the head subpage which the byteBuf belongs to.
                head = subpage;
                break;
            }
        }
        // We intentionally lock the head subpage in main thread.
        head.lock(); 
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                // Because the head subpage was already locked in the main thread, so this should hang and wait.
                byteBuf.release();
            }
        });
        t1.setDaemon(true);
        t1.start();
        // wait max 3 seconds.
        t1.join(1000 * 3);
        if (!t1.isAlive()) {
            fail("The t1 thread should still alive and wait for the head lock.");
        }
    } 
```
The test will also fail when `int directMemoryCacheAlignment = 64;`. 
But if we changed it to `int directMemoryCacheAlignment = 16;`, then the test will pass.
### Netty version
4.1 branch
### JVM version (e.g. `java -version`)
JDK-17

### PR DESCRIPTION
**Pull request by fishb1**
Motivation:

If Netty is started from an Android app and certificate/private key are passed into the builder as input streams, an error occurs: org.conscrypt.OpenSSLX509CertificateFactory: org.conscrypt.OpenSSLX509CertificateFactory: java.lang.RuntimeException: error:0c0000a2:ASN.1 encoding routines:OPENSSL_internal:NOT_ENOUGH_DATA

Due to a bug in the regex implementation in Android SDK, the certificate is parsed from the input stream as BEGIN and further creating of the X.509 certificate fails.

See https://issuetracker.google.com/issues/293206296 

Modifications:

The end position of the latest match is saved into a variable and used as the start position for the next match as a workaround for the bug.

Result:

Fixes #13515

Netty starts on Android without an error.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@fishb1 I think the mentioned issue on the `Fixes` is incorrect.

**Comment by fishb1** [comment]
> @fishb1 I think the mentioned issue on the `Fixes` is incorrect.

Oops, sorry! Fixed.

**Comment by normanmaurer** [comment]
@fishb1 did you sign our icla yet ? https://netty.io/s/icla

**Comment by fishb1** [comment]
> @fishb1 did you sign our icla yet ? https://netty.io/s/icla

Yes, I did.

**Review by chrisvest — APPROVED** [review]

**Pull request merged**
