### PR TITLE
Some EpollEventLoop tasks might be pended for a long time

### PR DESCRIPTION
**Pull request by hyangtack**
Motivation:
If a task was submitted when wakenUp value was 1, the task didn't get a chance to produce wakeup event. So we need to check task queue again before calling epoll_wait. If we don't, the task might be pended until epoll_wait was timed out. It might be pended until idle timeout if IdleStateHandler existed in pipeline.

Modifications:
Execute epoll_wait in a non-blocking manner if there's a task submitted when wakenUp value was 1.

Result:
Every tasks in EpollEventLoop will not be pended.

### CODE REVIEW

**Comment by normanmaurer** [comment]
Looking

**Comment by normanmaurer** [comment]
@hyangtack good catch! Can you also do the same fix for NioEventLoop ?

**Comment by hyangtack** [comment]
@normanmaurer Ok. I will check it in the next week. :)

**Comment by normanmaurer** [comment]
Thx! Ahould be more or leess the same code change

**Comment by hyangtack** [comment]
@normanmaurer Actually I didn't find any problem under my test environment when I used nio instead of epoll. But I think this issue might be possible in `NioEventLoop`. Please take a look on 87a3319.

**Comment by normanmaurer** [comment]
@hyangtack thanks... I think the change for nio is not 100% correct. Please check my comment and ping me once fixed

**Comment by normanmaurer** [comment]
@hyangtack actually nevermind ... Your code is correct. Let me merge it

**Comment by hyangtack** [comment]
@normanmaurer Thank you for reviewing. :)

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 as (877767da00f7ab93d401b4df7351040eb0c36a8b) (f44f3e7926f1676315ae86d0f18bdd9b95681d9f) and 4.0 (013abb5c5874768bd327d41e2da85c188c9c7a11) (ee9d8c9162b92b508f9c6a9d6b118b200c4f01fc)

@hyangtack thanks again!

**Pull request closed without merging**
