### PR TITLE
version: remove Duplicating managed version

### PR DESCRIPTION
**Pull request by leeyazhou**
Motivation:

remove Duplicating managed version, cause it is already defined in the parent project.

Modification:

- origin 
```
<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-dev-tools</artifactId>
      <scope>test</scope>
      <version>${project.version}</version>
      <optional>true</optional>
</dependency>

<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>1.10</version>
</plugin>
```

- after modify

```
<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-dev-tools</artifactId>
      <scope>test</scope>
      <optional>true</optional>
</dependency>

<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
</plugin>
```

Result:

remove Duplicating managed version

### CODE REVIEW

**Comment by leeyazhou** [comment]
yeah, do it please.

> Can one of the admins verify this patch?

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@leeyazhou can you please sign our ICLA and let me know once done:

https://netty.io/s/icla

**Comment by normanmaurer** [comment]
@leeyazhou ping ...

**Comment by leeyazhou** [comment]
OK. I sign it just now.

**Comment by leeyazhou** [comment]
@normanmaurer  I have sign it just now.

**Comment by normanmaurer** [comment]
@leeyazhou thanks a lot!

**Pull request merged**
