### PR TITLE
Documentation update to MessageSizeEstimator.java

### LINKED ISSUE #9031: Typo Documentation - MessageSizeEstimator.class
https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/transport/src/main/java/io/netty/channel/MessageSizeEstimator.java#L19

"Responsible to estimate size of a message. The size represent how much memory the message will ca. reserve in memory."

I was going through the source and trying to determine where MessageSizeEstimator.class is used and what "ca" in the documentation means. I will make the pull request once I know what "ca" means, if it needs to be corrected.

### PR DESCRIPTION
**Pull request by Mr00Anderson**
Motivation:

Did not understand the context of "ca".

Modification:

Clarified "CA" to "approximately".

Result:

Fixes #9031

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@Mr00Anderson please fix the check style error:

```
12:01:02 [ERROR] /code/transport/src/main/java/io/netty/channel/MessageSizeEstimator.java:19: Line is longer than 120 characters (found 127). [LineLength]
12:01:02 Audit done.
```

**Comment by Mr00Anderson** [comment]
That is what i get for using the web editor.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Pull request merged**
