### PR TITLE
fix recycler npe bug

### PR DESCRIPTION
**Pull request by zhaojigang**
Fix https://github.com/netty/netty/issues/8220.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@zhaojigang Can you add a test case please ?

**Comment by zhaojigang** [comment]
ok, I will new a newPullRequest

**Comment by zhaojigang** [comment]
I add a newPullRequest : https://github.com/netty/netty/pull/8222

**Comment by zhaojigang** [comment]
hi, @normanmaurer ,
I add a newPullRequest:https://github.com/netty/netty/pull/8224 but I dont known why have some error

**Pull request closed without merging**
