### PR TITLE
Make PrimitiveCollections generated for all primitive maps.

### LINKED ISSUE #4001: PrimitiveCollections should apply for all "scripted" types
Currently the PrimitiveCollections class has an implementation of `EmptyMap` and `UnmodifiableMap` only for the `int` variant of the primitive map.  These objects should be templatized like the other primitive map types.

### PR DESCRIPTION
**Pull request by nmittler**
Motivation:

We should support XXXCollections methods for all primitive map types.

Modifications:

Removed PrimitiveCollections and added a template for XXXCollections.

Result:

Fixes #4001

### CODE REVIEW

**Comment by nmittler** [comment]
@Scottmitch PTAL.  This is actually based on #3984 ... I'll rebase after that's in.

**Comment by nmittler** [comment]
@Scottmitch PTAL ... I've rebased these changes after the commit of the primitive map changes.

**Comment by Scottmitch** [comment]
@nmittler - LGTM! Sorry for the delay (been busy looking at headers)!

**Comment by nmittler** [comment]
@Scottmitch np, thanks for reviewing!

Cherry-picked into master (348082c) and 4.1 (296649c)

**Pull request closed without merging**
