### PR TITLE
Return ChannelOutboundInvoker for methods that take Promise

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We should better return ChannelOutboundInvoker for methods that take Promise to make it more clear how notications for completed operations work.

Modifications:

- Change API
- Adjust usage for new API

Result:

More clear API

### CODE REVIEW

**Comment by normanmaurer** [comment]
This is based on https://github.com/netty/netty/pull/11575

**Comment by ejona86** [comment]
Seems this would encourage "addListener to promise before calling operation":

```java
// This just looks too pretty
ctx.write(obj, promise.addListener(MY_LISTENER));
// vs
ctx.write(obj, promise);
promise.addListener();
```

There was other discussion in #11575 like splitting Promise and Future and that seems to be the opposite of the approach taken here.

I'd much rather just add a `@returns {@code promise}` to the API. That seems about as clear, as we know Netty returns "convenient" objects in much of its API, and in this case it is actually slightly functional as well as it purposefully throws away some type information.

**Comment by normanmaurer** [comment]
> Seems this would encourage "addListener to promise before calling operation":
> 
> 
> 
> ```java
> 
> // This just looks too pretty
> 
> ctx.write(obj, promise.addListener(MY_LISTENER));
> 
> // vs
> 
> ctx.write(obj, promise);
> 
> promise.addListener();
> 
> ```
> 
> 
> 
> There was other discussion in #11575 like splitting Promise and Future and that seems to be the opposite of the approach taken here.
> 
> 
> 
> I'd much rather just add a `@returns {@code promise}` to the API. That seems about as clear, as we know Netty returns "convenient" objects in much of its API, and in this case it is actually slightly functional as well as it purposefully throws away some type information.

This is just a first step and yes I agree we should do something like not allow adding listeners to a Promise . That's also why this is marked as a draft for now as I wanted to do things in small steps so it is easy to follow the progress

**Comment by ejona86** [comment]
> This is just a first step

I don't need to see code for all the other steps, but without a rough idea this seems like a step backward. Was this based on a discussion on another PR? I accept that sometimes you have to step backward to go forward on a better path, but what is the other path here?

**Comment by normanmaurer** [comment]
Alright... After more thinking I think we should just not do this but pull in https://github.com/netty/netty/pull/11346

**Pull request closed without merging**
