### PR TITLE
Javadoc improvements

### PR DESCRIPTION
**Pull request by tbcs**

### CODE REVIEW

**Comment by normanmaurer** [comment]
@tbcs why did you remove the `{@link ...} ` tags ?

**Comment by tbcs** [comment]
@normanmaurer The javadoc is full of links, to an extent that I find it hard to read.  I think it is sufficient to link to a particular thing once in a section, that's why I removed _repeated_ links to the same thing within the same section.

**Comment by trustin** [comment]
Your IDE / Javadoc tool should let you read them easily?

**Comment by tbcs** [comment]
I agree that linking is useful, I just think that it is a bit excessive in some places.  Another example is the javadoc of [ByteToMessageDecoder](http://netty.io/4.1/api/io/netty/handler/codec/ByteToMessageDecoder.html), which links to `ByteBuf` three times in the same paragraph and also features three links _to itself_.  Feel free to just reject this PR if you don't agree with my view, I'm sure you'd rather be working on important things for the upcoming 4.1 release then dealing with such trivialities.

**Comment by trustin** [comment]
Excessive use of `{@link }` tags was justified because it made renaming of classes very easy in the early phase of development; IDE will know it's a class name obviously.

I'm not sure if it still makes sense to do so like 3 times in a paragraph given that our API is now very stable.

One thing to consider is 'consistency' - if we wanna change this we gotta make the same change in every single Javadoc, which will require heroic (!) effort. Are you up for this? :-)

**Comment by tbcs** [comment]
@trustin Indeed, using links makes it much easier to keep the docs in sync with the code, I didn't consider this perspective.  I can also understand your concern about consistency.  I'd rather not make any promises about updating all of Netty's javadoc, so I dropped the changes related to linking.

Let me know if I should squash the commits and update the branch linked to this PR via a forced push (or create a new PR instead).

**Comment by normanmaurer** [comment]
@tbcs yep please squash and again use our commit message template :) I will cherry-pick then :)

**Comment by tbcs** [comment]
@normanmaurer I squashed and pushed, but the commit message template looks a bit of an overkill for this trivial change.  Let me know if it's truly necessary, then I will try to rephrase the commit message.

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (6e840d8e62e98590e129ab6f21e2deba46bfcacf) and 4.0 (4784f2761a1e18c24bbf6bdf3b901873aa598c68).

@tbcs thanks!

**Comment by trustin** [comment]
@tbcs Thanks for understanding and I appreciate your effort for making better docs. Please keep up the great work! :+1:

**Pull request closed without merging**
