### PR TITLE
Store reference to IovArray in the EpollEventLoop to reduce thread lo…

### PR DESCRIPTION
**Pull request by normanmaurer**
…cal access.

Motivation:

If we have a lot of writes going on we currently need to lookup the IovArray for each Channel that does writes. This can have quite some perf overhead. We should not need to do this and just store a reference of the IovArray on the EpollEventLoop itself.

Modifications:

- Remove IoArrayThreadLocal
- Store the IoArray in the EventLoop itself

Result:

Less FastThreadLocal lookups

### CODE REVIEW

**Comment by normanmaurer** [comment]
@nmittler @Scottmitch @trustin PTAL

**Comment by trustin** [comment]
LGTM

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (63c2ad4b7d99753de06d2e2ff9943615cd9ff6ec), 4.1 (edb2250d355134d1c24c577d921add01b34cbd5f), master (ba19837f2f81571525b8ab68e00365a76da83a6a)

**Comment by ninja-** [comment]
@normanmaurer ok so you admit not liking the ThreadLocals everywhere :grinning: how about revisiting the rest of my ThreadLocal purge PR?

**Pull request closed without merging**
