### PR TITLE
IOUringCompletionQueue::process can be more cache-friendly

### PR DESCRIPTION
**Pull request by franz1981**
Motivation:

- some CQE fields addresses can be pre-computed
- IOUringCompletionQueue::process can save repeatedly loading local fields

Modifications:

Ensure that IOUringCompletionQueue::process save using shared resources
to make progress as much as possible (see Motivation)

Result:

More cache-friendly processing and better performance

### CODE REVIEW

**Comment by franz1981** [comment]
Given that `IOUringCompletionQueue` is a wrapper around direct memory it could be possible to create a micro bench that isn't using any kernel support to just evaluate the performance of different approaches, so I can create one if we really need it.
In other projects (ie JCTools), using a cache tail field (on producers or consumers, depending on the context) has proved to beneficial with burst of offers, to save some cache coherency traffic to happen (ping-pong of shared fields like our ring `tail`, that a consumer doesn't need to be up to date value to make process), especially for Lamport-like ring buffers like this (see @nitsanw http://psy-lob-saw.blogspot.com/2013/09/diving-deeper-into-cache-coherency.html on the subject).

`IOUringSubmissionQueue::enqueueSqe` seems to not need something like this because it's already batching submissions in a way that the kernel and Java code doesn't have a shared resource in the hot path (when `Native.ioUringEnter` isn't called).

**Comment by franz1981** [comment]
Let me think better about this: I see that probably the caching isn't needed here given that we were performing the `tail` read just once, so we could just save loading local fields instead to benefit the hot-path case (ie when there's some value in)

**Comment by franz1981** [comment]
There are few things that need to be fixed/discussed here:

1. `available` computation given unsigned nature of `head` and `tail`
2. batch `PlatformDependent.putIntOrdered(kHeadAddress, head);` it's worth it? 

The reason behind the `available` computation is to turn the original un-counted loop into a counted one (which the JVM can predict for-I-don't-know-whatever-reason that won't last long), while the other choices are being explained as comments in the PR code.

**Comment by franz1981** [comment]
And I've a small question for anyone that knows about it...

On the original libaio kernel code (ages before io_uring) the completion queue what using tail/head but it was `%` with the (not power of 2) ring capacity: I don't see such adjustment on io_uring, hence head/tail just seems monotonic increasing until 2^32-1...that's way less then the max Java `long` value (what I'm used to choose for sequence data types)...it's correct?

**Comment by chrisvest** [comment]
> Another note about available: the math should work fine as long as the distance between head and tail is within Integer.MAX_VALUE and I assume that's always true, if not, I can think to some way to improve that.

If the kernel does not already prevent that, we can place an assertion that the submission queue is never greater than some value less than half of `Integer.MAX_VALUE`, and also that `IORING_SETUP_CQSIZE` is either not used, or the requested size is small enough.

> On the original libaio kernel code (ages before io_uring) the completion queue was using tail/head but it was adjusting them using % with the (not power of 2) ring capacity: I don't see such adjustment on io_uring, hence head/tail just seems monotonic increasing until 2^32-1...that's way less then the max Java long value (what I'm used to choose for sequence data types)...it's correct?

We're given masks (`io_sqring_offsets.ring_mask` and `io_cqring_offsets.ring_mask`) to use for indexing into the queues. So I think it's correct that the head and tail will grow until they wrap around and start over.

**Comment by franz1981** [comment]
Thanks @chrisvest for the answers!

> We're given masks (io_sqring_offsets.ring_mask and io_cqring_offsets.ring_mask) to use for indexing into the queues. So I think it's correct that the head and tail will grow until they wrap around and start over.

Probably I'm just too used to the way I've seen ring queues implemented on JCTools: I understand the choice of `unsigned` to easily support 32-bit machines, but it means that `head/tail` sequences cannot be used to anything different then indexing the ring items and size computation, while there are few cases where being able to sample the same sequence allow to average the ingress/egress throughput is rather useful, but that's a personal opinion

**Comment by 1Jo1** [comment]
> There are few things that need to be fixed/discussed here:
> 
>     1. using a counted loop really worth it?
>     2. batch `PlatformDependent.putIntOrdered(kHeadAddress, head)` worth it?

I think the counted loop it's more cache friendly, it would be interesting to see how the assembly instructions look like :) 
the `putIntOrdered` batch could cause a backpressure issue(io_uring_enter -> EBUSY) in submitting in sqe when cqe is full (2 *sqe_size currently) as `PlatformDependent.putIntOrdered(kHeadAddress, head)`  is called after loop (by increasing the head you make more space cqe)

> > Another note about available: the math should work fine as long as the distance between head and tail is within Integer.MAX_VALUE and I assume that's always true, if not, I can think to some way to improve that.

I'm not entirely sure but `available` could be negative as io_uring is used unsigned int(32 bit) internally for tail and head, so just use Math.abs

**Review by chrisvest — COMMENTED** [review]
My impression of the code is that perhaps we don't need to push it so hard, e.g. with the local variables for caching. Maybe just changing to the counted loop and batched putIntOrdered is enough for the compiler to do a good job on the code, without leaving the code "uglier" than before.

**Comment by franz1981** [comment]
@chrisvest 
> My impression of the code is that perhaps we don't need to push it so hard, e.g. with the local variables for caching

Hope the same: i don't have a box here to measure if it can worth the cost of uglier code, but looking at both JCTools and the java.util.* stuff, it seems like a common pattern to avoid performing fields loads over and over...
Need some numbers to decide

@1Jo1 
> the putIntOrdered batch could cause a backpressure issue(io_uring_enter -> EBUSY) in submitting in sqe when cqe is full (2 *sqe_size currently)

Thanks for the hint: it makes sense to me and I should dig a bit more on it to be sure of it, will try to answer as soon as I get this knowledge :)

**Comment by franz1981** [comment]
@normanmaurer when you'll have some time to bench this change I as it is I would be curious to see if it brings anything (but bugs, as @1Jo1 has suggested https://github.com/netty/netty/pull/10705#issuecomment-712734834)

**Comment by normanmaurer** [comment]
Please re-open in https://github.com/netty/netty-incubator-transport-io_uring which is the new home of the io-uring transport

**Pull request closed without merging**
