### PR TITLE
Change q050's nextList from q075 to q100, to reduce the call stack depth of method PoolChunkList.add(chunk)

### PR DESCRIPTION
**Pull request by laosijikaichele**
Motivation:

In `PoolArena`, the `q050`'s `nextList` should be  `q100`. 

Because when we call method `PoolChunkList.add(chunk)` to move a chunk, if a `chunk` moved from `q050` to `q075`, it will eventually move to `q100` after the call finished. 

So we can make `q050.nextList = q100` in `PoolArena`'s constructor, to reduce the call stack depth of method `PoolChunkList.add(chunk)`.

Modification:

Change `q050`'s `nextList` from `q075` to `q100` in `PoolArena`'s constructor.

Result:

Reduced the call stack depth of method `PoolChunkList.add(chunk)`.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@chrisvest @franz1981 @trustin can you please have a look

**Comment by luke-zhou** [comment]
> Motivation:
> 
> In `PoolArena`, the `q050`'s `nextList` should be `q100`.
> 
> Because when we call method `PoolChunkList.add(chunk)` to move a chunk, if a `chunk` moved from `q050` to `q075`, it will eventually move to `q100` after the call finished.
> 
> So we can make `q050.nextList = q100` in `PoolArena`'s constructor, to reduce the call stack depth of method `PoolChunkList.add(chunk)`.
> 
> Modification:
> 
> Change `q050`'s `nextList` from `q075` to `q100` in `PoolArena`'s constructor.
> 
> Result:
> 
> Reduced the call stack depth of method `PoolChunkList.add(chunk)`.

I believe this would be the same for the `q000` and `q025`, `nextList` of `q000` should be `q050` and `nextList` of `q025` should be `q075`

**Comment by chrisvest** [comment]
> when we call method PoolChunkList.add(chunk) to move a chunk, if a chunk moved from q050 to q075, it will eventually move to q100 after the call finished.

I don't understand why this is a given.

If the call stack depth is a problem, we can make the `add` method iterative instead of recursive.
If the 75-percentile list serves little purpose (it's last resort in allocation order), we could perhaps remove it entirely?

**Comment by normanmaurer** [comment]
> > when we call method PoolChunkList.add(chunk) to move a chunk, if a chunk moved from q050 to q075, it will eventually move to q100 after the call finished.
> 
> I don't understand why this is a given.
> 
> If the call stack depth is a problem, we can make the `add` method iterative instead of recursive. If the 75-percentile list serves little purpose (it's last resort in allocation order), we could perhaps remove it entirely?

I agree... IMHO we can just close this

**Comment by laosijikaichele** [comment]
@chrisvest 
> If the call stack depth is a problem, we can make the add method iterative instead of recursive.

The gain of reducing only one stack depth is trivial, but it is still a positive trivial change, IMHO.
We can skip `q075` in allocation order by simply not linked it in `PoolArena`'s constructor, without need to modify the `add` method, I think this is the most simple way to approach this.

> If the 75-percentile list serves little purpose (it's last resort in allocation order), we could perhaps remove it entirely?

We can't remove the 75-percentile list entirely, because although the 75-percentile list is not needed in allocation order, but it is still needed in de-allocation order, as the following code shows in `PoolArena`'s constructor:
```
q100.prevList(q075);
q075.prevList(q050);
```

**Comment by normanmaurer** [comment]
@chrisvest is there anything we need to do or can we just close this one ?

**Review by chrisvest — APPROVED** [review]

**Comment by chrisvest** [comment]
I think @laosijikaichele is correct, and we can merge this if the conflicts are resolved. It just looks counter intuitive and you have to work through the allocation logic to see it.

**Pull request merged**
