### PR TITLE
Add sessionPresent to MqttConnAckVariableHeader

### PR DESCRIPTION
**Pull request by flozano**
As per:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718033

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by Scottmitch** [comment]
@netkins accept

**Comment by bobmcwhirter** [comment]
thanks?

**Comment by normanmaurer** [comment]
@flozano thanks.. Adjusted commit message and cherry-picked into 4.1(a91e648) and master (6ff66fe).

**Comment by normanmaurer** [comment]
@bobmcwhirter fat fingers buddy ;)

**Pull request closed without merging**
