### PR TITLE
OioSctpChannel iterating over selected keys

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
OioSctpChannel.doReadMessages is iterating over the selected keys, and ignoring each selected key. It is not known why this is needed and no other channel implementation does this.

Modifications:
- Stop iterating over selected keys, and just read like other channels

Result:
No unnecessary iteration in OioSctpChannel.doReadMessages.
Fixes https://github.com/netty/netty/issues/3884

### CODE REVIEW

**Comment by Scottmitch** [comment]
@trustin @normanmaurer - FYI

**Comment by trustin** [comment]
LGTM. Thanks for taking care of this.

**Comment by normanmaurer** [comment]
@Scottmitch go for it

**Comment by Scottmitch** [comment]
Cherry-picked 4.0 (1525edf) 4.1 (56cc0bb) master (fae5d88)

**Pull request closed without merging**
