### PR TITLE
MQTT v5 implementation

### LINKED ISSUE #6285: Support for MQTT v5
Is there any planning to support MQTT v5 on netty-codec-mqtt? Do you need an hand.
Thanks.
 Andrea

### PR DESCRIPTION
**Pull request by andsel**
Motivation:

Developement PR of MQTT v5 codec

Modification:

Changes to MQTT codec to satisfy MQTT v5 protocol specs

Result:

Fixes #6285

### CODE REVIEW

**Comment by andsel** [comment]
Hi @normanmaurer this is is just initial effort to introduce MQTT v5 codec, and start a discussion about it

**Comment by normanmaurer** [comment]
@andsel I will review soon, a bit busy atm

**Comment by andsel** [comment]
@normanmaurer no problem, it's work in progress effort, thanks for your time

**Comment by andsel** [comment]
Hi @normanmaurer I have updated all the encoding and decoding part to let the codec works correctly with MQTTv5:
- I've introduced MqttProtocolVersionHandshakeHandler to switch the pipele between MQTT v3 and v5 codecs
- Added missed message AUTH
- Enriched existing MQTTT messages with new section MqttProperties (connect, connack, publish, puback, pubrec, purbrel, pubcomp, subscribe, suback unsuback, disconnect), the only untouched by this adding is unsubacribe.
- I've created the builders methods for some existing messages, updating with properties section
- Added new unit test to verify MQTTv5 codec part (named Mqtt5CodecTest)

I think we could start a review if you want.

Regards 
Andrea

**Comment by andsel** [comment]
Hi, I moved the code of this PR in a separate project into moquette-io  (https://github.com/moquette-io/netty-mqtt5-codec) and close the PR

**Pull request closed without merging**
