### PR TITLE
removed an unnecessary local variable for consistency

### PR DESCRIPTION
**Pull request by lime62**
for cleanup code and consistent pattern with other functions in the same class (AbstractBootstrap.java)

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by normanmaurer** [comment]
@lime62 could you please sign our ICLA: http://tinyurl.com/netty-icla ?

**Comment by normanmaurer** [comment]
@netkins accept

**Comment by lime62** [comment]
@normanmaurer I signed it before :)

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (a2f77e743e78c8e9092137d6d2e0639161a9f47e) , 4.1 (1e09409604cfb9e0da787a3f493faae3282e6e18) and master (ed416e01891472e362d637c1975b044f477994cc)

**Pull request closed without merging**
