### PR TITLE
Update ProtocolDetectionResult.java

### PR DESCRIPTION
**Pull request by parkcheolu**
Motivation:

Just to correct a typo.

Modification:

Changed a name of a private constant variable, 'NEEDS_MORE_DATE' to 'NEEDS_MORE_DATA'

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@parkcheolu can you please sign our ICLA: https://netty.io/s/icla ?

**Comment by parkcheolu** [comment]
I've signed.

**Comment by normanmaurer** [comment]
Thanks a lot!

**Pull request merged**
