### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by jyane**
Motivation:

There are many same typos.

Modifications:

Fix typos. Docs only changing.

Result:

Fixed.

### CODE REVIEW

**Comment by jyane** [comment]
This is my first PR.
I've signed CLA as an individual contributor.

**Comment by jyane** [comment]
```
java.lang.AssertionError
    at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSend0(DatagramUnicastTest.java:189)
    at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSend(DatagramUnicastTest.java:130)
    at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendCompositeHeapByteBuf(DatagramUnicastTest.java:92)
    at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendCompositeHeapByteBuf(DatagramUnicastTest.java:85)
------- Stdout: -------
03:05:52.459 [main] INFO  i.n.t.t.socket.DatagramUnicastTest - Running: testSimpleSendCompositeHeapByteBuf 1 of 4 (Bootstrap(BootstrapConfig(group: NioEventLoopGroup, channelFactory: NioDatagramChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@7d407990)) + Bootstrap(BootstrapConfig(group: NioEventLoopGroup, channelFactory: NioDatagramChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@7d407990))) with UnpooledByteBufAllocator
03:05:52.465 [main] INFO  i.n.t.t.socket.DatagramUnicastTest - Running: testSimpleSendCompositeHeapByteBuf 2 of 4 (Bootstrap(BootstrapConfig(group: NioEventLoopGroup, channelFactory: NioDatagramChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@7d407990)) + Bootstrap(BootstrapConfig(group: OioEventLoopGroup, channelFactory: OioDatagramChannel.class, options: {SO_TIMEOUT=10, ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@7d407990))) with UnpooledByteBufAllocator
03:05:52.631 [main] INFO  i.n.t.t.socket.DatagramUnicastTest - Running: testSimpleSendCompositeHeapByteBuf 3 of 4 (Bootstrap(BootstrapConfig(group: OioEventLoopGroup, channelFactory: OioDatagramChannel.class, options: {SO_TIMEOUT=10, ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@7d407990)) + Bootstrap(BootstrapConfig(group: NioEventLoopGroup, channelFactory: NioDatagramChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@7d407990))) with UnpooledByteBufAllocator
03:05:52.717 [main] INFO  i.n.t.t.socket.DatagramUnicastTest - Running: testSimpleSendCompositeHeapByteBuf 4 of 4 (Bootstrap(BootstrapConfig(group: OioEventLoopGroup, channelFactory: OioDatagramChannel.class, options: {SO_TIMEOUT=10, ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@7d407990)) + Bootstrap(BootstrapConfig(group: OioEventLoopGroup, channelFactory: OioDatagramChannel.class, options: {SO_TIMEOUT=10, ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@7d407990))) with UnpooledByteBufAllocator
```

Is test which is flaky...? 🤔

**Comment by normanmaurer** [comment]
Thanks... Cherry-picked into 4.1 (73f23c5fa)

**Comment by jyane** [comment]
@normanmaurer Ah...sorry, Was this PR not necessary? I will do my best for contributing the netty.

**Comment by normanmaurer** [comment]
@jyane it was... I just cherry-picked the commit to the 4.1 branch as stated above. Thanks again for the contribution :)

**Comment by jyane** [comment]
Thanks!

**Pull request closed without merging**
