### PR TITLE
Removed old CHM ported from JDK 5 to JDK 1.4

### PR DESCRIPTION
**Pull request by guidomedina**
Removed old JSR 166 CHM which was ported from JDK 5 to JDK 1.4

**Motivation:**

To benefit from newer JDK CHM as the current internal CHM is the one from JDK 5.

**Modification:**

Removed old JDK 5 CHM from internal package.

**Result:**

If you are using JDK 7 or 8 there will be a slight performance benefit.

### CODE REVIEW

**Comment by darionyaphet** [comment]
+1 why don't use JDK CHM ?

**Comment by guidomedina** [comment]
I think it was because Netty 3.X (some old version I can't tell exactly which) minimal requirement was JVM 1.4 hence the JSR 166 CHM was ported back.

In later versions support for JVM 1.4 was dropped but that ported back CHM was left behind and CHM has only become better specially JVM 7 and 8.

**Comment by guidomedina** [comment]
This is a quick and easy solution, TBH I don't care about JDK 5, 6 or 7 because I'm using JDK 8, a proper solution would be to copy CHMv8 to internal package just like it was done for Netty 4, but I guess Netty 4 users are thinking exactly what I'm thinking, they don't care about Netty 3 anymore, hence this quick hack solution shouldn't really bother anyone.

**Comment by johnou** [comment]
I'm not sure if the Netty maintainers will accept this unless you can demonstrate the stock CHM (in JDK 5) performance is above or on par with the JSR 166 CHM, whilst you don't care about JDK 5 the Netty team does or they wouldn't be accepting Netty 3.x issues.

You may also want to look over the contributing guide, in particular http://netty.io/wiki/writing-a-commit-message.html

If you are using JDK 8 why are you still using Netty 3.x?

**Comment by guidomedina** [comment]
The old CHM at Netty 3 is the old CHM candidate for JDK 5, that should be enough to go for it, in the worst scenario you would be using EXACTLY the same CHM, best scenarios: Java 7 & 8, you would be using a slightly faster CHM.

As for Netty 3 usage, I don't use Netty 3 directly, the APIs I use are based on Netty and they are written in Scala, it would at been easier for me to go somewhere else and just migrate to Netty 4 but unfortunately I don't have a choice.

I'm only contributing what I already did, I already compiled Netty 3.10.6 with the current fixes and put it on my company's archiva, this contribution is not for me, is for the community. It is up to you to accept it or close it.

**Comment by guidomedina** [comment]
Initial description edited though it was trivial enough.

**Comment by guidomedina** [comment]
From the main author of JSR 166 Doug Lea: http://gee.cs.oswego.edu/dl/concurrency-interest/ search for "JDK 5" and see the statement:

_The initial contents of JSR166 were released as part of JDK 5, mostly in new package java.util.concurrent._

**Comment by johnou** [comment]
@guidomedina heads up you will need to change the actual git commit message.

**Comment by guidomedina** [comment]
@johnou done.

**Comment by johnou** [comment]
@guidomedina looks like the Result section of your commit message is missing? (letting you know to save you time / speed up the merge).

**Comment by guidomedina** [comment]
@johnou result section added and whole commit message simplified to better express the simplicity of the solution.

**Comment by johnou** [comment]
:+1:

**Comment by normanmaurer** [comment]
@trustin WDYT ? Sounds good to me...

**Comment by darionyaphet** [comment]
Hi @guidomedina  Could compare JDK CHM and Netty . Maybe JDK have some improvement on performance

**Comment by guidomedina** [comment]
@darionyaphet

There is only two things you can expect from this change:
- **Potential performance improvement:** If you are on JDK 7 & 8 which have indeed better CHM implementations, and are proven to be faster than the ones from JDK 5 & 6 (Which I think they are the same), I looked at each CHM source code and it starts changing at JDK 7.
- **Small cleanup:** Few thousands of lines of code removed.

_Again I consider this a small effort for a potential and considerable benefit, no bad side effect that I could possible see._

**Comment by slandelle** [comment]
@guidomedina @darionyaphet There's one additional benefit from CHMV8, even if Netty isn't probably impacted: protection against hash collision attacks.

**Comment by guidomedina** [comment]
For your reference:

- **JDK 6:** http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b27/java/util/concurrent/ConcurrentHashMap.java?av=f

It looks like JDK 7 added alternate hashing:

- **JDK 7:** http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7u40-b43/java/util/concurrent/ConcurrentHashMap.java?av=f

**Comment by guidomedina** [comment]
@slandelle The idea with this change was to give some love to a dying man ;-)

**Comment by normanmaurer** [comment]
@trustin ping

**Comment by trustin** [comment]
LGTM. :+1:

**Comment by normanmaurer** [comment]
@guidomedina could you fill our icla please and let me know once done ? 

http://netty.io/s/icla

**Comment by guidomedina** [comment]
I did that already on my previous PR?
Just in case I think I did and did not just filled it again.

**Comment by normanmaurer** [comment]
@guidomedina oh sorry... Thanks!

**Comment by normanmaurer** [comment]
Cherry-picked into 3.10 as c9f963dc8e75d9abb89750807ec6627b40f7aada

**Comment by normanmaurer** [comment]
@guidomedina thanks!

**Pull request closed without merging**
