### PR TITLE
[#4705] Ensure ChannelHandler.handlerAdded(...) is always called as f…

### PR DESCRIPTION
**Pull request by normanmaurer**
…irst method of the handler

Motivation:

If a user adds a ChannelHandler from outside the EventLoop it is possible to get into the situation that handlerAdded(...) is scheduled on the EventLoop and so called after another methods of the ChannelHandler as the EventLoop may already be executing on this point in time.

Modification:

- Ensure we always check if the handlerAdded(...) method was called already and if not add the currently needed call to the EventLoop so it will be picked up after handlerAdded(...) was called. This works as if the handler is added to the ChannelPipeline from outside the EventLoop the actual handlerAdded(...) operation is scheduled on the EventLoop.
- Some cleanup in the DefaultChannelPipeline

Result:

Correctly order of method executions of ChannelHandler.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@johnou can you test this with jython as well ?

**Comment by johnou** [comment]
@normanmaurer @nickmbailey hoping I have made a mistake somewhere in the patch process because it's failing..

$ java -jar jython-standalone-2.7.1b2-patched.jar netty-ssl-bug.py
200 OK
0
200 OK
1
200 OK
2
Traceback (most recent call last):
  File "netty-ssl-bug.py", line 4, in <module>
    conn.request("GET", "/")
  File "/home/johno/netty/tmp/jython-standalone-2.7.1b2-patched.jar/Lib/httplib.py", line 1001, in request
  File "/home/johno/netty/tmp/jython-standalone-2.7.1b2-patched.jar/Lib/httplib.py", line 1035, in _send_request
  File "/home/johno/netty/tmp/jython-standalone-2.7.1b2-patched.jar/Lib/httplib.py", line 997, in endheaders
  File "/home/johno/netty/tmp/jython-standalone-2.7.1b2-patched.jar/Lib/httplib.py", line 850, in _send_output
  File "/home/johno/netty/tmp/jython-standalone-2.7.1b2-patched.jar/Lib/httplib.py", line 812, in send
  File "/home/johno/netty/tmp/jython-standalone-2.7.1b2-patched.jar/Lib/httplib.py", line 1204, in connect
  File "/home/johno/netty/tmp/jython-standalone-2.7.1b2-patched.jar/Lib/_socket.py", line 357, in handle_exception
  File "/home/johno/netty/tmp/jython-standalone-2.7.1b2-patched.jar/Lib/_socket.py", line 357, in handle_exception
  File "/home/johno/netty/tmp/jython-standalone-2.7.1b2-patched.jar/Lib/ssl.py", line 320, in wrap_socket
  File "/home/johno/netty/tmp/jython-standalone-2.7.1b2-patched.jar/Lib/ssl.py", line 147, in __init__
  File "/home/johno/netty/tmp/jython-standalone-2.7.1b2-patched.jar/Lib/ssl.py", line 196, in do_handshake
_socket.SSLError: [Errno 1] Unmapped exception: java.lang.NullPointerException

**Comment by normanmaurer** [comment]
@johnou bummer... Can you explain how exactly I can build the "patched jython" ?

**Comment by johnou** [comment]
@normanmaurer something like this https://gist.github.com/johnou/481d3d361be0ba76dbb1

**Comment by johnou** [comment]
@normanmaurer any luck with the ant script?

**Comment by normanmaurer** [comment]
Had no time yet, sorry

**Comment by johnou** [comment]
@nickmbailey what's the best way to get the full stacktrace from java? I would like to verify it's the same NPE and see what causes the below exception..

```
Traceback (most recent call last):
  File "netty-ssl-bug.py", line 4, in <module>
    conn.request("GET", "/")
  File "/home/johno/netty/build/Lib/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/home/johno/netty/build/Lib/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/home/johno/netty/build/Lib/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/home/johno/netty/build/Lib/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/home/johno/netty/build/Lib/httplib.py", line 812, in send
    self.connect()
  File "/home/johno/netty/build/Lib/httplib.py", line 1204, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/home/johno/netty/build/Lib/_socket.py", line 357, in handle_exception
    return method_or_function(*args, **kwargs)
  File "/home/johno/netty/build/Lib/_socket.py", line 357, in handle_exception
    return method_or_function(*args, **kwargs)
  File "/home/johno/netty/build/Lib/ssl.py", line 320, in wrap_socket
    return SSLSocket(
  File "/home/johno/netty/build/Lib/ssl.py", line 147, in __init__
    self.do_handshake()
  File "/home/johno/netty/build/Lib/ssl.py", line 196, in do_handshake
    raise SSLError(SSL_ERROR_SSL, e.strerror)
_socket.SSLError: [Errno 1] Illegal state exception
```

**Comment by johnou** [comment]
Whilst trying to capture the exception I came across this hack? in jython's Lib/ssl.py.

```python
        handshake = self.ssl_handler.handshakeFuture()
        time.sleep(0.001)  # Necessary apparently for the handler to get into a good state
        try:
            self._sock._handle_channel_future(handshake, "SSL handshake")
        except socket_error, e:
            raise SSLError(SSL_ERROR_SSL, e.strerror)
```

**Comment by johnou** [comment]
@normanmaurer 

```
java.lang.NullPointerException
        at org.python.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:596)
        at org.python.netty.handler.ssl.SslHandler.handshake(SslHandler.java:1364)
        at org.python.netty.handler.ssl.SslHandler.channelActive(SslHandler.java:1405)
        at org.python.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:184)
        at org.python.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:170)
        at org.python.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:811)
        at org.python.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:260)
        at org.python.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:290)
        at org.python.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
        at org.python.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at org.python.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at org.python.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at org.python.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)
```

```
java.lang.IllegalStateException
        at org.python.netty.handler.ssl.SslHandler$LazyChannelPromise.executor(SslHandler.java:1489)
        at org.python.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:614)
        at org.python.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:139)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
        at org.python.core.PyObject.__call__(PyObject.java:478)
        at org.python.core.PyObject.__call__(PyObject.java:482)
        at org.python.core.PyMethod.__call__(PyMethod.java:141)
        at _socket$py._handle_channel_future$70(/home/johno/netty/build/Lib/_socket.py:782)
        at _socket$py.call_function(/home/johno/netty/build/Lib/_socket.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyFunction.function___call__(PyFunction.java:471)
        at org.python.core.PyFunction.__call__(PyFunction.java:466)
        at org.python.core.PyFunction.__call__(PyFunction.java:461)
        at org.python.core.PyObject._callextra(PyObject.java:601)
        at _socket$py.handle_exception$30(/home/johno/netty/build/Lib/_socket.py:370)
        at _socket$py.call_function(/home/johno/netty/build/Lib/_socket.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:161)
        at org.python.core.PyFunction.__call__(PyFunction.java:434)
        at org.python.core.PyMethod.__call__(PyMethod.java:156)
        at ssl$py.do_handshake$9(/home/johno/netty/build/Lib/ssl.py:201)
        at ssl$py.call_function(/home/johno/netty/build/Lib/ssl.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.core.PyMethod.__call__(PyMethod.java:126)
        at ssl$py.__init__$5(/home/johno/netty/build/Lib/ssl.py:149)
        at ssl$py.call_function(/home/johno/netty/build/Lib/ssl.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
        at org.python.core.PyMethod.__call__(PyMethod.java:228)
        at org.python.core.PyMethod.__call__(PyMethod.java:223)
        at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
        at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
        at org.python.core.PyType.type___call__(PyType.java:1715)
        at org.python.core.PyType.__call__(PyType.java:1698)
        at org.python.core.PyObject.__call__(PyObject.java:394)
        at ssl$py.wrap_socket$38(/home/johno/netty/build/Lib/ssl.py:325)
        at ssl$py.call_function(/home/johno/netty/build/Lib/ssl.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyFunction.function___call__(PyFunction.java:471)
        at org.python.core.PyFunction.__call__(PyFunction.java:466)
        at org.python.core.PyFunction.__call__(PyFunction.java:461)
        at org.python.core.PyObject._callextra(PyObject.java:601)
        at _socket$py.handle_exception$30(/home/johno/netty/build/Lib/_socket.py:370)
        at _socket$py.call_function(/home/johno/netty/build/Lib/_socket.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:161)
        at org.python.core.PyFunction.__call__(PyFunction.java:434)
        at httplib$py.connect$45(/home/johno/netty/build/Lib/httplib.py:1204)
        at httplib$py.call_function(/home/johno/netty/build/Lib/httplib.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.core.PyMethod.__call__(PyMethod.java:126)
        at httplib$py.send$26(/home/johno/netty/build/Lib/httplib.py:826)
        at httplib$py.call_function(/home/johno/netty/build/Lib/httplib.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
        at org.python.core.PyFunction.__call__(PyFunction.java:423)
        at org.python.core.PyMethod.__call__(PyMethod.java:141)
        at httplib$py._send_output$28(/home/johno/netty/build/Lib/httplib.py:854)
        at httplib$py.call_function(/home/johno/netty/build/Lib/httplib.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
        at org.python.core.PyFunction.__call__(PyFunction.java:423)
        at org.python.core.PyMethod.__call__(PyMethod.java:141)
        at httplib$py.endheaders$31(/home/johno/netty/build/Lib/httplib.py:997)
        at httplib$py.call_function(/home/johno/netty/build/Lib/httplib.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
        at org.python.core.PyFunction.__call__(PyFunction.java:423)
        at org.python.core.PyMethod.__call__(PyMethod.java:141)
        at httplib$py._send_request$34(/home/johno/netty/build/Lib/httplib.py:1035)
        at httplib$py.call_function(/home/johno/netty/build/Lib/httplib.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.__call__(PyMethod.java:187)
        at httplib$py.request$32(/home/johno/netty/build/Lib/httplib.py:1001)
        at httplib$py.call_function(/home/johno/netty/build/Lib/httplib.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:161)
        at org.python.core.PyFunction.__call__(PyFunction.java:434)
        at org.python.core.PyMethod.__call__(PyMethod.java:156)
        at org.python.pycode._pyx0.f$0(netty-ssl-bug.py:2)
        at org.python.pycode._pyx0.call_function(netty-ssl-bug.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1403)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
        at org.python.util.jython.run(jython.java:362)
        at org.python.util.jython.main(jython.java:142)
```

**Comment by johnou** [comment]
@normanmaurer think it's ok now https://github.com/netty/netty/pull/4776

**Comment by normanmaurer** [comment]
Closed... Using https://github.com/netty/netty/pull/4776.

**Pull request closed without merging**
