### PR TITLE
Test that CompositeByteBuf releases its components

### PR DESCRIPTION
**Pull request by kevinherron**

### CODE REVIEW

**Comment by kevinherron** [comment]
This test is interesting because it fails on 4.0.32.Final and earlier, passes on 4.0.33.Final and later, but there is nothing in the change log or issues to indicate that something was fixed (that I can find, anyway).

**Comment by normanmaurer** [comment]
@kevinherron actually I think this was fixed by this:

https://github.com/netty/netty/commit/31ef2370854734e61881cd6ad99820979fb0aecc

Before `Unpooled.EMPTY_BUFFER` was returned for `slice()` here and so the reference count was not shared in this case.

**Comment by kevinherron** [comment]
I've updated the test so that it does not use any empty buffers or slices.

**Comment by johnou** [comment]
@kevinherron would you kindly squash your commits and update your commit message to respect the Netty commit message template? http://netty.io/wiki/writing-a-commit-message.html

**Comment by normanmaurer** [comment]
@kevinherron thanks a lot ! I am still not 100 % sure atm what exactly fixed it :( I will need to dig into it when I have a bit more time. Let me just merge the test for now tho.

**Comment by normanmaurer** [comment]
@kevinherron can you please sign our ICLA:

http://netty.io/s/icla

**Comment by normanmaurer** [comment]
@kevinherron let me know once done

**Comment by kevinherron** [comment]
I've signed the ICLA

**Comment by normanmaurer** [comment]
@kevinherron thanks

Cherry-picked into 4.0 (8dd95757f28ee288c5c543d324c3a66db701a76b) and 4.1 (ee3c8e0580781a0497f365a0337b9be8e590f547)

**Pull request closed without merging**
