### PR TITLE
Fix the 'branches to look' section for 4.0 branch

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Comment by normanmaurer** [comment]
@slachiewicz please only have on commit in here...

**Comment by slachiewicz** [comment]
Sorry.. fixed :)

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (1bcfb910d19b5b210fc9d2aaf1ed764accce9cd3) , 4.1 (c068ae8d84787d618e6bebf942af50dea2c19c16) and master (7aac2d9703e93c83237e137b5d7ea5b60f0ef40b)

**Comment by normanmaurer** [comment]
@slachiewicz thanks!

**Pull request closed without merging**
