### PR TITLE
All override methods must be added @override

### PR DESCRIPTION
**Pull request by slievrly**
Motivation:

Explain here the context, and why you're making that change.
What is the problem you're trying to solve.

Modification:

All override methods must be added @override

Result:

### CODE REVIEW

**Comment by normanmaurer** [comment]
@slievrly can you please sign our ICLA and let me know once done ?

https://netty.io/s/icla

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by slievrly** [comment]
@normanmaurer I have signed the ICLA agreement, thank you.

**Comment by slievrly** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Pull request merged**
