### PR TITLE
Fix ByteBuf leak in Http2ControlFrameLimitEncoderTest

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We recently introduced Http2ControlFrameLimitEncoderTest which did not correctly notify the goAway promises and so leaked buffers.

Modifications:

Correctly notify all promises and so release the debug data.

Result:

Fixes leak in HTTP2 test

### CODE REVIEW

**Comment by normanmaurer** [comment]
Let me merge this so other PRs don't fail.

**Comment by normanmaurer** [comment]
Yes we basically release the debug data in the listener as we retain it before and as we never notified the promise it leaked

**Comment by ejona86** [comment]
But what _code_ is retaining that data in the listener. It isn't Http2ControlFrameLimitEncoder and this code change is not specific to a certain test method, so there's no easy way to figure out the issue you saw.

**Comment by normanmaurer** [comment]
Http2ConnectionHandler

**Comment by ejona86** [comment]
I see. https://github.com/netty/netty/blob/1cce3b1ac9293940a1731ea31455d538631b6329/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L843 is where it is retained and it is only retained for DEBUG-level logging.

**Pull request merged**
