### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by ifesdjeen**
Motivation: https://twitter.com/normanmaurer/status/682493372397940736 
:) 

Happy new year everyone! 
Hope to be able to contribute more next year :)

### CODE REVIEW

**Comment by normanmaurer** [comment]
@ifesdjeen maybe just squash ? Happy new year too you as well :)

**Comment by ifesdjeen** [comment]
True, squashed

**Comment by ifesdjeen** [comment]
:( somehow build fails, not sure if i caused it

**Comment by normanmaurer** [comment]
Nope... Just rebase

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (78c4bd474e9b67f40536714a028da5091a98e81f) and 4.1 (78c4bd474e9b67f40536714a028da5091a98e81f)

**Comment by Scottmitch** [comment]
@ifesdjeen - thanks for the fixes!

**Pull request closed without merging**
