### PR TITLE
PlatformDependent ASCII hash code broken on big endian machines

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
PlatformDependent has a hash code algorithm which utilizes UNSAFE for performance reasons. This hash code algorithm must also be consistent with CharSequence objects that represent a collection of ASCII characters. In order to make the UNSAFE versions and CharSequence versions the endianness should be taken into account. However the big endian code was not correct in a few places.

Modifications:
- Correct bugs in PlatformDependent class related to big endian ASCII hash code computation

Result:
Fixes https://github.com/netty/netty/issues/5925

### CODE REVIEW

**Comment by Scottmitch** [comment]
@rz-itac - Please verify this fixes your issue.

@johnnyquestep - Since this may be related to https://github.com/netty/netty/issues/5916 ... can you verify if it fixes your issue too?

@normanmaurer - FYI.

**Comment by Scottmitch** [comment]
I was able to use qemu to emulate a PPC based architecture ... but it is painfully slow. So please provide feedback if you have a big endian machine.

**Comment by rz-itac** [comment]
Hi, the sparc machine I have is very old, and is very slow also. I didn't manage to get git running (missing dependencies).

But I compiled your change and run my application against it and the smoke test worked, the http connection was upgraded to websocket protocol.

I might be able to provide more feedback on monday, if I can get git to work or maybe I can borrow another solaris box that is newer.

Or maybe @johnnyquestep can help us if he has access to an sparc machine.

Thank you!

**Comment by johnnyquestep** [comment]
I  rebuilt my app with the 4.1.7 all jar. still getting the same error 
i am running on SunOS 5.10 Generic_150400-32 sun4v sparc sun4v

**Comment by rz-itac** [comment]
Hi, maybe the difference in the outputs is related to the architecture, in my box,  `uname -a` prints:

`SunOS sparc 5.10 Generic_137137-09 sun4u sparc SUNW,Sun-Blade-100`

My setup has 64-bit capability enabled.

Maybe this can be related, but I had some weird behaviour while trying to run the maven tests: the enforcer plugin always fired the X64 rule. I tried with 32 and 64 bit JVM, I commented the rule to get beyond that point as I was clueless.

If you need more details please tell me.

**Comment by johnnyquestep** [comment]
that jar name was copy paste error , i tested with yesterday nights build as well and still same error.

**Comment by slandelle** [comment]
> i tested with yesterday nights build as well and still same error

@johnnyquestep This pull request hasn't been merged yet in master as @Scottmitch is waiting for your feedback to confirm the fix. Hence, nightly builds don't ship it.

**Comment by johnnyquestep** [comment]
I copied the code for that file and tried build it myslef on linux. my build kept failing due to missing dependency. Anyway @slandelle  or @rz-itac  can post the all in one jar somehwere ? iill be happy to pull it and test again.

**Comment by slandelle** [comment]
https://www.dropbox.com/s/wcy6dfmsyv07tsl/netty-all-4.1.7.Final-SNAPSHOT.jar?dl=0

Will delete in 20 minutes.

**Comment by johnnyquestep** [comment]
Confirmed fix is good. Thank you all @slandelle @rz-itac @Scottmitch

**Comment by Scottmitch** [comment]
Thanks @slandelle for providing assistance. Thanks @johnnyquestep @rz-itac for verifying!

4.1 (9cfa467)

**Pull request closed without merging**
