### PR TITLE
Use buffer recycler for ZstdDecoder

### PR DESCRIPTION
**Pull request by yuzawa-san**
Motivation:

I surfaced this in https://github.com/netty/netty/pull/13531. [ZstdInputStreamNoFinalizer](https://github.com/luben/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/ZstdInputStreamNoFinalizer.java#L53-L55) will [allocate](https://github.com/luben/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/NoPool.java#L16) a byte[] of length 131075 ("[recommendedDInSize](https://github.com/luben/zstd-jni/blob/20014d19a91a1b04e4e198ac1cb85b5acb1c1142/src/main/java/com/github/luben/zstd/ZstdInputStreamNoFinalizer.java#L35)") on each instantiation. This will put a lot of pressure on the JVM allocator and garbage collector.

Modifications:

Use the [RecyclingBufferPool](https://github.com/luben/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/RecyclingBufferPool.java) to reuse buffers.

Result:

The number of buffers should converge to the number of zstd decode operations in flight. Given this would typically be related to the number of active channels with this handler added, as long as that is stable, the number of allocations will remain stable.

### CODE REVIEW

**Comment by chrisvest** [comment]
I think this should be configurable (e.g. provide buffer pool implementation as constructor parameter) because that buffer pool is 1) unbounded and never shrinking, which can lead to resource exhaustion issues, and 2) using SoftReferences, which can length reference processing times.

**Comment by normanmaurer** [comment]
@yuzawa-san can you please make the suggested changes by @chrisvest

**Comment by yuzawa-san** [comment]
@normanmaurer Would a constructor argument of type BufferPool be a reasonable solution? Should I keep a zero-arg constructor? If so, what should the default BufferPool be?

I would still vote for the RecyclingBufferPool to be the default. NoPool, I would argue, would have drastically worse performance, and RecyclingBufferPool would be better even despite the aspects that @chrisvest mentioned (although it should not resource overload as fast since the GC pressure would start culling the soft references ideally). When I enabled zstd in Kafka I saw excessive allocation and GC activity without pooling. That was the original the rationale for me adding this to zstd-jni and Kafka a few years back and it helped immensely all without any custom configuration (since pooling was the default in kafka).

**Comment by normanmaurer** [comment]
I think we should provide a no-arg constructor as well and not use the pool by default.

**Comment by yuzawa-san** [comment]
@normanmaurer I've pushed a fix that has the default of NoPool and allows configuration, but I have run afoul of `java.class.externalClassExposedInAPI: interface com.github.luben.zstd.BufferPool: A class from supplementary archives is used in a public capacity in the API. [com.github.luben:zstd-jni:jar:1.5.5-11]` if this is not allowed would a property like this https://github.com/netty/netty/pull/13885/files#diff-d0ac41a388b4b8f2f33ee52b25e0e922679eecc29f0b062c474e7c1f76b6074aR57-R67 be more desirable?

Also, I see that https://github.com/netty/netty/pull/13909 was merged. Given that the embedded channel in there will create a new ZstdDecoder for every http request (rather its content, as I understand it), should at least that use the RecyclingBufferPool? Otherwise, each request will allocate a new byte[131075], which would be quite a shock. And if the concern is the particulars of the RecyclingBufferPool, should Netty have its own default BufferPool implementation? It would seem like anything would be better than the NoPool.

**Comment by normanmaurer** [comment]
I think this is a better "fix" https://github.com/netty/netty/pull/13928

**Comment by yuzawa-san** [comment]
superseded by https://github.com/netty/netty/pull/13928

that gets over the whole issue and i like it better

**Pull request closed without merging**
