### PR TITLE
Add support for snappy http2 content decompression

### PR DESCRIPTION
**Pull request by skyguard1**
Motivation:

Since netty already supports the decompression of snappy's http content encoding, it should also consider supporting snappy's http2 content decompression

Modification:

Add support for snappy http content decompression

Result:

Netty supports snappy http content decompression

### CODE REVIEW

**Comment by normanmaurer** [comment]
@skyguard1 can you add some unit tests ?

**Comment by skyguard1** [comment]
@normanmaurer I think `io.netty.handler.codec.http2.DataCompressionHttp2Test.snappyEncodingSingleMessage()` has tested it. Do we need other test cases to test snappy http2 content decompression?

**Comment by normanmaurer** [comment]
@skyguard1 thanks

**Comment by skyguard1** [comment]
It is my pleasure

**Pull request merged**
