### PR TITLE
Native EPOLL Library Allows Shading

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
If Netty's class files are renamed and the type references are updated (shaded) the native libraries will not function. The native epoll module uses implicit JNI bindings which requires the fully qualified java type names to match the method signatures of the native methods. This means EPOLL cannot be used with a shaded Netty.

Modifications:
- Make the JNI method registration dynamic
- support a system property io.netty.packagePrefix which must be prepended to the name of the native library (to ensure the correct library is loaded) and all class names (to allow classes to be correctly referenced)
- remove system property io.netty.native.epoll.nettyPackagePrefix which was recently added and the code to support it was incomplete

Result:
transport-native-epoll can be used when Netty has been shaded.
Fixes netty#4800

### CODE REVIEW

**Comment by Scottmitch** [comment]
@normanmaurer @Harry5573 - FYI

**Comment by Harry5573** [comment]
@Scottmitch Having some trouble compiling:

> 
[INFO] --- maven-hawtjni-plugin:1.10:generate (build-native-lib) @ netty-transport-native-epoll ---
[INFO] executing: /bin/sh -c ./autogen.sh
[INFO]
[INFO] --- maven-hawtjni-plugin:1.10:build (build-native-lib) @ netty-transport-native-epoll ---
[INFO] executing: /bin/sh -c ./autogen.sh
[INFO] executing: /bin/sh -c ./configure --disable-ccache --prefix=/root/netty/transport-native-epoll/target/native-build/target 'CFLAGS=-O                                               3 -DIO_NETTY_SENDMMSG_NOT_FOUND -Werror'
[INFO] executing: /bin/sh -c make install
[INFO] /bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./src     -O3 -DIO_NETTY_SENDMMSG_NOT_FOUND -Werror -I/usr/lib                                               /jvm/java-1.7.0-openjdk-1.7.0.91.x86_64/include -I/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.91.x86_64/include/linux -c -o src/netty_epoll_nativ                                               e.lo src/netty_epoll_native.c
[INFO] libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src -O3 -DIO_NETTY_SENDMMSG_NOT_FOUND -Werror -I/usr/lib/jvm/java-1.7.0-openjdk-1.7.0                                               .91.x86_64/include -I/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.91.x86_64/include/linux -c src/netty_epoll_native.c  -fPIC -DPIC -o src/.libs/ne                                               tty_epoll_native.o
[INFO] src/netty_epoll_native.c: In function ‘freeDynamicMethodsTable’:
[INFO] src/netty_epoll_native.c:777: error: ‘for’ loop initial declarations are only allowed in C99 mode
[INFO] src/netty_epoll_native.c:777: note: use option -std=c99 or -std=gnu99 to compile your code
[INFO] make: *** [src/netty_epoll_native.lo] Error 1
[INFO] rc: 2
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Netty .............................................. SUCCESS [ 16.045 s]
[INFO] Netty/Common ....................................... SUCCESS [ 40.831 s]
[INFO] Netty/Buffer ....................................... SUCCESS [ 26.982 s]
[INFO] Netty/Transport .................................... SUCCESS [ 29.792 s]
[INFO] Netty/Codec ........................................ SUCCESS [ 16.030 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  7.318 s]
[INFO] Netty/Handler ...................................... SUCCESS [ 25.112 s]
[INFO] Netty/Codec/HTTP ................................... SUCCESS [ 30.685 s]
[INFO] Netty/Codec/Socks .................................. SUCCESS [  6.940 s]
[INFO] Netty/Transport/RXTX ............................... SUCCESS [  4.415 s]
[INFO] Netty/Transport/SCTP ............................... SUCCESS [  6.402 s]
[INFO] Netty/Transport/UDT ................................ SUCCESS [  9.736 s]
[INFO] Netty/Example ...................................... SUCCESS [ 15.581 s]
[INFO] Netty/Testsuite .................................... SUCCESS [ 11.388 s]
[INFO] Netty/Testsuite/OSGI ............................... SUCCESS [  6.198 s]
[INFO] Netty/Microbench ................................... SUCCESS [ 21.459 s]
[INFO] Netty/Transport/Native/Epoll ....................... FAILURE [ 31.192 s]
[INFO] Netty/All-in-One ................................... SKIPPED
[INFO] Netty/Tarball ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:09 min
[INFO] Finished at: 2016-02-02T18:53:58-05:00
[INFO] Final Memory: 33M/110M
[INFO] ------------------------------------------------------------------------

**Comment by Harry5573** [comment]
Fixed the compilation issue with https://github.com/Harry5573/netty/commit/7a8afd78fb0468f3fea89ba5f6f35e881f503df9

**Comment by Scottmitch** [comment]
@Harry5573 - Sorry about that. try updated code.

**Comment by Harry5573** [comment]
@Scottmitch No luck.

> 
[20:20:35] [Server thread/INFO]: Netty property(io.netty.packagePrefix): net.minecraft.util.
[20:20:35] [Server thread/ERROR]: Exception stopping the server
java.lang.UnsatisfiedLinkError: failed to load the required native library
        at net.minecraft.util.io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:76) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.ServerConnection.<init>(ServerConnection.java:45) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.ai(MinecraftServer.java:1328) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.stop(MinecraftServer.java:401) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:537) [Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Krunchit.jar:git-Krunchit-8b33eba]
Caused by: java.lang.NoClassDefFoundError: io/netty/channel/epoll/NativeStaticallyReferencedJniMethods
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_65]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938) ~[?:1.8.0_65]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821) ~[?:1.8.0_65]
        at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_65]
        at java.lang.System.load(System.java:1086) ~[?:1.8.0_65]
        at net.minecraft.util.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.util.io.netty.channel.epoll.Native.<clinit>(Native.java:60) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.util.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:32) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.ServerConnection.<init>(ServerConnection.java:45) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.ai(MinecraftServer.java:1328) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:147) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:470) ~[Krunchit.jar:git-Krunchit-8b33eba]
        ... 1 more
Caused by: java.lang.ClassNotFoundException: io.netty.channel.epoll.NativeStaticallyReferencedJniMethods
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_65]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_65]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_65]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_65]
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_65]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938) ~[?:1.8.0_65]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821) ~[?:1.8.0_65]
        at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_65]
        at java.lang.System.load(System.java:1086) ~[?:1.8.0_65]
        at net.minecraft.util.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.util.io.netty.channel.epoll.Native.<clinit>(Native.java:60) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.util.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:32) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.ServerConnection.<init>(ServerConnection.java:45) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.ai(MinecraftServer.java:1328) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:147) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:470) ~[Krunchit.jar:git-Krunchit-8b33eba]
        ... 1 more

**Comment by Harry5573** [comment]
@Scottmitch Also tried renaming the .so file as you said in the issue report, however that throws:

> 

[20:24:39] [Server thread/INFO]: Netty property: net.minecraft.util.
[20:24:39] [Server thread/ERROR]: Exception stopping the server
java.lang.UnsatisfiedLinkError: failed to load the required native library
        at net.minecraft.util.io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:76) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.ServerConnection.<init>(ServerConnection.java:45) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.ai(MinecraftServer.java:1328) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.stop(MinecraftServer.java:401) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:537) [Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Krunchit.jar:git-Krunchit-8b33eba]
Caused by: java.lang.UnsatisfiedLinkError: no netty-transport-native-epoll in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864) ~[?:1.8.0_65]
        at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_65]
        at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_65]
        at net.minecraft.util.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:168) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.util.io.netty.channel.epoll.Native.<clinit>(Native.java:60) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.util.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:32) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.ServerConnection.<init>(ServerConnection.java:45) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.ai(MinecraftServer.java:1328) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:147) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:470) ~[Krunchit.jar:git-Krunchit-8b33eba]
        ... 1 more

**Comment by Scottmitch** [comment]
@Harry5573 -

> [20:20:35] [Server thread/INFO]: Netty property(io.netty.packagePrefix): net.minecraft.util.

Did you set your system property as outlined in https://github.com/netty/netty/issues/4800#issuecomment-178257698 (-Dnet.minecraft.util.io.netty.packagePrefix=net.minecraft.util.)

**Comment by Harry5573** [comment]
@Scottmitch I'm doing the following:

Set:
> 
System.setProperty("io.netty.packagePrefix", "net.minecraft.util.");

Debug:
> 
b.log(Level.INFO, "Netty property(io.netty.packagePrefix): " + System.getProperty("io.netty.packagePrefix"));

**Comment by Scottmitch** [comment]
If you are using the [maven shadow plugin](https://maven.apache.org/plugins/maven-shade-plugin/) or the [gradle shadow](https://github.com/johnrengelman/shadow) plugin to rename netty's class files then the system properties **names** will also be changes. So you have to append `net.minecraft.util.` to the **names** of the system properties. This is so you can configure each version of the shadowed dependency uniquely if multiple exist.

**Comment by Harry5573** [comment]
@Scottmitch Ah, my bad! 

After setting that and renaming the .so to "libnetty-net-minecraft-util-netty-transport-native-epoll" its throwing the following:
> 
[20:43:55] [Server thread/ERROR]: Exception stopping the server
java.lang.UnsatisfiedLinkError: failed to load the required native library
        at net.minecraft.util.io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:76) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.ServerConnection.<init>(ServerConnection.java:45) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.ai(MinecraftServer.java:1328) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.stop(MinecraftServer.java:401) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:537) [Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Krunchit.jar:git-Krunchit-8b33eba]
Caused by: java.lang.UnsatisfiedLinkError: no net-minecraft-util-netty-transport-native-epoll in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864) ~[?:1.8.0_65]
        at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_65]
        at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_65]
        at net.minecraft.util.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:168) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.util.io.netty.channel.epoll.Native.<clinit>(Native.java:60) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.util.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:32) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.ServerConnection.<init>(ServerConnection.java:45) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.ai(MinecraftServer.java:1328) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:147) ~[Krunchit.jar:git-Krunchit-8b33eba]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:470) ~[Krunchit.jar:git-Krunchit-8b33eba]
        ... 1 more

**Comment by Scottmitch** [comment]
Looks like it can't find the renamed version of the library. What is the name/location of the shadowed jar which includes the netty epoll module?

Can you show me the output from the following command:

```bash
jar -tf <path to shadowed jar with native epoll .so> | grep netty-transport-native-epoll
```

**Comment by Harry5573** [comment]
> 
jar -tf Krunchit.jar | grep netty-transport-native-epoll
META-INF/native/libnetty-net-minecraft-util-netty-transport-native-epoll.so

**Comment by Scottmitch** [comment]
@Harry5573 - Thanks. Change `META-INF/native/libnetty-net-minecraft-util-netty-transport-native-epoll.so` to `META-INF/native/libnet-minecraft-util-netty-transport-native-epoll.so` (remove the first `netty-`).

**Comment by Harry5573** [comment]
@Scottmitch It appears to be working with `META-INF/native/libnet-minecraft-util-netty-transport-native-epoll`! Will report back with any issues. 

Side question: Why do we have to remove the `ty-` from the default of `netty-`?

**Comment by Scottmitch** [comment]
> It appears to be working

Great news!

> Side question: Why do we have to remove the ty- from the default of netty-?

You are actually just prepending your class prefix and replacing `.` with `-`.

Library name = your class prefix with `.` replaced with `-` + original library name
`net-minecraft-util-netty-transport-native-epoll` = `net-minecraft-util-` + `netty-transport-native-epoll`

**Comment by Scottmitch** [comment]
@Harry5573 - Have you been running with this PR under load? Anything interesting to report (good or bad)?

**Comment by Harry5573** [comment]
@Scottmitch Have not rolled it out to production yet, will be doing that later today.

**Comment by normanmaurer** [comment]
@Scottmitch LGTM

**Comment by Scottmitch** [comment]
Cherry-picked 4.1 (075a54a) 4.0 (7e057de)

**Pull request closed without merging**
