### PR TITLE
fixed "sensative" typo to read "sensitive"

### PR DESCRIPTION
**Pull request by mosesn**
I was reading [CharSequenceMap][0] and noticed a typo, so I fixed it.

[0]: https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/CharSequenceMap.java

### CODE REVIEW

**Comment by trustin** [comment]
Hey @mosesn. Thanks for a PR. I hope you are doing great there! (Read your Finagle blog post just today!) PR LGTM

**Comment by mosesn** [comment]
Thanks!  Hope you're doing well too.  We're working on http2 support in finagle now that we're (finally) getting onto netty4, so I'm beginning to read the package.  It looks great so far, I'm really excited about joining line, google, etc in using it :+1:.  Hoping to use this as an opportunity to learn more about netty and maybe give back to the community a little bit :fireworks:

**Comment by normanmaurer** [comment]
LGTM... Cherry-picking in a sec..

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 as f0f0b69d90be9eee51434a0c9abce0db5c2b66d2.

@mosesn thanks!

**Comment by trustin** [comment]
@mosesn Happy to hear that Finagle is getting there finally. I hope you enjoy Netty till its last drop and have a chance to contribute here. :laughing:

**Pull request closed without merging**
