### PR TITLE
[#5773] AbstractByteBuf.forEachByteDesc(ByteProcessor) starts from wr…

### PR DESCRIPTION
**Pull request by normanmaurer**
…ong index

Motivation:

We introduced a regression in 1abdbe6f6798732447df6dd3af15f6cd871d6279 which let the iteration start from the wrong index.

Modifications:

Fix start index and add tests.

Result:

Fix regression.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@Scottmitch PTAL.. also @npordash

**Comment by npordash** [comment]
My unit tests are now passing 👍

**Comment by normanmaurer** [comment]
@Scottmitch reviewed offline...

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (463b5cf21b6fe6e0e8b08615f3e47beb31f39025) and 4.0 (f66f4c9)

**Comment by Scottmitch** [comment]
lgtm ... thanks @normanmaurer !

**Pull request closed without merging**
