### PR TITLE
Remove the pcap handler

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
This code now lives in the Netty Contrib organisation:
https://github.com/netty-contrib/handler-pcap

Modification:
The pcap handler code is removed.

Result:
The code now lives in contrib.

### CODE REVIEW

**Comment by chrisvest** [comment]
Also, please take a look, @hyperxpro

**Comment by hyperxpro** [comment]
How can I contribute to the development of Pcap from now onwards?

**Comment by chrisvest** [comment]
@hyperxpro I sent you an invite to the contrib org

**Comment by hyperxpro** [comment]
Thanks a lot!

**Review by normanmaurer — APPROVED** [review]

**Pull request merged**
