### PR TITLE
Add advanced leakdetection for methods introduced by [#4842]

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

[#4842] introduced 4 new methods but missed to implement advanced leak detection for these.

Modifications:

Correctly implement advanced leak detection for these methods.

Result:

Advanced leak detection works for all methods as expected.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@trustin @nmittler @Scottmitch @windie PTAL

**Comment by trustin** [comment]
Ugh, sorry about the JVM crash. I was upgrading JDK in the CI machines.

**Comment by trustin** [comment]
LGTM

**Comment by windie** [comment]
LGTM

**Comment by nmittler** [comment]
LGTM

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 as 74495fd27f65277530214ed09ef858ab4f39498e

**Pull request closed without merging**
