### PR TITLE
Speedup max direct memory estimation via Unsafe

### PR DESCRIPTION
**Pull request by franz1981**
Motivation:

PlatformDependent::estimateMaxDirectMemory reflectevly allocates MX Beans to detect JVM's arg MaxDirectMemory (often failing to find any, because unconfigured).

Modifications:

Allow unsafe to find Bits's max memory static field and use it as a fast path to detect the same direct memory limits used by the JVM runtime

Result:

Faster and less memory hungry (in term of mallocs) startup

### CODE REVIEW

**Comment by franz1981** [comment]
FYI this is the `malloc` flamegraph from a Quarkus's startup, for the Netty's `PlatformDependent` static init:

image


about half of the `malloc` events are due to allocating the MX beans (for no reasons, most of the time!).

**Comment by normanmaurer** [comment]
@franz1981 honestly I think the bigger advantage is that this will work even if Reflection is not possible

**Comment by franz1981** [comment]
@normanmaurer 

Yep, that's indeed the other "good" thing, although i don't feel well using `Unsafe` again

**Comment by geoand** [comment]
Thanks for this @franz1981!

**Comment by franz1981** [comment]
@normanmaurer 
i see that 

```
private static final Pattern MAX_DIRECT_MEMORY_SIZE_ARG_PATTERN = Pattern.compile(
            "\\s*-XX:MaxDirectMemorySize\\s*=\\s*([0-9]+)\\s*([kKmMgG]?)\\s*$");
            ```

is not really needed anymore and I can just skip allocating it, in case we have our fast-path satisfied, saving both time and some useless allocation/memory footprint, wdyt?

**Comment by normanmaurer** [comment]
@franz1981 can you please port to main as well ?

**Pull request merged**
