### PR TITLE
Fixed broken optional OSGi Import-Package header (#3424).

### PR DESCRIPTION
**Pull request by CodingFabian**

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by Scottmitch** [comment]
@netkins accept

**Comment by Scottmitch** [comment]
@CodingFabian - Thanks for the fix!  Could you please follow the commit guide http://netty.io/wiki/writing-a-commit-message.html and then squash your commits.

**Comment by Scottmitch** [comment]
@normanmaurer - I'll let you take this one over.

**Comment by normanmaurer** [comment]
Sure thing will do

**Comment by CodingFabian** [comment]
@Scottmitch What do you mean? It is only one commit, so nothing to squash. Also I think it does qualify for "the commit is trivial", don't you think? It adds two colons in the OSGi Manifest, which right now does not validate...

**Comment by normanmaurer** [comment]
@Scottmitch I thinkg @CodingFabian is right here. It is fine to cherry-pick. Just one thing... I know it may sound a bit like overkill but could you please sign the ICLA ?
http://tinyurl.com/netty-icla

**Comment by CodingFabian** [comment]
legal stuff is always overkill :-) Just signed that agreement.

**Comment by normanmaurer** [comment]
@CodingFabian thanks... cherry-picked into 4.0, 4.1 and master

**Pull request closed without merging**
