### PR TITLE
Replace toArray(new T[size]) with toArray(new T[0]) to eliminate zero…

### PR DESCRIPTION
**Pull request by normanmaurer**
…-out and allow the VM to optimize.

Motivation:

Using toArray(new T[0]) is usually the faster aproach these days. We should use it.

See also https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion.

Modifications:

Replace toArray(new T[size]) with toArray(new T[0]).

### CODE REVIEW

**Comment by Bennett-Lynch** [comment]
Would shared zero-length array constants benefit at all here?

E.g.,
https://commons.apache.org/proper/commons-lang/apidocs/src-html/org/apache/commons/lang3/ArrayUtils.html#line.87

**Comment by normanmaurer** [comment]
@Bennett-Lynch I suspect no... Let me ask Shipley.

**Comment by njhill** [comment]
@Bennett-Lynch @normanmaurer it's addressed in the same article: https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_caching_the_array

But I'm not sure that includes the deferred cost to GC (which could still be insignificant in grand scheme)?

**Comment by normanmaurer** [comment]
@Bennett-Lynch did not notice it ... doh 👍

**Comment by hc-codersatlas** [comment]
@njhill escape analysis probably takes care of that in this case.

**Comment by Scottmitch** [comment]
Did we observe any performance gains as a result of this PR?

**Comment by normanmaurer** [comment]
I did no do any specific benchmarking for this but just trusted shiplev

**Comment by doom369** [comment]
@Scottmitch I tested this a lot on java 8, 9, 10 many days ago. In all cases `new T[0]` is faster. Also, some static analyzers and IDE inspections now mark `toArray(new T[size])` code as slow.

**Pull request merged**
