### PR TITLE
If user explicit ask to use an Inet6Address we should try to do so in…

### PR DESCRIPTION
**Pull request by normanmaurer**
… native transports

Motivation:

Even if the system does not support ipv6 we should try to use it if the user explicit pass an Inet6Address. This way we ensure we fail and not try to convert this to an ipv4 address internally.

This incorrect behavior was introduced by https://github.com/netty/netty/commit/70731bfa7ef884ee354a5cf96e1545a8d9d090b8

Modifications:

If the user explicit passed an Inet6Address we force the usage of ipv6

Result:

Fixes https://github.com/netty/netty/issues/10402

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Nice, thanks for the fix!

**Comment by meteorcloudy** [comment]
One thing feels a bit strange, 70731bf is only included since 4.1.37. But before my recent [upgrade](https://github.com/bazelbuild/bazel/commit/99646d956ddb1fe54208b96143446c0c01c65d69) of netty, we were using 4.1.34. When [upgrading](https://github.com/bazelbuild/bazel/commit/dfbf87c9196a15d491e9cbb81ee2d3da416cc0c2) grpc we didn't upgrade the netty version, but I guess it switched from using nio to epoll, which exposed the bug. But the bug seems to exist even before 70731bf?

**Comment by normanmaurer** [comment]
@meteorcloudy hm... all I can say is that this PR fixes it. So maybe it exists before but in a different flavour

**Comment by meteorcloudy** [comment]
Cool, happy to test this if there is a prebuilt jar.

**Comment by benjaminp** [comment]
It would be good to turn my reproducer into a test case.

At least for epoll, the socket address family is fixed at channel creation time. So, if the `ipv6` field is false, there's no chance binding a `Inet6Address` would work. The best immediate fix given the current API would be to throw an exception if `Socket.ipv6` is false and a `Inet6Address` is passed in.

It would desirable to allow applications to bind and connect both IPv4 and IPv6 regards of the IPv4/IPv6 preferences. Creation of the underlying OS socket would have to be made lazy for that to work, though.

**Comment by normanmaurer** [comment]
@benjaminp added a test case.

**Comment by carl-mastrangelo** [comment]
FWIW, this will break down when binding to ::, which will end up preferring 0.0.0.0 if java.net.preferIPv4Stack is set.

**Pull request merged**
