### PR TITLE
Consume tcnative options update

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
tcnative has updated how constants are defined and removed some constants which are either obsolete or now set directly in tcnative.

Modifications:
- update to compile against tcnative changes.

Result:
Netty compiles with tcnative options changes.

### CODE REVIEW

**Comment by Scottmitch** [comment]
This is required for https://github.com/netty/netty-tcnative/pull/231

**Comment by Scottmitch** [comment]
@normanmaurer https://github.com/netty/netty-tcnative/pull/231 was cherry-pick ... is this OK too?

**Comment by normanmaurer** [comment]
@Scottmitch yes... sorry

**Comment by Scottmitch** [comment]
4.1 (cd3bf3d) 4.0 (dbb0088)

**Pull request closed without merging**
