### PR TITLE
Support global pinned max direct memory.

### PR DESCRIPTION
**Pull request by horizonzy**
Motivation:
Fixes-#12877

### CODE REVIEW

**Comment by hangc0276** [comment]
Good job! Would you please add a unit test?

**Comment by normanmaurer** [comment]
Honestly I am not a big fan of this... First of its a static field which means we are now basically add some extra overhead but also its in `internal.` which means people should not call it directly

**Comment by horizonzy** [comment]
Maybe we can add a JVM flag to trigger it. In my program, I will use reflect to get the value.

**Comment by horizonzy** [comment]
Sorry, I didn't notice that method is as follows:
```
    public static long usedDirectMemory() {
        return DIRECT_MEMORY_COUNTER != null ? DIRECT_MEMORY_COUNTER.get() : -1;
    }
```

Also, export the `PINNED_DIRECT_MEMORY_COUNTER.`

**Comment by horizonzy** [comment]
@normanmaurer Pls give some advice.

**Comment by chrisvest** [comment]
I agree with @normanmaurer on this. I don't think we want this. You're trying to account for 3rd party code creating their own allocators, but a static field in `PlatformDependent` is also not enough because 3rd party code use shading.
If you want to get the pinned memory, you need to take charge of the dependencies that go into the system; make sure they don't shade, and make sure they all use the same allocator.

**Comment by horizonzy** [comment]
I got. I will change the way of the netty PooledByteBufAllocator.

**Pull request closed without merging**
