### PR TITLE
Fixed typo in LimitingByteInput

### PR DESCRIPTION
**Pull request by terrarier2111**
Motivation:

I found a typo in LimitingByteInput.

Modification:

Fixed the typo in LimitingByteInput

Result:

No typo anymore in LimitingByteInput.

### CODE REVIEW

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by hyperxpro** [comment]
@terrarier2111 Can you sign our ICLA and let us know when done?

https://netty.io/s/icla/

**Comment by hyperxpro** [comment]
@normanmaurer Just being a helping hand. :D

**Comment by terrarier2111** [comment]
It's done

**Pull request merged**
