### PR TITLE
[#5931] Ensure we not complete the same promise that may be failed be…

### PR DESCRIPTION
**Pull request by normanmaurer**
…cause of outbound handler exception.

Motivation:

It's important that we do not pass in the original ChannelPromise to safeClose(...) as when flush(...) will throw an Exception it will be propagated to the AbstractChannelHandlerContext which will try to fail the promise because of this. This will then fail as it was already completed by safeClose(...).

Modifications:

Create a new ChannelPromise and pass it to safeClose(...).

Result:

No more confusing logs because of failing to fail the promise.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@Scottmitch PTAL

**Comment by normanmaurer** [comment]
Also @johnou FYI

**Comment by johnou** [comment]
nice catch!

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (6dbec4181cabe2d836e4a46b253d2f400fa296ac) and 4.0 (5b457c8a22b5e6ab2e40b8a6eacb7b53458c70b6)

**Pull request closed without merging**
