### PR TITLE
Fix reentrancy bug in SslHandler which can cause IllegalReferenceCoun…

### PR DESCRIPTION
**Pull request by normanmaurer**
…tException

Motivation:

These days our native SSL implementation makes use of "tasks" to allow off-loading operations. Due a bug this could lead to an re-entrancy issue when the Executor used is directly executing the task by the same thread that submits it. As an end-result it was possible to see IllegalReferenceCountException when the tryDecode(...) method will cause the original buffer to be released.

Modifications:

- Always submit the resume to the eventloop to ensure we never have an re-entrancy problem
- Add unit tests that would fail before the fix.

Result:

Fixes https://github.com/netty/netty-tcnative/issues/680

### CODE REVIEW

**Review by chrisvest — APPROVED** [review]

**Comment by johnou** [comment]
@normanmaurer you rock, looks like this could explain https://github.com/netty/netty/issues/11850 as well, any idea when this regression was introduced?

**Comment by normanmaurer** [comment]
@johnou 4.1.64 ... https://github.com/netty/netty/pull/11242

**Comment by johnou** [comment]
@normanmaurer we have been offloading tasks earlier than that, infact we weren't seeing any problems when downgrading to 4.1.51.Final + tcnative 2.0.34.Final

**Comment by normanmaurer** [comment]
@johnou  so you did use `io.netty.handler.ssl.openssl.useTasks=true` before ?

**Comment by johnou** [comment]
@normanmaurer yep

**Pull request merged**
