### PR TITLE
Switch to AdaptiveByteBufAllocator by default

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

The AdaptiveByteBufAllocator reduce the memory overhead quite a lot while still provide kind of the same performance characteristics. Let's use it as the default allocator

Modifications:

Switch default allocator from PooledByteBufAllocator to AdaptiveByteBufAllocatore. Users can use -Dio.netty.allocator.type=pooled to switch the old default if wanted

Result:

Less memory overhead by default

### CODE REVIEW

**Comment by normanmaurer** [comment]
I think we might need to figure out https://github.com/netty/netty/issues/14272 first tho

**Comment by franz1981** [comment]
@normanmaurer I'm aswering to #14272

**Comment by franz1981** [comment]
> while still provide kind of the same performance characteristics

FYI https://github.com/eclipse-vertx/vert.x/issues/5168#issuecomment-2259633047

which, although is quite unscientific, shows that there is some additional overhead...

Talking with @chrisvest about it, some months (IIRC) ago, it was due to the additional level of indirection which doesn't happen with Netty 5, for the same allocators buffers.

**Comment by nitsanw** [comment]
IMO, the default should reflect what we believe to benefit most users. This is not something we typically see in benchmarks, but perhaps something we should frame better.

A benchmark which reflects RSS impact would be great here, to illustrate the tradeoff. We expect low CPU cost increase (or none), and significant RSS savings under most scenarios.

The trickier to measure impact is the expected latency impact when the pool resizes.

**Comment by normanmaurer** [comment]
so seems like the problems reported in https://github.com/netty/netty/issues/14272 disappear when using `FastThreadLocalThread` hurray ...

**Comment by chrisvest** [comment]
Issue #14272 has developed a sub-issue around bad reference counts, which sounds more serious than degraded performance. We should get to the bottom of that before making the adaptive allocator the default.

**Review by chrisvest — APPROVED** [review]

**Comment by normanmaurer** [comment]
I think this was fixed by https://github.com/netty/netty/pull/14301

**Pull request merged**
