### PR TITLE
Add log level check simply before logging.

### PR DESCRIPTION
**Pull request by seedeed**
Motivation:

In general, we will close the debug log in a product environment. However, logging without external level check may still affect performance.

Modification:

Add log level check simply before logging.

Result:

Improve performance slightly in a product environment.

### CODE REVIEW

**Comment by Bennett-Lynch** [comment]
This change seems mostly harmless, but can you please elaborate on why you think this will improve performance?

None of the logging statements appear to perform any unnecessary string concatenation since they use format parameters (`{}`), and none of the statements appear to make any expensive method calls.

(Java 8 lambda support for lazy logging would be ideal here, but would have to wait until Netty 5.)

**Comment by seedeed** [comment]
In my opinion, these several logging statements all have over 3 arguments, so the debug method with varargs will be invoked. Varargs is a nice syntactic sugar but will cause an array instance's creation implicitly. So I think if we add a log level check for these several logging statements, the creation of the array instance would be eliminated in a product environment with the debug log closed.

```java
    /**
     * Log a message at the DEBUG level according to the specified format
     * and arguments.
     * <p/>
     * <p>This form avoids superfluous string concatenation when the logger
     * is disabled for the DEBUG level. However, this variant incurs the hidden
     * (and relatively small) cost of creating an {@code Object[]} before invoking the method,
     * even if this logger is disabled for DEBUG. The variants taking
     * {@link #debug(String, Object) one} and {@link #debug(String, Object, Object) two}
     * arguments exist solely in order to avoid this hidden cost.</p>
     *
     * @param format    the format string
     * @param arguments a list of 3 or more arguments
     */
    void debug(String format, Object... arguments);
```

**Comment by Bennett-Lynch** [comment]
Got it. Good point. I did not realize that Netty's `InternalLogger` only supported up to two placeholder parameters before using varargs.

In contrast, Log4j2's [`Logger`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/Logger.html#debug-java.lang.String-java.lang.Object-java.lang.Object-java.lang.Object-java.lang.Object-java.lang.Object-java.lang.Object-java.lang.Object-java.lang.Object-java.lang.Object-java.lang.Object-) interface supports up to 9 different placeholder parameters before using varargs.

To make this potentially more future-proof and readable, what are your thoughts on extending the number of parameters that Netty's `InternalLogger` will accept, similar to Log4j2? This could be accompanied by marking the varargs method signature as `@Deprecated` to increase visibility on the performance concern, or even outright removing it.

**Comment by seedeed** [comment]
@Bennett-Lynch Good idea. In long term, I think it's better and more future-proof to extend the parameter count of  InternalLogger's logging method.

**Comment by normanmaurer** [comment]
@seedeed I will merge this one that said I think all these logs should not happen frequently anyway.

**Comment by seedeed** [comment]
@normanmaurer Got it.

**Pull request merged**
