### PR TITLE
Correct OSGi manifests in source jars

### PR DESCRIPTION
**Pull request by FeiWongReed**
Solution for https://github.com/netty/netty/issues/3886

### CODE REVIEW

**Comment by netkins** [comment]
**AUTOMATED MESSAGE for ADMINS**:<br>Please verify and accept the pull request.<br>To accept, say `@netkins accept`<br>To build again, say `@netkins build`<br>To whitelist the author, say `@netkins whitelist`

**Comment by Scottmitch** [comment]
@netkins accept

**Comment by Scottmitch** [comment]
@FeiWongReed - Thanks a bunch!

@ChristianSchwarz - Would you mind reviewing / commenting?

**Comment by FeiWongReed** [comment]
So, maybe merge because of no comments?..

**Comment by Scottmitch** [comment]
@FeiWongReed - Sorry for the delay. @ChristianSchwarz - Last call.

@normanmaurer @trustin - Anyone else with OSGi experience that should take a look?

**Comment by trustin** [comment]
@FeiWongReed Looks good to me. Could you please sign the ICLA? http://netty.io/s/icla

**Comment by normanmaurer** [comment]
@FeiWongReed once you signed the ICLA we can merge in. So please let us know once done.

**Comment by FeiWongReed** [comment]
Ok, I signed it

**Comment by trustin** [comment]
@FeiWongReed Thanks! Will cherry-pick soon.

**Comment by trustin** [comment]
Cherry-picked: 24bcc11095a234cd5c97fba2f3a81c18107612ef (4.0), 2eb680907021c92044bcc9083e598533c8862181 (4.1), and 269101436ce4b0a1fb43ecd5bd968f13c2cc2077 (master)

Please update your commit message to meet our standard next time.

**Pull request closed without merging**
