### PR TITLE
epoll_wait produces an EINVAL error since 4.1.30

### PR DESCRIPTION
**Pull request by johnou**
Fixes regression with 6d8745179844caba0f3a0f3d7f3a1fbf392c925f

Closes https://github.com/netty/netty/issues/8348

### CODE REVIEW

**Comment by johnou** [comment]
@normanmaurer I verified using debugger it works as expected but had trouble adding a unit test, I tried a bunch of different ways eg.

```java
        Future<Integer> pendingTasks = el.submit(new Callable<Integer>() {
            @Override
            public Integer call() throws Exception {
                return ((EpollEventLoop) el).pendingTasks();
            }
        });
        assertEquals(Integer.valueOf(1), pendingTasks.get(1000, TimeUnit.SECONDS)); // accepted scheduled task
```

but no nice.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by johnou** [comment]
@normanmaurer yep

screenshot from 2018-10-11 12-21-20

**Comment by normanmaurer** [comment]
@johnou why not just make `EpollEventLoop` (but still keep it package-private) not final and change `handleLoopException` to be not static and package-private (+ add a comment this is because of testing). This way you could extend the class and override and just assert that it is not called. 

WDYT ?

**Comment by johnou** [comment]
@normanmaurer i'll give that a go after lunch :+1:

**Comment by johnou** [comment]
@normanmaurer I could only get it working by removing the final from EpollEventLoopGroup too..

**Comment by normanmaurer** [comment]
@johnou it should not be needed to do this... what was the problem ?

**Comment by johnou** [comment]
@normanmaurer PTAL I swapped out the EpollEventLoopGroup with EpollEventLoop directly in the test to avoid removing final from EpollEventLoopGroup.

**Comment by normanmaurer** [comment]
@johnou this looks great... can you adjust the commit message to match our template tho ?

**Comment by johnou** [comment]
@normanmaurer yep sure, done.

**Comment by normanmaurer** [comment]
@johnou thanks a lot!

**Comment by carl-mastrangelo** [comment]
LGTM

**Pull request merged**
