### PR TITLE
Fix FlowControlHandler's autoreading breakage.

### LINKED ISSUE #12445: FlowControlHandler breaks auto-reading
_FlowControlHandler_ breaks auto-reading (i.e. the channel does not auto-read even though its config has auto-read set to true). This happens when auto-read is turned on when the queue is not empty. The reason is that _FlowControlHandler.read()_ does not pass the call to the _ChannelHandlerContext_ if at least one message has been dequeued. This is a problem when _FlowControlHandler.read()_ has been called as a result of auto-read having been turned on (_DefaultChannelConfig.setAutoRead()_ calling read() in case of _autoRead && !oldAutoRead_).
Taking _ctx.read();_ out of the body of the if statement fixes the bug and I also did not notice any unwanted side effects. I.e.:
```
public void read(ChannelHandlerContext ctx) throws Exception {
    if (dequeue(ctx, 1) == 0) {
        shouldConsume = true;
    }
    ctx.read();
}

``` 
### Expected behavior
Auto-reading.

### Actual behavior
Reading the messages that are already in the queue and then no auto-reading.

### Steps to reproduce
On a channel with a FlowControlHandler in its pipeline, turn auto-read off while a message is in the process of being added to the handler's queue.  When the message is already in the queue, turn auto-read back on.

### Minimal yet complete reproducer code (or URL to code)
It is a bit hard to reproduce with simple code so I hope that you understand the issue from my description.

### Netty version
any

### JVM version (e.g. `java -version`)
any

### OS version (e.g. `uname -a`)
any

### PR DESCRIPTION
**Pull request by gbrdead**
Fix FlowControlHandler's autoreading breakage
 
Motivation:

FlowControlHandler breaks auto-reading (i.e. the channel does not auto-read even though its config has auto-read set to true). This happens when auto-read is turned on when the queue is not empty. The reason is that FlowControlHandler.read() does not pass the call to the ChannelHandlerContext if at least one message has been dequeued. This is a problem when FlowControlHandler.read() has been called as a result of auto-read having been turned on (DefaultChannelConfig.setAutoRead() calling read() in case of autoRead && !oldAutoRead).
 
Modifications:

Always pass the call to read() down the pipeline.
 
Result:

Auto-reading works, regardless of the handler's queue state in the moment it is turned on.
Fixes #12445

### CODE REVIEW

**Comment by hyperxpro** [comment]
Well, the Bug report and PR description can be different and as per https://netty.io/wiki/developer-guide.html, you must add a description.

**Comment by normanmaurer** [comment]
@gbrdead thanks this looks good. Can you please sign our ICLA and let me know once done: https://netty.io/s/icla ?

**Comment by gbrdead** [comment]
@normanmaurer I just signed the ICLA.

**Comment by normanmaurer** [comment]
Thanks!

**Pull request merged**
