### PR TITLE
Do not try to init TrustManagerFactory if trustCertChainFile is null.

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We called TrustManagerFactory.init(...) even when the trustCertChainFile is null. This could lead to exceptions during the handshake.

Modifications:

Correctly only call TurstManagerFactory.init() if trustCertcChainFail is not null.

Result:

Correct behavior.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@trustin please review

**Comment by normanmaurer** [comment]
@netkins build

**Comment by normanmaurer** [comment]
@netkins build

**Comment by trustin** [comment]
LGTM

**Comment by normanmaurer** [comment]
Cherry-picked into 4.0 (bb230579f8721283857b68e6da5bc42e01fb0c47) ,4.1 (6fce3b79c3225e84f2be50df370198c39da5140c) and master (0b58e92bce2568070bd0037c2bba6dfaa16fc88d)

**Pull request closed without merging**
